### ISSUE TITLE
Write content for the site

### ISSUE THREAD

**Issue by jacchau** [bloom-housing/bloom#100]
Write and develop content for the Bloom Housing site

https://docs.google.com/document/d/1p9chMLvxzH91Z2uGCFFQV84kJM4M0Z0Spnmu7guUNoI/edit

**Comment by bk3c** [comment]
Superseded for the moment by the Exygy marketing site at https://housing.exygy.com. Eventually we'll want something more detail and engineering focused that's targeted at OSS project users and potential developers, but closing this issue since that's pretty far future at this point.
