### ISSUE TITLE
CSV Exporter Household Sizes

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1018]
When I added an application with multiple household size members, 
the CSV export continues to only show columns for the first household size member

**Comment by pbn4** [comment]
@kathyccheng How many household members were there in total (including primary applicant) ?  I just tested for 3 (2 + primary) and it works as expected. If you also had a problem with 3 in total that would require investigating what frontend is sending in application form data.

**Comment by kathyccheng** [comment]
@pbn4 oh it looks like it's working! Okay going to close
