### ISSUE TITLE
Paper Application language submitted in should include Vietnamese and Chinese

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1022]
In the add application screen, language submitted should include: Spanish, Vietnamese, Chinese 

![Screen Shot 2021-02-16 at 6.08.46 PM.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/4560f7e4-8d56-488d-afaa-76833f07d1ba)

**Comment by dominikx96** [comment]
@pbn4 can we update backend to support these languages?
