### ISSUE TITLE
Partners Portal Preference Formatting 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1026]
Remove all caps formatting from displacement preferences in Partners Portal 

In the Application Detail View 
![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/5769b3cc-8c23-4bd6-8df2-5f3f7402f408)

In the Add/Edit Application View
![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/1bb73a80-8bc4-4a3b-9172-cf3fba4a45d0)

**Comment by dominikx96** [comment]
@kathyccheng these settings come from the backend (@software-project) - can we update this text to lower case (the first letter capitalized only)?

**Comment by kathyccheng** [comment]
This looks good!

**Comment by kathyccheng** [comment]
Closed in #233
