### ISSUE TITLE
Update logged out error text 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1027]
When I leave the application, an error shows asking me to log back in 

![image](https://user-images.githubusercontent.com/3453407/108273381-7aae7a80-7141-11eb-9fa4-bfc60540ffe2.png)

If user accounts are enabled use the current copy

If user accounts are disabled replace with:
We care about your security. We ended your session due to inactivity. Please start a new application to continue.

**Comment by emilyjablonski** [comment]
How do I handle the translations for a new string?

**Comment by kathyccheng** [comment]
@emilyjablonski create a new like line item for the new user accounts disabled text, I'll send it over to the translators but it's okay for now if it's not translated

**Comment by kathyccheng** [comment]
Closed in HousingBayArea
