### ISSUE TITLE
Partners portal - listing page displaying "0" in top left corner of listings table

### ISSUE THREAD

**Issue by pbn4** [bloom-housing/bloom#1028]
Happens when you log in with a user having no permissions for any listing e.g. an unassigned leasing agent. 

<img width="1430" alt="Zrzut ekranu 2021-02-18 o 12 03 49" src="https://user-images.githubusercontent.com/11684414/108348398-07107a00-71e2-11eb-94b8-da5469aaa57c.png">

**Comment by dominikx96** [comment]
Closed by #1032
