### ISSUE TITLE
Reduce CSS bundle size

### ISSUE THREAD

**Issue by software-project** [bloom-housing/bloom#1046]
Our CSS bundle fine is quite big, at 3MB area. At this stage we are not using any mini and uglyfiers. But first we should explore ways to reduce tailwind size as I believe it's the source of most of that huge size.

**Comment by jaredcwhite** [comment]
Related: https://github.com/bloom-housing/bloom/issues/78

**Comment by jaredcwhite** [comment]
I just found this issue — it's been fixed, so we can close this.
