### ISSUE TITLE
Update 211 Resource 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1053]
Update the 211 Resource on /additional-resources

![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/5d88194c-f3e5-45b2-bd96-f8accd15037b)

**Change link to:** 
https://achousingchoices.org/

**Update copy:** 

English 
If you are in need of immediate emergency shelter and housing assistance, please contact Eden Information & Referral at 510-537-2552 or the Bay Area Helpline at 1-800-273-6222, or visit https://achousingchoices.org/.

Spanish

"211_resource_subtext":"Si necesita asistencia inmediata de emergencia para obtener un refugio o vivienda, sírvase poner en contacto con Eden Information & Referral llamando al 510-537-2552 o con la Bay Area Helpline llamando al 1-800-273-6222 o visitando https://achousingchoices.org/.",

Vietnamese

"211_resource_subtext":"Nếu quý vị cần nơi trú ẩn khẩn cấp và hỗ trợ về nhà ở ngay lập tức, vui lòng liên lạc ban Thông tin & Giới thiệu Eden theo số 510-537-2552 hoặc Đường dây Trợ giúp Bay Area theo số 1-800-273-6222, hoặc truy cập https://achousingchoices.org/.",

Chinese

"211_resource_subtext":"如果您需要立即入住緊急收容所和尋求住房協助，請致電 510-537-2552 與 Eden Information & Referral（伊甸資訊和轉介中心）聯絡，或致電 1-800-273-6222 與 Bay Area Helpline（灣區求助熱線）聯絡；或可瀏覽 https://achousingchoices.org/。",

**Comment by dominikx96** [comment]
@kathyccheng ready for review in https://github.com/housingbayarea/bloom/pull/249

**Comment by dominikx96** [comment]
@kathyccheng merged :)
