### ISSUE TITLE
CSV Export Bugs

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1055]
It looks like there are 2 columns for Primary Applicant Residence Zip 
And in some cases, the zip code is showing 0, you'll see that in the Primary Applicant Zip here and it's also in the Primary Applicant Work Zip 
Not just if this is a script issue or storing issue, but it's in both the Partners Portal Export and the sample CSV export you pulled for me @pbn4 

![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/bac246ed-40b2-4d8c-beb1-8df0c41e2deb)

**Comment by pbn4** [comment]
@kathyccheng Thanks. I removed the redundant residence zip column. Zeroes is what this spreadsheet is doing with an input "00000", reducing number of zeroes, also all zip codes are created as number is they are digits only.
