### ISSUE TITLE
CSV Export Missing Displacement Columns 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1066]
The CSV Export from the Partners Portal seems to be missing the displacement columns: Displacee + Name + Address, Mission Corridor + Name + Address 

![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/14564689-8222-4ed2-9171-97e60f0ae27e)

**Comment by pbn4** [comment]
Closed, this was a data level problem, listing must specify CSVFormattingType property to have an appropriate CSV formatter for this new Displaced tentant preference.
