### ISSUE TITLE
Partners Table Monthly Income Issue

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1068]
* When I put in a monthly income in the add paper application form, it **doesn't** show up in the monthly income column on the main partners table. It shows up in the CSV export though. 
* When I put in a yearly income, it **does show** up in the yearly income column and calculates the monthly income too. 

![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/23119584-a7f1-4b86-9fad-a543de668972)

**Comment by dominikx96** [comment]
@kathyccheng it's frontend related issue, so I assigned this to me and working on it :)
