### ISSUE TITLE
Translation Updates 3/11

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1073]
Update these translation strings below 

"lottery_results": "Lottery_Results",
      "lottery_results_coming_soon": "Complete lottery results will be posted soon.",
      "lottery_download": "Download Results",
      "lottery_results_posted": "Lottery Results Posted",
      "lottery_results_subtitle": "You can now check lottery results on these listings.",
      "hide_lottery_results": "Hide Lottery Results",
      "which_household_member": "Which household member is claiming this preference?",
      "address_displaced": "What address was the household member displaced from?",
      "additional_resources": "View Additional Housing Opportunities and Resources",
      "logged_out_error_no_account": "We care about your security. We ended your session due to inactivity. Please start a new application to continue."

"lottery_results": "抽籤結果",
      "lottery_results_coming_soon": "全部抽籤結果將很快發佈。",
      "lottery_download": "下載結果",
      "lottery_results_posted": "抽籤結果已發佈",
      "lottery_results_subtitle": "您現在可以在這些列表中查看抽籤結果。",
      "hide_lottery_results": "隱藏抽籤結果",
      "which_household_member": "哪一位家庭成員在使用此優先權？",
      "address_displaced": "這位家庭成員是從哪個地址被迫搬遷？",
      "additional_resources": "瀏覽其他住房機會和資源",
      "logged_out_error_no_account": "我們關心您的網上安全。由於網頁閒置，我們已結束您的工作階段。請展開全新申請以便繼續。"
         
"lottery_results": "Resultados de la lotería",
      "lottery_results_coming_soon": "Los resultados de la lotería serán publicados pronto.",
      "lottery_download": "Descargar resultados",
      "lottery_results_posted": "Resultados de la lotería publicados",
      "lottery_results_subtitle": "Ahora puede consultar los resultados de la lotería en estas listas.",
      "hide_lottery_results": "Ocultar resultados de la lotería",
      "which_household_member": "¿Qué miembro del hogar solicita esta preferencia?",
      "address_displaced": "¿De qué dirección fue desplazado el miembro del hogar?",
      "additional_resources": "Vea Oportunidades y recursos adicionales de vivienda",
      "logged_out_error_no_account": "Su seguridad es importante para nosotros. Concluimos su sesión debido a inactividad. Sírvase iniciar una nueva solicitud para continuar."
      

   "lottery_results": "Kết quả Xổ số",
      "lottery_results_coming_soon": "Toàn bộ kết quả quay xổ số sẽ sớm được đăng.",
      "lottery_download": "Tải xuống Kết quả",
      "lottery_results_posted": "Kết quả Xổ số đã Đăng",
      "lottery_results_subtitle": "Quý vị đã có thể kiểm tra kết quả xổ số trên các danh sách này.",
      "hide_lottery_results": "Ẩn Kết quả Xổ số",
      "which_household_member": "Thành viên hộ gia đình nào đang yêu cầu lựa chọn này?",
      "address_displaced": "Địa chỉ mà thành viên hộ gia đình này đã chuyển khỏi là gì?",
      "additional_resources": "Xem Các Cơ hội Nhà ở và các Nguồn Hỗ trợ Bổ sung",
      "logged_out_error_no_account": "Chúng tôi quan tâm đến sự bảo mật của quý vị. Chúng tôi đã chấm dứt phiên truy cập của quý vị do không có hoạt động nào. Vui lòng bắt đầu làm một đơn ghi danh mới để tiếp tục."

**Comment by dominikx96** [comment]
@kathyccheng I don't see any keys from the list above (in the master branch, bloom-housing).

Here is the EN translation file: https://raw.githubusercontent.com/bloom-housing/bloom/master/ui-components/src/locales/general.json

I think a few translations look similar, but some not exists. Could you help me and update keys to match with available keys in general.json?

**Comment by kathyccheng** [comment]
@dominikx96 these are the mappings, there are a couple tied to a feature we haven't implemented yet so don't worry about those, I'll move them into the relevant issue 

"lottery_results" --> header under lotteryResults 
"lottery_results_coming_soon" --> completeResultsWillBePosted under lotteryResults
"lottery_download" --> downloadResults under lotteryResults 
"lottery_results_posted" --> Ignore for now, we'll handle it in #988 
"lottery_results_subtitle" --> Ignore for now, we'll handle it in #988 
"hide_lottery_results" --> Ignore for now, we'll handle it in #988 
"which_household_member" --> whichHouseholdMember under displacedTenant
"address_displaced" --> whatAddress under displacedTenant
"additional_resources" --> viewAdditionalHousing in welcome 
"logged_out_error_no_account" --> afterMessage in timeout
