### ISSUE TITLE
Next.js upgrade for best practices in SSG/SSR, i18n, and more

### ISSUE THREAD

**Issue by jaredcwhite** [bloom-housing/bloom#1081]
In order to have more fine-grained control over which pages and routes are statically generated upon deployment on Netlify and which are rendered dynamically through Netlify's serverless infrastructure (SSR), we need to rewrite how we implement static paths and data fetching. This also touches the way we handle i18n and support of multiple locales per route.

I worked on testing some of these new techniques out in this repo: https://github.com/jaredcwhite/exygy-nextjs-starter
Deployed on Netlify: https://exygy-test-nextjs-ssr.netlify.app

### Notes:

- First of all, it's using Next's native i18n routing. I'm happy to say this is quite simple and elegant and provides us a `locale` key in router/context data so we always know what's being viewed. Locale-specific links and switching between locales is now super easy as well.
- To use all the new data fetching methods, we can't use `getInitialProps` or anything like it in `_app.tsx`. This brought with it some real challenges, but I think I've worked through them now. In the process I switched from a class-based component to functional (largely just so we're in sync with the Next-recommend approach).
   - This required some granular working through how to use hooks effectively to replicate all the heavy lifting of the previous app class without causing performance/data/rendering issues. I think I've proven the system now, but it could very well require a few more tweaks. (Some of the issues are related to the application conductor, loading user data from sessionStorage, etc.)
- I included examples of both static and SSR-based listing pages, using a dynamic route (`[id].tsx))` filename.  It literally comes down to whether the file exports `getServerSideProps` or `getStaticProps`. At first glance the two methods seem comparable, but there's a difference:
   - The SSR version is truly dynamic so you can pass any ID into the route and the page handles it. You just look at the `params` provided by the incoming `context` and do with it what you will. Also no rewrite rules needed in Netlify's config with wildcards or whatever.
   - The static version is similar in terms of getting the ID out of `params`, but the trick there is Next needs to know which static pages to generate in the first place. Since we’d no longer be using `exportPathMap` in the config, we need to write a `getStaticPaths` function in the page file itself. I was surprised that there's no automatic accounting for configured locales, so you essentially need to loop through the item IDs and duplicate them for all available locales. Fairly simple code but non-obvious.
   - There's a `fallback` mechanism to static pages…related to refreshing the page with up-to-date data after the static version has first loaded, but that's a can of worms in and of itself so I haven't tested it out yet.
- I thought about looking into a Next-specific method of handling translation strings and moving away from our Polyglot-based method. However, I decided (a) not to rock the boat too much for now, and (b) that might actually be a bad idea for ui-components usage by S.F. because they aren't using Next at all for their React codebase. So probably better to keep ui-components/translation code decoupled from Next.

### Next Steps

I propose I do a first pass of upgrading these items in our Bloom codebase for the `public` app. I think it makes sense for @dominikx96 to upgrade `partners`, and regarding that we could do either:

* I work on public first and then Dominik works on partners based on that, or
* We both work in parallel and then compare notes to make sure both apps are in-sync for this new approach. There's one small changed required in ui-components I'd make to kick things off, but then otherwise it's mainly all just working within the Next.js code.

**Comment by jaredcwhite** [comment]
Prior related issues: #509 #834

**Comment by jaredcwhite** [comment]
One other thing that's worth mentioning — the previous method of using `getInitialProps` along with our translation code resulted in *all language JSON* being sent over-the-wire in the HTML for every page. Yikes! This new code results in the JSON embedded in a chunk via Webpack, so it'll get downloaded only once and cached. Big win!

**Comment by dominikx96** [comment]
@jaredcwhite everything looks good for me. I also agree we should focus on the next update (for now), and after that focus on Polyglot change (or other refactoring things).

About splitting our work:

I think, partners switch could be pretty simple, also it's stable (without problems like delays, etc.) so maybe we can start with a public app, and next I can apply changes to partners? It should prevent some code/approach differences. Happy to help you with code review or different work on the public app if needed! :)

**Comment by jaredcwhite** [comment]
@dominikx96 Yeah that makes sense to me. I've started to work on upgrading the public app, so I'll let you know when I have something you can review and provide input on. Thanks!￼

**Comment by jaredcwhite** [comment]
From our discussion on TypeORM: we should optimize the REST API queries we're making so it reduces load on the API server in general and the database in particular. Will pair with @pbn4 to determine the necessary changes.

**Comment by kathyccheng** [comment]
Closed in #1211 and #1087
