### ISSUE TITLE
Open House section disappears on mobile 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1084]
I think we have to fix this on bloom core and then Alameda, but the Open House section disappears in the mobile view 

![image](https://user-images.githubusercontent.com/3453407/112228582-eafc6000-8c07-11eb-9814-db116e49472c.png)

![image](https://user-images.githubusercontent.com/3453407/112228802-429acb80-8c08-11eb-9218-a4224a014bc1.png)

**Comment by kathyccheng** [comment]
@netrabadami can you take a look at this? it seems similar to the waitlist issue you had tackled earlier

**Comment by netrabadami** [comment]
@kathyccheng Sure!

**Comment by netrabadami** [comment]
@kathyccheng is it what it should look like in mobile version??
![Screen Shot 2021-03-23 at 5 38 57 PM](https://user-images.githubusercontent.com/58486174/112237224-77565500-8bff-11eb-9234-848736dfd128.png)

**Comment by kathyccheng** [comment]
@netrabadami this looks right on mobile. i'd like to release this sooner rather than later since it's relevant information for the SoHay listing

**Comment by kathyccheng** [comment]
Closed in #1091
