### ISSUE TITLE
Disable Max Household Size on SoHay 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1085]
Can we disable the max household size validation on Sohay? 

Currently, when I try to add a 6th household member and then click Done Adding People, then the application shows the you do not qualify banner. I think we can turn it off in general. 

I'm not sure if this is SoHay specific or should be on housingbayarea 

![image](https://user-images.githubusercontent.com/3453407/112229383-424f0000-8c09-11eb-8ee3-a62b9e8cc8e2.png)

**Comment by kathyccheng** [comment]
@jaredcwhite can you take a look at this? I guess there's a validation on the upper limit too

**Comment by jaredcwhite** [comment]
Taking a look. Just SoHay right?

**Comment by jaredcwhite** [comment]
Should be fixed in 0.3_alameda.
