### ISSUE TITLE
Pull in City for Do you work in or Do you live in questions in Application 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1129]
In the application right now, the question of Do you work in <region> and Do you live in <region> for the primary applicant + household members just say <region> or were hardcoded to "City of Hayward" for Sohay. We want this question to pull in the City Name. Don't need to worry about translations right now for the "City Name."

**Comment by dominikx96** [comment]
@kathyccheng just to clarify: we want to put a proper city instead of <REGION> hardcoded string, right?


![Image 2021-04-28 at 9 26 43 AM](https://user-images.githubusercontent.com/16655908/116365002-1aa11800-a805-11eb-8a50-a9a8f1b8ae46.png)

**Comment by kathyccheng** [comment]
Yes the places where it's currently hardcoded as <Region> should pull in the relevant region. It's on the contact information for the applicant and household members too

![image](https://user-images.githubusercontent.com/3453407/116429925-5a233080-a814-11eb-8951-2e8ab779df81.png)

**Comment by kathyccheng** [comment]
The region it pulls in should actually be the region that a Live/Work preference is attached to. So if it's Live or Work in City of Hayward like in SoHay, it should pull in City of Hayward. In the ones coming up it's Live or Work in Alameda County. @slowbot the more I think about this, I think the questions maybe should be grouped in with the preference. But for now @dominikx96 what do you think is the more efficient path to support the listings coming up?

**Comment by dominikx96** [comment]
@kathyccheng @pbn4 I created PR in housing bay: https://github.com/housingbayarea/bloom/pull/261

All <Region> will be the `City of Hayward` now (in the ALA instance).

@kathyccheng question to you. In the Alameda translations I noticed the link: "https://www.hayward-ca.gov/238/background" -  Should it be visible in "missionCorridor" description?

**Comment by kathyccheng** [comment]
@dominikx96 can we have all as "Alameda County" instead of City of Hayward for now? And we won't need the Mission Corridor preference for the ones coming up so we can remove for now.
