### ISSUE TITLE
Custom component for referral CTA 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1142]
For 2 of the listings coming up, we'll want to replace all the current application components - Apply Online, Paper Application, etc with a component prompting applicants to call a phone number as the main CTA. It would look something like this: 

![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/c1323259-45e5-4de2-9420-b931461a13ee)

Title - For further information 
CTA - phone number, Call Number text (just like our current phone number treatment) 
Description text 

* You'll need to add it to the sidebar manually for mobile

**Comment by emilyjablonski** [comment]
@kathyccheng Can you clarify what CTA stands for?

**Comment by kathyccheng** [comment]
Call to Action!

**Comment by kathyccheng** [comment]
Also, this is like a referral widget for no application listings (which I believe we have something in place for). Also cc @slowbot for any extra details here!
