### ISSUE TITLE
My Applications link broken 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1152]
On bloom.exygy.dev, when I click on the application link from one of the applications I've submitted, I get a 404.

**Comment by emilyjablonski** [comment]
@jaredcwhite Do you have any ideas as to why this works locally but not on bloom.exygy.dev?

**Comment by jaredcwhite** [comment]
Ah, it likely has something to do with the static routing setup on Netlify. Maybe look at how the partners app is setup? I know @dominikx96 had to do something specific to get the dynamic routes there working
