### ISSUE TITLE
Limit redirect to only relative URLs

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1162]
Currently, you can put in any redirect URL

**Comment by jaredcwhite** [comment]
Since I already just redid a bunch around routing in the Next v10 update, it probably makes sense to add the fix there, unless we want to hotfix prod more rapidly.

**Comment by jaredcwhite** [comment]
Working on this now.

**Comment by kathyccheng** [comment]
Closed in #1087
