### ISSUE TITLE
Improve theme-ability of the site

### ISSUE THREAD

**Issue by jaredcwhite** [bloom-housing/bloom#117]
Recent attempts to theme the site for a demo revealed some problems…the main ones are:

* Many components still don't have any dedicated class name, so we should continue along the BEM-ish lines that Jesse originally set up and make sure each component or layout section has a proper class name. That makes it easy to hook changes into the markup from a custom stylesheet.
* A number of references to colors via utility classes or `@apply` functionality are to specific shades (like blue-800, gray-400, etc.) instead of semantic references like primary-lighter, alert-dark, etc. That makes changing the Tailwind theme config and getting straightforward results problematic.
* Less of an immediate priority but still important is to make sure we're using semantic HTML wherever possible. React makes it all too easy to think in terms of components = div/span tags everywhere and lose sight of the markup integrity. This helps not only from a development standpoint but also from an accessibility and extensibility standpoint. (For example, HTML microformats can enable web pages to get parsed for a variety of metadata.)

**Comment by bk3c** [comment]
@jaredcwhite looking through some open issues, and I'm wondering if this one was already fixed by #168, or whether there's more work to do. If the latter, what's your opinion of the relative priority of what's left?
