### ISSUE TITLE
Move Link/Router components to React Context

### ISSUE THREAD

**Issue by jaredcwhite** [bloom-housing/bloom#1185]
Related to #1087 #1117 

I've already started to investigate this. Initially I looked into "prop drilling" to ensure Next.js's Link/Router components get pushed into the ui-component layer, but that's pretty onerous. It feels like React Contexts are there to solve for this sort of thing, so I'm hoping to get a handle on that shortly and, with luck, incorporate it into our Next v10 PR (but for SF's purposes, an updated ui-components package is the goal).

**Comment by akegan** [comment]
@james-wills-sf FYI Jared is starting to actively work on removing NextJS from UI-components

**Comment by jaredcwhite** [comment]
Just making a note we should be in pretty good shape on this issue once #1087 is merged. Incorporated feedback from an in-depth review by @james-wills-sf

**Comment by ColinBuyck** [comment]
Outdated and think it's generally resolved
