### ISSUE TITLE
Throttle Submit button to prevent multiple application submissions

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1193]
Right now, people are sometimes submitting duplicate applications inadvertently. We think this has to do with clicking the submit on the Terms page multiple times. Can we lock the button after the first click to prevent these unintentional duplicates

**Comment by jaredcwhite** [comment]
I'll try to approach this through a component-level concern – aka a "loading" prop. I've been impressed by the one used in Shoelace: https://shoelace.style/components/button?id=loading
