### ISSUE TITLE
Only display relevant Household Size on the Household Maximum Income table for an individual listing

### ISSUE THREAD

**Issue by jacchau** [bloom-housing/bloom#120]
**Summary:**
Only display relevant Household Size and AMI combinations for the Household Maximum Income table in an individual listing based on the min and max of occupancy for the units in the listing

**User Story:**
As an applicant,
I want to view the maximum incomes for only the AMI and occupancy combinations relevant to the listing,
So that I can determine self-eligibility without viewing non-relevant occupancy/ AMI combinations

**Acceptance Criteria:**
Given that the units for a listing has x min and y max occupancies, 
When the applicant views the AMI table for the individual listing
Then the AMI table only displays the max incomes for the relevant AMI and x - y occupancy combinations

**Comment by jaredcwhite** [comment]
@jacchau Hey I believe this was already dealt with a while ago. Can you confirm?

**Comment by jacchau** [comment]
Yes, this has already been dealt with. Closing this ticket FYI @jaredcwhite
