### ISSUE TITLE
Update how preferences are showing up in partners portal 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1204]
On the table view and in the application detail view, clean up the preference Display. They should be Live or Work. 

![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/38ed1905-d80a-4cc8-a750-c4131c74000b)
![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/cd3f043a-3931-4f44-ab6d-6ac964e454a0)

**Comment by dominikx96** [comment]
@kathyccheng for this preference we use the following translations:

```
      "liveWork": {
        "live": {
          "label": "Live in <REGION> Preference",
          "description": "Live in <REGION> copy goes here…",
          "link": "http://domain.com"
        },
        "work": {
          "label": "Work in <REGION> Preference",
          "description": "Work in <REGION> copy goes here…",
          "link": "http://domain.com"
        }
      },
```

so we don't have "Live or Work" text. Instead of I defined `"Live in <REGION> Preference` and `Work in <REGION> Preference` in the table cell.

**Comment by kathyccheng** [comment]
hey @dominikx96 looks like this isn't showing up in partners at the moment, maybe got reverted or something. can you look into it?

**Comment by dominikx96** [comment]
@kathyccheng can we close it? I think our latest fix resolved this problem.

**Comment by kathyccheng** [comment]
Yes closing
