### ISSUE TITLE
Drop displacement preference columns from the CSV Export 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1205]
Simplest fix, drop the displacement columns and keep the Live and Work columns. Eventually I think we should have one column for live and work and it will show Live or Work like we do in Partners. 

![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/4881ad14-9838-4574-a801-57a207e29f20)

**Comment by pbn4** [comment]
@Kathy we can configure how the CSV output looks like per listing, is it dropped because we do not have it on the upcoming ones? Because if so we can just define a content of a CSV export for that new one and leave this one for future use?

**Comment by kathyccheng** [comment]
@pbn4 for this round of listings, let's just drop the 4 displacement columns and keep the separate live preference and work preference column. for the next round of listings, I'll create a new issue to move the column treatment here to match the partners treatment (one column for the preference title, show sub_preference selections in the column)

**Comment by pbn4** [comment]
Closed through https://github.com/housingbayarea/bloom/commit/775b5cba09fb6346ae48eedf31a5c866511b57aa @software-project @emilyjablonski I updated the importer seeds and also actual DB tables via postman on staging. IIRC those listings are not yet uploaded to an actual prod environment right? 

Kathy please verify if this is the expected output.

**Comment by kathyccheng** [comment]
@pbn4 I think this looks right, but I can't do a full test run with all the data since the seeds have been updated and now the listing pages are erroring out. and yeah I think the listings haven't been uploaded to an actual prod environment yet.
