### ISSUE TITLE
Listings Management: States Prototype 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1210]
The most barebones flow that would be helpful to see is a listing with minimum data that can move through the basic states 

**Listing** 
* Title 
* Address
* Housing Developer
* Application Deadline Date 
* Apply Online button 

**Actions** 
* Publish, pushes to open 
* Preview, during draft 
* Edit and Delete actions could be optional, but might be interesting to double check for pushing updates to preview or open listings 

**States** 
* Draft 
* Open - live on the public site with a URL, included in the list of listings  
* Closed - closed on the public site, no application data, this part should be automatic based on timing   

**Notes**
* I think the publish action can be manual vs scheduled, but I think the closing should be automatic (open to discussing this)

**Comment by seanmalbert** [comment]
This is complete here https://github.com/bloom-housing/bloom/pull/1247. I can perform a demo on Monday. As part of this I created a base listing form and detail page with some updates to the listing grid as well, so we can link to the listing detail and the applications. A new listing can actually be created (with some hardcoded values) with name and application due date and status respecting the form values. Please see the PR for more notes. As stated in those notes, this includes a lot of legwork necessary for listings management in general, and if we wish to use it (with some adjustments required), it gives us a framework to add the new components and build out the rest of the features.
