### ISSUE TITLE
Setup Documentation for Google.org

### ISSUE THREAD

**Issue by seanmalbert** [bloom-housing/bloom#1212]
The team at Google requested documentation on setting up the apps for a new jurisdiction. They were unclear on whether they want the partner app, but I think we can include documentation for both public and partners along with the backend. This includes information on dependent accounts like SendGrid (we should not include any of our credentials).

In terms of deployment, I think we can share with them our infrastructure in general terms, including how we handle environment variables. Maybe a version of https://app.diagrams.net/#G1_vBtEpKIJwwDsU8kG76FpnyXmIqRRcug with the specifics removed would be useful to them. If they want specifics beyond that, we can let them ask.

**Comment by pbn4** [comment]
What I did so far:

- [Overview page](https://github.com/bloom-housing/bloom/wiki/Overview)
- [Setup page](https://github.com/bloom-housing/bloom/wiki/Setup)
- clean up env variables in both backend and partners portal https://github.com/bloom-housing/bloom/pull/1246

**Comment by pbn4** [comment]
@seanmalbert Do you maybe have comments about that ^?

**Comment by seanmalbert** [comment]
@pbn4 , I think this looks good and hopefully answers their questions, and if not it's a good place to iterate from. I added a custom sidebar to the wiki so there's more of a navigation to it too.

**Comment by seanmalbert** [comment]
@pbn4 , one more thing, along with the environment variables, especially COUNTY_CODE, it would probably be useful to include updating the CountyCode enum.

**Comment by kathyccheng** [comment]
Closing for this round
