### ISSUE TITLE
Translations 4/16

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1237]
These are translations for Core

**English** 

"for_more_information": "For more information",    
        "account_confirmed": "Your account was successfully confirmed.", 
        "my_applications_description": "See lottery dates and listings for properties for which you've applied",
        "account_settings_descriptions": "Account Settings, email and password",
        "forgot_password": "Forgot password",
        "confirmation_needed": "Confirmation needed",
        "email_send": "An email has been sent to",
        "email_confirm_instructions": "Please click on the link in the email we sent you in order to complete account creation.",
        "resend": "Resend the Email",

"household": {
          "addMembers": {
            "doubleCheck": "Please double-check the information for each household member.",
          },

"review": {
          "confirmation": {
            "imdone": "I'm done."
          }

**Spanish** 

"for_more_information": "Para más información",    
        "account_confirmed": "Su cuenta ha sido confirmada correctamente.", 
        "my_applications_description": "Vea las fechas de la lotería y los listados de las propiedades para las que ha presentado solicitudes",
        "account_settings_descriptions": "Configuraciones de la cuenta, email y contraseña",
        "forgot_password": "Olvidé la contraseña",
        "confirmation_needed": "Se necesita confirmación",
        "email_send": "Se ha enviado un email a",
        "email_confirm_instructions": "Por favor haga clic en el enlace del email que le hemos enviado para completar la creación de su cuenta.",
        "resend": "Volver a enviar el email",

"household": {
          "addMembers": {
            "doubleCheck": "Por favor revise la información de cada miembro del hogar.",
          },

"review": {
          "confirmation": {
            "imdone": "Terminado."

**Chinese** 

"for_more_information": "了解詳情",    
        "account_confirmed": "您的帳戶已成功確認。", 
        "my_applications_description": "查看您已申請物業的抽簽日期和好屋推薦",
        "account_settings_descriptions": "帳戶設定、電郵和密碼",
        "forgot_password": "忘記密碼",
        "confirmation_needed": "需要確認",
        "email_send": "本電郵已發送至 ",
        "email_confirm_instructions": "請按一下我們發送的電子郵件內連結，並完成建立帳戶程序。",
        "resend": "重新發送電子郵件",

"household": {
          "addMembers": {
            "doubleCheck": "請再次確認每位家庭成員的資訊。",
          },

"review": {
          "confirmation": {
            "imdone": "確認完成。"

**Vietnamese**

"for_more_information": "Để biết thêm thông tin",    
        "account_confirmed": "Tài khoản của quý vị đã được xác nhận.", 
        "my_applications_description": "Xem ngày rút thăm và danh sách các bất động sản mà quý vị đã ghi danh",
        "account_settings_descriptions": "Thiết lập Tài khoản, email và mật khẩu",
        "forgot_password": "Quên mật khẩu",
        "confirmation_needed": "Cần xác nhận",
        "email_send": "Một email đã được gửi tới",
        "email_confirm_instructions": "Hãy nhấp vào đường liên kết trong email mà chúng tôi gửi cho quý vị để hoàn thành việc lập tài khoản.",
        "resend": "Gửi lại Email",

"household": {
          "addMembers": {
            "doubleCheck": "Hãy kiểm tra lại thông tin cho mỗi thành viên hộ gia đình.",
          },

"review": {
          "confirmation": {
            "imdone": "Tôi đã làm xong."

**Comment by emilyjablonski** [comment]
"For more information" and "I'm done" are not strings we currently have in English

**Comment by seanmalbert** [comment]
Ready for review on https://dev-bloom.netlify.app/

**Comment by kathyccheng** [comment]
@emilyjablonski can we add in the translations to "Your account was successfully confirmed."

![image](https://user-images.githubusercontent.com/3453407/145334614-429b65d9-2e3f-4d97-ad5c-d10d2d59d908.png)

Spanish: Su cuenta ha sido confirmada correctamente.
Chinese: 您的帳戶已成功確認。
Vietnamese: Tài khoản của quý vị đã được xác nhận.

**Comment by emilyjablonski** [comment]
@kathyccheng We already have those translations in but for some reason they aren't updating in the alert box - I'll fix it here and see if there are any other alerts where this is the case, thank you!

**Comment by kathyccheng** [comment]
LGTM
