### ISSUE TITLE
Investigate using Docker for Bloom

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#1258]
This came out of Retro on 5/10, as a response to trying to get Bloom/Next 10 working on a new M1 Mac and needing to update various packages/Node version for it to run.

**Comment by pbn4** [comment]
@emilyjablonski I have much experience with docker and docker-compose, so I can pick that up too, but one thing is creating definitions for containers and running it on x86 (which I can do) and other is solving the problem and running it on M1 with ARMv8.4 ISA. 

Should the docker-compose spin up the entire stack - public, partners and backend?

**Comment by seanmalbert** [comment]
@pbn4 ,

If you want to pick this up, I can test and troubleshoot on M1. I put this together as a starter, and still needs some work if you want to use it https://github.com/seanmalbert/bloom/tree/1258-docker.

In that branch docker-compose spins up the entire stack with services for postrgres, redis, backend, partners and public.

**Comment by ludtkemorgan** [comment]
This work was done with the Doorway deployment pipeline. We can utilize that if we want to pull it over to core
