### ISSUE TITLE
String formatting issue in address on application review page

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#1260]
Application Review Page:
![Screen Shot 2021-05-20 at 2.28.13 PM.png](https://images.zenhubusercontent.com/601c7ede5322cf8ac29d50c4/2007df26-aee9-483c-8441-4caae6c3d92b)
Preference page:
![Screen Shot 2021-05-20 at 2.28.24 PM.png](https://images.zenhubusercontent.com/601c7ede5322cf8ac29d50c4/4499045f-c092-4d95-b237-4c4d06a6fdc5)

An extra comma has snuck into the application review page (once you fill out an entire application, the last page is a summary of everything you have inputted). The error looks like it is in the `preferenceHelperText` function. This particular error is appearing when you select a preference that has an address sub-field. The only preference we have in our seed data that allows you to trigger this state is the `Test: Default, Two Preferences` which has the displacee preference that when selected has an additional address input.

**Comment by YazeedLoonat** [comment]
seems to be resolved
