### ISSUE TITLE
Display of OHA in Partners 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1274]
In Partners Portal, in the application summary view, it looks like the display of the preference title and selection is off 

![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/85becfc8-5669-4974-b1f3-785c1b7e4314)

**Comment by kathyccheng** [comment]
@emilyjablonski @dominikx96 has done this update a few times before if you need help!

**Comment by emilyjablonski** [comment]
I've already fixed this, it will update in the next push
