### ISSUE TITLE
Add OHA to CSV Export 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1275]
Add a column for OHA into the CSV Export 
The values in the rows should be any preference selected, comma separated (Residency, Family, Veteran, Homeless), No preferences apply but still want to be considered, Do not want to be considered

**Comment by kathyccheng** [comment]
@pbn4 can we do this dynamically for new preferences, adding the column to the CSV export if it's there on the listing, or do we have to add it to all of them right now?

**Comment by emilyjablonski** [comment]
I think this might need to be a front-end change, I'll take a look tomorrow

**Comment by pbn4** [comment]
@kathyccheng It's not clear to me how should this exactly be displayed in the CSV export, there are 6 preferences: 

```
  "preferences": [
    {
      "ordinal": 1,
      "title": "Preference 1a",
      "subtitle": null,
      "description": "Persons who are living in a Below Market Rate deed restricted unit in Foster City for a minimum of twelve (12) months that is subject to termination of affordability restrictions within three (3) years.",
      "links": [

      ]
    },
    {
      "ordinal": 2,
      "title": "Preference 1b",
      "subtitle": null,
      "description": "Persons who live and work in Foster City.",
      "links": [

      ]
    },
    {
      "ordinal": 3,
      "title": "Preference 2",
      "subtitle": null,
      "description": "Persons who live in Foster City.",
      "links": [

      ]
    },
    {
      "ordinal": 4,
      "title": "Preference 3",
      "subtitle": null,
      "description": "Employees of the City of Foster City.",
      "links": [

      ]
    },
    {
      "ordinal": 5,
      "title": "Preference 4",
      "subtitle": null,
      "description": "Classroom teachers who are employees of the San Mateo-Foster City School District, the San Mateo Union High School District and the San Mateo County Community College District.",
      "links": [

      ]
    },
    {
      "ordinal": 6,
      "title": "Preference 5",
      "subtitle": null,
      "description": "Persons who work in Foster City.",
      "links": [

      ]
    },
```
 
do you want an aggregate for 6 preferences in a single column?

**Comment by kathyccheng** [comment]
@pbn4 I don't think these are the right preferences for OHA, there shouldn't be any mention of Foster City. 

But in terms of structure, ideally I'd like the column to be titled Oakland Housing Authority Project Based Vouchers, and then in each row should be which of the options the applicant selected, we can use the ordinal title field for the names. Those should be titled "Residency, Family, Veteran, Homeless" based on how Emily had structured it. But we need to also consider the option "No preferences apply but I still want to be considered." If they chose the none of these option, the column should be blank. So I'd expect to see values like: 
"Residency, Family" 
"Homeless" 
"No preferences apply but still want to be considered" 
" " 

If that's especially tricky, we can have a column for each of the ordinal sub-preferences, but we still need a column for "no preferences apply but I still want to be considered" just for the OHA set
