### ISSUE TITLE
Create Jurisdiction Module

### ISSUE THREAD

**Issue by seanmalbert** [bloom-housing/bloom#1286]
A jurisdiction module is necessary, so we can begin to add configuration and logic based off of a jurisdiction. Currently, we base this kind of logic off of CountyCode. The use of the jurisdiction model will replace that, though that need not be done in this task.

The jurisdiction table/entity should have the following initial fields:
- id: UUID
- name: string
- timezone: string

**Comment by pbn4** [comment]
Partially addressed by https://github.com/bloom-housing/bloom/pull/1391 (missing timezone)

**Comment by kathyccheng** [comment]
I think this is good
