### ISSUE TITLE
Create Jurisdiction X Feature Relationship

### ISSUE THREAD

**Issue by seanmalbert** [bloom-housing/bloom#1288]
More background information on this can be found in this [TDD](https://docs.google.com/document/d/1vRvfEW5xQVU5WlND6j8Pbr1BPP5I5sdffzE4PkOBODc/edit?usp=sharing) 

Jurisdictions and features have a many-to-many relationship. Once this is done, we'll be able to easily set and maintain feature flags per jurisdiction.

The table should have these fields:
- jurisdiction_id: fk on jurisdiction.id
- feature_id: fk on feature.id

**Comment by kathyccheng** [comment]
@ludtkemorgan for reference for configuration work

**Comment by ludtkemorgan** [comment]
@sarahlazarich This ticket is something that should be done after our conversation on https://docs.google.com/document/d/1vRvfEW5xQVU5WlND6j8Pbr1BPP5I5sdffzE4PkOBODc

**Comment by ludtkemorgan** [comment]
Combined with #1287
