### ISSUE TITLE
Create Wiki Entry for Contribution Guidelines

### ISSUE THREAD

**Issue by seanmalbert** [bloom-housing/bloom#1289]
The document should outline the steps necessary for a contributor. It should include at least the following:
- Reference to Code of Conduct
  - To be addressed in separate issue
- Getting Started
  - Reference setup section of wiki and Readmes
- Issue Tracking
  - An explanation that our development tasks are managed through GitHub issues and any development should be addressed via an issue. Existing issues should be checked before creating a new one.
- Pull Requests
  - What we expect form a pull request
- Review, Approval and Merging
  - Our review and merging guidelines

**Comment by emilyjablonski** [comment]
https://github.com/bloom-housing/bloom/wiki/Contributing

**Comment by emilyjablonski** [comment]
@seanmalbert Does the above look good to you?

**Comment by kathyccheng** [comment]
@seanmalbert take a look!

**Comment by seanmalbert** [comment]
Looks good!
