### ISSUE TITLE
Replace Moment JS

### ISSUE THREAD

**Issue by seanmalbert** [bloom-housing/bloom#1290]
Moment is a heavy date library that create mutable date objects, which can make it unreliable and a pain to work with. This will become more prevalent  as we have to deal with multiple timezones.

@dominikx96  has experience with datejs and recommends that, but I don't know how active the development is for this. On my last project, I started to replace moment with date-fns, which follows a modular, functional pattern and is immutable by default (I am biased towards this).

This issue is to evaluate and decide on which library will replace moment and then to replace it.

**Comment by dominikx96** [comment]
@seanmalbert dayJS* :) 

https://github.com/iamkun/dayjs/

**Comment by jaredcwhite** [comment]
Day.js looks nice to me, I like keeping the Moment-style API.

**Comment by jaredcwhite** [comment]
I guess the other main option that bubbles up is https://github.com/moment/luxon (but I don't find its API particularly compelling).

FYI, I tried swapping out Moment for Day.js on a couple components and it seems like a piece of cake.

**Comment by seanmalbert** [comment]
@dominikx96 and @jaredcwhite ,

I think the only requirements I had on my end is that the dates are immutable and it supports timezone, so if you both like Day.js and it's easier to replace, then I'm for it.

**Comment by jaredcwhite** [comment]
This has been done and on dev for some time. Closing.
