### ISSUE TITLE
Build out Application Service v0

### ISSUE THREAD

**Issue by jacchau** [bloom-housing/bloom#130]
**Infrastructure:**
- [x] Database + ORM
- [ ] Schema create migrations
    - listing
    - unit
    - preference_rule
    - income_eligibility_chart (fka AMI chart)
- [ ] Object versioning

**Build out endpoints:**
- [ ] /Applications/submit => returns ID
- [ ] /Applications/{userID}/list => returns list of applications received for userID
- [ ] /Applications/{ID} => returns Application JSON

**Comment by bk3c** [comment]
@pbn4 I realize that we're still working on a number of things on the Infrastructure list above, but do the endpoints below make sense to stub out? I'm not wedded to the exact naming or semantics listed above (e.g. the `list` endpoint taking the userID as a query param might be better), but it seems like maybe we can build little hard-coded stubs for each of them to get the API details ironed out and the front-end components in-progress?

**Comment by pbn4** [comment]
@bk3c Here's my proposition:

```
POST /users/<userId>/applications        => returns appId
GET /users/<userId>/applications         => returns applications array for a given user
GET /users/<userId>/applications/{appId}  => returns single Application JSON
PUT /users/<userId>/applications/{appId}  => updates existing application
```

Then it **should** play nicely with permissions e.g. user can access only those that match his uuid and a super user can access any. 

For super users I'd create a separate endpoint for querying 

```
GET /applications?userId=id&listingId=id => returns all applications (queryable by user and listing id)
```

What do you think?

**Comment by bk3c** [comment]
@pbn4 That looks great to me as a starting point, so let's go with it and we can adjust later if need be.

As a way to get started while we figure out the eventual object model, what do you think about just having an `applications` table with a big jsonb column for the content of the application, along with the normal meta fields for ID, created_at, etc? I'm mostly sure it's not where we want to end up, but it seems like the quickest way to get basic functionality of saving and loading.

**Comment by pbn4** [comment]
I recognize that we had a discussion about having permission guard at service level. According to [this](https://docs.nestjs.com/faq/request-lifecycle) services can not be decorated with guards decorators. Maybe it's a good moment to think about https://github.com/bloom-housing/bloom/issues/315
