### ISSUE TITLE
Create an Enum for unitType for units module

### ISSUE THREAD

**Issue by seanmalbert** [bloom-housing/bloom#1335]
Right now on the unit entity, unitType is a string, but there are places in the backend that rely on it being a certain set of values, introduced with https://github.com/bloom-housing/bloom/pull/1306 in units-transformations. If we make an enumerable UnitType for both the model and code to use, we can ensure there aren't any issues going forward.

1. Create an enum with the following values: "studio", "oneBdrm", "twoBdrm", "threeBdrm"
2. Update the model to use this enum
3. Replace the use of `UnitTypeSort` in shared/units-transformations with this enum

**Comment by emilyjablonski** [comment]
@seanmalbert I think we can close this :)
