### ISSUE TITLE
Create v0 of a Submit Application flow

### ISSUE THREAD

**Issue by jacchau** [bloom-housing/bloom#135]
In this initial version of the Submit Application flow, we want to set up the basic form flow, even though it'll include a relatively small percentage of the overall fields and validation logic. Based on #131, let's start with react-hook-form as the form library, and then re-evaluate that decision at the end of this task to confirm it's the right direction.

- [ ] add a field or value to a listing to indicate that it will take an online application of type X (since we're 100% likely to have variance in applications between listings, but also we want to offer easy reuse). Forms will probably need both a nanoid and a user-facing name.
- [ ] create a (JSON?) format for the application options to be stored in the future Application Service (and eventually edited through the Partners Portal). This can then be hard coded as a flat file into the front-end until we build that out.
- [ ] create the first few screens of the form, capturing name and contact info, as well as information about members of the proposed household. See designs from @slowbot, though consistent with the early Bloom days we're not looking for anything close to pixel perfection, so focus on functionality as long as things are set up in a way that's easy to polish later
- [ ] submit the form to a soon-to-be-developed endpoint, complete with user feedback if the application isn't accepted by the service for any reason.

The list of subtasks is likely missing items, so adjust as neccessary.

**Comment by bk3c** [comment]
Superseded by other issues, so closing in favor of them.
