### ISSUE TITLE
Yarn peerDep warnings related to ""workspace-aggregator..."

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#137]
This has been happening for a while and we've been ignoring it without a bigger problem, but I just wanted to document the relevant Yarn issues that are causing the warnings for tracking, especially since it looks like they might be fixed soon. Check out:

https://github.com/yarnpkg/yarn/issues/5810
https://github.com/yarnpkg/yarn/pull/7812

**Comment by antoine-malliarakis** [comment]
Hello,

Sorry for bothering you, but as the author of PR https://github.com/yarnpkg/yarn/pull/7812 I was wondering: is there anything I had missed in terms of process to ensure it moves to the next stage? (whether towards rejection or approval of course) 

All apologize for any inconvenience caused

Thanks

**Comment by bk3c** [comment]
@antoine-malliarakis Sorry, I don't think we have much insight to offer you, since we're just downstream users of yarn and not involved with the development team. I will say that we were able to resolve most of our peerdep / workspace-aggregator warnings within this project by just making sure that all of the peers were explicitly declared in every workspace they were used, which is probably the desired pattern anyway.

I know yarn 2 was just released, and I understand there are significant updates to workspace handling, so if you haven't already it might be worth checking to see if that resolves the issues. We haven't gotten there yet. Otherwise, if this is a PR you're excited to move forward then it's sometimes helpful to @ a maintainer who's done work in the area and maybe they'll take a look?

**Comment by antoine-malliarakis** [comment]
@bk3c thanks for the advice I'll look into both (if the issue is already solved with yarn 2, it may be no wonder why I wouldn't get answers there :D)
