### ISSUE TITLE
Spike to increase visibility of outside collaborators PRs

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#1386]
What are ways that we can highlight outside collaborator PRs? Can we auto-add labels to them? Post in slack? Or maybe we just add labels to ours and filter on those without labels? Lots of options to make sure we are seeing these easily and more quickly

Came out of Retro on 6/17

**Comment by YazeedLoonat** [comment]
I think the slack github notifier covers this
closing
