### ISSUE TITLE
Spike to consider tools to better filter our logs / error messages

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#1387]
Look into possibilities for better filtering and understanding our logs/error messages (ie the storm of error messages we have right now coming out of Heroku)

Sentry is one option, consider pricing

Came out of retro on 6/17

**Comment by pbn4** [comment]
@emilyjablonski Is this frontend only or both?

**Comment by ludtkemorgan** [comment]
This can be closed in favor of https://github.com/bloom-housing/bloom/issues/3593
