### ISSUE TITLE
Listings - Open House 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1445]
**Goal**: Leasing agent should be able to add open house events to a listing 

**Fields**:
Field Name | Entity Model | Type | Current State | Required
------------ | ------------- | --- | ----- | -----
Open House Date | | date | No | Yes
Open House Start Time | | date | If selected | Yes
Open House End Time | | date | If selected | Yes
URL | | date | ? | No

**Acceptance Criteria**
- If user adds Open House, open modal with Open House date, times and URL fields
- Once saved, display summary of event in Open House table

**Notes:** 
* Add Open House module to the Application Dates section of the listings mgmt fields 

**Figma**:
Default:
https://www.figma.com/file/Y8bFd0aSz7eYJ2TCNid6s3/bloom-partners?node-id=2726%3A127598

Filled:
https://www.figma.com/file/Y8bFd0aSz7eYJ2TCNid6s3/bloom-partners?node-id=2726%3A127818

Modal:
https://www.figma.com/file/Y8bFd0aSz7eYJ2TCNid6s3/bloom-partners?node-id=2736%3A126754

Open House:
https://www.figma.com/file/Y8bFd0aSz7eYJ2TCNid6s3/bloom-partners?node-id=2736%3A126865

**Comment by seanmalbert** [comment]
This is currently accommodated by the events field directly on the listing. I would like this to be moved off onto the listing_events table, which already exists, but is lacking an entity. This will need to be added and the field definition in lisitng.entity will need to be updated to create the one (listing) to many (event) relationship. A migration script should also be created to move the current event data into the table with the corresponding listing.

**Comment by kathyccheng** [comment]
This looks good!
