### ISSUE TITLE
Listings Mgmt - Validations MVP 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1446]
Need to add first set of validations

**Comment by seanmalbert** [comment]
Spreadsheet with fields and if they're required: https://docs.google.com/spreadsheets/d/1yzy7t1n0lNuhjmElnBH7rFOk2qZYdK7iHwhnyY3QrmM/edit#gid=0

**Comment by kathyccheng** [comment]
Closing to handle in #1541 and #1542
