### ISSUE TITLE
Add notifications for Unit Form

### ISSUE THREAD

**Issue by seanmalbert** [bloom-housing/bloom#1452]
With the addition of units to listings management, a user can save and create a copy or save and create a new unit. We need to add a notification, so that when a user clicks this they know that the initial record they save was created/updated.

Relates to #1350

**Comment by seanmalbert** [comment]
We can use the same toast notification used when we saved. There's also a styling issue with the box, so that should get fixed as well.

**Comment by seanmalbert** [comment]
If a new unit, messaging should read "Unit Created".

**Comment by kathyccheng** [comment]
Closed with updates to copy and save behavior
