### ISSUE TITLE
Dev infrastructure improvements

### ISSUE THREAD

**Issue by jaredcwhite** [bloom-housing/bloom#1456]
This issue tracks remaining items to implement or fix for the switchover from `master` to `dev`.

- [x] Verify all Netlify apps are present (Public, Partners, Storybook, anything we're forgetting?)
- [ ] Verify all tests pass (that should pass)
- [x] Verify the Heroku backend used is a "staging" backend, not "production" backend (even though production in Bloom core is just for QA/demos)

**Comment by seanmalbert** [comment]
All netlify apps are now present:
Public - https://dev-bloom.netflify.app
Partners - https://dev-partners-bloom.netlify.app
Storybook - https://dev-storybook-bloom.netlify.app (was missing)

Verified that bloom-backend-dev was setup as a "staging" app.

**Comment by seanmalbert** [comment]
Still have to verify all tests.
