### ISSUE TITLE
Straggler 0 on the preview 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1460]
Under the Additional Fees section, there's a straggler "0" that's hanging out. This seems to be when the longitude and latitude are zero and the map doesn't render.  

![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/65cd6fe8-fc8b-4c29-9f12-f3254d36cd1d)

**Comment by jaredcwhite** [comment]
@kathyccheng @emilyjablonski  I believe this was fixed by #1463 ?

**Comment by kathyccheng** [comment]
Closed in #1463
