### ISSUE TITLE
Minor visual bugs on menu, button components

### ISSUE THREAD

**Issue by akegan** [bloom-housing/bloom#1465]
We just did a visual design review of our react homepage ahead of launch, and the design team found some design issues that they marked as blockers for deploy. 

These are two minor ones

## 1. Button color ~~and animation~~
Button border doesn't match the fill
![Button border color issue](https://user-images.githubusercontent.com/11825994/124334227-4a450700-db4b-11eb-97e7-3b3b8eaee6f7.png)

~~Button fill doesn't have the nice animation that we have on DAHLIA (current is on top, bloom version is on the bottom)~~
Edit: We won't fix this in this ticket, Exygy is not interested in the animation piece)
![button_animation](https://user-images.githubusercontent.com/11825994/124334183-2aadde80-db4b-11eb-9f10-3b821a07273c.gif)

## 2. Extra whitespace between menu focus state and background image
![1 px gap between highlight and image](https://user-images.githubusercontent.com/11825994/124334248-5a5ce680-db4b-11eb-9335-c2e020b07d4d.png)

cc @emilyshore

**Comment by akegan** [comment]
Next step, pull out button transition into a separate ticket. Exygy is not interested in the button transition. 

Other 2 are fine to keep in the same ticket.

**Comment by kathyccheng** [comment]
Closed in #1596
