### ISSUE TITLE
Double-submit issue with Listings forms

### ISSUE THREAD

**Issue by jaredcwhite** [bloom-housing/bloom#1480]
In `sites/partners/src/listings/PaperListingForm/index.tsx`, the `onSubmit` handler for the `Form` component was running through a flow in an `onSubmit` function to save data and redirect to the listings detail page. However, in the the `sites/partners/src/listings/Aside.tsx` component, clicking either Publish or Save as Draft triggers `setStatusAndSubmit` which adds a bit of additional logic and then runs the `onSubmit` function. Essentially the two end up running simultaneously and thus perform a double-submit.

I believe the event handlers for the buttons in Aside run before the form's submit handler, so likely the best outcome here is to do any necessary state setup from Aside and then let the form's submit handler run automatically. Otherwise, we can provide an empty function to the form's submit handler directly and only rely on the buttons performing full submits.

I'm also noticing a similar pattern for the PaperApplicationForm so we should double-check that as well to ensure we don't have double-submits.

Thoughts?

**Comment by seanmalbert** [comment]
@jaredcwhite ,
I opened a PR which addresses this issue @ https://github.com/bloom-housing/bloom/pull/1501, which removes the need for the setStatusAndSubmit function.
