### ISSUE TITLE
Add description prop to ImageCard to allow for descriptive alt text

### ISSUE THREAD

**Issue by akegan** [bloom-housing/bloom#1487]
While addressing #142 with #1450, axe found an issue where on ImageCard we were passing the title as the alt text for the image. It was flagged because the recommended best practice is to not repeat image alt text as text on the page. There's more info about this rule [on the Deque website](https://dequeuniversity.com/rules/axe/4.2/image-redundant-alt?application=axe-puppeteer). 

As a temporary fix, [we added the alt text](https://github.com/bloom-housing/bloom/pull/1450/files#r662674459) of "A picture of the building" to the alt text, but we'd like to follow up to allow for a description prop to be passed as alt text because the image card could in theory be used in different contexts. If the description prop is not available, we want to default to empty alt text to avoid having the title read out twice.

**Comment by seanmalbert** [comment]
This was actually done with #1450 .

**Comment by akegan** [comment]
OK then I'll close that out
