### ISSUE TITLE
New Pre-Application Listing State

### ISSUE THREAD

**Issue by jacchau** [bloom-housing/bloom#153]
**Description:** Create a 'Pre-Application' listing state for property managers/ developers to market their listings prior to when the application period is opened

**User Story**
As a property manager
I want to publish a 'Pre-Application' listing
So that the property manager can market the listing prior to the application period is opened

**Acceptance Criteria**
1. The admin can update the 'Application Open Date' on a listing.
2. When the 'Application Open Date' is less than system current date, then the listing is in 'Pre-Application' state.
3. When that the listing is in the 'Pre-Application' state, then the following fields are changed and hidden in the listing:
- change 'Application Deadline [Application Due Date] to 'Application Open Period from [Application Open Date] to [Application Due Date]' in the listing page
- Hide 'Download Application' button and replace with sub text 'Application will be available for download and pick up on [Application Open Date]
- Hide 'Contact Leasing Agent' section
- change 'Application Deadline: [Application Due Date]' to 'Coming Soon: [Application Open Date]'
- Hide 'Waitlist box on listing sidebar' component

**Comment by jacchau** [comment]
Future design consideration: As we get more listings in the system, should Coming Soon listing be mixed with Open Listings? If they are grouped together do coming soon listings come first or last? (Hypothesis is last). (cc @slowbot )

**Comment by jaredcwhite** [comment]
@jacchau One thing I'm confused about…does this change to the data model still require a value for the Application Due Date? Or is that due date optional and we can have just a future open date?

**Comment by jaredcwhite** [comment]
@jacchau Also, should we hide the whole waitlist box on the listing sidebar as well?

**Comment by jacchau** [comment]
@jaredcwhite sorry for responding to this late. Yes, I was thinking that the Application Due Date would still be required so that we'd have the two dates (1) Application Open Date and (2) Application Due Date. The Application Open Date would always be before the Application Due Date. 

Pre Application State: Current System Date < Application Open Date. 
Open Application Period (normal listing state): Application Open Date < Current System Date < Application Due Date
Close Listing: Application Due Date < Current System Date 

Good point, let's hide the whole waitlist box as well, let me add that to the AC.
