### ISSUE TITLE
Cleanup Main Readme

### ISSUE THREAD

**Issue by seanmalbert** [bloom-housing/bloom#1534]
The main readme file should be reviewed in general and cleaned up where appropriate. These sections for example could be cleaned up:

### Installing Dependencies
This section needs review and updates, since it does not cover all dependencies. It's OK to add more robust setup instructions under each sub directory and reference them here. This may be preferable.

### Adding a new app
I'm not sure we even want this here, or at the very least we should clearly state that if you need to create a new app, please discuss with the core team.

### Contributing
There should be a link here to a Contributing page in the Wiki. Adding those pages is a separate task (#1289 )

**Comment by emilyjablonski** [comment]
Moved app-specific setup to those readmes, removed the adding a new app section, added the contributing information to the core readme from the wiki, and generally just added missing information and removed outdated information.
