### ISSUE TITLE
Ability to Apply Online by directing to a third party site

### ISSUE THREAD

**Issue by jacchau** [bloom-housing/bloom#154]
**Summary:** Alameda County's pilot Eden Housing will work with a third party vendor to allow for application intake to occur online. Alameda Bloom needs to allow for the application button to redirect to this third party site

**User Story:**
As a property manager
I want to redirect users to a third party vendor for application intake within the listing
So that users can apply online using a third party service

**Acceptance Criteria**
- Admin can indicate that a listing is accepting online applications
- Admin can indicate the link to the third party service URL for online application intake
- Given the listing accepts online application, when the user views the listing, then the 'Download Application' button is changed to 'Apply Online' and when the user clicks on the 'Apply Online' button, it redirects the user to a third party service's 'URL'

**Notes**
Is the 'accepting_online_applications_boolean' being used? If not, would it make sense to repurpose that field?

**Comment by jaredcwhite** [comment]
@jacchau That sounds good to me. We can utilize the attachment system we already have, and use that boolean to alter the way the button displays.
