### ISSUE TITLE
Listings Mgmt Validations: Preview and Save as Draft - Backend

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1541]
As a leasing agent, 
I want to it to be easy to save a draft and preview,
So that I can easily save work as I go along 

**Acceptance Criteria** 
* When I am on a new listing form, and I click Save without having filled anything in, then I expect to see an error letting me know I need to add a listing name
* When I fill in a listing name, and I click Save, then I expect it to be a success and I will see the listing summary page
* When I am on a new listing form, I expect to see the defaulted values in the form 

**Notes** 
* Move validation to back end

**Required Fields** 
* The only field that is required for Save as a Draft or Preview is Listing Name 
* I believe this is the current behavior already 

**Updates to the Listing Form** 
* Remove from the form defaults - 
  * Year Built (2021), 
  * Leasing Agent Email (test@email.com)
  * Application Fee $0
* Add form default - Is waitlist open --> NO 
* Add default rental assistance text to form: The property is subsidized by the Section 8 Project-Based Voucher Program. As a result, Housing Choice Vouchers, Section 8 and other valid rental assistance programs are not accepted by this property.
* Add form default Deposit Min and Deposit Max to $0

**Updates to the Public Site Defaults** 
* Remove from public form defaults - 
  * Neighborhood if empty, 
  * Application Fee section if empty, 
  * Rental Assistance text (because this should be on the form instead) 
  * It should not default to the Referral type with the For More Information, that block should only be there if they choose referral in application types 

**Spreadsheet** 
This summarizes all of the updates above 
https://docs.google.com/spreadsheets/d/1yzy7t1n0lNuhjmElnBH7rFOk2qZYdK7iHwhnyY3QrmM/edit#gid=515768701

Public Listing Screenshot for Reference 
https://share.getcloudapp.com/DOuqOlXn

**Comment by seanmalbert** [comment]
@pbn4 , @software-project and @jaredcwhite ,

So I can make sure I understand what was proposed from the planning meeting regarding state and validation management, here is how I'm understanding it from a basic high level.

- On the backend we want to define some structure or structures that can be used to determine what fields on the front end should be required. This structure could also be used to maintain the error states based off of the state change action.
- in the backend service, we can use this structure along with the data submitted to determine if the listing can be updated to the intended state.
  - there seems to be some discussion needed around whether we want to save any part of that as unpublished first and then return the errors (if action is publish)
 - if there is a submission error, we map those validation errors, where appropriate, to the validation structure and send back for the frontend to use. Any errors that don't get mapped to the fields would display in the general error bar at the top of the form.

I think @software-project had brought up using something like Redux, which we can consider, or at the very least we can take its main concept of having state, actions and reducers, where a reducer is a function that takes the current state and an action, which in this case would be the submission of data with a status change, as arguments and returns a new state (which for this may include the validation structure). It may also make sense to dispatch the submission of data and changing the status as separate actions.

**Comment by jaredcwhite** [comment]
@seanmalbert That outline makes sense to me. I'm not sure Redux is what we're looking for here…I'm thinking more like a FSM (Finite State Machine) specifically (e.g., I'd reach for this if in the Rails world: https://github.com/aasm/aasm). Maybe something like this? https://github.com/statelyai/xstate/tree/main/packages/xstate-fsm

**Comment by software-project** [comment]
@seanmalbert I agree with @jaredcwhite, I'm not sold on Redux concept and I don't think thats what we need. Xstate should work much better. We can use guards as kinda validators. The way I would approach it in Ruby is wrap model in context class that would validate it and map fields with errors.

**Comment by seanmalbert** [comment]
Please note that the actual research and work for the state machine will be done in #1582 . The implementation on the frontend for draft will be handled here.
