### ISSUE TITLE
Listings Mgmt Validations: Required to Publish 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1542]
As a leasing agent, 
I want to know what's required to publish a listing
So that I know I have inputted all the right information

**Acceptance Criteria** 
* When I am filling out a listing, and I click publish, if I don't have all of the required fields filled out, then I will see an error message message and all of the fields I'm missing highlighted in red 
* When I have filled out all of the required fields, and I click publish, then I will be taken to the summary view where I can preview the listing and I will see the listing live on the public site 

**Notes**
* Update error message from "There was an issue submitting the form" to "Please resolve any errors before publishing your listing." 
* Validating the listing to transition to Open state 

**Required Fields** 
* Name
* Developer
* Asset
* Is there a digital application? - boolean
* Is there a paper application? - boolean
* Is this a referral opportunity? - boolean
* Building Address
* Units - At least one unit
* Deposit Min
* Deposit Max
* Rental Assistance
* How is the application review order determined?
* Is the waitlist open?
* Leasing agent email
* Leasing agent name
* Leasing agent phone 

**Notes**
* This issue DOES NOT consider dependency or sub-object required dependencies

**Reference Spreadsheet**
https://docs.google.com/spreadsheets/d/1yzy7t1n0lNuhjmElnBH7rFOk2qZYdK7iHwhnyY3QrmM/edit#gid=515768701

**Comment by kathyccheng** [comment]
@slowbot please update error copy

**Comment by kathyccheng** [comment]
Need to figure out how we move between states

**Comment by seanmalbert** [comment]
From conversation the other day, we're going to create two separate "dtos" to validate the fields against. These could be usable on the frontend and backend. @pbn4 , can you add more info based off of what you're doing with state management.

**Comment by seanmalbert** [comment]
On the boolean types, if the user says "yes", then they need to add at least one of those items.

**Comment by seanmalbert** [comment]
For these types:
Is there a digital application? - boolean
Is there a paper application? - boolean
Is this a referral opportunity? - boolean

We want to add actual boolean fields on the model to make this easier.

**Comment by seanmalbert** [comment]
@pbn4 ^
