### ISSUE TITLE
Listings Mgmt: Lat/Long Map 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1545]
As a leasing agent, 
I want to see the map location and be able to edit the pin
So that I can be sure the map is pointing to the right location especially because for new construction, it might be on the maps properly yet 

**Acceptance Criteria** 
* When I edit an existing listing that has an address already entered, then I will see the Map preview in the Building Details section with Automatic option defaulted 
* When I try to interact with the map with the Automatic option selected, then I can't do anything between it fixes the address to the pin 
* When I select Custom, then I can move the pin around. When I move the pin around, I expect the address to remain fixed based on what I had entered 
* When I move the pin in the edit view with Custom selected and then click Save or Publish, then I expect to see the updated pin on the preview and public listing if it's already published
* When I select Automatic after I have selected Custom, then I expect the pin to go back to the default based on the address selection 

Notes
* We should probably use Mapbox's own library 
* There's no preview on the summary view of the listing 
* We will need to make a back end update to add a boolean to know whether it's custom or automatic 

**Designs** 
https://www.figma.com/file/Y8bFd0aSz7eYJ2TCNid6s3/bloom-partners?node-id=4017%3A167126
https://www.figma.com/file/Y8bFd0aSz7eYJ2TCNid6s3/bloom-partners?node-id=4112%3A170185

**Comment by akegan** [comment]
This could be useful for SF too! We just recently had a listing called 290 Malosi, but that street doesn't exist yet, so they had to put in another address to get the pin to show up correctly. 

Seems tough to do though!

**Comment by emilyjablonski** [comment]
@kathyccheng I'm not sure what `There's no preview on the summary view of the listing` means?

**Comment by kathyccheng** [comment]
@emilyjablonski when you save a listing as a draft, there's a page that renders all of the information with the preview action. I just mean you don't need to show the map on that page

**Comment by kathyccheng** [comment]
This looks good! Closing
