### ISSUE TITLE
Timezone rendering for application due date time 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1562]
Double check if timezones are working okay

**Comment by emilyjablonski** [comment]
I'm not able to reproduce issues with the application due date or time, can someone post some repro steps?

**Comment by dominikx96** [comment]
@emilyjablonski @kathyccheng I'm sorry for the confusion, I tested it again and noticed, the problem is in the non-incognito mode where I have my local timezone, not PST, in incognito with PST everything works as expected!

**Comment by kathyccheng** [comment]
Closing
