### ISSUE TITLE
Add new ListingCard component

### ISSUE THREAD

**Issue by akegan** [bloom-housing/bloom#1574]
[slack thread](https://sfinnovation.slack.com/archives/CMMDVPPDX/p1627343685011100)

When looking at the [ListingsList](https://github.com/bloom-housing/bloom/blob/master/ui-components/src/page_components/listing/ListingsList.tsx) component to try to pull out the direct dependency on a listings list, we realized that it would make more sense to create a customizable ListingCard (or ListingDirectoryCard) component, then do the mapping of listings array to list of ListingCards in the bloom app.

# AC

Create a new ListingCard component that accepts `ImageProps`, and `TableProps`
For ImageProps:
- use same image card (DAHLIA has pills, multiple statuses) with props: Title, subtitle, imageUrl, pill label, statuses, link to listing

For TableProps:
- Try to see if we can use the same interface with: headers, data, responsive collapse, cell class name, style (style = ‘bloom’ || ‘dahlia’
- @software-project  is going to pivot his table work to see if he can extend the GroupedTable component.

**Comment by akegan** [comment]
@emilyjablonski here's Marçin's PR creating our pricing table styling for reference https://github.com/bloom-housing/bloom/pull/1566. We're not actually using it yet so it's alright to modify that as a part of this work too if that makes the most sense.

**Comment by seanmalbert** [comment]
@emilyjablonski and @akegan , can this issue be closed?
