### ISSUE TITLE
Improve management of app -> service url mapping

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#159]
For the moment, we're putting a url for each service as an environment variable on the Netlify deployment of each app. Some drawbacks of this setup are:

- no version control or workflow around maintaining these
- no inherent documentation of non-obvious jsonpath queries
- not well suited when we get to complex configuration (e.g. poll listings from multiple services)

None of these are pressing, but it would be good to find a better solution as we evolve the API mechanics themselves.

**Comment by ludtkemorgan** [comment]
This will be better tackled when we move to AWS
