### ISSUE TITLE
Create process for managing listing photo and assets

### ISSUE THREAD

**Issue by jacchau** [bloom-housing/bloom#161]
Add detailed process on how to upload, manage, and serve photos on listings

**Comment by jaredcwhite** [comment]
So, I believe this process would work:

* Check the photos into `apps/public-reference[or equivalent]/public/images`
* In the listing JSON, use a relative URL (i.e. `/images/someimage.jpg`)

Maybe try creating a new subfolder in images, say listing-photos, then the URL could be: `/images/listings-photos/someimage.jpg`

**Comment by bk3c** [comment]
This would be great to validate with one of our reference museum listings, but sounds like the right general plan to me.

**Comment by jacchau** [comment]
Tested process with reference museum listings and works well! Closing issue.
