### ISSUE TITLE
First Come First Serve with Due Date Label 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1629]
If a listing is first come first serve with an application, 
* Change label to show both on the listings details page, line break 
* Change label to show both on the listings page, comma separated 

Don't re-introduce business logic into this component 

![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/f39906c4-11b8-43df-a474-6f16d5465f1b)

**Comment by emilyjablonski** [comment]
![Screen Shot 2021-08-17 at 10.16.14 AM.png](https://images.zenhubusercontent.com/601c7ede5322cf8ac29d50c4/b09da9b3-0aa2-4c22-be07-17606e831617)
@kathyccheng Going to line break them both based on the above, pending other suggestions

**Comment by kathyccheng** [comment]
This looks good, closing
