### ISSUE TITLE
Update Next

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1685]
There are security vulnerabilities in our current version of Next which is forcing us to update to the latest version sooner than later.

We are upgrading from 10 to 11 - https://nextjs.org/docs/upgrading#upgrading-from-version-10-to-11

Most of this looks pretty straightforward, but this will also bring us up to webpack 5 and react 17, which may have consequences on its own.

**Comment by kathyccheng** [comment]
Some dependencies on react 16

**Comment by jaredcwhite** [comment]
Supersedes #1215

**Comment by seanmalbert** [comment]
For QA, you basically need to do a run through and make sure everything looks and works as expected. It will probably be useful to compare this to the live public site to catch any unintended changes.

**Comment by kathyccheng** [comment]
Closing, see progress in #857
