### ISSUE TITLE
Add user-friendly custom error pages

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#170]
Since we don't have the additional info pages defined yet they're currently showing a 404, but it's a very generic / unhelpful 404 error page. Clearly we should fix the actual link in this case too, but I think it would be prudent to also define branded and user friendly error pages as well, in case someone has a URL typo or anything else that causes a page not to be served.

@jacchau can you work on defining the text and desired look for this page?
@jaredcwhite while we're waiting for that, can you go ahead and get the pages roughed out?

**Comment by jacchau** [comment]
Hi @jaredcwhite , I added some very generic copy here in the content library for Bloom. https://docs.google.com/spreadsheets/d/1aSSDQTNIjUEZADwUF_Ew4NRoPMUKZl0UK0PjnpUyrIU/edit#gid=85678091 (see Heading and Heading 2) for copy. 

I'd suggest we have the global header, menus, and footer as the home page but change the hero heading and heading 2. Let me know if this makes sense, it's hard to tell without it having mocked up.
