### ISSUE TITLE
Common App - Demographics Update

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1739]
As an applicant, 
I want to be able to identify as multi racial
So that I can give the county accurate demographic information about myself 

**Acceptance criteria:**
- Race options should be presented as checkboxes allowing for multi-select
- The following races should have conditional sub-options
   - Asian
      - Asian Indian
      - Chinese
      - Filipino
      - Japanese
      - Korean
      - Vietnamese
      - Other Asian
         - Add text box
   - Native Hawaiian or Other Pacific Islander
      - Native Hawaiian
      - Guamanian or Chamorro
      - Samoan
      - Other Pacific Islander
         - Add text box
- It should continue not to show up in the CSV export from partners
- It should continue to show up in the CSV export endpoint with demographics

**Design Mockup**
https://www.figma.com/file/oU5mI1afPd9zjt9vNxcLFa/bloom-short-form?node-id=598%3A4676

Content Mockup
![image](https://user-images.githubusercontent.com/3453407/130714150-725317ce-f767-4bab-8bd6-2059ac3dfe32.png)

#### Public App

1. Go to https://dev-bloom.netlify.app/ and choose a listing that has a common digital application
2. apply to the listing and when you get to the `applications/review/demographics` section, select the race checkboxes to test
3. continue to submit the application
4. go to https://dev-partners-bloom.netlify.app/ and find the listing for which you submitted the application
5. view that listing's applications and find the application(s) you submitted
6. edit the application and scroll to the demographics section, you should see what you selected for race

### Partner App
1. you can continue with where you left off above and edit the race selection or create a new application – save
2. Re-edit the application and you should see the changes you made persist
3. go back to the application list and click `export`, open the downloaded CSV file
4. you should not see any demographic information, since includeDemographics is set to false in the request

**Comment by seanmalbert** [comment]
Two options on how we can store this:
1. keep the existing field and decide on string `paths` we can use to parse out what we need for the form, so something like `Asian[Chinese, Filipino];Black or African American;`
2. Add a new cat/subcat structure in the db to relate to demographics

**Comment by kathyccheng** [comment]
@emilyjablonski can you swap the order of the Race and Ethnicity questions while you're at it?

**Comment by kathyccheng** [comment]
This looks good, closing
