### ISSUE TITLE
Listings Management - Add Building Selection Criteria 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1755]
As a leasing agent, 
I want to specify additional building selection criteria 
So that I can provide more information 

Acceptance Criteria
* Field exists on listings management form 
* Public site will now 

Questions
* Will this always be a link? Should we support a form or text?

**Comment by jaredcwhite** [comment]
@slowbot @kathyccheng Makes sense. Are we currently showing this data on the public site in some other fashion? Will this require new field in the backend schema?

**Comment by kathyccheng** [comment]
We want to update the backend schema because right now it's a text field and we want to keep the text field, but add in a building selection criteria file 

On the partners form, have 2 separate fields 
* If they choose URL, saves to the text field
* If they choose File, saves to new file field 


On the public site, we can send through the same thing

**Comment by seanmalbert** [comment]
To add to that, in the listing DTO, we can  do a transform for the current criteria field that checks for the existence of buildingSelectionCriteria or buildingSelectionCriteriaFile, and map the URL to the same field, so we don't have to make changes to the frontend.

**Comment by jaredcwhite** [comment]
Thanks @kathyccheng and @seanmalbert. I'll see if I can manage updating the backend schema for the new file field, and then work on the upload form.

**Comment by seanmalbert** [comment]
@jaredcwhite ,
The DTO is inheriting the field from the entity, which we generally do for fields that are not relationships, so this is expected. As part of this, you will need to add an entry for `buildingSelectionCriteria` that uses a `@Transform`, to check for `listing. buildingSelectionCriteriaFile` and if it's there return the URL instead of the text. You'll also need to omit `buildingSelectionCriteriaFile` from the DTO. Does that make sense?

**Comment by jaredcwhite** [comment]
@seanmalbert OK I grok that…will let you know if I get stuck later on.

**Comment by jaredcwhite** [comment]
@slowbot Updated. Let me know how this seems to you: https://deploy-preview-1994--dev-partners-bloom.netlify.app
