### ISSUE TITLE
Clean up general.json key names

### ISSUE THREAD

**Issue by jacchau** [bloom-housing/bloom#176]
[ ] Check each general.json key name to see if it is used in the code and categorize unused key names into the following categories:
1. missing feature
2. key name not used (needs to be deprecated) 

[ ] Identify hard coded strings - will need @jaredcwhite 's help to change values to key names and go through each page to identify hard coded strings

**Comment by jaredcwhite** [comment]
@jacchau FYI, this seems to overlap with https://github.com/bloom-housing/bloom/issues/158

**Comment by jacchau** [comment]
good point, I will close this issue for now - duplicate of #158
