### ISSUE TITLE
Foon Lok West - Greystar - Customizations 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1770]
**Customizations Needed** 

**1. Add Building Selection Criteria**  
https://www.midpen-housing.org/wp-content/uploads/2021/09/Foon-Lok-West-Resident-Selection-Criteria.pdf

**2. Update Oakland Housing Authority Preference** 

Title: 
OAKLAND HOUSING AUTHORITY PROJECT-BASED VOUCHER
Description: 
You are currently applying to be in a general applicant waiting list. Of the total apartments available in this application process, several have Project-Based Vouchers for rental subsidy assistance from the Oakland Housing Authority. With that subsidy, tenant households pay 30% of their income as rent. These tenants are required to verify their income annually with the property manager as well as the Oakland Housing Authority. If you are interested in these apartments, the following preferences also apply.

Sub-Preferences

Title: 
Residency
You have lived and/or worked in the City of Oakland when you submitted your initial application and/or at the time of your application interview for a Project-Based Voucher and can verify your previous residency/employment at the applicant interview.

Title: 
Family
You are a family with two or more persons, or a single person applicant that is 62 years of age or older, or a single person applicant with a disability.

Title: 
Veteran
You are a Veteran or active member of the military.

Title: 
Homeless
You are an individual or family who meets the McKinney-Vento Act definition of homelessness. Family is identified as: individuals who lack a fixed, regular, and adequate nighttime residence and: (i) children and youths who are sharing the housing of other persons due to loss of housing, economic hardship, or a similar reason; are living in motels, hotels, trailer parks, or camping grounds due to the lack of alternative adequate accommodations; are living in emergency or transitional shelters; or are abandoned in hospitals; (ii) children and youths who have a primary nighttime residence that is a public or private place not designed for or ordinarily used as a regular sleeping accommodation for human beings; (iii) children and youths who are living in cars, parks, public spaces, abandoned buildings, substandard housing, bus or train stations, or similar settings; and (iv) migratory children who qualify as homeless for the purposes of this subtitle because the children are living in circumstances described in clauses (i) through (iii).

**3. Make sure CSV export has all of the preferences for the listing**

**Comment by kathyccheng** [comment]
https://docs.google.com/document/d/17x8R-seuz7S28JnE62j6BfFsRdkrkDkhaGOJ7KXuq1w/edit

**Comment by seanmalbert** [comment]
@kathyccheng ,

1. added building selection criteria
2. added the new preference, I didn't assign it yet to the listing, but it's the one in all caps as you have above
3. I set the export type to use the 'ohaFormat', which has preferences and PBV. You can run an export on the listing and look at the columns. Let me know if I should update that format or create a new one.

**Comment by seanmalbert** [comment]
There is a new string for the preference which is on staging, but I'll have to push up to prod.

**Comment by kathyccheng** [comment]
@seanmalbert for the CSV export, here are the columns currently on production
* It shouldn't have HOPWA
* It should have the other preferences associated with Foon Lok on production - Displaced Household, Neighborhood Residents, Oakland Residents and Workers

![image](https://user-images.githubusercontent.com/3453407/135646070-0598ad59-1a77-447b-980e-a6559f1c3e92.png)

**Comment by kathyccheng** [comment]
@sean is the string update on staging on the old preference for Oakland Housing Authority? I can't see it because when I add it to the listing, it's not showing up in the application for some reason. And then when I go to an old listing with that preference like Coliseum, it doesn't seem updated.

**Comment by seanmalbert** [comment]
@kathyccheng , you can now see the update here https://partners.housingbayarea.org/listings/b802eb20-867a-4519-98cc-fa02c6c92c22

**Comment by kathyccheng** [comment]
@seanmalbert when I finish the income part and proceed to the preferences section, I get this error

![image](https://user-images.githubusercontent.com/3453407/135660556-9db61661-f8bb-4ada-bb94-c4375f6ad051.png)

I have a feeling it has to do with the same thing that was causing this to happen on Starling, but in the case of Starling it worked. I'm not sure we're using that /preferences/all path? Or it might be because we don't have a Live/Work in Alameda County first on the list? 
![Screen Shot 2021-09-30 at 3 14 09 PM](https://user-images.githubusercontent.com/3453407/135660630-d09f2176-7681-4aa1-a501-2ca8cfade3ac.png)
