### ISSUE TITLE
Fruitvale Studios - Abode - Customizations 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1771]
**Customizations Needed** 
* Are there any new preferences? 
  *  Please give title, description, any sub-options and read more text
* Are there any new AMI charts?
  * Please provide the whole chart so we can add it into the system 
* Are there any new community types? 
  * Please provide title and description 
* Is there a building criteria document? 
  * Please provide the URL 
* Is there anything else we need to add to support this listing?

**Comment by vubang228** [comment]
- Listings management doesn't allow for multiple unit floors to be selected for "unit types"
- Listings management doesn't allow for just "hearing" to be selected in ADA/accessibility in "Listings Units"
