### ISSUE TITLE
Create unit tests in partners 

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#1786]
Add a new CircleCI job to run the tests on PRs
As part of this work, add these tests back in: https://github.com/bloom-housing/bloom/pull/1744

**Comment by jaredcwhite** [comment]
FYI, there was some initial work I did to add unit tests here: https://github.com/bloom-housing/bloom/pull/2012.

**Comment by jaredcwhite** [comment]
https://github.com/bloom-housing/bloom/pull/2012 has now been merged into dev.

**Comment by seanmalbert** [comment]
This looks to be done!
