### ISSUE TITLE
Upgrade to Next.js 9.4

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#182]
Looks like Next.js 9.3 is out, with [some new features that are meaningful for us](https://nextjs.org/blog/next-9-3#next-gen-static-site-generation-ssg-support).

The minimal version of this is just to update the dependencies, since nothing major seems to be deprecated, but I think it's probably also worth investigating:

- [ ] If we can use the native SCSS handling now and simplify the config, and if there's an opportunity / need to otherwise refactor the CSS to take advantage of their new support
- [ ] Whether it's worth switching to getServerSideProps for listings data, in anticipation of a database-backed service that changes much more frequently than the code does (obviously it shouldn't make any positive difference at the moment, since any content updates will also be repo updates)

 This is probably a good time to update other related dependencies as well, in the general effort to stay current.

**Comment by jaredcwhite** [comment]
Yeah, there's a bunch of cool meaty stuff in this update. I'm starting to feel the effects of churn in the codebase right now though so maybe this is something we can tackle after the first release of the public apps.

**Comment by bk3c** [comment]
Among other things that would be nice to take advantage of in 9.4 is the ability to send performance data (e.g. load and render times) to Google Analytics. See [the release announcement](https://nextjs.org/blog/next-9-4) or [this documentation page](https://nextjs.org/docs/advanced-features/measuring-performance#sending-results-to-analytics) for more details.

**Comment by jaredcwhite** [comment]
This might be easier than I thought…somehow I had gotten the idea that they'd deprecated or moved away from the `exportPathMap` function in the config, but looking at the docs it seems like that's still good to go. :+1:

**Comment by bk3c** [comment]
@software-project I'm flexible about how much you want to take on as part of this. It looks like we could do a pretty minimal upgrade but there are also updated patterns in the last few releases that we could move to and set ourselves up for the future. If it's helpful to make issues for things that we should do at some point but are too big for an initial PR, feel free.

**Comment by software-project** [comment]
@pbn4 @bencpeters @jaredcwhite @bk3c, regarding the CSS/ SASS discussion that I started yesterday. 
Next has css and sass support but it has it limits/ way of working. Right now we are using 
```
// next.config.js
const withSass = require("@zeit/next-sass")
const withCSS = require("@zeit/next-css")
```
both of those module are not need, but we would need to include styles in a specific ways:
- Option 1: use build-in modules that can load styles along with components. That requires keeping the naming convention: `Button.tsx | Button.module.scss`. There might be a problem with components that are using external stylesheets like mapbox. But I could try doing a `Map.module.scss` file that would use SASS `@import` to load mapbox styles from the node_modules folder.
- Option 2: Keep using `next-sass` and `next-css` as they are used right now.
- Option 3: Combination of above. Use modules when we can and option 2 for external csses.
A side note the issue that @bk3c reported (#305) might be related to this config, because we are not using modules, everything is imported all together. 

Source: https://nextjs.org/docs/basic-features/built-in-css-support

**Comment by bk3c** [comment]
@software-project I think the consensus as I understand it is that in general we want our styles to continue to be global, imported primarily from `ui-components`, but with the opportunity for a small number of overrides local to a particular site/app. I'm definitely open to improving the syntax and setup of how we do the imports and trying to align with the preferred nextjs way of doing things, but I'm also fine with the current solution since it doesn't seem too cumbersome.

That said, I think Mapbox and other similar external CSS dependencies are somewhat of a different case, and if I remember correctly, that's the only place where we're using CSS instead of SASS, so maybe we can clean that up. It seems to me to be a good place to have the styling only be component-scoped, so I would be in favor of trying to make that happen as long as it's not too much work or I'm missing a downside of that approach (@slowbot? @jaredcwhite?)

**Comment by jaredcwhite** [comment]
@bk3c That makes sense to me. Mapbox's CSS is a third-party dependency so I don't think we'd need to do anything to change it.

**Comment by software-project** [comment]
@bk3c @jaredcwhite I'm a little confused. Correct me if I'm wrong, but our styles, that are in `ui-components` are global as per project, but are not global in Next.js sense. Global next.js css would be imported in `_app.jsx` and css for lets say `ImageCard` is imported within `ImageCard.tsx` which makes it not global. 
So do we want to keep using:
```
// next.config.js
const withSass = require("@zeit/next-sass")
const withCSS = require("@zeit/next-css")
```
or should I remove css/scss imports from components and move them to `_app.jsx` ?

**Comment by jaredcwhite** [comment]
@software-project It's global in the sense that all the little scss partials are tracked by Webpack and eventually compiled into a single global stylesheet with global classes. Importing from within a component TSX file doesn't actually scope anything.

So we want to continue in that vein, in whatever manner Next will best facilitate that. I'm not sure exactly what Next changed in their update to remove the next-scss plugin.

Thanks, let me know if you'd like to pair up on further investigation.
