### ISSUE TITLE
Add A11Y linting tools

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#1825]
eslint-plugin-jsx-a11y for static linting which runs on yarn lint. 

@axe-core/react for dynamic "linting" which comes in the form of console errors when you run the app

try to configure so it doesn't block git commits for false positives

**Comment by seanmalbert** [comment]
@kathyccheng , I moved this into next sprint, hoping that we can make room for it.

**Comment by emilyjablonski** [comment]
QA Notes (QA-able by only a dev locally): 

I tried to look through all of our public site pages and fix any axe console issues (I bet I missed a few with the # of pages). I only fixed some in partners just because there were more there that were more complex / required refactoring & I didn't want to inflate this PR. I think the expectation going forward is to fix any you see or create as you're working on any pages.

You can checkout some of the app and keep the console open & see what if any a11y errors are logged.

**Comment by ColinBuyck** [comment]
LGTM!
