### ISSUE TITLE
Test on IE

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1872]
"As of v2.0, Tailwind CSS is designed for and tested on the latest stable versions of Chrome, Firefox, Edge, and Safari. Tailwind CSS v2.0 does not support any version of IE, including IE 11."

**Comment by jaredcwhite** [comment]
Also worth noting that MS won't even support IE 11 on some newer Windows versions by June 2022.

https://blogs.windows.com/windowsexperience/2021/05/19/the-future-of-internet-explorer-on-windows-10-is-in-microsoft-edge/

**Comment by emilyjablonski** [comment]
@kathyccheng Are we currently supporting IE?

**Comment by YazeedLoonat** [comment]
with changes may want to re-evaluate this: @emilyjablonski @jaredcwhite thoughts?

@kathyccheng not sure if we still intend to support IE though

**Comment by emilyjablonski** [comment]
We have dropped IE support we can close this
