### ISSUE TITLE
Add npmignore files for ui-components and core

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#189]
I think this is mostly an issue for ui-components given the size of the storyshots, but as long as we're publishing we might as well do core for good measure.

The goal here is to make sure we're only publishing what we need at runtime -- no testing stuff or config files, etc.

NB: apparently defining an npmignore makes yarn/npm no longer ignore the things in gitignore by default, so we need to make sure we copy all those entries and probably leave some comments in both places reminding our future selves to make sure the appropriate things are listed in both places.

**Comment by bk3c** [comment]
refs:

- https://zellwk.com/blog/ignoring-files-from-npm-package/
- https://medium.com/@jdxcode/for-the-love-of-god-dont-use-npmignore-f93c08909d8d

**Comment by bk3c** [comment]
For whatever reason yarn doesn't give you stats when you publish, but since lerna uses `npm` to publish even when we're using yarn for package management, they make it painfully obvious.

`npm pack --dry-run` should show a pretty complete list of all the things we're needlessly putting in the package. Some of them should maybe be added directly to `.gitignore`, and some (e.g. storyshots) we definitely want in the the repo but not to publish.

**Comment by pbn4** [comment]
@bk3c The author of the 2nd article actually suggests using a whitelist. What do you think about that? He makes a good point with .env files being leaked.

**Comment by bk3c** [comment]
After thinking about this a little more, I'm relatively unconcerned about leaking .env files or similar secrets from those packages since they're shared code not specific to any site, and thus less likely to have secrets we're worried about leaking to begin with.

That said, if there's a way to do the more secure explicit whitelist without setting a trap for us to trip over every time we forget to add something to the whitelist, I'm all in favor of the extra security. I'm just not sure it's worth the complexity in this case...
