### ISSUE TITLE
Update default character limit to 1000

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1890]
As a leasing agent, 
I want the flexibility to add text that might be lengthy because of the policy documents
So that I can make sure the language is accurate

**Acceptance Criteria:** 
* Change default character count limit on all text fields using text area component to 1000 
* Change the previously specified character count limits that were set to 600 to 1000 too 

**Notes:** 
* For the previously specified, we can remove an override and use the default 
* Those fields were: 
Property Amenities
Unit Amenities
Pets Policy
Accessibility
Smoking Policy
Services Offered
Credit History
Criminal Background
Rental History
Rental Assistance
Required Documents
Special Notes
Important Program Rules

Last Issue: #1781

**Comment by dominikx96** [comment]
Thanks again @emilyjablonski ! I removed `maxLength: 1000` and set 150 for old components, also branch is up to date with dev :)
