### ISSUE TITLE
Disability Seeds

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1896]
Right now, this is the accessibility priority type options 
![image](https://user-images.githubusercontent.com/3453407/135289239-bcca4a16-7195-4562-879a-ef06990653ad.png)

We want to clean those up to:
Mobility
Hearing
Visual
Hearing and Visual
Mobility and Hearing
Mobility and Visual
Mobility, Hearing and Visual

**Comment by seanmalbert** [comment]
I updated the seed to the above list and updated production to have the correct list and mapped incorrect set ones to the right types where applicable. 
![Screen Shot 2021-09-30 at 7 38 36 AM](https://user-images.githubusercontent.com/4401157/135476428-82c62f1b-5f70-4471-b137-991eff28d7d9.png)

**Comment by kathyccheng** [comment]
Looks good, closing
