### ISSUE TITLE
Add sample core product translation strings

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#19]
While most text and translated strings will be implemented in the end-apps, it seems like shipping with validated strings for things like “bedroom” in N common languages is worthwhile to consider for the core product.

This is less about comprehensive localization, and more about making sure we have a good home for shared/core strings separate from the individual app ones, and a process for doing the work.

As a related documentation note, when doing the actual translations for both these shared strings and any reference implementation, we should document the process and provide links to resources and service providers as appropriate.

**Comment by akegan** [comment]
@bk3c @jaredcwhite and I were just discussing housing translations for strings used in components in the shared/ui-components folder, with the ability for individual implementation to override it. Do you think that that discussion/implementation belongs in this ticket too, or are you thinking about core vocabulary that isn't necessarily associated with a component but is useful to multiple sites.

**Comment by kathyccheng** [comment]
Closing with recent translation work
