### ISSUE TITLE
Re-enable Apply and Download links 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1909]
On the preview, re-enable the Download and Apply links for the digital and paper applications so we can test on production

**Comment by seanmalbert** [comment]
Enabled on alameda staging. https://ala.bloom.exygy.dev/preview/listings/611f91c8-60f2-45cd-ac85-bf1a2cd47508

**Comment by kathyccheng** [comment]
@seanmalbert this looks good!

**Comment by seanmalbert** [comment]
This is on prod now. https://housing.acgov.org/preview/listings/b802eb20-867a-4519-98cc-fa02c6c92c22

**Comment by kathyccheng** [comment]
Closing
