### ISSUE TITLE
Investigate switching to conventional commits and automatic releases

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#193]
As we start to scale up contributors, it might be useful to use [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) (along with maybe [Commitizen](https://github.com/commitizen/cz-cli)) and something like [Semantic Release](https://github.com/semantic-release/semantic-release) to reduce the manual work for publishing releases and improve developer documentation. 

This might be too much overhead/standardization in the short term, but filing the issue now to track interest for future implementation.

**Comment by bk3c** [comment]
See also [this blog entry](https://www.asyncapi.com/blog/automated-releases/) for an example of how to tie things together with Github Actions.

**Comment by bk3c** [comment]
#210 should probably happen before we start on this.

**Comment by emilyjablonski** [comment]
Just seeing this issue for the first time! :D We have this now
