### ISSUE TITLE
GA Updates 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1932]
**Acceptance Criteria**
* When I hit the listings browse page, then I will be able to see the new event with associated properties
* When I hit the listings browse page, then I'll see new properties in the default pageview event
* When I hit a listings page, then I will be able to see the new event with associated properties

**Documentation** 
https://airtable.com/shrpTlCXtMyA1KcBe/tblKovUImJGAwtBWw/viwTKj8YzvsZSrSxr/reckU7m12jBWhyoaZ

**Updates** 
* Add listing ids to listing view event
* Remove download application to additional eligibility properties on view listing event

**Comment by seanmalbert** [comment]
I let Lori know that the events were up on https://dev-bloom.netlify.app/ for her to view.

**Comment by kathyccheng** [comment]
This is good to go!
