### ISSUE TITLE
Closed Listings Clean Up 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1938]
**What Happened**
* When we released the FCFS and Lottery updates to Listings Mgmt, some of the older listings got labelled as FCFS by accident 

**Acceptance Criteria**
* The closed listings on Alameda should reference the original closing dates + First Come First Serve vs Lottery types 

**Notes**
All of these are lottery types, not FCFS, and some have to update application due date. 

* Reilly Station - Lottery
* Jones Berkeley - Lottery
* City Center Apartments - Lottery
* Coliseum Place - Lottery
* 1475 167th Ave - Lottery, Due Date: July 6, 2021 at 5pm PST
* Monarch Homes - Lottery, Due Date: September 28 2020 at 5pm PST
* The Skylyne at Temescal - Lottery, December 1, 2020 at 5pm PST
* Atlas - Lottery, Due Date: October 6, 2020 at 5pm PST
* Logan - Lottery, Due Date: November 15, 2020 at 5pm PST

**Not Same as Above But** 
* The Mix at SoHay - Can we check why lottery date is invalid? 

**No changes necessary**
* Nova - N/A
* Jordan Court - N/A
* Loro Landing - N/A
* The Starling - N/A
* Blake at Berkeley - N/A
* Foon Lok West - N/A
* Aurora - N/A
* Alexan Webster - N/A

**Comment by seanmalbert** [comment]
@kathyccheng ,
Can you provide the list of which ones should be cleaned up?

**Comment by seanmalbert** [comment]
@kathyccheng ,
These are all updated. The Mix at SoHay had an invalid date, because the lottery result event didn't have a date set. I set it to April 14, 2021, which was set for the "lottery" event on the listing.

**Comment by kathyccheng** [comment]
LGTM!
