### ISSUE TITLE
ciricleci - redis setex error in listing e2e tests

### ISSUE THREAD

**Issue by seanmalbert** [bloom-housing/bloom#2006]
There appears to be a race condition, where the app is closed before requests are finished. In the listing module, we have a listener for `onModuleDestroy`, which quits redis. This is necessary, otherwise processes will hang and tests will time out. What we're seeing is that after redis.quit is called, we see the cache manager in `ListingLangCacheInterceptor` try and set a key on the out going response.

We need to ensure that there isn't a race condition, and since this doesn't happen every time, there likely is one. We probably also want to more gracefully handle the issue, so that if the app is closing and the connection to redis severed, the outgoing response can finish without erroring.

**Comment by pbn4** [comment]
@seanmalbert There is a chance I have fixed it here https://github.com/bloom-housing/bloom/pull/1996/files#diff-ba40c0bff6d29c78535cef3678d3a7aa022c54d976b4b387fb74c827d6d638b4R71 by calling flush immediately before quitting, so that there are no outstanding redis requests when closing the app.

**Comment by YazeedLoonat** [comment]
no longer an issue
