### ISSUE TITLE
In LM, cannot save a mailing, pickup, or dropoff address

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#2018]
I create a published listing with the minimal fields on dev.

-----

I cannot save a mailing address.

I check "paper apps are mailed to another address" and fill out the mailing address.

We send `arePaperAppsMailedToAnotherAddress: true` but no `applicationMailingAddress` and cannot save a mailing address

------

I cannot save a unique pick up address.

If I try to set a unique pick up address I get the following errors:
{"statusCode":400,"message":["applicationPickUpAddress.id must be an UUID","applicationPickUpAddress.id must be a string","applicationPickUpAddress.createdAt must be a Date instance","applicationPickUpAddress.updatedAt must be a Date instance"],"error":"Bad Request"}

------

I cannot save a unique drop off address.

I don't get any validation errors but if I try to save with a unique drop off address on save it just reverts to saying that you cannot drop applications off. (I can say that we can drop off and save it as the same as the leasing agent address).

**Comment by kathyccheng** [comment]
@emilyjablonski I still can't seem to save the mailing address for paper applications. I enter it and then when I come to the listing, it isn't there

**Comment by emilyjablonski** [comment]
Should be able to save a unique dropoff, pickup, and mailing address

**Comment by kathyccheng** [comment]
LGTM
