### ISSUE TITLE
Mapbox console warnings on listing page

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#204]
Seen on the Alameda site, but I'm pretty sure it's a core problem:

1. `This page appears to be missing CSS declarations for Mapbox GL JS, which may cause the map to display incorrectly. `
2. `A cookie associated with a cross-site resource at http://mapbox.com/ was set without the 'SameSite' attribute. It has been blocked...`

Neither appears to be a major user-facing problem at the moment, but I think better to fix stuff like this sooner rather than later.

**Comment by software-project** [comment]
@bk3c seems like point 2. is not a problem: https://github.com/mapbox/mapbox-gl-js/issues/9404#issuecomment-599374704
