### ISSUE TITLE
shared-helpers needs loaders to handle typescript 

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#2065]
![Screen Shot 2021-10-21 at 10.52.47 PM.png](https://images.zenhubusercontent.com/601c7ede5322cf8ac29d50c4/8e1e1deb-de48-4fcc-90f0-3e95ef34a013)

**Comment by jaredcwhite** [comment]
Hey @emilyjablonski, I think this has been resolved now? Or if there is still an issue with the shared helpers package (testing?), just let me know
