### ISSUE TITLE
Duplicates UX Updates

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#2096]
Because duplicate applications have an edit/delete action a developer was actually deleting applications under the assumption they were just deleting the duplicate. We should adjust the UX here. Additionally we might not have made it clear that we are only allowing adjusting duplicates when the applications are closed now.

@slowbot @kathyccheng Can you add any more specific feedback or requests?

**Comment by kathyccheng** [comment]
duplicates #1833
