### ISSUE TITLE
SMC Copy Updates

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2123]
**Notes**
* On Additional Resources, change county contact email from housing@smchousing.org to **doorway@smchousing.org** in Contact 
* On Additional Resources, remove the Foster City reference in Contact 
* On Additional Resources, add a resource under RENTALS -- 
  * Affordable Rental Housing List
  * Affordable Rental Opportunities San Mateo County
  * Link: https://housing.smcgov.org/san-mateo-county-affordable-rental-housing-list
* Add Additional Resource under OTHER RESOURCES
  * Housing Choices
  * Housing Choices provides housing navigation services to people with intellectual and developmental disabilities served by the Regional Center. 
  * Submit a request for Housing Choices Services. 
  * Call 408-498-5777
  * Email intake@housingchoices.org

![image](https://user-images.githubusercontent.com/3453407/143916118-9856e052-23d9-44b0-8dd8-91aa48f635b9.png)
![image](https://user-images.githubusercontent.com/3453407/143916148-63933879-6dfc-468b-b697-75ad0dd8a29e.png)

QA: Available here https://smc.bloom.exygy.dev/

**Comment by seanmalbert** [comment]
These updates are ready for review at https://smc.bloom.exygy.dev/

**Comment by kathyccheng** [comment]
LGTM
