### ISSUE TITLE
The street2 field is not displayed in the ui for alternate contacts

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#2128]
![Screen Shot 2021-11-03 at 11.42.50 AM.png](https://images.zenhubusercontent.com/601c7ede5322cf8ac29d50c4/8118cacb-dc73-4cdc-a6d5-921e65f9d54f)

**Comment by adriencyberspace** [comment]
QA Notes:

Entry Point: http://localhost:3000/applications/contact/alternate-contact-contact

1. Begin an application and select that you have an alternate contact
2. Fill out alternate contact's address and use the second street field (Apt or Unit #)
3. At the review section of the application, you will see your alt contact's full address
4. In partners, open your application and you will also see your alt contact's full address

![image](https://user-images.githubusercontent.com/60076088/165331779-3a090c62-d19b-4b09-988c-d8f31b5ac76a.png)

**Comment by kathyccheng** [comment]
LGTM
