### ISSUE TITLE
If I indicate I don't have an e-mail or a phone number, then hide those from the contact section

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#2131]
On the public site application, before applicants get to this contact preferences question, they have to answer two questions about whether or not they have or don't have an email and phone number.

It doesn't make sense in the below followup question to include phone number and email in this list if we know they have already indicated they don't have one. We should dynamically hide any options they don't have (phone/text or email) based on what they have entered so far.

![Screen Shot 2021-11-03 at 11.58.04 AM.png](https://images.zenhubusercontent.com/601c7ede5322cf8ac29d50c4/3bc0d907-c02f-49f8-b0a3-6f5f2c676f6c)

**Comment by adriencyberspace** [comment]
QA Notes:

Entry point: http://localhost:3000/applications/contact/name

In public portal, get to the /name page of the application.
Check the "I don't have an email address" checkbox
Go to next page, and check "I don't have a telephone number" checkbox
Scroll down to the "How do you prefer to be contacted?" section and see that both the Email and Phone checkboxes are disabled

**Comment by kathyccheng** [comment]
LGTM
