### ISSUE TITLE
Applications Search - require at least three characters

### ISSUE THREAD

**Issue by seanmalbert** [bloom-housing/bloom#2145]
**What is this feature or what feature is this part of?**
In partners when you are looking at the applications table (click on a listing status link in the listings table), there is a text input which is currently querying all applications for every single keypress. This isn't very helpful for the first 2 letters and is not performant. Additionally, between every search, the table toggles a "no rows to show" state.

**Describe the solution you'd like**
The applications endpoint should require at least three characters to perform a search. If applications are searched with fewer than three characters, a 400 should be thrown with a message indicating that at least three characters are required. Make sure that zero characters is acceptable. Additionally, while we are fetching, show a loading overlay over the table so that it does not toggle the empty state.

You can see the frontend in partners/pages/listings/[id]/applications/index, the hook the frontend is using to fetch in partners/lib/hooks called `useApplicationsData`, and the backend endpoints in `applications.service.ts`

**QA Review Instructions**
Go to an applications page for a listing and type in the filter one or two characters and hit enter. You should see a message indicating that at least three characters are required to search. Enter zero, three or more characters and applications should return on the keypress, not on enter.

**Comment by kathyccheng** [comment]
LGTM
