### ISSUE TITLE
Avance - MidPen Listing

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2154]
**Customizations for Avance MidPen**
* New Community Type - Developmental Disability 
* 2 new preferences - Live work in Livermore, Live work in Tri Valley 
* 2 new program questions - Developmental Disability, Developmental Disability Registration (now preferences, do not show on listing)
* 1 new housing authority type preference - Livermore Housing Authority Preferences (do not show on listing)

https://docs.google.com/document/d/1Sb0xkoqd6W-V5JThbJ6eFCXIsdYpkhOKY15xlbLNyuE/edit

Live Work Livermore
https://www.figma.com/file/tUtgsJO8XnF9Ij2dwu22EF/bloom-general?node-id=864%3A2201
https://www.figma.com/file/tUtgsJO8XnF9Ij2dwu22EF/bloom-general?node-id=864%3A2269

Live Work TriCounty
https://www.figma.com/file/tUtgsJO8XnF9Ij2dwu22EF/bloom-general?node-id=865%3A2680
https://www.figma.com/file/tUtgsJO8XnF9Ij2dwu22EF/bloom-general?node-id=865%3A2716

Developmental Disability
https://www.figma.com/file/tUtgsJO8XnF9Ij2dwu22EF/bloom-general?node-id=815%3A1720
https://www.figma.com/file/tUtgsJO8XnF9Ij2dwu22EF/bloom-general?node-id=815%3A1748

Developmental Disability Registration
https://www.figma.com/file/tUtgsJO8XnF9Ij2dwu22EF/bloom-general?node-id=815%3A1778
https://www.figma.com/file/tUtgsJO8XnF9Ij2dwu22EF/bloom-general?node-id=815%3A1803

Livermore Housing Authority Preferences 
https://www.figma.com/file/tUtgsJO8XnF9Ij2dwu22EF/bloom-general?node-id=815%3A2176
https://www.figma.com/file/tUtgsJO8XnF9Ij2dwu22EF/bloom-general?node-id=815%3A2278

**Comment by kathyccheng** [comment]
@slowbot can you add mocks here?

**Comment by seanmalbert** [comment]
I think at this point this has probably been QAd several times. The listing can be viewed at https://partners.housingbayarea.org/listings/1168ac23-f97c-40a0-8a51-ff81736432fe. View the preview at https://housing.acgov.org/preview/listings/1168ac23-f97c-40a0-8a51-ff81736432fe. Apply to the listing to view the preferences and ensure they save.

**Comment by kathyccheng** [comment]
I think this is good at this point, closing
