### ISSUE TITLE
Display the type of listing on the browse listing page

### ISSUE THREAD

**Issue by jacchau** [bloom-housing/bloom#216]
**Summary**
Actual Result: On the browse listing page, the listing type is static and displays 'Open waitlist' only without any dynamic logic. 
Expected Result: The system should be able to dynamically display each of the 3 different types of listings based on 'status' fields for each of the units within the listing.

Type of Listings and logic:
- Available Units: If all the units within the listing are 'available'. 
- Open Waitlist: If all the units within the listing are 'occupied'
- Available Units & Open Waitlist: If the units within the listing are a mix of 'available' and 'occupied'

**Comment by bk3c** [comment]
@jaredcwhite is this still open?
