### ISSUE TITLE
Rosefield - Listing

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2165]
**Customizations for Rosefield**
* 2 New Preferences - Alameda Unified School District, Previous Residents 
* Add Filipino as a language option for Paper Application - we can add this to everyone

https://docs.google.com/document/d/1AkyiQ1W5RxBV4gnbwWWvEMS_SH2mDrtszZOkheuC11Y/edit

**QA NOTES**
verify you can assign the new preferences to listing properly
verify the new preferences on a listing shows on public listing preview properly
verify the new preferences on a listing shows properly on a public application form
verify the new preferences on a listing shows properly on a partner paper application form
verify a saved application has the preferences properly
verify that csv export works with the new preferences

**Comment by seanmalbert** [comment]
The listing went live yesterday and I think we can say that Vu-Bang and the client QAd it.
