### ISSUE TITLE
San Jose - Application Copy Updates

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2166]
**Acceptance Criteria**
* “How did you hear about this listing” option on the demographics page should be “San José Housing Department Website” not "Alameda County HCD" --> This should be tied to jurisdictions 
* On terms page after submission, delete “If we cannot verify a housing lottery preference that you have claimed, you will not receive the preference but will not be otherwise penalized." --> Terms language probably could also be tied to jurisdiction 

### QA Review Instructions
- How did you hear - https://sj.bloom.exygy.dev/applications/review/demographics
- Tems - https://sj.bloom.exygy.dev/applications/review/terms

**Comment by seanmalbert** [comment]
We should use the locale overrides to make these changes.

**Comment by kathyccheng** [comment]
Looks good, closing!
