### ISSUE TITLE
Paper Application shows weird values in confirmation code CSV row

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#2194]
![Screen Shot 2021-11-17 at 10.15.31 AM.png](https://images.zenhubusercontent.com/601c7ede5322cf8ac29d50c4/66557c57-f8a6-4f3a-a85c-e86e06b2ecf1)

**Comment by seanmalbert** [comment]
We could look into escaping the `E`s so spreadsheets do not try and force the code into "E" notation.
