### ISSUE TITLE
SMC Language Nav Update

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2217]
**Acceptance Criteria**
* When I am on the San Jose site, then I will see Tagalog as a language option in addition to Spanish, Chinese and Vietnamese

**Notes**
* Add Tagalog as a language option to San Mateo, this is for San Mateo only, NOT for Alameda or San Jose
* Using the environment variables for languages 

![image](https://user-images.githubusercontent.com/3453407/143912656-6f99cdbb-f5f5-46a8-9715-831b59cdd9d7.png)

**Comment by emilyjablonski** [comment]
This is ready for QA but there is a separate ticket to include the translations themselves. So this is just seeing Tagalog in the nav bar.

**Comment by kathyccheng** [comment]
LGTM!
