### ISSUE TITLE
SMC Add Tagalog to Google Translate

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2218]
**Acceptance Criteria**
* When I am on an SMC listing and click Tagalog, then I expect Google Translate to translate the listing fields we usually translate via Google Translate into Tagalog 

**Notes**
* Add Tagalog as an option for Google Translate
* This should be for SMC only

**Comment by emilyjablonski** [comment]
Waiting to pull over to SMC

**Comment by kathyccheng** [comment]
LGTM, closing
