### ISSUE TITLE
Add polyfills for IE11 support in the public-facing app

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#222]
See https://github.com/housingbayarea/bloom/issues/35 -- it appears that IE11 is not rendering correctly. It seems like NextJS still has underlying support (they fixed a bug in 9.3 that broke it pretty quickly), but I expect it'll be decent work to fix and maintain ongoing.

@akegan - My understanding is that the primary reason we'd want to maintain support is that IE11 is still widely used on publicly available computers in SF, e.g. libraries. Is that still the case for the foreseeable future? It would be great to wontfix this if at all reasonable, but not if that's going to affect a meaningful number of users.

**Comment by akegan** [comment]
yes I believe so. My understanding is that for dahlia we don't expect 100% look for IE11 but it needs to be 100% functional for folks

**Comment by bk3c** [comment]
See also https://github.com/tailwindcss/tailwindcss/pull/1635 when we get to working on this, as a way to identify / prevent CSS that's not IE11 compatible.

**Comment by bk3c** [comment]
@akegan It looks like SFPL is [upgrading all of their computers to Windows 10 with Chrome](https://sfpl.org/services/public-computer-upgrade). I'm not sure what the timing has turned into these days, but do you think there would be an opportunity to forego IE11 support if that's truly in progress? 

It looks to be about 2% of the total DAHLIA user base in 2020 according to GA, down from 4% in 2019, and further declining the last few months that the libraries have been closed. As much as it's a priority for Bloom to make sure we're supporting otherwise underserved users, I'd like to see if we can direct said effort elsewhere.
