### ISSUE TITLE
Detroit Set Up 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2223]
We want to create a setup for Detroit in heroku and netflify that is isolated from the rest of Bloom. It will not have the same shared backend and Googlers will be given permission to access and edit.

**Comment by pbn4** [comment]
@seanmalbert Some questions:

1. What should be the source github? (I don't have access to detroit's fork)
2. What should be the values of following environment variables: 
- CLOUDINARY_API_URL
- CLOUDINARY_ENV
- CLOUDINARY_KEY
- CLOUDINARY_NAME
- CLOUDINARY_SECRET
- CLOUDINARY_URL
- EMAIL_API_KEY
- EMAIL_FROM_ADDRESS
- GOOGLE_API_KEY
- NEW_RELIC_APP_NAME
- NEW_RELIC_LICENSE_KEY

**Comment by seanmalbert** [comment]
@pbn4 ,
We should be getting GitHub access today, and it should point to https://github.com/CityOfDetroit/bloom/tree/main.
I think we only need the cloudinary and email for now, and you can use what we have on dev and we can swap them out when I get them from Gabe.
