### ISSUE TITLE
Listings closed manually should not have application information available

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2228]
**Acceptance Criteria**
* When I am looking at a listing that is closed, then I do not expect to see the Apply button for the common digital application for the Download option for paper application 
* When a listing is closed, the listing summary on the browse listings page should show as closed with the red treatment

**Notes** 
* For Monarch and Alexan, even though the listings are closed, the apply button is still there, it might have to do with the fact that they don't have an application due date
* I don't know if the do not show application logic is tied to application due date or closed status, but it should probably be closed status. Also for the case of manual closes. 
* Right now it looks like if there's no application due date, we don't change the summary bar to red with the closed indicator, it should be marked as closed if the status is closed. 

![image](https://user-images.githubusercontent.com/3453407/143918536-8a4fa8cd-f931-489d-b729-4755b8030660.png)

**QA NOTES**
Create or edit a listing so that:
1) it has no application due date
2) it allows digital applications via the common digital application
3) it has a paper application attached
mark that listing as closed

from there go to the public site and take a look at closed listings
the listing's card should indicate that the listing is closed now
viewing the preview page for that listing should not show application info in the side bar

**Comment by kathyccheng** [comment]
@YazeedLoonat I closed this listing, but on the listing page, the How to Apply section + Submit Paper Application by mail section are still there. Also the text under How to Apply, I've never seen that before! Also, I think the First Come First Serve label probably should also say Applications Closed after First Come First Served

![image](https://user-images.githubusercontent.com/3453407/146274360-f25fd8a5-f894-4bb2-9304-383fe0728646.png)

**Comment by YazeedLoonat** [comment]
@kathyccheng ookay fixes were merged and ready for 👀  again please!

**Comment by kathyccheng** [comment]
LGTM!
