### ISSUE TITLE
Available Units incorrect in Partners

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2229]
**Acceptance Criteria**
* The available units column should show the count for all units for the listing 

**Notes**
* It doesn't look like the available units are always correct 
* In the case of Alexan, there are 3 units on the listing view but 6 on the summary 
* Some listings also don't have anything in this column even though there are units on the listing 

![image](https://user-images.githubusercontent.com/3453407/143917226-d35d0f66-fed3-434e-b31b-a684f04cfbaa.png)

![image](https://user-images.githubusercontent.com/3453407/143917104-be4964cd-6d74-444e-ad0a-9e61dcbaf74c.png)

**Comment by seanmalbert** [comment]
This was fixed.
