### ISSUE TITLE
Store terms on jurisdiction 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2233]
We can start by storing the terms on the jurisdiction.

**Comment by seanmalbert** [comment]
@pbn4 ,
I think all we need for this is a text field on for partner_terms on the jurisdiction.

**Comment by emilyjablonski** [comment]
@kathyccheng Is this the terms at the end of an application? If so not sure I would call them `partner_terms`

**Comment by kathyccheng** [comment]
@emilyjablonski No these are on partners, different terms for the leasing agents to accept
