### ISSUE TITLE
Ala - Duplicates - Cannot open a new tab in Partners and stay signed in

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#2250]
As a leasing agent, 
I might want to have multiple windows open at once in Partners 

**Acceptance Criteria**
* When I am signed in on Partners as a leasing agent, admin or jurisdictional admin, and I open a new tab that's also in Partners, then I should be logged in on all tabs 
* When I sign out of one, then I should be logged out on all 

**Notes**
* This will require some investigation into the best approach - some ideas below: 
* Move towards a session cookie, we think this currently has something to do with how we do session storage  
* We can also use local storage to persist session storage across tabs 
* Will need to update how we handle timeout for inactivity 

**QA NOTES**
The easiest way to test this is to go through a few of the different log in processes

try to log into the public site (as a non-mfa user) then try opening a new tab. You should remain logged in to both without needing to relog in

try to log into the partner site (as an mfa user and later as a nonmfa user). Try opening a new tab, and you should see that user remains logged in the new tab.

you should also try to make sure that if the user is a jurisdictional admin then the permissions should still work correctly

you should be able to log out

you should be able to create/confirm a new public user

you should be able to create/confirm as a new partner user

**QA NOTES**
The best way to test this is to use the stood up environments:
https://bloom-partners-orm.netlify.app/sign-in
and
https://bloom-core-orm.netlify.app/

testers should verify that basically all backend endpoints work correctly. This would include:

testing the flow of creating -> editing -> viewing details for -> viewing in public site for listings

testing the flow of creating -> editing -> viewing details for -> logging in as a user on both the public and parter site

testing the flow of applying for a listing on both the partner and public site

**Comment by emilyjablonski** [comment]
Likely related to #2626

**Comment by YazeedLoonat** [comment]
This is good to go, pending wrapping up of: https://github.com/bloom-housing/bloom/issues/3368
