### ISSUE TITLE
Missing SRO translation string 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2261]
**Notes**
* We're missing one more translation string for SRO unit type on the auto-filled application summary 

![image](https://user-images.githubusercontent.com/3453407/144460998-85b6fb7a-4957-4a83-b955-ed8c4e417708.png)

**Comment by jaredcwhite** [comment]
Hmm, this feels like an issue with bad data coming in. The last segment of the string is `undefined` which to me signals that somewhere in the chain between the listing data and the application data, it's missing a `name` field. I'm not sure how to troubleshoot without additional context on how to reproduce.

**Comment by jaredcwhite** [comment]
(Also if it were defined and were `SRO`, that should work as that string is in the general translation file already.)

**Comment by kathyccheng** [comment]
Repro steps: 
Complete an application with SRO as an available unit type and choose SRO as your unit type preference 
Create an account with that application 
Apply to another application logged in 
You should see this on your last application summary string

**Comment by seanmalbert** [comment]
@kathyccheng and @jaredcwhite , turns out this was an existing bug, where if you follow the repro steps Kathy noted and the two listings have different preferred units, it wasn't setting the name correctly. Thankfully, it was an easy fix.

**Comment by kathyccheng** [comment]
LGTM!
