### ISSUE TITLE
Sorting tables in partners only sorts current view

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#2283]
https://images.zenhubusercontent.com/197330191/18e7387b-506f-49a6-a24e-48ea16151a14/sorting_only_sorts_current_paginated_view.mov

Sorting a column should sort across all results

Could be this error I am also getting but it does sort single views fine

BACKEND_CORE [Nest] 98475   - 12/07/2021, 2:03:15 PM   [ExceptionsHandler] column distinctAlias.applicant_first_name does not exist +113ms
 BACKEND_CORE QueryFailedError: column distinctAlias.applicant_first_name does not exist

**Comment by kathyccheng** [comment]
Should be solved in latest work
