### ISSUE TITLE
Alameda Resource Translations

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2284]
**1. Add translations for resource page for the new resource cards we added this year** 

![image](https://user-images.githubusercontent.com/3453407/145293351-0f4ca061-0169-4236-a4df-36f9ab4f1673.png)

_Translations Below in PURPLE:_
Spanish: https://docs.google.com/document/d/1SNwJX2n0kfnMHY_GbKBUhAwJUUb3H0d8/edit#bookmark=id.7tnxdh6qdv
Chinese: https://docs.google.com/document/d/1kVYfBhPNWwJpp_nG7c4qmEEOLYA5wt1r/edit#bookmark=id.5eow9lhh76c4
Vietnamese: https://docs.google.com/document/d/1CLIIgg_S2h7NEmcZVq8XxCgQ3pJWVyiN/edit#bookmark=id.m4itl2mdi28k

**2. Update 2 missing translations in footer** 
![image](https://user-images.githubusercontent.com/3453407/145293679-69932557-1e3a-498c-b69d-aea6305449f1.png)

_Translations Below in PINK:_ 
Spanish: https://docs.google.com/document/d/1SNwJX2n0kfnMHY_GbKBUhAwJUUb3H0d8/edit#bookmark=id.n8th7xjznz43
Chinese: https://docs.google.com/document/d/1kVYfBhPNWwJpp_nG7c4qmEEOLYA5wt1r/edit#bookmark=id.jg2g2efxdkky
Vietnamese: https://docs.google.com/document/d/1CLIIgg_S2h7NEmcZVq8XxCgQ3pJWVyiN/edit#bookmark=id.w55kvukz3ese

**Comment by jaredcwhite** [comment]
@kathyccheng This is ready to look at here:
https://deploy-preview-383--wonderful-joliot-c00737.netlify.app/additional-resources

**Comment by kathyccheng** [comment]
@jaredcwhite I think the footer text is duplicated in Chinese

![image](https://user-images.githubusercontent.com/3453407/145649129-9c2b83a3-e053-4723-ba68-e36bc886a05b.png)

**Comment by jaredcwhite** [comment]
@kathyccheng I wonder if they translated "Housing Portal" into Chinese but didn't translate the county/city? Looks to my untrained eye like the characters are the same for both links.

**Comment by kathyccheng** [comment]
@jaredcwhite you're totally right, that just was the translation!

**Comment by kathyccheng** [comment]
Okay, then LGTM! let's merge it into Alameda

**Comment by jaredcwhite** [comment]
Sounds good!
