### ISSUE TITLE
Core Application Translations

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2285]
**1. Homepage - Calls to Action** 
![image](https://user-images.githubusercontent.com/3453407/145286549-929e365b-00b9-4167-a2bc-aab60d8660ac.png)

Translations in YELLOW Below
Spanish - https://docs.google.com/document/d/1SNwJX2n0kfnMHY_GbKBUhAwJUUb3H0d8/edit#bookmark=id.20x6wfx5tmz0
Vietnamese - https://docs.google.com/document/d/1CLIIgg_S2h7NEmcZVq8XxCgQ3pJWVyiN/edit#bookmark=id.3jjflfvyzs2x
Chinese - https://docs.google.com/document/d/1kVYfBhPNWwJpp_nG7c4qmEEOLYA5wt1r/edit#bookmark=id.5d10ijoaiwwe

**2. Application - Household Questions** 
* Two new household questions
* Please select yes or no
* Demographics race subcategories

Translations in BLUE below: 
Spanish: https://docs.google.com/document/d/1SNwJX2n0kfnMHY_GbKBUhAwJUUb3H0d8/edit#bookmark=id.elndgnt889n2
Chinese: https://docs.google.com/document/d/1kVYfBhPNWwJpp_nG7c4qmEEOLYA5wt1r/edit#bookmark=id.p3bf0ccd1it8 
Vietnamese: https://docs.google.com/document/d/1CLIIgg_S2h7NEmcZVq8XxCgQ3pJWVyiN/edit#bookmark=id.cqofnuk3s39g

**Comment by seanmalbert** [comment]
These updates can be reviewed on https://dev-bloom.netlify.app/

**Comment by kathyccheng** [comment]
@emilyjablonski the missing string! 
Asian Indian: 
Spanish: Indio asiático
Chinese: 亞洲 印度人
Vietnamese: Người Ấn Độ Châu Á

**Comment by kathyccheng** [comment]
It looks like we're showing Spanish text under Chinese and Vietnamese for How did you hear 

![image](https://user-images.githubusercontent.com/3453407/145608941-0841ef38-2c0c-4eef-8820-5d3c67b0376c.png)

![image](https://user-images.githubusercontent.com/3453407/145608995-b42f3c96-68a0-4f68-a83a-c72a55cd699c.png)

**Comment by kathyccheng** [comment]
LGMT!
