### ISSUE TITLE
Consider an API-first design/documentation tool

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#229]
This has come up in casual conversation a few times, so just making an issue to track thoughts, options, and progress. As we start to have more services to coordinate, two apps (public and partners), and hopefully some external developers, this will hopefully become more of a priority over time.

Options I'm aware of include:

- [Stoplight](https://stoplight.io/)
- [Swagger](https://swagger.io/)
- [OpenAPI Studio](http://openapistudio.com/)

If we go down the OpenAPI route, there's also a big list of tools at https://openapi.tools/, some of which may apply or lead to other options.

**Comment by pbn4** [comment]
@bk3c Have you seen how nestjs/swagger works these days? Maybe this is not an API-first approach, but keeps a single source of truth for what is there. If a need for a different server side implementation pops up one can always take what is generated by nestjs/swagger and base his new implementation on this. What do you think? As you can see I am very eager to use NestJS. :)

**Comment by bk3c** [comment]
@pbn4 It's a good point. I created #263 to track that, which you should feel welcome to jump in on. I'd like to leave this open to track tools that might be good for doing API design ahead of code implementation, but I agree that something like the swagger implementation in Nestjs would get us a good chunk of the way there on the documentation side.

**Comment by bk3c** [comment]
Going truly API-first with tooling seems like it should be on hold for at least the short-medium term, but we're going to still move forward as suggested with the NestJS/Swagger integration via #140.

**Comment by bk3c** [comment]
Ok, closing this as we seem to be coalescing around having the NestJS entities be the single source of truth.
