### ISSUE TITLE
Translate Terms for SJ 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2327]
1. Fix Date - It should be pulling in the due date. The date in the translation is highlighted so you can pull around that. 
![image](https://user-images.githubusercontent.com/3453407/146806958-b2f472fb-0c52-4c41-bc48-13001d38dee6.png)
2. Update terms language in English
3. Add translations for Chinese, Vietnamese and Spanish 

Spanish
https://docs.google.com/document/d/1oh3kIYrp7K-n2MvPL8R3qqoZJaiwDVNk6EIbdNlj-ro/edit#bookmark=id.f7tmu41i2xg0

Chinese
https://docs.google.com/document/d/1GDhm697sltEgvqoAlfAVIgRf_2Et8FqpxwO8Wtv7j3M/edit#bookmark=id.iqrky2wx5kwh

Vietnamese
https://docs.google.com/document/d/1karZhceBVbccFc3x32n2N3McTQjBO-rbxr6nTU2k7-I/edit#bookmark=id.46380cc0wew

**Comment by jaredcwhite** [comment]
@kathyccheng There's now a deploy preview for this here: https://deploy-preview-385--hopeful-rosalind-ded1cd.netlify.app/listings

HOWEVER, there aren't any open listings currently available via the backend. Maybe somebody can refresh the SJ content?

**Comment by jaredcwhite** [comment]
@kathyccheng So these particular translations are code-level/PR-specific. I just made sure the deploy preview is updated, so you should be able to verify this issue before merging here: https://deploy-preview-385--hopeful-rosalind-ded1cd.netlify.app/listing/68ff0fed-37f5-468a-a161-185bb135933a/met_north_2122_monterey_road_san_jose_ca

**Comment by kathyccheng** [comment]
LGTM thanks @jaredcwhite
