### ISSUE TITLE
Translate Emails for San Jose 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2330]
* Update copy in English
* Add translations for Spanish, Chinese, Vietnamese
* For the account confirmation email, update the URL to confirm in each of the languages to reflect the language path, not just the English
* Translations are in yellow in each of the docs below. 

Spanish
https://docs.google.com/document/d/1oh3kIYrp7K-n2MvPL8R3qqoZJaiwDVNk6EIbdNlj-ro/edit#heading=h.z2we68wtdnff

Chinese
https://docs.google.com/document/d/1GDhm697sltEgvqoAlfAVIgRf_2Et8FqpxwO8Wtv7j3M/edit

Vietnamese
https://docs.google.com/document/d/1karZhceBVbccFc3x32n2N3McTQjBO-rbxr6nTU2k7-I/edit#heading=h.z2we68wtdnff

## QA Review Notes
Go to https://sj.bloom.exygy.dev/ and create an account and/or submit an application in a language other than English. The confirmation/welcome email you receive should be in the language you selected.

**Comment by jaredcwhite** [comment]
@seanmalbert I'm having to familiarize myself with how emails are translated on the backend. I think it's all in the database, but I'm not sure what the process is for adding this content to the DB and testing that.

**Comment by jaredcwhite** [comment]
@seanmalbert Oops, it looks like we have a relationship issue on the translations table. Because the jurisdiction is a `OneToOne` relationship, I can't create a second record in a different language with the same jurisdiction ID. I think we'd want it to be a `ManyToOne` relationship instead?

**Comment by seanmalbert** [comment]
@jaredcwhite , updates to change the relationship to a `ManyToOne` have been merged in with #2506. You should be good to continue.

**Comment by jaredcwhite** [comment]
Yep, can confirm. All set to work on this and wrap things up. 👍

**Comment by kathyccheng** [comment]
@jaredcwhite for the application confirmation email - how are we detecting which language the email should send?

**Comment by kathyccheng** [comment]
@jaredcwhite there are different strings for FCFS and Lottery which doesn't look like it's showing up yet 

![image](https://user-images.githubusercontent.com/3453407/156023135-4122958c-2fd7-479d-b622-1c3d71298274.png)

**Comment by jaredcwhite** [comment]
@kathyccheng So I looked into this…it appears there are three different states for that part of the email template — lottery, noLottery, and FCFS. All the translations I plugged in are for noLottery and FCFS…nothing for lottery. Do we need something new for that third state?

**Comment by kathyccheng** [comment]
@jaredcwhite Hmmm I don't know why we have 3 states, I think there should only be 2 - Lottery, FCFS. If we don't want to make that update now, I think FCFS and noLottery should share the same language, and then Lottery would be different.

**Comment by emilyjablonski** [comment]
@kathyccheng These were the two states, just want to confirm that we only want the lottery string and to not have the waitlist string?
lottery: "Applicants will be contacted by the agent in lottery rank order until vacancies are filled.",
noLottery: "Applicants will be contacted by the agent in waitlist order until vacancies are filled.",

**Comment by kathyccheng** [comment]
Yeah ultimately, we only want these 2 states 
lottery: "Applicants will be contacted by the agent in lottery rank order until vacancies are filled."
FCFS: "Applicants will be contacted by the property agent on a first come first serve basis until vacancies are filled."

so we want to remove this one 
noLottery: "Applicants will be contacted by the agent in waitlist order until vacancies are filled.",

**Comment by jaredcwhite** [comment]
@kathyccheng I just had a "duh!" moment on this…_all_ of this text including English will apparently be superseded by the new confirmation email template (see https://github.com/bloom-housing/bloom/issues/2513), so I think we may just want to fast-track #2557 and merge it in before we then focus on this, rather than wait to try to get new translations in.

**Comment by kathyccheng** [comment]
Closing in favor of new one
