### ISSUE TITLE
Investigate adding `max-lines` & `max-lines-per-function` rules for ESLint

### ISSUE THREAD

**Issue by jaredcwhite** [bloom-housing/bloom#2337]
**Update:** looking into a `max-lines` rule as well, so we don't end up overall with really long files which might also be considered a code smell.

----

As part of tech debt cleanup, I wanted to get this on the radar. I did look into it a while back.

Basically the sales pitch here is that we have a number of files with really long functions, as in hundreds of lines, and while sometimes that's necessary and unavoidable, other times I would argue it's a code smell (needs to be refactored, various things broken out, maybe a different pattern would work better, etc.). Adding the linting rule is easy enough, but figuring out what the ideal cap should be might take some doing. The added complication is there can be a lot of lines in a React JSX template function which isn't necessarily that complex because it's largely HTML markup, so that can otherwise throw off a reasonable linting rule.

I'll play around with some different values to try to get a sense of what's passing vs. what's failing, and then maybe I can provide a more informed recommendation for the team to review.

FYI: https://eslint.org/docs/rules/max-lines-per-function

**Comment by jaredcwhite** [comment]
P. S. I need to double-check this, but I'm pretty sure the rule equally applies to methods in a class definition.

**Comment by kathyccheng** [comment]
Closing, associated PR still relevant
