### ISSUE TITLE
Logo button overflow

### ISSUE THREAD

**Issue by pbn4** [bloom-housing/bloom#2344]
**Describe the bug**
![Screen Shot 2021-12-28 at 09 16 17](https://user-images.githubusercontent.com/11684414/147544719-ecf96194-7d60-457c-aa66-8cf752b0f4d3.png)

**Desktop (please complete the following information):**
 - OS: macOS 11.6
 - Browser Google Chrome 96.0.4664.110

**Comment by emilyjablonski** [comment]
Resolved
