### ISSUE TITLE
Fix backend returning an error when email used for forgot password flow does not exist

### ISSUE THREAD

**Issue by pbn4** [bloom-housing/bloom#2346]
**Describe the bug**
Backend should not fail with an error on forgot-password endpoint when given email does not exist because it allows for emails enumeration. 

Current Error:
![image](https://user-images.githubusercontent.com/42942267/203591930-c81293bd-5958-4092-bd89-b08d2d6cfeb9.png)

**To Reproduce**
Go to "forgot password?" page on public portal and try to use invalid email. You will see an error message.

**Expected behavior**
When given an invalid email address backend should still return a success code as if the message was sent.

QA:
Start Here: https://bloom.exygy.dev/sign-in
1. Click Forgot Password
2. Enter a correct email
3. After submitting, you should be redirected to the sign-in page with a neutral message saying that an email was sent if it is correct.
4. Verify that the email was sent
5. Repeat the steps 1-3 above but with an incorrect email

Start Here: https://partners.bloom.exygy.dev/sign-in
Repeat steps 1-5 above

**Comment by sarahlazarich** [comment]
This passed QA for the public site at [https://ala.bloom.exygy.dev/](https://bloom.exygy.dev/sign-in)

I was able to create an account + reset my password at https://partners.bloom.exygy.dev/sign-in. However, my confirmation email did not work -- see below. Not sure if this related to this or a separate issue.

![Screenshot 2023-01-05 at 5 41 36 PM](https://user-images.githubusercontent.com/118844176/210900818-0d584f35-5d1f-41ac-92ba-c0cd2b52969f.png)

**Comment by sarahlazarich** [comment]
Spoke with @ludtkemorgan -- it's a separate issue, good to close.
