### ISSUE TITLE
Explore passwordless authentication for the public app

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#236]
The public-facing application seems like it would be a good candidate for a passwordless authentication flow, since many of the users will be occasional and can't be expected to be excited about creating "another account". Instead of bothering people to create a username and password, we could just use the specified contact information to email/text and authorization link when requested, though it would take some thought to work through all of the edge cases where separate applicants might share contact info.

See [this MSFT whitepaper](https://www.microsoft.com/en-us/security/business/identity/passwordless) for their thoughts and a good intro, and many other resources on the web.

If successful, this could also be used for the Partners App, but I expect there's less need since it's a smaller, more frequent user base who is used to dealing with accounts.

**Comment by bk3c** [comment]
@bencpeters not sure we're going to go this direction, but something to think about as you start work on #133. In all cases I still think what we're issuing is a JWT that will provide the authentication to the apps and services, but eventually a sizable part of this will be all the UI pieces for signup/login/forgot password etc. so happy to take your thoughts on what will be best from an implementation point of view, as well as the work we'll do to figure out what should work best for users.

**Comment by bk3c** [comment]
More links:

- https://siliconangle.com/2020/02/23/passwordless-authentication-not-everywhere/
- https://www.nngroup.com/articles/mobile-login-china/ (I'm definitely not suggesting QR codes)
- https://www.okta.com/security-blog/2019/11/how-to-improve-security-and-usability-with-passwordless-authentication/ (okta obviously has a vested interest)
- https://www.mitre.org/publications/technical-papers/usability-of-biometric-authentication-methods-citizens-disabilities (biometrics focused, but interesting anyway)
- https://www.freecodecamp.org/forum/t/rant-the-case-against-password-less-authentication/180963/15 (just to be fair to the opposing POV)

**Comment by YazeedLoonat** [comment]
we have passwordless now!
