### ISSUE TITLE
Catch up Detroit on Partners

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2361]
Do a fresh one, but can reference existing PR

**Comment by seanmalbert** [comment]
PR up @ https://github.com/CityOfDetroit/bloom/pull/968

**Comment by seanmalbert** [comment]
Detroit dev is now up-to-date with latest bloom core master. https://detroit-public-dev.netlify.app/ and https://detroit-partners-dev.netlify.app/
