### ISSUE TITLE
LM Units - Cannot save unit with AlamedaCountyTCAC2021 and 120%

### ISSUE THREAD

**Issue by seanmalbert** [bloom-housing/bloom#2364]
**Describe the bug**
Units cannot be saved when selecting the AlamedaCountyTCAC2021 chart with 120 as the percentage of AMI.

**To Reproduce**
1. Go to https://partners.housingbayarea.org/
2. Click on Add Listing
3. Scroll down to the units section and add a unit
4. Select AlamedaCountyTCAC2021 and enter 120
5. Try to save the unit
5. You'll see the error in the console

**Expected behavior**
You should be able to add a unit.

**Screenshots**
![Screen Shot 2022-01-06 at 12 54 31 PM](https://user-images.githubusercontent.com/4401157/148443076-0bcf9b08-2da2-43e1-aff5-9cf5f8abbb2b.png)

**Comment by kathyccheng** [comment]
Closing
