### ISSUE TITLE
Add user drawer all listings checkbox should uncheck when list is changed

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#2366]
![Screen Shot 2022-01-06 at 3 13 39 PM](https://user-images.githubusercontent.com/65367387/148459889-0998d05a-dbdd-48b3-937b-7613eb267db8.png)

In the partners application under the users tab, if you go to the add new user form and click "all listings" every listing gets checked appropriately, but then if you uncheck a listing from below, "all listings" stays checked. The listings still save appropriately.

The expected behavior is that when you remove a listing from the listings list that "all listings" should automatically uncheck.

(Initially tested in Firefox)

**Comment by kathyccheng** [comment]
LGTM
