### ISSUE TITLE
Partners Add User Button in Safari

### ISSUE THREAD

**Issue by seanmalbert** [bloom-housing/bloom#2367]
**Describe the bug**
The Add User button's style doesn't appear correctly on first load.

**To Reproduce**
1. Go to https://dev-partners-bloom.netlify.app/users
2. See the Add User button
3. hover over and off it and you'll see it become correct

**Expected behavior**
The button styling is correct initially.

**Screenshots**
<img width="1312" alt="Screen Shot 2022-01-06 at 3 14 52 PM" src="https://user-images.githubusercontent.com/4401157/148459804-a0414747-6b4b-46fd-ad80-0f9a5a95d37e.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: safari
 - Version: 14.1.1 (16611.2.7.1.4)

**Comment by kathyccheng** [comment]
Looks like it's fixed
