### ISSUE TITLE
Partners tables small screen/mobile display issue

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#2370]
**Describe the bug**
The status column on the partners listings table on a small screen are small enough as to not be readable, and there are padding issues in the footer on mobile.

**To Reproduce**
1. Go to the listings list
2. Make your screen size smaller (occurs on small desktop and also mobile)

**Expected behavior**
Not sure, maybe @slowbot will have a suggestion as to whether or not we have a minimum width or only show some columns

**Screenshots**
![Screen Shot 2022-01-06 at 3.30.29 PM.png](https://images.zenhubusercontent.com/601c7ede5322cf8ac29d50c4/4b24b581-adf5-4d31-bcf4-0932a699dad5)

![Screen Shot 2022-03-31 at 3 46 59 PM](https://user-images.githubusercontent.com/65367387/161154768-226ea1a2-8d4f-4279-8c2d-0c0f29fc317e.png)

**Desktop (please complete the following information):**
Firefox

**Comment by YazeedLoonat** [comment]
resolved
