### ISSUE TITLE
Listing page infinitely scrolls horizontally

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#2374]
**Describe the bug**
Listing page infinitely scrolls horizontally
**To Reproduce**
1. Visit an individual listing page
2. Scroll horizontally

**Expected behavior**
Should not scroll

**Screenshots**
https://images.zenhubusercontent.com/197330191/79a83f37-1362-4c9c-a7b6-df3d8a49bf09/scrolly_doo.mov

**Desktop (please complete the following information):**
Chrome, Firefox

**Comment by jaredcwhite** [comment]
Wow, that's wild! 😲
