### ISSUE TITLE
Applications listPaginated search - require at least three characters to search

### ISSUE THREAD

**Issue by seanmalbert** [bloom-housing/bloom#2378]
**What is this feature or what feature is this part of?**
Currently, in the partner portal, a user can search applications with only one or two characters, which isn't useful to the user and fetches too many records.

**Describe the solution you'd like**
We should limit the text search, so that a user must enter at least three characters. If a user attempts to search with less than three, we should return and display a friendly message that they must enter at least three characters to search. We should have this check on the backend and return a 400 with a message like `Please enter at least three characters to search.`

**What is the acceptance criteria/definition of done?**
As a user if I only enter one or two characters, I should see a message that I must enter at least three characters. Upon entering at least three characters, the query should be ran and return the results.

**QA Review Instructions**
This is to be filled out by the developer who completes this issue, before passing to QA.

**Comment by seanmalbert** [comment]
We can also add the check on the frontend.

**Comment by kathyccheng** [comment]
duplicate
