### ISSUE TITLE
Update San Jose Email Moniker

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2383]
Doorway San Jose

**Comment by seanmalbert** [comment]
@emilyjablonski,
This value is currently an environment variable set on the backend, so it is the same for all jurisdictions. We want to add this as a setting on the jurisdiction entity and update the code to read from that, instead of the environment variable. Seeds should also be updated.

**Comment by emilyjablonski** [comment]
Waiting for confirmation on the string 👍

**Comment by kathyccheng** [comment]
Alameda: Housing Bay Area 
SJ: HousingBayArea.org
SMC: HousingBayArea.org

**Comment by seanmalbert** [comment]
@kathyccheng ,
These should now be testable on their corresponding staging URLs:
https://ala.bloom.exygy.dev/
https://sj.bloom.exygy.dev/
https://smc.bloom.exygy.dev/

**Comment by kathyccheng** [comment]
@emilyjablonski are these prefixes just for staging? I don't think we'll want those on production. But I could see how they're helpful on staging. And then if they are just for staging, I would add Staging to them so Alameda Staging just so it's extra explicit. 

![image](https://user-images.githubusercontent.com/3453407/154316033-4b717ad8-00a5-4a06-a709-3541b3baec28.png)

**Comment by kathyccheng** [comment]
On staging - add STAGING to the prefix so SMC Staging: HousingBayArea.org 

On production - drop the SMC, SJ and Alameda prefixes
