### ISSUE TITLE
Open house times listed as range incorrectly 

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#2384]
**Describe the bug**
When start and end time are the same, the open house time is still displaying as a range

**To Reproduce**
1. Create an open house event with the same start and end time
2. Visit the listing, issue is in the right sidebar where we display open house evens

**Expected behavior**
Should show as a single time if start and end time are the same

**Screenshots**
![Screen Shot 2022-01-10 at 1.01.28 PM.png](https://images.zenhubusercontent.com/601c7ede5322cf8ac29d50c4/86f392c2-e8b8-4dfb-a7c2-9b6a4bddddca)

Chrome

**Comment by kathyccheng** [comment]
Closed in #2359
