### ISSUE TITLE
Refreshing in the middle of an application loses draft data, cannot submit without refilling

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#2385]
**Describe the bug**
Refreshing in the middle of an application loses draft data, cannot submit without refilling

**To Reproduce**
1. Start an application, fill out the first screen
2. Hit next
3. Refresh
4. Hit back

The draft data is gone

So you can also fill out an entire application and refresh at the end at demographics, hit next --> terms --> submit and the data is lost as well

Here is the app summary page after refreshing at demographics
![Screen Shot 2022-01-10 at 3.18.03 PM.png](https://images.zenhubusercontent.com/601c7ede5322cf8ac29d50c4/1613508e-973d-46a7-b8a1-e5d750343b47)

Resulting in the below on submit
![Screen Shot 2022-01-10 at 3.18.11 PM.png](https://images.zenhubusercontent.com/601c7ede5322cf8ac29d50c4/36e9ff4d-a92d-4a05-8257-a3929ec39c3c)
**Expected behavior**
Draft data should persist after refresh

Video of loss example
https://images.zenhubusercontent.com/197330191/db18c208-a12c-4b74-babb-d1a8816042b7/screen_recording_2022_01_10_at_3_15_49_pm.mov
(you can also see here we lose the header styling for some reason)

**Desktop (please complete the following information):**
Chrome

**Comment by emilyjablonski** [comment]
Potentially caused by https://github.com/bloom-housing/bloom/issues/2259

**Comment by jaredcwhite** [comment]
Yeah, I'm not exactly sure how this happened but https://github.com/bloom-housing/bloom/pull/2292 shouldn't have gotten merged in. The application-in-flight *must* be cached in browser storage. We should talk about the best way to delete that cached data on idle timeout or completing the application, not remove the caching. cc @seanmalbert @YazeedLoonat

**Comment by emilyjablonski** [comment]
Plan is to follow up in the next backlog grooming about an interim solution until we can plan for a more permanent solution (like saving drafts to the db)

**Comment by seanmalbert** [comment]
Was fixed.
