### ISSUE TITLE
My Applications should show an indication when it is empty, and a spinner while it is loading

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#2396]
**Describe the bug**
When you load my applications under a signed in profile on the public site, nothing displays if it is empty.
Additionally, regardless of many you have, the page sits for second with no feedback as it loads.

**Expected behavior**
We need to have a spinner in the content area while the applications are being fetched and an indication that you have no applications if nothing returns.

Interested in @slowbot input on how both of these states should work.

Loading Component
https://storybook.bloom.exygy.dev/?path=/story/overlays-loading-overlay--default

Blank Slate
https://www.figma.com/file/i3IAkbjv4nVPKg1d1E1g1d/bloom-public-accounts?node-id=1101%3A4139

Loading State
https://www.figma.com/file/i3IAkbjv4nVPKg1d1E1g1d/bloom-public-accounts?node-id=1101%3A4210

QA Notes:
Starting URL: https://dev-bloom.netlify.app/sign-in

Two Main Cases: 
1) Sign in to admin@example.com, click "My Applications", and observe the rendering of the spinner and "no application" message.
2) Sign in to test@example.com, click "My Applications", and observe the rendering of the spinner, loading of applications and their corresponding listings.

Note: For any of the cases, throttling the network when loading the 'My Applications' page can help to observe the frontend behavior.

**Comment by kathyccheng** [comment]
LGTM
