### ISSUE TITLE
Partner footer links don't do anything

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#2398]
**Describe the bug**
![Screen Shot 2022-01-13 at 3.39.50 PM.png](https://images.zenhubusercontent.com/601c7ede5322cf8ac29d50c4/251dac5b-a488-4149-bfa7-d9812be16fdd)

**Expected behavior**
The footer links don't go anywhere. @kathyccheng Should we remove them or make the pages?

If we keep them they probably should not show when signed out

**Comment by seanmalbert** [comment]
I think it makes sense to remove the links for now until we have the pages that these links should point to.

**Comment by emilyjablonski** [comment]
QA: Ensure the two footer links have been removed on partners pages.

**Comment by kathyccheng** [comment]
LGTM
