### ISSUE TITLE
New users after being added in partners are not appearing

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#2402]
**Describe the bug**
Newly added users not showing in partners users table

**To Reproduce**
1. Sign into partners as an admin
2. Add a new user (an email that doesn't exist in public, this is a different known issue)
3. As admin you get a success alert but the user does not appear in the table as unconfirmed
4. From the new email, which is sending successfully, confirm your account and set a password
5. Visit the users table, even after confirmed the user is not there but can sign in/out of partners

**Expected behavior**
User should first appear as unconfirmed and then as confirmed

**Comment by YazeedLoonat** [comment]
Currently users created/edited and marked as admins will not sure in the user table
we currently have a filter of `WHERE LOWER(CAST(user_roles.is_partner as text)) = LOWER('true') ` will bring up at stand up and come back to add notes from that convo

**Comment by emilyjablonski** [comment]
Fixed
