### ISSUE TITLE
Clean up netlify base directory configuration

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#241]
We made a change while adding the netlify.toml file (#177) to set the base directory for app deployments to be the app itself, not the monorepo root. This is probably the right configuration for production-ish builds, since it forces dependencies to be properly published to NPM, but it's painful in development for the same reason -- the whole point is to be able to test all of the changes on the branch, including those in /shared.

Netlify only respects a toml file in the base directory for the foreseeable future, but [this blog post](https://www.netlify.com/blog/2020/04/21/deploying-nx-monorepos-to-netlify/) seemed to have some good ideas for how we might work around that.

I'm self-assigning this since I caused the problem, but if anyone else is interested in helping fix it, then please feel free to speak up.

**Comment by emilyjablonski** [comment]
Does anyone know if this ticket is still relevant after the restructure?
