### ISSUE TITLE
Add SMC AMI Chart

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2421]
Title:
2021 San Mateo County HUD AMI

Link: 
https://docs.google.com/spreadsheets/d/1bnf0EUrzLAw30cL0c2xaU96D6jdN48Qyr9fQSi6xl7c/edit#gid=0

**Comment by seanmalbert** [comment]
This is now on https://partners.housingbayarea.org/

**Comment by kathyccheng** [comment]
LGTM
