### ISSUE TITLE
Update copy and translations in common application

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2424]
1. Intro screen on application - first row in translation file
2. Do you anticipate any changes in your household question - second row in translation file

Spanish
https://docs.google.com/document/d/1oh3kIYrp7K-n2MvPL8R3qqoZJaiwDVNk6EIbdNlj-ro/edit#heading=h.z2we68wtdnff

Chinese
https://docs.google.com/document/d/1GDhm697sltEgvqoAlfAVIgRf_2Et8FqpxwO8Wtv7j3M/edit

Vietnamese
https://docs.google.com/document/d/1karZhceBVbccFc3x32n2N3McTQjBO-rbxr6nTU2k7-I/edit#heading=h.z2we68wtdnff

**Comment by jaredcwhite** [comment]
Hey @kathyccheng — so is this a translation we should be updating in Bloom core, or one of the specific jurisdictions? And I noticed for the intro the English string in the Google doc is a bit different than what we currently have, e.g.: "Finally, we’ll give you an opportunity to review all of your application data before submitting." in the Google doc vs. "Finally, we'll see if you qualify for any affordable housing lottery preference." in the current JSON file.

**Comment by kathyccheng** [comment]
@jaredcwhite sorry this might be more tedious. But could we do the first one for just SJ, so the first page of the application. And then the second one, the household size question for everyone?

**Comment by jaredcwhite** [comment]
Sure, no big deal, I just want to make sure we're updating the right places. 👍

**Comment by jaredcwhite** [comment]
All right, this is implemented now in two different PRs:

- https://github.com/bloom-housing/bloom/pull/2452
- https://github.com/housingbayarea/bloom/pull/386

**Comment by kathyccheng** [comment]
LGTM
