### ISSUE TITLE
Spike: Opening a listing on partners on mobile zoomed out, hard to read, misaligned

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#2446]
![Screen Shot 2022-01-27 at 5.22.49 PM.png](https://images.zenhubusercontent.com/601c7ede5322cf8ac29d50c4/5db3a10e-bd64-45a4-9835-7cf4ced62e34)

<img width="373" alt="Screen Shot 2022-01-27 at 5 28 38 PM" src="https://user-images.githubusercontent.com/65367387/151454133-de5f3d75-c26e-4ff7-b42d-4c43185bef3f.png">

On mobile log-in, click on a listing. The details page will show zoomed out and with the header misaligned. The text is very small.

Clicking on edit and the state persists to the edit page.

My biggest concern is the size of the text. I recommend visiting [dev-partners](https://dev-partners-bloom.netlify.app/) on a mobile device, it's not as clear in the screenshots.

This is also happening on an individual application page in partners.

**Comment by emilyjablonski** [comment]
@kathyccheng One of the bigger ones out of bash imo as a heads up

**Comment by kathyccheng** [comment]
Might need browser stack to reproduce

**Comment by YazeedLoonat** [comment]
closing!
