### ISSUE TITLE
Cannot remove building selection criteria PDF from a listing

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#2463]
As a leasing agent
I might want to remove a Lottery Result
So that I can correct a mistake or update the Results 

**Acceptance Criteria**
* When I am editing a Closed Listing in partners portal and I add a Lottery Result and click Save, then I should see that the Results have been added and I can both Preview and Edit
* When I click on the Edit icon, then I should see the current file with the ability to Delete instead of the Add New screen 

**Notes**
* Currently, after you add a file, it shows the add New screen instead of the Edit screen

**Add Screen**
![image](https://user-images.githubusercontent.com/3453407/183522060-5d53321d-9d63-4453-90a0-a0e7a4f75d3c.png)

**Summary Screen**
![image](https://user-images.githubusercontent.com/3453407/183522143-329f961b-fb1d-44e7-9855-163379791513.png)

**Comment by kathyccheng** [comment]
LGTM
