### ISSUE TITLE
Hayward Preferences

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2469]
Update the description copy for the existing Displacee preference 

Displacee Tenant Housing Preference: At least one member of my household was displaced from a residential property due to redevelopment activities by the Hayward Housing Authority, the Redevelopment Agency or the City of Hayward **(including code enforcement activities)**. 

Adding the bolded text in parentheses

**Comment by YazeedLoonat** [comment]
```
UPDATE preferences
SET description = 'At least one member of my household was displaced from a residential property due to redevelopment activity by the Hayward Housing Authority, the Redevelopment Agency or the City of Hayward (including code enforcement activities).\nOR\n At least one member of my household is an SR 238 Program Participant as required under the terms of the SR 238 Settlement Implementation Project. Program Participants are tenants of previously sold Caltrans properties along the SR 238 Mission Boulevard Corridor and are given occupancy preference when new below-market housing is constructed in the Corridor.'
WHERE title = 'Displacee Tenant or Mission Boulevard Corridor (SR 238) Displacee Tenant Housing Preference'
```

@seanmalbert is the sql that I think should resolve this

**Comment by YazeedLoonat** [comment]
QA Notes:
This is updated on live alameda, please verify that the description contains the text that was bolded in the description
