### ISSUE TITLE
Application Confirmation ID

### ISSUE THREAD

**Issue by seanmalbert** [bloom-housing/bloom#2479]
There are cases where the application ID can get gnarly and end up with E notation like `2.5422E+042`. Since we're using `crypto.randomBytes(4)`, I would figure that the largest number would be 2^32, but apparently that's not the case. Either way, crypto.randomBytes can return a large integer outside of the eight character alpha-numeric we're looking for. We want to address that. I'm not sure how random something like `Math.random().toString(36).slice(2)` would be compared to what we're using.

We also currently retry 6 times to generate a random string, two thoughts on that:
1. would it be faster to first only query for the confirmation number by the listing id, instead of trying to save the entire application to check if it's unique? Right now this query `select confirmation_code from applications where confirmation_code = $1 and listing_id = $2` isn't fast (in production). Generating the string is fast however, so we could generate 6 or 10 strings, do one query to make sure at least one is unique before we try to save the application.
2. if we do reach 6 tries before generating a unique confirmation ID per listing, then the submission fails and a user will have to try again. Instead, I think it would be better to set the application ID as the confirmation ID.

**Comment by pbn4** [comment]
@seanmalbert E.g. value `812679E0` is interpreted as `8,13E+05` because google spreadsheet find `E\d+` regex suffix there. Is this something we should address backend side? I think during import there is an option to disable the conversion of some values.
