### ISSUE TITLE
Users - Unconfirmed Login

### ISSUE THREAD

**Issue by seanmalbert** [bloom-housing/bloom#2481]
**Acceptance Criteria** 
* Suppress error, pop modal to reconfirm
* Make sure confirmation modal works when you click okay, and x and resend
* Resend should trigger toast with Email sent
* If user resets password, consider confirmation

**Notes**
It appears that many users try and login without first confirming their account, which they cannot do.

We should at the very least update the invalid login message to let them know their account must first be confirmed and to check their email. We could also provide a link to resend the confirmation email.

**QA Notes**
1. Open partners login page
2. Try to log in using not confirmed user credentials
3. You should see a confirmation modal with pre-filled email input
4. Try to resend an email
5. Check your inbox
6. Try to provide an incorrect email - you should see an error alert
7. Try to activate an account by using an activation email from point 5.

**Comment by dominikx96** [comment]
@seanmalbert I think it has been completed here: https://github.com/bloom-housing/bloom/pull/2560, can we close it?

**Comment by kathyccheng** [comment]
@dominikx96 I don't see this working on dev yet. When I create a new user and then try to log in before I've confirmed my account, I still get the wrong email/password error

**Comment by dominikx96** [comment]
QA Notes:

1. Open partners login page
2. Try to log in using not confirmed user credentials
3. You should see a confirmation modal with pre-filled email input
4. Try to resend an email
5. Check your inbox
6. Try to provide an incorrect email - you should see an error alert
7. Try to activate an account by using an activation email from point 5.

**Comment by kathyccheng** [comment]
LGTM
