### ISSUE TITLE
Core - Update Confirmation Screen - Application

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2510]
**Acceptance Criteria**
* When I'm on the confirmation screen of the application, then I should see the new confirmation screen 

**Design** 
https://www.figma.com/file/tUtgsJO8XnF9Ij2dwu22EF/bloom-public-general?node-id=1163%3A8735

**QA**
To QA on https://dev-bloom.netlify.app/

**Comment by kathyccheng** [comment]
@jaredcwhite I think we're gonna want the Lottery language that we talked about for the email on the confirmation screen too

**Comment by jaredcwhite** [comment]
@kathyccheng Yeah, good point! Will get on that.

**Comment by kathyccheng** [comment]
LGTM
