### ISSUE TITLE
Translations - Audit of Partner Strings

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2514]
Notes 
* Move out all things specific to Partners to override files 
* Move everything to keys
* Not in this issue, but for future, will re-format script 
* Additionally flatten the strings

**Comment by emilyjablonski** [comment]
QA Notes: This will be challenging to QA. We have moved a lot of our strings around that could cause some strings to not render / show just a translation key. You could do a general walkthrough of the app and ensure the strings are still in place. (We did this manual QA in code review as well).

**Comment by kathyccheng** [comment]
Closing this, will file new issues if I find them
