### ISSUE TITLE
Add Detroit AMI Charts

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2525]
2 Charts

**MSDHA 2021** - Just the by household size, not the rent table 
https://docs.google.com/spreadsheets/d/1LOUWj_bqtCcGtRyq_jrr4aTYVJzmtzpItYVZVL0Yl3k/edit#gid=814349145

**HUD 2021**
https://docs.google.com/spreadsheets/d/1LOUWj_bqtCcGtRyq_jrr4aTYVJzmtzpItYVZVL0Yl3k/edit#gid=596442994

**Comment by seanmalbert** [comment]
These are now on https://detroit-partners-dev.netlify.app/ via a migration.

**Comment by kathyccheng** [comment]
LGTM
