### ISSUE TITLE
Convert "AppHeader" prototype component to React

### ISSUE THREAD

**Issue by jaredcwhite** [bloom-housing/bloom#253]
There's a `MultistepProgress` component already present but it's basically unstyled, so we should get that updated with all the new styles/markup in the `AppHeader` prototype.

@slowbot would that be something you want to work on?

**Comment by bk3c** [comment]
@jaredcwhite Is this still an open task we care about?

**Comment by bk3c** [comment]
Sounds like it's all set and implemented with the form scaffolding work (e.g. #330)
