### ISSUE TITLE
Update SMC County in How Did You Hear Application 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2533]
**Acceptance Criteria**
* When I'm on the demographics page of the application for an San Mateo application, then I should see San Mateo County HCD Website instead of Alameda County HCD Website under the How Did You Hear About Us 

![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/d9524924-8af8-4185-9551-cc84682eb1e8)

**Comment by seanmalbert** [comment]
This is up on staging at https://smc.bloom.exygy.dev/. And on partners paper application, where we updated it to read HCD Website (e.g. https://partners.housingbayarea.bloom.exygy.dev/application/4c77667a-d24d-456e-bfba-c9e781af4e2b/edit).
