### ISSUE TITLE
Add SJ Terms 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2537]
**Acceptance Criteria**
* When I am on the Terms screen to get access to Partners for a new user, then I will see the following Terms instead of the current default 

**Notes**
* We'll need scroll in that modal
* Add max width, max height + overflow

https://docs.google.com/document/d/1uvyO7PwrlBRQTlRQLGAYUD_PcS54nfzQ/edit

### QA Review Notes
1. go to https://dev-partners-bloom.netlify.app/
2. Create a user and assign them to a SJ listing
3. after setting your password, you should be taken to a screen for terms
4. create a user and assign them to a non SJ listing
5. since there is no terms for the jurisdiction, you should not see the screen
6. if you edit that user and assign them a SJ listing, the next time the user logs in or refreshes, they should get the terms page

**Comment by dominikx96** [comment]
@kathyccheng I don't have access to this google doc, can you add me?

Also, can you elaborate on what should I update (ideally a screenshot)? :)

**Comment by kathyccheng** [comment]
@dominikx96 permissions have been updated and then this is the modal where we'll want to place the content 

![image](https://user-images.githubusercontent.com/3453407/157282006-50ef3032-25f4-479e-aabe-d865ca0ca4d9.png)

**Comment by seanmalbert** [comment]
@kathyccheng , the issue with adding a new user is fixed.

**Comment by kathyccheng** [comment]
Looks good!
