### ISSUE TITLE
Core: Update Rental Assistance Default by Jurisdiction

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2538]
**Acceptance Criteria**
* When I am creating a listing in either SJ or SMC or Alameda jurisdictions and I select a jurisdiction at the top of the page, then I expect to see a different default Rental Assistance text in each one 

**Notes**
* We want the default Rental Assistance text to be different for each jurisdiction 

_SJ Copy_
Housing Choice Vouchers, Section 8 and other valid rental assistance programs will be considered for this property. In the case of a valid rental subsidy, the required minimum income will be based on the portion of the rent that the tenant pays after use of the subsidy.

_SMC Copy_
Housing Choice Vouchers, Section 8, and other valid rental assistance programs will be considered for this property. In the case of a valid rental subsidy, the required minimum income will be based on the portion of the rent that the tenant pays after the use of the subsidy.

_Alameda Copy_
Housing Choice Vouchers, Section 8, and other valid rental assistance programs will be considered for this property. In the case of a valid rental subsidy, the required minimum income will be based on the portion of the rent that the tenant pays after the use of the subsidy.

## QA Review Notes
1. On https://dev-partners-bloom.netlify.app/, go to add a new listing
2. select a jurisdiction and the rental assistance default should get set
3. if there is already text in the field then it should not change

**Comment by emilyjablonski** [comment]
@kathyccheng Can I get some context on this change? It looks like SMC and Alameda are identical and that the only difference from the SJ copy is formatting/grammar

<img width="1134" alt="Screen Shot 2022-03-31 at 12 55 55 PM" src="https://user-images.githubusercontent.com/65367387/161129276-069ab1b8-9b91-4695-bc99-111595168e45.png">

**Comment by kathyccheng** [comment]
LGTM
