### ISSUE TITLE
Alameda: Add How It Works Page to Alameda 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2552]
As a resident
I want to see an overview of how affordable housing works
So that I better understand where the Bloom platform fits in and to get a better understanding of what to expect 

**Acceptance Criteria** 
* When I hit the How It Works page, then I will see the following content 

**Notes**
* Do we have the full content somewhere? 

**Designs** 
https://www.figma.com/file/tUtgsJO8XnF9Ij2dwu22EF/bloom-public-general?node-id=1113%3A3731

## QA Notes

Visit the new page at https://ala.bloom.exygy.dev/how-it-works and compare the AC with the Figma mockup.

**Comment by jaredcwhite** [comment]
@kathyccheng @slowbot Hey, just wanted to double-check the notes on this regarding an accordion. Is this supposed to be set up like all you see is

(1) Find Listings
(2) Check Eligibility
etc.

and then when you click on one of those headings, you see the rest of the content expand below it?

**Comment by kathyccheng** [comment]
LGTM
