### ISSUE TITLE
Alameda - Homepage Updates 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2555]
As a resident, 
I want to see an overview of affordable housing on the homepage
So that I can better understand how the platform can serve me 

**Acceptance Criteria** 
* When I am on the homepage, then I will see an overview under the main CTA's 
* When I click on read about how it works, then I will be taken to the how it works page 

**Notes**
* On mobile it should stack 

**Designs**
https://www.figma.com/file/tUtgsJO8XnF9Ij2dwu22EF/bloom-public-general?node-id=1108%3A3399

## QA Notes

Visit the homepage at https://ala.bloom.exygy.dev and compare the AC with the Figma mockup.

**Comment by kathyccheng** [comment]
Yep!

**Comment by jaredcwhite** [comment]
All right, this and the other two Alameda page updates can now be reviewed here: https://deploy-preview-389--wonderful-joliot-c00737.netlify.app

**Comment by kathyccheng** [comment]
LGTM
