### ISSUE TITLE
Base Email Layout Template

### ISSUE THREAD

**Issue by seanmalbert** [bloom-housing/bloom#2576]
**What is this feature or what feature is this part of?**
Emails with an HTML layout and images.

**Describe the solution you'd like**
We currently have very basic email templates found in `backend/core/src/shared/views` and it makes sense to have a more robust wrapper that includes HTML. This is accomplished in Detroit with templates like [`backend/core/src/views/new-listing.hbs`](https://github.com/CityOfDetroit/bloom/blob/dev/backend/core/src/views/new-listing.hbs).

Using the email templates created by @slowbot  in https://github.com/bloom-housing/bloom/pull/2556, we can create a base layout.

If we have a need for images in the email that are for the header or footer or something that's static for a jurisdiction, I think we can accomplish that in a number of ways. Two options that I'm thinking of now are:
1. store and use assets from `sites/public/public/images` or `sites/partners/public/images`. So if the layout requires a header and footer image, we could add default images to core like `email-header` and `email-footer`. On each public site, we would then need to replace the defaults with what the jurisdiction provided. This approach also means that if we're using this template for partners, then emails would use the same image for all jurisdictions, which may be ok.
2. we store the images in Cloudinary and have the URLs as jurisdictional settings. This approach has a couple of benefits over option one: it allows for emails sent from the partners portal to have different images, depending on the user's jurisdiction and it allows us to update the email images without having to re-deploy a site.

A mix of the two may be the answer depending on what we need to accomplish.

**Comment by jaredcwhite** [comment]
Note: working on this in conjunction with #2576 for a single PR.

**Comment by seanmalbert** [comment]
This is merged and QA can be done with #2513 .
