### ISSUE TITLE
Spacing issues between fields on mobile listing form

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#2609]
**Describe the bug**
There is not consistent spacing between textbox form fields on mobile on the partners add listing form, likely due to the differing padding/margin we are applying to the desktop version.

**Expected behavior**
The padding/margin to be consistent between the fields on mobile (the larger padding seen below).

**Screenshots**
![Screen Shot 2022-08-08 at 6.04.22 PM.png](https://images.zenhubusercontent.com/601c7ede5322cf8ac29d50c4/08149e96-80f4-4403-b52d-aa1cd60a734b)

**Comment by kathyccheng** [comment]
LGTM
