### ISSUE TITLE
Core - Show admins in user table 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2657]
**Acceptance Criteria** 
* When I am on the users table in Partners Portal, then I should see admins and partners in the table 

**Notes**
* Right now I think we're excluding admins who also have a public account and are not partners. This is more likely to happen with internal team members or city stakeholders  

**QA Notes**
1. Log in as an admin in the partners portal at https://dev-partners-bloom.netlify.app/sign-in
2. Open the "users" tab
3. Make sure that a table includes admins from the public website - you can also try to create a new admin account in the public website and check again partners "users" table

**Comment by dominikx96** [comment]
@pbn4 I see that we use the following filter in a users table:

```
filter: [
{
 isPartner: true,
 $comparison: EnumUserFilterParamsComparison["="],
},
]
```

so I think we need to somehow edit/add a filter to fetch all admins (public/partners) + partners

**Comment by dominikx96** [comment]
QA Notes:
1. Log in as an admin in the partners portal
2. Open the "users" tab
3. Make sure that a table includes admins from the public website - you can also try to create a new admin account in the public website and check again partners "users" table

**Comment by kathyccheng** [comment]
LGTM
