### ISSUE TITLE
Fix language routes on account dashboard

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#2679]
https://github.com/CityOfDetroit/bloom/issues/1141

**Comment by adriencyberspace** [comment]
QA Notes:

Entry Point: http://localhost:3000/account/dashboard

In dashboard, select a language other than English
When you click on Favorites or Account Settings, you will now see the language prefix in the url (i.e. /es/account/favorites)

**Comment by kathyccheng** [comment]
LGTM
