### ISSUE TITLE
Refactor Field, FieldGroup components

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#2695]
Both the `Field` and `FieldGroup` components have become bloated with props for 1-off customizations.

We should consider how we can simplify these components while still offering the functionality we need.

**Comment by YazeedLoonat** [comment]
Would the component library overhaul cover this/can this become the issue where we handle this

**Comment by YazeedLoonat** [comment]
closing per grooming on 03/08/2023
