### ISSUE TITLE
Core - Missing Translations + Filipino

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2699]
**Notes**
* Add missing translation strings for Spanish, Vietnamese, Chinese
* Add Filipino 

https://docs.google.com/spreadsheets/d/15lm4SOME07gn1LKrdODDOGRYhFoH4LqH/edit#gid=754779653

**Comment by emilyjablonski** [comment]
QA Notes: Ensure that https://dev-bloom.netlify.app/ has the new translations added
