### ISSUE TITLE
Close icon changes to hamburger icon on mobile in Chrome & Firefox

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#2701]
![Screen Shot 2022-04-27 at 2.20.24 PM.png](https://images.zenhubusercontent.com/601c7ede5322cf8ac29d50c4/b3c2c163-55e0-43f8-8ea9-aedc36c2a550)

Add the `closeSmall` icon anywhere on the page, and on smaller view it changes to the hamburger icon. For some reason, this is being caused by the `SiteHeader` component which does purposefully swap between these two for its functionality.

**Comment by YazeedLoonat** [comment]
still happens on prod

**Comment by jaredcwhite** [comment]
@YazeedLoonat @sarahlazarich Do we have an example URL where this is still happening?

For example [I'm looking at this page](https://homeconnect.detroitmi.gov/listings/filtered?page=1&limit=8&status=active&availability=vacantUnits&homeType=&region=&accessibility=&bedRoomSize=&communityPrograms=) and I can't repro.

**Comment by jaredcwhite** [comment]
Never mind, it seems to be happening in Firefox and Chrome, but not Safari! Odd indeed.
