### ISSUE TITLE
Filtering does not show results, but indicates there are results

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#2706]
Currently on dev, if you select `Vacancies` and `Open Waitlist` it has the below strange UI which indicates that is one result but it does not show.

![Screen Shot 2022-04-28 at 3.39.32 PM.png](https://images.zenhubusercontent.com/601c7ede5322cf8ac29d50c4/1bf790f2-def6-4ba1-9279-041df5971134)

**Comment by kathyccheng** [comment]
I think this is good
