### ISSUE TITLE
Listings Search - Update Backend Search

### ISSUE THREAD

**Issue by seanmalbert** [bloom-housing/bloom#2720]
Listings search was implemented on the fronted via #2711. That works by searching on the name, which means it currently requires the exact name. On the backend, we want to add a `search` parameter that when passed does a fuzzy search on name. Then we can update the frontend to pass in the new parameter.

**Comment by kathyccheng** [comment]
@seanmalbert when I search, I'm not sure the results are changing / filtering, but something is flashing indicating some kind of change

**Comment by kathyccheng** [comment]
LGTM
