### ISSUE TITLE
Backend - Custom Extension Model Research/Discussion

### ISSUE THREAD

**Issue by seanmalbert** [bloom-housing/bloom#2724]
Because there are features in Detroit that we may not want or are ready for in core, we need a way to extend the different pieces of a module, so we don't have to deal with merge conflicts in the core files. This is a research task, to outline and discuss different approaches to this.

For example, let's take the marketing fields on Detroit and let's say we don't want those in core. `marketingType` shows up in the following places:

- `addOrderByToQb` in listings service
- listing DTOs
- listing types
- in the listing entity
- listing tests
- listing seeds

There are some other locations, but these are the core pieces that create conflicts every time we want to sync core.

One solution could be to create a custom module that sits on top of or adjacent to the listing module. Would we want a to create touch points throughout the listing module, so it could pull in the custom fields, dtos etc from the custom module. Would we want an additional abstraction layer on top of both modules so the listing module itself doesn't need to care about the presence of a custom module? These are the kind of questions we want to answer.

**Comment by YazeedLoonat** [comment]
closing per grooming on 03/08/2023
