### ISSUE TITLE
Delete question in Oakland preference under "Description"

### ISSUE THREAD

**Issue by sheneral** [bloom-housing/bloom#2735]
![Screen Shot 2022-05-17 at 5.33.11 PM.png](https://images.zenhubusercontent.com/622f87292316976540c8d5bd/0fc42ad3-261e-4466-b08a-7a4bfddd5066)

**Comment by kathyccheng** [comment]
No I think we're good here

**Comment by sarahlazarich** [comment]
closing based on comments.
