### ISSUE TITLE
Emeryville Preference - Add description

### ISSUE THREAD

**Issue by sheneral** [bloom-housing/bloom#2743]
Add description to Emeryville preference:

"At least one member of my household lives or works in Emeryville or has a child enrolled in a local school district."

Sorry for the back and forth on this!

**Comment by seanmalbert** [comment]
@sheneral , I updated the description for the preference in production. If you have a listing that's using that preference, you may need to edit and resave the listing to clear the public side cache to see it.

**Comment by sheneral** [comment]
looks good!
