### ISSUE TITLE
Core - "Actionable Row / Table" Variant for Settings 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2747]
### Story
As a user I want to take actions on an individual table row item

### Properties
- edit - allows user to open edit panel for this table item
- clone - creates a copy of this table item with the name "[Title] Copy" or "[Title] Copy [#]" etc
- delete - soft deletes the item 
- remove - removes the item from the table but does not soft delete the item

### States
- delete - prompts a modal confirming deletion
   - Heading: Are you sure?
   - Content: Deleting a [item] cannot be undone.
   - Actions: Cancel and Delete
- remove - prompts a item removed notification
   - Content: [Item] removed
- clone - prompts a item copied notification
   - Content: [Item] copied
  
### Acceptance Criteria
- action icons should have screen reader only labels that read the name of the actions to the browser

### Notes
- based on [Minimal Table ](https://storybook.bloom.exygy.dev/?path=/story/tables-minimaltable--default)
- we can use this ticket to leverage font awesome icons https://github.com/bloom-housing/bloom/issues/2634

### Mockups
https://www.figma.com/file/Y8bFd0aSz7eYJ2TCNid6s3/bloom-partners?node-id=5876%3A183489

**Comment by emilyjablonski** [comment]
PR 2857 QA Notes (modal redesign): Checkout the new [stories](https://deploy-preview-2857--dev-storybook-bloom.netlify.app/?path=/story/overlays-modal--basic-modal) and the documentation for the component. Compare the stories / modal visuals to the [mock](https://www.figma.com/file/Y8bFd0aSz7eYJ2TCNid6s3/bloom-partners?node-id=5876%3A183489).
