### ISSUE TITLE
Core - Admin Preference - Add New Preference

### ISSUE THREAD

**Issue by sheneral** [bloom-housing/bloom#2748]
**Add New Preference**

### Designs:
https://www.figma.com/file/Y8bFd0aSz7eYJ2TCNid6s3/bloom-partners?node-id=5725%3A182890

### User Story
- As an admin, I want to be able to add a new preference to my jurisdiction so that I can easily add that to my listings via the listings editor. 

### Acceptance Criteria
- When I am on the edit preference panel, I will see areas to enter the Title, and Description of the preference.
- When I select "Yes" for the "Can applicants opt out?" question, I am able to see an "Opt Out Label" field, and I am able to edit the text in that field.
- When I select "No" for the show on listing question, then the preference shouldn't show up in the list of preferences on the public listing detail page 
- When I am done with editing the preference, I can click "Save" and the preferences info is saved and the popup disappears, and it is saved in the preferences table on the Settings page.

### Notes
- The add preference panel is activated by the "Add Preference" button on the settings page
- Show preference on listing will set the "Do not show" label on the preference model
- The yes to the opt out should use the same current default behavior, where it will override the other answers in the checkboxes if the user selects none of these apply to me
- The "Add Preference Option" button needs will be outlined in a different story

### Questions

- What fields should be absolutely required on this panel? Maybe title and description?
   - I think just Title
- Should the question "Can applicants opt out?" default to yes
   - Yes

**Comment by emilyjablonski** [comment]
@sheneral Do we have answers to the two questions at the bottom of the description?

**Comment by emilyjablonski** [comment]
Blocked by #2746 #2745

**Comment by sheneral** [comment]
@emilyjablonski answered above!

**Comment by emilyjablonski** [comment]
QA Notes: 

Compare visually with the [Figma design](https://www.figma.com/file/Y8bFd0aSz7eYJ2TCNid6s3/bloom-partners?node-id=5725%3A182890) noting the differences from the design above.

Ensure the preferences populate according to your user.
Ensure you can add a preference with options, and exercise all the fields.
Ensure you can edit a preference / option.
Ensure you can duplicate a preference / option.
Ensure you can delete an option.
Ensure you can reorder options.

**Comment by kathyccheng** [comment]
LGTM
