### ISSUE TITLE
Admin Preference - Add Preference Options

### ISSUE THREAD

**Issue by sheneral** [bloom-housing/bloom#2750]
### Design
https://www.figma.com/file/Y8bFd0aSz7eYJ2TCNid6s3/bloom-partners?node-id=5725%3A182906

### User Story
- As an admin, I want to be able to add custom preferences so that I can make clear what applicants are eligible for in the application process for my listing.

### Acceptance Criteria
- When I'm on the add preference options panel, I am able to add details to my new preference via Title and Description
- When I'm on the add preference options panel, I am also able to add a URL and Link Title for in case I want to link to additional details about the preference
- When I'm on the add preferences options panel, I can check to collect the applicant address via a checkbox.

### Notes
- This panel is accessed through the "Add preference option" from the add preference panel
- When the preference option is saved from this panel, it shows up in the Add Preference Panel https://www.figma.com/file/Y8bFd0aSz7eYJ2TCNid6s3/bloom-partners?node-id=5725%3A187019
- Once the option shows up in the Add Preference panel, then there will be functionalities to order, edit, copy, or delete the preference

### Questions
- Does there need to be a confirmation popup/notice after someone clicks the delete icon?

**Comment by emilyjablonski** [comment]
QA Notes:
Compare visually with the [Figma design](https://www.figma.com/file/Y8bFd0aSz7eYJ2TCNid6s3/bloom-partners?node-id=5725%3A182890) noting the differences from the design above.

Ensure the preferences populate according to your user.
Ensure you can add a preference with options, and exercise all the fields.
Ensure you can edit a preference / option.
Ensure you can duplicate a preference / option.
Ensure you can delete an option.
Ensure you can reorder options.

**Comment by kathyccheng** [comment]
LGTM
