### ISSUE TITLE
Core - Populate Table of Preferences

### ISSUE THREAD

**Issue by sheneral** [bloom-housing/bloom#2751]
### Designs
https://www.figma.com/file/Y8bFd0aSz7eYJ2TCNid6s3/bloom-partners?node-id=5845%3A180315

### User Story
- As an admin, I want to be able to see all of the preferences available in my jurisdiction, so that I can access them and make edits as needed.

### Acceptance Criteria
- When I land on the page that displays the preferences table, I should see the table name, as well as "Name" and "Jurisdiction" and "Updated" fields indicating the name of the preference as well as when it was last updated

### Notes
- Need new table component
- Future: able to edit, duplicate, or delete

**Comment by emilyjablonski** [comment]
QA Notes: Log in as admin, on the settings page ensure you can see all jurisdictions preferences. Create a parter and assign them one jurisdiction, ensure you can see only that jurisdictions preferences.

Ensure the loading state and empty states trigger appropriately.

**Comment by kathyccheng** [comment]
LGTM
