### ISSUE TITLE
Admin Preferences - Show preference detail on listing mgmt panel

### ISSUE THREAD

**Issue by sheneral** [bloom-housing/bloom#2752]
### Design
https://www.figma.com/file/Y8bFd0aSz7eYJ2TCNid6s3/bloom-partners?node-id=5799%3A180605

### User Story
- As an admin, I want to be able to read more details about the preferences on the Select Preference panel when I'm editing a listing, so that I have clarity on which preferences I need to select.

### Acceptance Criteria
- When I'm on the select preferences panel while in the listing editor, I am able to see all of the preferences available to me, grouped by the county or the cities they're associated with.
- When I'm on the select preferences panel, I am able to read more details about each of the preference by clicking "read more" below each preference.
- When I click "read more", I am able to see the Title, Description of the preference expanded, as well as the Titles and Descriptions of the options associated with it, if any.

### Notes
- Disregard grouping by city in the listing management panel design

**Comment by emilyjablonski** [comment]
QA Notes: Check out the listing form and open the preferences and programs panel & compare to the [Figma](https://www.figma.com/file/Y8bFd0aSz7eYJ2TCNid6s3/bloom-partners?node-id=5800%3A179278).

**Comment by kathyccheng** [comment]
LGTM
