### ISSUE TITLE
Remove backend dependencies from tableSummaries

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#2773]
We need to remove all references to our backend from ui-components. `tableSummaries` in ui-components still contains references to `@bloom-housing/backend-core`.

This doesn't make sense to be in ui-components since it is so Bloom-specific, and this file mostly just handles formatting and doesn't export any component pieces. We should move it into the `helpers` file in public where it is used and import it from there.

**Comment by emilyjablonski** [comment]
QA Notes: Just moved code around. You can check the unit summary tables (the expandable content accordions that show an overview of units, which renders under the features section) and ensure there are no regressions.

**Comment by kramduckner** [comment]
https://deploy-preview-2795--dev-bloom.netlify.app/listing/af6c3dc9-e6a1-4deb-8d7c-08675b148e3e/emily_jablonski_1380_w_12_th_ave_broomfield_co - Looks like there's a null value showing in Additional Fees - could that be related to this change? If not, happy to move this done, and to dig deeper into the null field and make a ticket if it's an issue! lmk
![Screen Shot 2022-08-09 at 11 10 56 AM](https://user-images.githubusercontent.com/5691923/183714600-901b8802-3db5-46e1-85ca-efdf7162050a.png)

**Comment by emilyjablonski** [comment]
@kramduckner Unrelated but def a bug! I do think we have an issue already I'll check :)

**Comment by kramduckner** [comment]
Sounds good!
