### ISSUE TITLE
Remove backend dependencies from FormSignInMFACode

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#2778]
We need to remove all references to our backend from ui-components. `FormSignInMFACode` in ui-components still contains references to `@bloom-housing/backend-core`.

This component needs to be refactored to be more generic and to remove references to business logic and any translated strings. We are currently passing in a typed prop to toggle a string - but we can just toggle the string in props, which will be easy to do once translated strings are moved out into a prop of their own.

**Comment by emilyjablonski** [comment]
QA Notes: Ensure the MFA flow works without regression.

**Comment by YazeedLoonat** [comment]
looks good! closing!
