### ISSUE TITLE
Remove backend dependencies from FormSignInMFAType

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#2779]
We need to remove all references to our backend from ui-components. `FormSignInMFAType` in ui-components still contains references to @bloom-housing/backend-core.

This component needs to be refactored to be more generic and to remove references to business logic and any translated strings. Instead of pulling in the mfa type, we can just pass the value as a prop.

**Comment by emilyjablonski** [comment]
QA Notes: Ensure the MFA flow works without regression.

**Comment by YazeedLoonat** [comment]
Looks good! closing!
