### ISSUE TITLE
Core - Resources Translations Script

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2782]
**Acceptance Criteria**
* We're looking for some kind of spreadsheet output that includes a list of missing resource content strings that need to be translated for each language 

**Notes** 
* This is a sample of the one for JSON. I don't know if the keys are necessarily applicable here? 
* It would be nice to develop a script to also insert back in with the translations so it doesn't have to be manual forever 
https://docs.google.com/spreadsheets/d/15lm4SOME07gn1LKrdODDOGRYhFoH4LqH/edit#gid=754779653

**Comment by seanmalbert** [comment]
Demoed import/export with Alameda resources at planning and sending export to @kathyccheng
