### ISSUE TITLE
Core - Don't show application due date sentence if none

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2783]
As an applicant, 
I shouldn't see an application due date in the terms if the listing does not have one 

Acceptance Criteria
* Remove the first sentence of the terms (that includes the application due date language) if the listing does not have have a due date 

Notes 
* Move the first sentence into its own string
* Right now, there's a placeholder date 

Question
* Should this be in Core or in HousingBay because the terms differ by jurisdiction?

<img width="928" alt="image" src="https://user-images.githubusercontent.com/3453407/172692289-1fe2b94f-7acd-4b40-8548-c9cd0ef23fff.png">

**Comment by dominikx96** [comment]
QA notes:

1. Start an application for listing with a defined application due date
2. Make sure in the terms step the first paragraph includes the application due date
3. Start an application for listing without the application due date
4. Make sure in the terms step, the first paragraph with the application due date doesn't exist

**Comment by sheneral** [comment]
Hmm I'm not seeing the online common app show up in the deploy preview? I went into the partners link and checked that the common digital application question is checked in the listing but still don't see one that has the apply online button on the public listing -- should I be testing using a different link? @dominikx96

**Comment by sheneral** [comment]
nvm i figured it out - looks good
