### ISSUE TITLE
Core - Drop Lottery Date if none available 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2814]
Right now, the lottery date sentence is pulling the application due date. If there is not lottery date, then drop the first sentence "The Lottery will be held on [Date]" 

![Screen Shot 2022-06-14 at 4.49.12 PM.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/fc24740e-99b1-419c-bbef-30f0803aba68
)

## QA Notes

Submit an application with an upcoming lottery, then verify the lottery date is displayed on the final confirmation screen. (Note, may need some data added on dev if there's no upcoming lottery listing available.)

https://dev-partners-bloom.netlify.app/
https://dev-bloom.netlify.app/

**Comment by jaredcwhite** [comment]
@kathyccheng Hmm, so this should already be the case. The _The Lottery will be held on [Date]_ text is conditional on the presence of the due date field. Is there a recent example of this not working?

**Comment by kathyccheng** [comment]
@jaredcwhite It should be conditional on the lottery date not the application due date

**Comment by jaredcwhite** [comment]
@kathyccheng Ahhhh, OK, I got my wires crossed then. Yes, I'll make sure it pulls in the **Lottery Date** or else doesn't show that text. I'll make sure to update similar logic in the other new confirmation email PR as well.

**Comment by sheneral** [comment]
@jaredcwhite which link(s) should I be testing this on?

**Comment by jaredcwhite** [comment]
@seanmalbert I think we're missing an example Lottery-style listing with online application on dev. Do we need to refresh the seeds?

**Comment by sheneral** [comment]
LGTM
