### ISSUE TITLE
Ala - Duplicates - Manually select duplicate status of groups

### ISSUE THREAD

**Issue by sheneral** [bloom-housing/bloom#2832]
As a property manager, I would like to be able to manually update the duplicate statuses so that I can keep track of my progress 

**Acceptance Criteria**
* When I am on a flag group page, then I will see the default state that says Pending Review 
* When I click on Save, then I will see a modal giving me the option to choose Pending Review or Resolved 
* When I choose Pending Review, then the status will be Pending Review, any VALID applications will be marked valid, and other ones will be marked as PENDING 
* When click Resolved, then the status will be Resolved, any VALID applications will be marked VALID, any other applications in the set will be marked DUPLICATE. 
* Once a flagged set has been marked as Resolved, it should no longer be in the Pending Review tab and instead in the Resolved tab 
* When I go to the Resolved tab and click into a set, and then change the status back to Pending, then the applications marked as duplicate should go back to Pending, the Valid ones stay Valid, and the entire flagged set row should go back to the Pending tab 
* When I go to a Resolved Flag Set that already has a valid application, and then I select another application as Valid and then click Save and keep it as Resolved, then just that application will be marked as Valid and the other ones are still Duplicate 

### Statuses
- **Placeholder**: "Update Status" in dropdown
- **Status**: Pending review
- **Status**: Resolved

**Notes**
* This issue should cover a new way of saving the status. The related issue for selecting valid applications should cover removing the current logic that on save, the status gets updated. 
* Status's can go in between Pending to Resolved to Pending 
* Only applications in a Resolved flag set can be shown as Duplicate. If the flag set status is Pending Review, then the application status can only be Valid or Pending. Both Pending and Resolved can have Valid applications. 

**Designs** 

Save
https://www.figma.com/file/rK4OfJpwQ01qoBAwi5VWzg/Partners-Duplicates?node-id=404%3A22284

Modal
https://www.figma.com/file/rK4OfJpwQ01qoBAwi5VWzg/Partners-Duplicates?node-id=404%3A22302

Resolved
https://www.figma.com/file/rK4OfJpwQ01qoBAwi5VWzg/Partners-Duplicates?node-id=404%3A22370

Resolved Tab 
https://www.figma.com/file/rK4OfJpwQ01qoBAwi5VWzg/Partners-Duplicates?node-id=404%3A22231

**Comment by emilyjablonski** [comment]
QA Notes:
Check out the issue and the designs.

Visit a closed listing. Go to the applications tab and then the pending review tab. Click into an application flagged set. This page and the resolved page are the two main pieces of the ticket.

On the pending page:

All applications should have a default status of pending.
You can select any number of applications and when you hit the save button. If you save as "pending", the set stays as pending and the selected applications move to valid (pending). If you save as resolved the set moves to resolved and the selected applications move to valid and the unselected applications move to duplicate.
The leftmost and rightmost columns should be pinned

**Comment by emilyjablonski** [comment]
AC changes we made offline: (1) Checking applications as valid in a pending state are `Valid (Pending)` vs officially `Pending`, (2) You can save multiple valid applications from a set

**Comment by kathyccheng** [comment]
LGTM
