### ISSUE TITLE
Core - Settings Page Permissions 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2839]
**Acceptance Criteria**
* When I'm a leasing agent, I shouldn't see the Settings page in the nav 
* When I'm a jurisdictional admin, I should see the page and the table should show preferences in my jurisdiction only 
* When I'm a super admin, I should see the page and table should show all preferences

**Comment by kathyccheng** [comment]
@emilyjablonski looks like if I'm a partner, I can still see the settings page. I should only be able to see the settings page as a jurisdictional admin or admin type

**Comment by emilyjablonski** [comment]
Updated!

**Comment by kathyccheng** [comment]
LGTM
