### ISSUE TITLE
Ala - Duplicates - Allow to mark valid instead of duplicate

### ISSUE THREAD

**Issue by sheneral** [bloom-housing/bloom#2852]
**User Story**
As a property manager, I want to mark which application out of a list of applications I'm reviewing is valid, so that I can save time on reviewing duplicate applications.

**Acceptance Criteria**

Default State for Duplicate Group with Pending Review Status
- At the top of the table should be header that instructs the user to "Select Valid Applications"
- Each table row should have a checkbox
- Each **application** within the duplicate group should have a "pending" status, shown in the Status column for all of them
- The default status for a flagged set group is Pending Review 
- The Save button is disabled by default

Selected
- User is able to select one or more applications as "valid"
- Once one or more applications have been marked as valid, then the Save button is active again 

Save
- On save, the individual application statuses change. applications marked as valid change to valid status and unmarked applications status stays pending 
- Once I have saved an application as Valid, if I go to any other Flagged Set with that Application, it should be marked as Valid and checked 

**Notes**
- Backend update--create a duplicate status: pending, valid, duplicate; Applications come in as "valid" until conflict arise and it's flagged & becomes "pending", becomes "valid" or "duplicate" after review
- Replacing current flag set page we have
- Ignore "compare" tab
- Status will be set manually instead of current behavior in which it's set to resolved once the user saves. On this issue, we should remove the old logic for saving flagged set status to Resolved once any save as been applied, it should only update individual listing status 

**Designs**
Default State
https://www.figma.com/file/rK4OfJpwQ01qoBAwi5VWzg/Partners-Duplicates?node-id=404%3A22266

Selected
https://www.figma.com/file/rK4OfJpwQ01qoBAwi5VWzg/Partners-Duplicates?node-id=404%3A22284

**Comment by dominikx96** [comment]
@sheneral @slowbot I can't open these designs:
![Screenshot 2022-07-11 at 12 05 19](https://user-images.githubusercontent.com/16655908/178240837-be40a1c2-794b-4ce2-ab7e-876ccdb6d6bf.png)

**Comment by kathyccheng** [comment]
LGTM
