### ISSUE TITLE
Ala - Duplicates - Separate views for Main, Pending, Duplicates

### ISSUE THREAD

**Issue by sheneral** [bloom-housing/bloom#2853]
**User Story**
As a property manager, I would like to see applications divided up in to various categories so that I can easily scan what buckets the applications fall into and whether I need to manually review any pending applications

**Acceptance Criteria**
All States
- Include sidebar navigation and two column layout

All Applications
- Default menu item
- Side nav item includes a count of all applications
- All applications include pending and resolved applications

Pending Review
- Side nav item includes a count of applications in duplicate groups with applications that are pending review
- Do not include subcategories for individual rules

Resolved
- Side nav item includes a count of applications in duplicate groups that have been marked resolved and contain valid and duplicate applications

**Notes**
- HMW ensure algorithm accuracy for the duplicates counts? -- separate issue
- Need to update endpoint
- Yazeed: Backend updates to be able to filter by duplicate status
- Dominik: frontend

**Designs**
All Applications
https://www.figma.com/file/rK4OfJpwQ01qoBAwi5VWzg/Partners-Duplicates?node-id=41%3A5298

Pending Review
https://www.figma.com/file/rK4OfJpwQ01qoBAwi5VWzg/Partners-Duplicates?node-id=41%3A5426

Resolved
https://www.figma.com/file/rK4OfJpwQ01qoBAwi5VWzg/Partners-Duplicates?node-id=41%3A7164

**Comment by dominikx96** [comment]
@sheneral @slowbot I can't open these designs:
![Screenshot 2022-07-11 at 12 05 19](https://user-images.githubusercontent.com/16655908/178241181-412b4a2c-2705-498a-a4c4-0fb5eac1f622.png)

**Comment by kathyccheng** [comment]
LGTM
