### ISSUE TITLE
Unclear Messaging on Invalid Email When Creating a User

### ISSUE THREAD

**Issue by ColinBuyck** [bloom-housing/bloom#2934]
In partners in the add user form under the users tab, if you try to add a user with an invalid email, the messaging is that the field is required. This is confusing since you did enter input, it is just not a valid email. On the public side on account creation, what we do instead is show the `Please enter a valid email address` in both cases. We should update this error message to that string for when there is no input and when the input is invalid.

![image](https://user-images.githubusercontent.com/53269332/182714674-9c6dc647-9cd6-43c8-a207-6cb0682baae8.png)

**Comment by lisunshiny** [comment]
Fixed by #3302
