### ISSUE TITLE
Clean up react non-unique key warnings

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#294]
I got a couple of these warnings from the nextjs console, and it turns out the circleci logs for `shared/ui-components` are very full of them. Easy to replicate locally by doing `yarn test:shared:ui`

**Comment by jaredcwhite** [comment]
I meant to comment on this before. The challenge is we have a number of "lists" of things that don't have any particular ID associated with them…only thing I can think of maybe is find a way to create a deterministic hash based on the content of the item or something. Happy to do the research on this unless somebody has a good suggestion…

**Comment by bk3c** [comment]
@bencpeters Can I put this one on your plate? I think we're open to any reasonable solution, but it's getting annoying to have to scroll through 10k+ lines of console warnings to find the legit failure in CI. I realize we could probably just suppress the warning itself, but it seems like it should be straight-forward to assign temp IDs when we don't have them. It feels like this is one of those things where there should be a ton of prior art.
