### ISSUE TITLE
Core - Notifications Research for SJ

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2967]
Notification Platforms for SJ Research 
* Deliverable - Document or something outlining a 1-3 options for consideration 

Assumptions 
- Default is probably Sendgrid + Twilio, maybe on their account?
- We’ll probably want 2-3 options 
- Gov Delivery is out, they don’t have an account, but it could be a 3rd option if there aren’t too many other ones we ant to look at 

Things to look at 
- API support for triggers - e.g. when a new listing is published 
- Support for Email Templates
- Support for Multiple Lists (segmentation) 
- Performance Data Metrics - Sends, Opened, Bounces, etc
- Subscriber management -
- see list of subscribers, opt outs, etc
- Built in opt out pages 
- Does it support text message based notifications 
- Security specs
- Pricing 
-

**Comment by ludtkemorgan** [comment]
1. SendGrid + Twilio:
    - Multiple Prices depending on usage:
       - Most likely would go with the pro membership at $89.95/month if they stay under 100,000 emails a month
    - Email Templates supported 
    - Analytics supported (bounce rate, user information, etc)
    - Dedicated IP included at the pro membership
    - User management
    - To use SMS would be additional cost per text (using Twilio)
2. Mailgun:
    - Price varies based on usage:
       - ~$35 for 50,000 emails and ~$80 for 100,000
    - Really good API integration, not as good user interface
    - Email templates
    - Email segmentation
    - performance analytics
3. Amazon SES
    - Cheapest option:
       - only $0.10 per 1,000 emails. Also first 62,000 free if we switch to hosting on EC2
    - Good API integration
    - Lacking most of the other desired functionality
4. SendInBlue
    - Slightly cheaper than SendGrid:
       - ~$77 up to 100,000 emails. Cheaper if less emails are needed
    - Basically all of the same functionality as SendGrid
    - Hosted in EU

Recommendation:
- SendGrid + Twilio would be my choice as it appears to have all of the functionality that they are looking for plus we are familiar working with it so would be the easiest to integrate. 
- If price is the most important factor some of the other options would work, but the cheaper the option usually the fewer the bells and whistles.
- I would **not** recommend Amazon as it is more Developer focused than client focused and lacking lots of functionality
- MailGun also falls more into the category of developer focused, but could be doable.
- SendInBlue's biggest downfall is it is hosted in EU.
- here is a good comparison https://www.codeinwp.com/blog/sendgrid-alternatives/. They primarily are looking at the cheapest option though that often don't have the features we would need. so keep that in mind when comparing.

**Comment by ludtkemorgan** [comment]
| SendGrid + Twilio | SendInBlue | MailGun
-- | -- | -- | --
Price (100,000 emails) | $89.95 | $77.00 | $80.00
Dedicated IP | Yes | No | Yes
API Support | Yes | Yes | Yes
Email Templates | Yes | Yes | Minimal
Multiple Lists (segmentation) | Yes | Yes | Yes
Performance Metrics | Yes | Minimal without paying more | Yes
Subscriber management | Yes | Yes | Yes
See list of subscribers | Probably | Probably | ?
Built in opt out page | ? | Probably | ?
SMS | Yes - additional cost | Yes | No
Security | ? | ? | ?
Additional Users | 1,000 | At extra cost | Unlimited
  |   |   |  
Additional Info | - We currently use it | - Based in Europe | - API focused

**Comment by ludtkemorgan** [comment]
Izzy compiled the information into this google doc for better presentation https://docs.google.com/document/d/1V_B3ixKYn-WkS3W5hAN-YRuhneBXtxfbgWqFDgP1VDM/edit#heading=h.z2we68wtdnff

**Comment by kathyccheng** [comment]
Looks good! I think we can close!
