### ISSUE TITLE
Image on listing view width issue

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#2969]
We currently have a bug on production where at a tablet screen size, the image on a single listing view is not extending the full width of the screen

![Screen Shot 2022-08-17 at 8.16.59 PM.png](https://images.zenhubusercontent.com/601c7ede5322cf8ac29d50c4/1f0c23cc-0e5c-4323-a76f-3414ebb23811)

**Comment by emilyjablonski** [comment]
QA Notes: Check out a single listing view and check all screen widths. At a desktop width it should fit within the left/right panel view. Once the right panel collapses, the image should expand to full screen width.

**Comment by kathyccheng** [comment]
LGTM
