### ISSUE TITLE
Duplicates - Remove Flagged Set Tab

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#3002]
**Acceptance Criteria**
* When I am on a listing page in Partners Portal, then I will only see the Listing and Application tab. I should no longer see the Flagged Set tab and table 

**Notes**
* Removing old flagged set table in favor of new one 

![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/5cecb1da-2dfb-4bba-9cc9-0043b183ece8)

**Comment by emilyjablonski** [comment]
QA Notes: Ensure the tab is gone on the duplicates preview.

**Comment by kathyccheng** [comment]
LGTM
