### ISSUE TITLE
Duplicates - AG Grid Freeze Line

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#3004]
**Acceptance Criteria**
* When I am on the Pending or Resolved views, the table contents should go full width to the table container 

**Notes**
* Right now, it looks like the freeze columns line might be blocking the content from going full width?

**Comment by emilyjablonski** [comment]
https://stackoverflow.com/questions/65169997/react-ag-grid-auto-size-columns-and-grid-width

**Comment by emilyjablonski** [comment]
QA Notes: Checkout the listings table in partners and ensure the columns take up the full width of the table and do not super squish themselves on mobile.

**Comment by kathyccheng** [comment]
LGTM
