### ISSUE TITLE
Bug Core: Fix null label in application fees 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#3008]
**Acceptance Criteria**
* When the application fee is 0, show $0
* When the application fee is not provided show $N/A 

![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/26417b5a-009d-4e4b-ad54-3e8f2a09ace8)

**Comment by emilyjablonski** [comment]
QA Notes: Checkout listing/c324cf20-9f58-4ba5-89e4-67dc861ab1ec on dev which previously had this issue.

**Comment by kathyccheng** [comment]
LGTM
