### ISSUE TITLE
Core - Drop Redundant Line from Programs + Preferences 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#3009]
**Acceptance Criteria** 
When I am on the Program + Preference screens, then I will no longer see the line "Please select all that apply" 

![Screen Shot 2022-08-26 at 11.05.26 AM.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/0064eb3e-6c84-4777-9c4d-cc803f06f655)

![Screen Shot 2022-08-26 at 10.25.01 AM.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/e41bde09-f848-4948-8946-67e47a2ddfcc
)

**Comment by emilyjablonski** [comment]
QA Notes: View multiselect questions in an application and ensure the text is no longer present.

**Comment by kathyccheng** [comment]
LGTM
