### ISSUE TITLE
Allow custom strings in ui-components

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#3013]
For each component, we need to allow consumers to be able to pass in their own strings, as they may have a different translation tool or keys.

**Comment by emilyjablonski** [comment]
QA Notes: This PR added new optional props on multiple components to allow for consumers to pass in custom strings to our components that have strings built in. The goal in testing here is just that we have no regressions in displaying the strings we already have, so it's a little tricky to test manually vs in code review. I'd recommend mostly looking at the single listing view page where we had most of these strings and just ensure there are no broken translations.

**Comment by ludtkemorgan** [comment]
@kramduckner can you QA this for us?

**Comment by kathyccheng** [comment]
@kramduckner pinging again to see if you can help QA this issue and/or just close it out?

**Comment by kramduckner** [comment]
I tried to find as many of the changes as I reasonably coud and everything was looking great!
