### ISSUE TITLE
Core - Preferences Cloning UI Updates

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#3029]
As an admin
I want it to be more clear when I clone a preference 
So that I can make sure I don't inadvertently create clones that will be confusing for leasing agents 

**Notes**
* Some kind of indicator that the new one is new (e.g. "Copy of [Listing Name]" or something
* Maybe some kind of speed bump?

**Modal**
https://www.figma.com/file/Y8bFd0aSz7eYJ2TCNid6s3/bloom-partners?node-id=6826%3A185119

**Copy New State**
https://www.figma.com/file/Y8bFd0aSz7eYJ2TCNid6s3/bloom-partners?node-id=6828%3A185496

**Comment by emilyjablonski** [comment]
QA Notes: Copy some preferences and compare the result to the designs linked in the issue.

**Comment by kathyccheng** [comment]
@emilyjablonski this is an update from the original requirements but can we add Copy to the end of the title as opposed to "Copy of" in the beginning. Then it should keep the same alphabetical sorting so it'll show up beneath the original?

**Comment by emilyjablonski** [comment]
^ QA Notes: Copy a preference, ensure the `Copy` text appears after the name.

**Comment by kathyccheng** [comment]
LGTM
