### ISSUE TITLE
Core - Public What to Expect Updates (SJ)

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#3031]
As a resident
I want to better understand the process for a waitlist vs vacant unit opportunities 
So that I can be prepared 

**Acceptance Criteria**
* When I am on the listing detail page, then I will see different what to expect text for Waitlist, FCFS, and Lottery type listings
* When I am in Partners Portal, then I will no longer see or be able to edit the What to Expect section 

**Notes**
* We currently have default What to Expect text for listings that is flexible across FCFS and Lottery type listings, we want this section to now be dynamic based on whether the listing is Waitlist, Lottery or FCFS 
* Translations are still pending
* What's the Read More (after the first 3 rows?)
* Apply this text for all listings moving forward, don't override the text from the past for previous listings
* But we are going to now hide this section from Partners so partners can no longer edit 

**Designs** 
https://www.figma.com/file/5fGM1vGvQCmnhLCDkuqROr/Public-What-to-Expect?node-id=8%3A1904
![image](https://user-images.githubusercontent.com/3453407/187774960-7d031098-0c17-485d-8a90-75ed14eba497.png)

**Content**
(The What to Expect Rows) 
https://docs.google.com/spreadsheets/d/1zrZb9WFRJ2qFPIyfkFGK_BkeQ1_ejk7j9qYuxO35mOs/edit#gid=1891467199

**Product Brief**
https://docs.google.com/document/d/1905UwGoceAskeNlEjRcIoShDMgENcnE6PXzxewECGro/edit#heading=h.jhuf99j9fm9

**Comment by emilyjablonski** [comment]
@kathyccheng how important is it that `Apply this text for all listings moving forward, don't override the text from the past for previous listings`? that may prove to be a little tricky if we are basing the string off the listing type elsewhere

**Comment by emilyjablonski** [comment]
QA Notes: (For a dev): Reseed on dev. Add a listing with a what to expect value of the default. Run the migration on this branch. Ensure the what to expect value was set to null and that other custom ones were kept. Verify that changing the listing type does change the strings. (For product): Update the listing type by toggling lottery/fcfs and waitlist on the units, and ensure the right copy appears. Note that at the moment you can have a waitlist on both a lottery or fcfs type of listing through the listing form. The logic right now is that lottery overrides waitlist, but waitlist overrides fcfs.

**Comment by kathyccheng** [comment]
@emilyjablonski @ludtkemorgan I don't see this showing up in either HBA dev or the staging environments. I saw a note about reseeding, can we run that and then mark it as ready for QA on dev? @ludtkemorgan can you also just pass this through to the staging environments?
