### ISSUE TITLE
Some rent values showing as `NaN`

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#3035]
**Acceptance Criteria**
* When no rent numbers are provided, it should say "N/A" not NaN

![187236746-dade0867-e8b6-444e-a65e-f58c3098f893.png](https://images.zenhubusercontent.com/601c7ede5322cf8ac29d50c4/4e16f724-f033-4888-9cad-dce90cd91a26)
 
https://dev-bloom.netlify.app/listing/af6c3dc9-e6a1-4deb-8d7c-08675b148e3e/emily_jablonski_1380_w_12_th_ave_broomfield_co

**Comment by emilyjablonski** [comment]
QA Notes: Peruse the listings on dev and ensure none are showing `NaN` as table values. Many listings on dev were already doing so.

**Comment by kathyccheng** [comment]
LGTM
