### ISSUE TITLE
Allow alert boxes to be absolutely positioned

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#3037]
We need to create a version of the alert that is absolutely positioned at the top of the screen so that when a user is farther down a page and makes an update that throws a toast, it isn't hidden (ie in settings, users).

Alert box should initially show 1.5rem under nav bar and then show 1.5rem from top of the screen

Top
https://www.figma.com/file/Y8bFd0aSz7eYJ2TCNid6s3/bloom-partners?node-id=6852%3A185469

On Scroll
https://www.figma.com/file/Y8bFd0aSz7eYJ2TCNid6s3/bloom-partners?node-id=6853%3A185532

**Comment by kathyccheng** [comment]
@slowbot can you define the positioning and details here?

**Comment by emilyjablonski** [comment]
@slowbot  i can’t visually picture the positioning details (Alert box should initially show 1.5rem under nav bar and then show 1.5rem from top of the screen) - do you mind offering some more info?

**Comment by emilyjablonski** [comment]
QA Notes: You can view the new sticky site alerts in partners (examples: Update a user, update a listing, update a preference) or in the new story.

**Comment by kathyccheng** [comment]
LGTM

**Comment by jaredcwhite** [comment]
@emilyjablonski I noticed a change to the PageHeader component so the default background color uses `--bloom-color-gray-300` instead of `--bloom-color-primary-lighter`. Other similar uses such as table row backgrounds or the listing sidebar tinted blocks are still using `--bloom-color-primary-lighter`.
