### ISSUE TITLE
Core - Email What to Expect Update

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#3057]
As a resident
I want to better understand the process for a waitlist vs vacant unit opportunities 
So that I can be prepared 

**Acceptance Criteria**
* When I receive an email after I have submitted an application, then I will see different what to expect text for Waitlist, FCFS, and Lottery type listings

**Notes**
* Translations are still pending
* It's only in the What happens next section, the rest of the email stays the same 

**Designs** 
https://www.figma.com/file/5fGM1vGvQCmnhLCDkuqROr/Public-What-to-Expect?node-id=8%3A2982
<img width="571" alt="image" src="https://user-images.githubusercontent.com/3453407/189939270-ca621261-b3d3-494d-ad2e-adcc2989e3c4.png">

**Content**
(The Email Rows) 
https://docs.google.com/spreadsheets/d/1zrZb9WFRJ2qFPIyfkFGK_BkeQ1_ejk7j9qYuxO35mOs/edit#gid=1891467199

**Product Brief**
https://docs.google.com/document/d/1905UwGoceAskeNlEjRcIoShDMgENcnE6PXzxewECGro/edit#heading=h.jhuf99j9fm9

**Comment by emilyjablonski** [comment]
QA Notes: 
Submit an application with each of the three states. At the moment, the listing form allows for a waitlist (determined by the radio field on units) to exist on both a lottery or a first come first serve listing. The listing type [determination](https://exygy.slack.com/archives/C01Q4QG5R8Q/p1662650619602509?thread_ts=1662498643.729889&cid=C01Q4QG5R8Q) is that lottery overrides waitlist but waitlist overrides fcfs.

**Comment by emilyjablonski** [comment]
The way we're doing the listing status has since changed, we will need to update this with the new 3 category state.

**Comment by emilyjablonski** [comment]
Updated!

**Comment by kathyccheng** [comment]
@emilyjablonski it looks like we're missing a few translation strings on the emails 

FCFS
<img width="527" alt="image" src="https://user-images.githubusercontent.com/3453407/195112489-f6a86ed6-fe1b-417a-aa1c-4430cd354187.png">

Lottery
<img width="523" alt="image" src="https://user-images.githubusercontent.com/3453407/195112541-049def23-29e0-49db-9b8b-a00379902762.png">

Waitlist
<img width="526" alt="image" src="https://user-images.githubusercontent.com/3453407/195112593-7c2df0f2-96a4-40cf-8dae-277eff9f25b8.png">

**Comment by kathyccheng** [comment]
LGTM
