### ISSUE TITLE
SF Request: Support ability to move y-axis placement of modal

### ISSUE THREAD

**Issue by kramduckner** [bloom-housing/bloom#3062]
![bc711405-8d3b-455a-9de7-b090379a9fe6.png](https://images.zenhubusercontent.com/628d52f15bb6ced78872baae/5fcadf12-2068-40db-a230-79eff866b202)
There's a Modal instance in DAHLIA that gets very small when a user is inputting characters on a mobile device. Part of the fix the SF Design team's requested is that we use some of that overlay space above the modal (see screenshot). it'd be great if we had the ability to move the y position of the modal, or at least have a prop to fix the modal to the top.

**Proposal**

On Mobile
- Remove rounded corners
- Modal should load fixed at top of the window
- Remove current viewport rule, modal should extend to height 100% 
- Remove current scroll and fixed header, and allow Vertical scroll should kick in for the entire modal if the height of content exists beyond viewport 
- Example https://components.publishing.service.gov.uk/component-guide/modal_dialogue/with_large_content/preview

Layout
- See updated padding rules for header, inner and footer sections

Mockups
https://www.figma.com/file/tUtgsJO8XnF9Ij2dwu22EF/bloom-public-general?node-id=2601%3A8746
https://www.figma.com/file/tUtgsJO8XnF9Ij2dwu22EF/bloom-public-general?node-id=2601%3A8766

**Comment by kathyccheng** [comment]
@slowbot can you add your proposed solution?

**Comment by emilyjablonski** [comment]
QA Notes: Review all of the [modal stories](https://deploy-preview-3153--dev-storybook-bloom.netlify.app/?path=/story/overlays-modal--basic-modal) at all four of the Storybook viewports (default, tablet, large mobile, small mobile).

Ensure that when content is overflowing, the modal takes up the full width of the page and is scrollable.

**Comment by emilyjablonski** [comment]
QA Notes Round 2: Check out the new story for a modal with no footer. Ensure on mobile it takes up the full width of the screen and scrolls.

**Comment by eajensenwa** [comment]
@emilyjablonski LGTM!
