### ISSUE TITLE
Core - Ui Components Audit Investigation - Phase 1

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#3068]
For phase 1, each component should be in the Notion with its table fields filled out

https://www.notion.so/exygy/2c7d19ed7deb46f98a31e785d6ddce06?v=45e8cda4be254973b596e302d276122c

**Comment by emilyjablonski** [comment]
https://docs.google.com/document/d/1chI0819lloLqPaPl9wneVc1hVO8GfVok9RPjbDY2Ook/edit

**Comment by kathyccheng** [comment]
Closing out Phase 1
