### ISSUE TITLE
Fields in an error state should have a red field name

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#3078]
We have a visual discrepancies in the application on error states I noticed when I was walking through page by page comparing to SF. We need to ensure that when fields are in an error state the field is also red, and then when a field is in an error state, entering data removes the error state.

QA Notes: Walk through the application and at every page, try to submit without filling anything out.
Ensure that when a required field is in an error state, that the field itself as well as its label is red.
Additionally, ensure that when data is entered into a field in an error state, that updating the field removes the error state.

**Comment by kathyccheng** [comment]
LGTM
