### ISSUE TITLE
Core - What to Expect Back End 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#3081]
It's a little odd to be checking different fields in order to determine the full listing’s type which has 3 distinct categories (fcfs, lottery, waitlist) ([slack context](https://exygy.slack.com/archives/C01Q4QG5R8Q/p1663353081218739?thread_ts=1663342872.080439&cid=C01Q4QG5R8Q)). At the moment we have to check `listingAvailability` to see if that is `openWaitlist` and also `reviewOrderType` to see if that's `fcfs` or `lottery`.

We want to consolidate the unit waitlist question with the rankings and results question so we have one field we have to check for listing type, and also disable the lottery/fcfs question if waitlist is selected for units.

**Comment by emilyjablonski** [comment]
QA Notes: In a listing, ensure if you select `open waitlist` on the units section radio that the `fcfs/lottery` question in the rankings and results section no longer appears, and that setting it to `open waitlist` sets the `reviewOrderType` field on the listing.

**Comment by kathyccheng** [comment]
LGTM
