### ISSUE TITLE
Duplicates - Choose Valid Screen Updates

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#3098]
As a leasing agent
The select valid screen can be a little bit more helpful 

**Acceptance Criteria**
* When I have clicked into a duplicate set, then I should see primary applicant email as a column before Application Submission Type 
* When I am looking at the table of applications for either a Pending Review or Resolved set, the title for the status of the application should say Review Status not Application Status 

![image](https://user-images.githubusercontent.com/3453407/192887535-90f9d792-d0bc-4f30-b1d5-5cb6e6503b51.png)

**Comment by emilyjablonski** [comment]
QA Notes
In the partners portal, go to a listing that has duplicate applications. The listing must be closed.
Once you're in a duplicate set, the table should display the additional email column
The last column should be called Review Status now

**Comment by kathyccheng** [comment]
LGTM
