### ISSUE TITLE
Duplicates - Copy Updates

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#3100]
As a leasing agent, 
It might be easier to understand what's happening on duplicates with a few copy edits 

**Acceptance Criteria**
* When I am on the duplicates Pending Review or Resolved tabs, then the label at the bottom of the table should say X Sets instead of X Applications 

<img width="618" alt="image" src="https://user-images.githubusercontent.com/3453407/192886697-e1927535-8d65-4110-b9a3-a96819475a4b.png">

**Comment by emilyjablonski** [comment]
QA Notes: Open the `pending` and `resolved` tabs in the applications view and ensure the label on the total number of items is `set`/ 'sets`.

**Comment by emilyjablonski** [comment]
QA Notes: Open the `pending` and `resolved` tabs in the applications view and ensure the label on the total number of items is `set`/ 'sets`.

**Comment by kathyccheng** [comment]
LGTM
