### ISSUE TITLE
Duplicates - Add Flagged as Duplicate + Marked as Duplicate columns to All Applications table 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#3103]
As a leasing agent, 
I might want an indication that the application is a duplicate 

**Acceptance Criteria**
* When I am looking at the table of applications in the All Applications tab, then I should see 2 columns at the end of the table - one for Flagged as Duplicate, and one for Marked as Duplicate 

![image](https://user-images.githubusercontent.com/3453407/192888320-4c1eb760-86e1-458a-bf6e-f3bd71508ace.png)

**Comment by sarahlazarich** [comment]
lgtm - QA'd at https://partners.bloom.exygy.dev/listings/55b490e3-a654-42d3-bd66-c9c3e3d9a97a/applications.
