### ISSUE TITLE
Improve POIs and Style on the Listing Map

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#312]
Follow on issue from work begun in #308 and #311. The ideal solution would highlight nearby places in the following categories, which are already used by TCAC to define desirable locations for affordable housing:

- Transit
- Grocery Store
- Public School
- Medical clinic
- Public library
- Pharmacy
- Childcare
- Other Social Services/Programs 

At least some of these are available as explicit categories, so I think it's mostly just a matter of turning them on manually in such a way that it's helpful and not too much noise.

Given that we're also using the full mapbox-gl, I suspect that we'll need to make the controls more obvious if we want people to actually use any of the interactivity. I'd also personally be in favor of making the map size more reactive so that there's more screen real estate on wide screens, but I defer to @slowbot on whether that's reasonable without affecting usability or appearance in a negative way.

**Comment by ludtkemorgan** [comment]
These were tackled in Detroit in the "neighborhood amenities" feature
