### ISSUE TITLE
Bug - Invalid Date can sometimes appear for the lottery date

### ISSUE THREAD

**Issue by ludtkemorgan** [bloom-housing/bloom#3130]
A listing in Alameda (Acts Cherry Hill Apartments) was displaying INVALID DATE for the lottery field ![Screen Shot 2022-10-06 at 3.29.26 PM.png](https://images.zenhubusercontent.com/62e964b1581c5fc8f7169ebe/f459ca49-345a-43c3-9414-0a50d3c10cd2)

This appeared to happen when there is no lottery date listed and they have lottery selected. They have now entered a date and time so it is no longer happening, however it might have happened because there was either no date and time or potentially just a date and no time entered

**Expected Behavior** 
If no lottery date, provided do not show Lottery Section
If there's a date but no time show section with date (empty time) 
Time shouldn't be required for lottery event, remove required if it exists currently 
Lottery section should show on closed listing 
Make sure you can save a lottery date (right now looks like it says saves successfully, but isn't saving data)

**Notes**
* This particular listing might be fixed by now so might need new one to test 
* Add saving lottery date to cypress tests
* Test a new one and updating an existing one

**Comment by kathyccheng** [comment]
@sarahlazarich for QA - go through the expected behavior section above in this environment: https://dev-partners-bloom.netlify.app/

**Comment by sarahlazarich** [comment]
This passed QA at https://dev-partners-bloom.netlify.app/

**Comment by emilyjablonski** [comment]
![Screenshot 2023-03-07 at 11.22.43 AM.png](https://images.zenhubusercontent.com/601c7ede5322cf8ac29d50c4/0dda66c9-63cb-4ec4-bbf9-714c37e34f77)![Screenshot 2023-03-07 at 11.22.38 AM.png](https://images.zenhubusercontent.com/601c7ede5322cf8ac29d50c4/91495169-d7e5-47a0-ae24-a625c1dd1d86)

Not sure what happened here but I can get this error still

**Comment by sarahlazarich** [comment]
We can see this popping up again [here ](https://bloom.exygy.dev/listing/7aa0527d-af74-4edd-b28b-7af740b265c3/emily_jablonski_434_bennington_ct_saline_mi) - let's pull in and take a look?

**Comment by ludtkemorgan** [comment]
@sarahlazarich this is now in main. https://bloom.exygy.dev/listing/7aa0527d-af74-4edd-b28b-7af740b265c3/emily_jablonski_434_bennington_ct_saline_mi. 

Note, it will not update any open house that is already saved. Just new ones. We can write a script to fix all of the broken open houses

**Comment by sarahlazarich** [comment]
Thank you @ludtkemorgan ! Do we know how many open houses are showing this currently?

**Comment by sarahlazarich** [comment]
This looks good  - we should go ahead and release this, then save the listing to show the correct date.
