### ISSUE TITLE
Bug: user deletion does not work if that user has done any activity before

### ISSUE THREAD

**Issue by ludtkemorgan** [bloom-housing/bloom#3137]
On user deletion the follow error appears if the user has done an action before (entry in the activity_logs table) 
```
ERROR [ExceptionsHandler] update or delete on table "user_accounts" violates foreign key constraint "FK_458057fa75b66e68a275647da2e" on table "user_preferences"
```

```
ERROR [ExceptionsHandler] update or delete on table "user_accounts" violates foreign key constraint "FK_d54f841fa5478e4734590d44036" on table "activity_logs"
```

This means that right now you can only delete users that haven't created, edited, or done an action on a listing

**Comment by ludtkemorgan** [comment]
QA Notes:

In order to test this you'll need to have two accounts. One account you'll need to do an action with (e.g. close a listing) and the other account will be the one to delete the first account.

**Comment by kathyccheng** [comment]
LGTM
