### ISSUE TITLE
SF Req: Make Expandable Text More/Less button margin customizable

### ISSUE THREAD

**Issue by kramduckner** [bloom-housing/bloom#3140]
Right now, the ml-4 class is being applied to the more/less button inside the <ExpandableText /> component. SF want's the margin to be different, but the component doesn't support customizing that style.

**Comment by kramduckner** [comment]
qa notes - Go to a listing view (or create a listing) that has the following Additional Eligibility Rules: credit history, rental history, criminal background. The text will have to be long enough to warrant the More/Less button. Ensure that the More/Less button still has left margin (1 rem) applied on each panel. Also checkout a listing that has a long reserved community description and ensure that the More/Less button still has left margin (1 rem).

**Comment by eajensenwa** [comment]
@kramduckner looks good to me!
