### ISSUE TITLE
SF Request: Fix console warning re: react-media

### ISSUE THREAD

**Issue by kramduckner** [bloom-housing/bloom#3143]
Recipe to reproduce warning:

1. go to a detailed listing page on a desktop width
2. shrink window to mobile width

It's happening in other scenarios, but this is just one way to repro.

it appears it's coming from a dependency, react-media, and it's a known issue with nextjs - https://github.com/ReactTraining/react-media/issues/139 might be a fix in that thread.

Here's a screenshot of the warning: 
![Screen Shot 2022-10-27 at 9 03 21 AM](https://user-images.githubusercontent.com/5691923/198326578-e0117420-5f89-479e-be98-edc62391c628.png)

**Comment by emilyjablonski** [comment]
Unfortunately, this appears to be an issue within the package itself that is still under investigation and pending a fix. Afaik it's not producing any functionality issues at the moment and we can keep an eye for when a fix is released.
