### ISSUE TITLE
SF Request: Better support for markup in EventSection and QuantityRowSection

### ISSUE THREAD

**Issue by kramduckner** [bloom-housing/bloom#3144]
This ticket is re: updates to two components for better support for markup:

**Component - QuantityRowSection**

An example of it's usage that's problematic is in https://github.com/SFDigitalServices/sf-dahlia-web/blob/main/app/javascript/modules/listingDetailsAside/ListingDetailsWaitlist.tsx. The value for the description prop of QuantityRowSection is markup, and React throws this warning: 

![Screen Shot 2022-10-17 at 8.34.11 PM.png](https://images.zenhubusercontent.com/628d52f15bb6ced78872baae/ac604e36-d18d-4cb8-8f06-34d23928de5d)

Within QuantityRowSection, the description prop gets rendered as a child of a p tag, and any markup that gets passed as the description that isn't compatible with being a p tag child throws a warning.

**Describe the solution you'd like**
That warning wasn't thrown and the component supported description prop values that are arbitrary markup.

**Component - EventSection**

An example of it's usage that's problematic is in https://github.com/SFDigitalServices/sf-dahlia-web/blob/main/app/javascript/modules/listingDetailsAside/ListingDetailsOpenHouses.tsx The events.note is markup created from people managing listings. Here's a warning being thrown by React when it isn't compatible 

![Screen Shot 2022-10-17 at 8.47.37 PM.png](https://images.zenhubusercontent.com/628d52f15bb6ced78872baae/4e0b9f71-6634-4268-a449-110ba732246c)

**Describe the solution you'd like**
That warning wasn't thrown and the component supported an event.note prop values that are arbitrary markup

**Comment by emilyjablonski** [comment]
QA Notes:
Ensure existing stories have no visual regressions, and that the two custom content stories also have no regressions or console errors (they have been updated to include `<p>` tags in the inner content).

**Comment by eajensenwa** [comment]
@emilyjablonski  LGTM
