### ISSUE TITLE
Permissions library? / object model v1

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#315]
Now that we're settling on a NestJS / Passport [vision of authentication](https://docs.nestjs.com/techniques/authentication) (authn), at least in the short-medium term, we can turn our attention to authorization (authz), where there are more complex decisions for us to make.

In general, I think we should expect to use a version of role-based access control (RBAC) for the foreseeable future. If there's something off the shelf that would let us implement attribute-based access control instead, and we thought it would really be more robust for a similar amount of work, that could also be something worth discussing.

At runtime, we're looking for an authz solution that can easily plug into the [Guards](https://docs.nestjs.com/guards) infrastructure provided by NestJS, and where the authn part can remain with Passport so we get the benefit of all the strategies included there. We also want the underlying permission information to be stored in the database, presumably via TypeORM. In an ideal world, we'd have a clear path to splitting permissions storage by module (e.g. storing permissions on Listings separately than permissions on Applications, in case we ever split those two services), but so long as we have a pattern we can duplicate when the time comes there doesn't seem to be a big downside to just storing all the permissions information in the same place for now.

In addition to roles, the other key concept that we need to be able to support is permissions at various levels of a scope hierarchy. For example, the permission to edit a listing might be implemented only for that property (e.g. for a property manager), but it might also be implemented at a city or county level for the appropriate jurisdiction staffs. I'll cover the object model for that hierarchy in a separate issue, but whatever code is doing the evaluation will need to be able to traverse appropriately.

**Comment by bk3c** [comment]
Some libraries that we might consider using, stealing from, or otherwise being inspired by:

- [CASL](https://github.com/stalniy/casl)
- [Casbin](https://github.com/casbin/node-casbin)
- [AccessControl](https://github.com/onury/accesscontrol) (less maintained, but leans toward ABAC in a maybe-good way)

And see also for reading:

- https://www.ekransystem.com/en/blog/rbac-vs-abac

**Comment by hsluoyz** [comment]
Hi guys, Casbin provides a Nest.js middleware, which supports TypeORM exactly: https://github.com/dreamdevil00/nest-authz.

It also has an example: https://github.com/dreamdevil00/nest-authz-example

**Comment by software-project** [comment]
@pbn4 for reference here is Pundit that I used to use on Ruby side: https://github.com/varvet/pundit

**Comment by bk3c** [comment]
Some thoughts based on a design conversation that I had with @bencpeters:

- Properties should be our main permission-able entity for the foreseeable future, and then other levels (e.g. city, county) can essentially be represented as groups of properties. There's probably no need for actual hierarchy in the short-medium term, so long as a property can easily be a member of many groups.
- There are probably 5-6 roles per entity, from read-only, to read/write, to probably 2 levels of admin -- the first more targeted toward property managers, and the second more focused on company managers who can do things like invite/remove users.
- There's likely a need for non-property-aligned admin permissions for things like customer service to help reset passwords, etc. In the short-term, these requests will likely be handled by Exygy staff with global admin permissions, but we'll probably want to be able to delegate that to someone else within 12 months.

**Comment by bk3c** [comment]
Closing this since we picked Casbin and the first implementation is done. Certainly many more follow-ups, but will track those in separate issues.
