### ISSUE TITLE
Validate UUID on request

### ISSUE THREAD

**Issue by seanmalbert** [bloom-housing/bloom#3166]
We've discovered that we're not validating UUIDs on listing's get by ID endpoint, which can cause unnecessary server load. We should make sure this validation is in place for all get by ID endpoints.

**QA NOTES**
This shouldn't affect any of the regular usage. So going to partner's and viewing individual listings, and going to an application's page then that works 

what this should prevent is if you were to navigate to the listing's page then by hand trim the UUID in the url to no longer have all the parts

**Comment by kathyccheng** [comment]
LGTM
