### ISSUE TITLE
Spike How does TypeORM save perform?

### ISSUE THREAD

**Issue by YazeedLoonat** [bloom-housing/bloom#3185]
**This is blocked By**: https://github.com/bloom-housing/bloom/issues/3184

**What is this feature or what feature is this part of?**
We need to figure out whether TypeORM's `.save` functionality is performant, specifically on updating records.

we need to know how it holds up in terms of:
memory and time demands
under very large loads (records with MANY smaller sub records. Think listing with many units)

**Considerations**
If it turns out that typeorm's save isn't very performant we may want to find out what the overhead would be to roll a more performant save

**Comment by kathyccheng** [comment]
@YazeedLoonat do we still want this with latest spike?

**Comment by kathyccheng** [comment]
Closing this for now
