### ISSUE TITLE
Spike typeorm comparisons

### ISSUE THREAD

**Issue by YazeedLoonat** [bloom-housing/bloom#3188]
**This issue is blocked by:** https://github.com/bloom-housing/bloom/issues/3184

**What is this feature or what feature is this part of?**
we want to investigate a few things here
1. are there performance benefits from using a different ORM
2. what will the work load look like to switch over

The major 3 ORMs I know of are: 
TypeORM, Prisma, and Sequelize

**Comment by kathyccheng** [comment]
Closing
