### ISSUE TITLE
Spike More robust auth system 

### ISSUE THREAD

**Issue by YazeedLoonat** [bloom-housing/bloom#3190]
**What is this feature or what feature is this part of?**
our current auth system feels a bit unwieldy with the more complicated 4 tier system (user doesn't need to be logged in, user has complete access, user has access to only specific records, user has access to only a specific set of records)
this is a spike to investigate if our usage of our current tooling lines up with best practice for the tools. And if there might be a better/more appropriate permission management system we can leverage

auth tools:
- nestjs auth
- casbin

**Comment by seanmalbert** [comment]
Adding the link to this discussion from last year: https://github.com/bloom-housing/bloom/discussions/1570.

Also look into using something like AWS Cognito.

**Comment by YazeedLoonat** [comment]
closing in favor of 3502
