### ISSUE TITLE
Doorway - Prototype New Infrastructure 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#3195]
In anticipation of Doorway creating their own version of bloom it makes sense to prototype out what bloom would look like on different infrastructure.

This issue is to prototype what bloom would look like on AWS and should have at least the following things setup.
- Backend service
- Postgres DB
- Load balancer
- cache layer
- Public frontend
- Partners frontend
- image hosting

**Comment by ludtkemorgan** [comment]
Findings (all related to AWS):
- Several options for overarching setup
  - Amplify
    - Probably the easiest option for CI/CD and setup, especially for front-end
    - Costliest
  - Elastic Beanstalk
    - Easy to use, helps integrate services (DB, load balancer, etc)
    - This was the one I ended up using
  - Do everything manually
- Backend:
  - To get it to work on elastic beanstalk the following changes were needed
    - Add dockerfile
    - Add health check endpoint
    - Add .env variables to elastic beanstalk
  - Postgres connection is not too hard, but might require small code changes
- Image hosting:
  - Using S3 client api easy to use.
  - Would need to have code changes to remove all hard coding to cloudinary and reference s3 instead
- Postgres:
  - Really easy to add postgres to elastic beanstalk setup per app.
  - Might need to change authentication access to DB
- Public Site:
  - Need to add DockerFile
  - Either publish shared-helpers or pull it into public package.
  - Might need to optimize site more, ran into memory issues when trying to install/build the site.
  - Ran into issues with nextjs that were solved by upgrading to nextjs 12
- Partners site:
  - All of the same as the public site
