### ISSUE TITLE
HBA - Missing Translations 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#3197]
As a jurisdiction
I want to regularly make sure I have all of the translations on my public portal as content is changing 
So that I can better serve non English speakers 

**Notes** 
* Run the missing translations script for 
  * Alameda 
  * SMC
  * SJ 
* This should be an excel format for each of them 

Output:
[UPDATED-hba-missing-translations.csv](https://github.com/bloom-housing/bloom/files/10263873/UPDATED-hba-missing-translations.csv)

**Comment by sarahlazarich** [comment]
@ColinBuyck @kathyccheng can this be closed out? I was planning opening up new tickets with the results of my analysis, but happy to work in whatever format works best!

**Comment by kathyccheng** [comment]
Yes let's close out this one!
