### ISSUE TITLE
4+ Bedroom Listings

### ISSUE THREAD

**Issue by sarahlazarich** [bloom-housing/bloom#3211]
Acceptance Criteria:

As a Property Manager,
I want to be able to create a listing with five bedrooms in my partners portal
So that I can publish my larger listings on the public portal.

As a Property Manager,
I want the maximum occupancy for listings to go up to 11
So that I can publish five bedroom listings with an accurate max occupancy.

As an applicant,
I want to see the 5 Bedroom option translated in each language

**Notes**

* Add 5 Bedrooms as an option in the unit type drop down in the add units section
* Add 11 as an option to occupancy
* Public side will need translations for 5 BR option

**Translations on Public Side**
English: 5 BR
Spanish: 5 dormitorios
Vietnamese: 5 Phòng ngủ
Chinese: 5 臥室
Filipino: 5 BR

QA Notes:
- Go to the bloom core public site https://partners.bloom.exygy.dev/ and you should be able to add a 5 bedroom unit to a property along with increasing max occupancy to 11.
- Go To [public site ](https://bloom.exygy.dev/listing/9c4cacc6-0e4d-4da9-813b-fb146a3663df/test_default_lottery_results_pending_548_market_street_san_francisco_ca) and you should be able to see the 5 bedroom unit that was added in the partners site. Bedroom should be translated for all languages

**Comment by KrissDrawing** [comment]
@sarahlazarich  In Application proces (household step) applicant can pick unit size for now it is `3+ Bedroom` for 4 bedroom variant. I switched it to:
- `4 Bedroom` for 4 bedroom variants
- `4+ Bedroom` for 5 bedroom variants.

is that correct approach ? + I don't have translations for that.

**Comment by sarahlazarich** [comment]
@KrissDrawing -- We’d like the option to directly reflect the type of listings, and remove the “3/4+” room logic

So, the options should be: 
Studio, 1 Bedroom, 2 Bedroom, 3 Bedroom, 4 Bedroom, 5 Bedroom

Translations: 

3 bedroom listings: 
English: 3 Bedroom
Spanish: 3 dormitorios
Vietnamese: 3 Phòng ngủ
Chinese: 3 臥室
Filipino: 3 kwarto

4 bedroom listings: 
English: 4 Bedroom
Spanish: 4 dormitorios
Vietnamese: 4 Phòng ngủ
Chinese: 4 臥室
Filipino: 4 kwarto

5 bedroom listings:
English: 5 Bedroom
Spanish: 5 dormitorios
Vietnamese: 5 Phòng ngủ
Chinese: 5 臥室
Filipino: 5 kwarto

cc @kathyccheng

**Comment by sarahlazarich** [comment]
QA'd this at:

- https://partners.bloom.exygy.dev/
- Was able to create a 5 bedroom listing with a max occupancy of 11 in partners.

- https://bloom.exygy.dev/
- On public site, I see the 5 bedroom option in the listing detail page and in the application. It is translated in Spanish, Chinese, and Vietnamese. I don't see the option at this URL to translate into Tagalog.

**Comment by ludtkemorgan** [comment]
@sarahlazarich good catch, I've redeployed the public site with Filipino enabled

**Comment by sarahlazarich** [comment]
Awesome, I see this reflected in Filipino now. Closing this out.
