### ISSUE TITLE
Text Overlap in Listing Features Section

### ISSUE THREAD

**Issue by ColinBuyck** [bloom-housing/bloom#3215]
On smaller screen sizes, but before the breakpoint, the neighborhood text can overlap with the "Neighborhood" label 
<img width="446" alt="Screenshot 2022-12-13 at 12 45 00 PM" src="https://user-images.githubusercontent.com/53269332/207441392-22f6d551-5ee8-4468-b911-c37ceb408e93.png">

Ideal Behavior: Horizontal Scoot to the right rather than drop below label

**Comment by emilyjablonski** [comment]
QA Notes:

https://bloom.exygy.dev/

Check out the Features section on a listing detail page - gradually lessen the browser width and ensure at no point are the titles and descriptions of each section overlapping.

**Comment by sarahlazarich** [comment]
Apologies if I was meant to QA this! I didn't realize. But, I just did and it looks good I think!
