### ISSUE TITLE
Alignment issue in AdditionalFees component on mobile

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#3220]
![Screen Shot 2022-12-15 at 7.31.03 PM.png](https://images.zenhubusercontent.com/601c7ede5322cf8ac29d50c4/4ceabeee-b7aa-4470-a96b-aebd0b7e1004)

When the `AdditionalFees` component has two fee sections, the second section is not left aligned on mobile.

**Comment by lisunshiny** [comment]
supernit on title: this is happening on desktop too, not just mobile (at least for me)
