### ISSUE TITLE
Bug: Incomplete Unit Autofill Issue

### ISSUE THREAD

**Issue by ColinBuyck** [bloom-housing/bloom#3232]
When adding a unit for a listing on the partner's side, you can save a partially completed unit, but when you go to re-open it the drawer doesn't show the same unit type information that was saved. In the case below, the bedroom information defaults to Studio rather than the 5 bedroom previously inputted but it occurs with all non-'Studio' inputs.

https://user-images.githubusercontent.com/53269332/209235726-bcf672be-bb52-4106-89f6-5790cb9179bf.mov

The intended behavior is that the user should either not be able to save a unit with certain fields missing or the drawer should accurately populate the info that was previously inputted.

**Comment by kathyccheng** [comment]
@ColinBuyck is this just for the new 5BR or for any unit type that's not Studio?

**Comment by ColinBuyck** [comment]
@kathyccheng Sorry, any unit type that is not studio! I clarified in the description above as well.

**Comment by ludtkemorgan** [comment]
This has been fixed as part of the error resetting fix done. This can be QA'd here https://partners.bloom.exygy.dev/ by following the steps listed in the ticket
