### ISSUE TITLE
Figure out better translations for MDX files

### ISSUE THREAD

**Issue by software-project** [bloom-housing/bloom#324]
Right now we have a RenderIf in mdx files to handle translations. We should investigate if there is a better/ DRY way to do it.

**Comment by jaredcwhite** [comment]
I think the basic goal was to have a single MDX file with block(s) of text in each language, and using a React component to wrap those seemed to make sense. Happy to entertain other approaches.

**Comment by ludtkemorgan** [comment]
@jaredcwhite this is a long shot, but do you know if any additional discussions have been done with this? If the team is comfortable with the current implementation I feel like we could close this issue

**Comment by kathyccheng** [comment]
agrred @ludtkemorgan
