### ISSUE TITLE
Scaffold out all of the steps in the Application Form

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#325]
From our design/eng sync meeting this morning, the consensus is that it will be helpful to build out all of the form steps first, and then we can fill in the fields later with a much lower chance of merge conflicts, etc.

Latest Figma link from @slowbot: https://www.figma.com/file/ubE2C6P3XRpR0UAu4RJov0/Core-App-Flow-2?node-id=0%3A1

Write up on conditionals
https://docs.google.com/document/d/1KTfmzP8SgqjIhYXHfg_E4p6gTHE1P4ulRhb1tMHDy1I/edit?usp=sharing

User Flow:
https://app.flowmapp.com/share/3367021645a029eb2c66ff35de1e21a6/userflow/69488/

**Comment by bk3c** [comment]
@jaredcwhite I'm marking this Ready for Dev because I think we need to get started writing code to find out any open questions in the details, but feel free to post those questions back here if/when they turn up.

**Comment by jaredcwhite** [comment]
@slowbot I'm afraid I don't have permissions to access the Figma link. Do I need to sign up for an account, and if so, how?

**Comment by jaredcwhite** [comment]
@slowbot OK I created a jared.white@exygy.com account. I guess I just need to be added to the invite list.

**Comment by jaredcwhite** [comment]
@bk3c @software-project I realized I hadn't added any of the new form steps to the static routes in `next.config.js`…I just put a PR up which includes the first step — aka

```js
              "/applications/start/choose-language": {
                page: "/applications/start/choose-language",
              },
```

and stepping through the forms works fine after the initial step, but if you directly go to one of the step URLs you get a 404.

I'm wondering if there's any more elegant solution we can come up at this point than hardcoding all the URLs in `exportPathMap`…maybe we can write a little utility to glob the file paths and construct a list automatically? Thoughts?

**Comment by bk3c** [comment]
Calling this one generally done, with follow-on issues to come for the last few details.
