### ISSUE TITLE
markdown-to-jsx version 6.x.x causing issue in DAHLIA

### ISSUE THREAD

**Issue by kramduckner** [bloom-housing/bloom#3258]
There's an issue in DAHLIA where users are submitting markdown that's incorrectly being parsed by the markdown-to-jsx package. In a 7.x.x version, [this bug has been fixed ](https://github.com/probablyup/markdown-to-jsx/pull/381). We can use the updated version in DAHLIA, but some of the test suites are having trouble running due to a dependency clash. 
One way to fix the failing tests is to upgrade the version is Bloom, and since this
* allows the removal of a types package
* fixes issues that would also happen in Bloom

I figure it's a good idea to do upgrade the version in Bloom!

We need to upgrade to the latest version of markdown-to-jsx

**Comment by ludtkemorgan** [comment]
@kramduckner can this ticket be closed with your latest change?
