### ISSUE TITLE
Heading levels - listings page

### ISSUE THREAD

**Issue by sarahlazarich** [bloom-housing/bloom#3268]
**User Story** 
As a…. Person using a screen reader on the listings page
I want…The heading levels to reflect the structure of the page
So that…I can easily navigate through page content 

**Additional detail:** 

- These changes should be made on Desktop and Mobile
- "All rentals" should be H2
- Find rentals for you should be a button, not part of the heading (currently H3)
- Name of unit should be H3
- Eliminate address as part of heading

**Design Asset Documentation:**
Required (Y/N) N

**Technical Notes Link:** 
Change to UI components? (Yes) to the ListingCard.tsx file
Additionally, it will also require updates to public/pages/listings.tsx.

**Acceptance criteria:**
- Heading level structure is consistent for screen reader users on desktop. 
- Heading level structure is consistent for screen reader users on mobile.
- On the “listings” page, the "All rentals" should be H2 on desktop and mobile
- On the “listings” page, "Find rentals for you" should be coded as a button on desktop and mobile
- The name of the unit should be coded as H3 on desktop and mobile
- The address should not be a part of heading on desktop or mobile

**QA review instructions:**
Start here: https://detroit-public-dev.netlify.app/listings

1. Open inspect element
2. Ensure that the button on the left of the screenshot below is selected. Screenshot 2023-01-17 at 1.12.03 PM.png
3. Hover over each of the following "Rent Affordable Housing", "All rentals" and each rental name to ensure that they match the heading levels described in the AC above (h1, h2, and h3 respectively).
4. Check that the address is no longer an h tag
5. Ensure that there are no visual changes to the text.

OR
1. Check your settings to see what your VoiceOver modifier key is: 
<img width="943" alt="Screenshot 2023-01-19 at 4 38 29 PM" src="https://user-images.githubusercontent.com/53269332/213593563-f267c909-de9e-42dc-9944-7bb9d2259432.png">

2. Go back to the dev site
3. Click Command + f5 (voiceover should turn on)
4. Click your voiceover modifier key (in my screenshot it is caps lock) + U
5. Use the left or right arrow key until you locate the Headings Menu
6. Use the down arrow to the headings on the page and their respective levels
7. Ensure it matches the discussed changes above

**Comment by sarahlazarich** [comment]
Notes from 1/18 LH meeting clarifying AC: 
- "All rentals" should be H2
- Find rentals for you should be a button not be part of the heading (currently H3)
- Name of unit should be H3 
- Eliminate address as part of heading

**Comment by sarahlazarich** [comment]
@ColinBuyck It looks like the address here is still at leading level 3 -- is that something we need to fix before closing?

**Comment by ColinBuyck** [comment]
@sarahlazarich Hmm I'm seeing it as p here. Is that the same link you were using?
<img width="1440" alt="Screenshot 2023-02-21 at 8 56 04 AM" src="https://user-images.githubusercontent.com/53269332/220410307-8b2d9a64-240e-4d8b-93c2-c1cf815e402d.png">

**Comment by sarahlazarich** [comment]
talked through this with colin - passed QA!
