### ISSUE TITLE
Upgrade to ESLint 7 and typescript-eslint 3

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#327]
This looks to be relatively straight-forward, but there are a whole bunch of typescript rule changes so it might take some work to sort those out. Luckily the headline breaking change (Node 8 no longer supported) doesn't affect us.

See:

- https://eslint.org/docs/user-guide/migrating-to-7.0.0
- https://github.com/typescript-eslint/typescript-eslint/releases/tag/v3.0.0

The PR for this should include at least 2 commits -- one for changes to the tooling and any configuration changes we may want, and another with all of the code changes to comply with the new regime. I *think* the top-level `yarn lint` target should be helpful in testing here, but the details there might have to be adjusted as part of this work to make them more useful.

For extra credit: there are a **ton** of linter warnings (100+), almost all of which are either `no-explicit-any` or `no-named-as-default`. Not a blocker, but any progress (even partial) toward reducing those so we have less noise in the process would be much appreciated.

I recommend we don't start on this until we have relatively few other open branches so there aren't a ton of merge conflicts, but if anyone is feeling up to it soon then let's figure out how to get it done.

**Comment by bk3c** [comment]
Note: This is now blocking the (admittedly non-urgent) upgrade to Typescript 4. The current (old) linter versions fail unhappily with parse errors on a non-existent .map property if one tries to upgrade, and reverting to TS3.9 gets us back to normal. Updating to the latest versions of ESLint and typescript-eslint allows the linter to run cleanly again without too much effort, but surfaces a significant (few hundred) number of latent linter errors due to stricter enforcement of things we've been putting off. 

Unsurprisingly, use of Any types seems to be the biggest problem based on my quick scan of errors and warnings.

**Comment by jaredcwhite** [comment]
We should definitely decrease the number of anys in the system whether explicit or implicit, but are you saying the updated linter rules would change _explicit_ any from warning to error? I wouldn't be in favor of that change to be sure. Maybe there's a way to tweak the rules after doing the update.
