### ISSUE TITLE
Move AMI Charts from JSON into the database

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#328]
Some of these things may be big enough to split off into their own issues if further discussion is needed, and I would certainly expect that we try to spread it over multiple PRs at least so it's not too big to review or too long-standing of a branch.

Tasks that I see for this work:

- [ ] Add DB schema for charts
- [ ] Convert existing charts into seed files (or come up with test charts of comparable complexity)
- [ ] Document the seed file format so that it's easy for other developers to make new seeds for new AMI charts (expecting we may want to keep them under source control for a while)
- [ ] Change code to use DB-based data instead of JSON files
- [ ] Decide if we want an endpoint for AMI charts directly (for Partners, integration, and testing) and implement if so
- [ ] Evaluate whether we can make the JSON schema to the front-end be more compact without being less legible, and adjust as needed
- [ ] Add API-layer tests to make sure we're serving everything correctly
- [ ] Remove JSON files

Note that this seems like a good opportunity to make sure we have the schema correct, which will probably not be a straight port of the current JSON.

**Comment by kathyccheng** [comment]
Closed in #824
