### ISSUE TITLE
Align ui-components in Detroit

### ISSUE THREAD

**Issue by ludtkemorgan** [bloom-housing/bloom#3283]
With UI-components being pulled out of the core mono-repo and into it's own [repo](https://github.com/bloom-housing/ui-components) we need to now pull that back into Detroit's repo. Currently Detroit's ui-components are within the Detroit's repo which has caused some discrepancies between the core's ui-components. So to get the pulled out ui-components to work in Detroit a couple of extra steps will need to be taken.

What needs to be done:
- Update "@bloom-housing/ui-components" dependency to at least `7.3.0`
- Delete the ui-components package from the Detroit repo
- Resolve the discrepancies for each ui-component between detroit and ui-component repo. (see below for what this entails)

Options for resolution:
- Pull in the new ui-components and for any component that is divergent create a new version of that component in the Detroit repo.
- For components that have diverged update the components in ui-components to accommodate the Detroit use-case
- Keep part of the diverged component in Detroit (e.g css only) and use the rest of new component. (probably won't work for all use-cases)

Most likely it will require changes in both Detroit and UI-components

**Comment by emilyjablonski** [comment]
Step 1: Where the components are the same, pull in the UIC version and delete the local version

Core Changes
- ActionBlock: (1) Pull in our `Heading` component and take a custom priority, (2) Bring over Detroit's RTL styles
- Additional Fees: Detroit has structural style improvements, add to core (might be an easy copy / paste, but ensure we maintain core functionality)
- Breadcrumbs: Remove default blue class from core
- Button: Detroit has improvements (three new props), add to core
- Contact: Detroit has added a key within a map, add to core
- Drawer: Detroit has added a class name prop, add to core (diff the scss, some differences there as well)
- GridSection: Detroit has added a new class name prop, add to core
- Hero: New props and styles (diff), needs V2 styling
- Icon: Detroit has added two new props, add to core
- ImageCard: Detroit has tooltip feature, add to core
- LanguageNav: Needs V2 styling
- LinkButton: Core and Detroit take different approaches to accomplish being able to open in a new tab - use the Detroit spread version
- ListingCard: Diff
- ListingDetailHeader: Diff
- ListingDetails: Diff
- ListSection: Use heading component and allow for custom priority, and bring in Detroit's id prop addition
- LoadingOverlay: Detroit has added a class name prop, add to core
- Modal: Diff
- PageHeader: Diff
- ProgressNav: Detroit has an a11y improvement, bring to core
- SiteHeader: Diff, needs V2 styling
- StepHeader: Detroit has an a11y fix, bring to core
- Tag: Detroit has a tab index prop, bring to core
- ViewItem: Diff

Detroit Changes

**Comment by emilyjablonski** [comment]
Note: Will likely need to rename uic package in Detroit so that it doesn't conflict w the external package

**Comment by emilyjablonski** [comment]
^ For the above, QA Notes:

There will be some visual changes. Ideally, they are only minimal and are improvements. Some of the components that Detroit is now using from UIC were actually a little different, but the UIC version is better or more consistent, so this PR and dev are not identical.

[Here](https://docs.google.com/document/d/1CixA6lJdnuqQX0TkmgrVPW_DOnGhoe_I7Wo4HYRXENA/edit?usp=sharing) are some known and IMO acceptable or preferred visual changes.

QA could be relatively large. We need to audit both sites and compare to dev to make sure there are no unwanted or breaking visual changes.

**Comment by ludtkemorgan** [comment]
@emilyjablonski as discussed in grooming today there are some issues in Detroit dev since my latest changes going in. One of which is the Hero on the home page lost the white background 
![image](https://user-images.githubusercontent.com/42942267/234716786-ebd1c0e2-a513-4a22-ab46-5bfc6f445be2.png)

Also, for some reason the deployed version doesn't have the right font.

I'm hoping this will be addressed when pulling in the ui-c version of the Hero component. But let me know if that is not the case and you need assistance on it
