### ISSUE TITLE
Core - Listings Export

### ISSUE THREAD

**Issue by sarahlazarich** [bloom-housing/bloom#3291]
**User Story:** 

As a jurisdictional admin OR an admin in partners portal, 
I want to be able to export my listing information in CSV format,
So that I can look at my listings data in aggregate. 

**Acceptance Criteria:** 

Given that I am an admin in partners portal: 
- When I am on the listings page, then I should see a button indicating that I can export my listing data.
- When I click the “export to csv” button on my listings page, then my general listings and unit group data download as two zipped CSVs. 
- When I click the “export to csv” button on my listings page, then my page shows an indication that the export is in progress.
- When I click the “export to csv” button on my listings page, then my listings export will download in a timely fashion.
- When my listings export downloads successfully, then I see a message indicating the download was completed. 
- When there is an issue with my download, then I see an error message on the page.

Given that I am an admin looking at my listings export:  
- When I open the general listings CSV, then I see the columns listed in the [listing details tab](https://docs.google.com/spreadsheets/d/1iMhybYs0RSdW940e402oI8xsqot8BlAYHaVTXaORIeA/edit#gid=670984196).
- When I open the unit group CSV, then I will see the columns listed in [unit group details tab](https://docs.google.com/spreadsheets/d/1iMhybYs0RSdW940e402oI8xsqot8BlAYHaVTXaORIeA/edit#gid=670984196).
- When I look through my listings export files, then I will see data that reflects the state of my listings at the time of download.

QA Notes
Start here: https://partners.bloom.exygy.dev/sign-in

1. Sign in
2. Click Export to CSV button and observe the rows of each the listings and unit exports
3. Edit or add listing data to listings, save, and then click export to csv again to ensure that all data is correctly reflected in the download

**Comment by sarahlazarich** [comment]
After your question yesterday, I Spoke with Kathy and made the following updates to the Core export mock-up! Hope this doesn't require too much reworking for you. 

Listings Export: 
- Changed Column O in the Listing Detail tab should be number of units (analogous to number of unit groups in Detroit). 
- Dropped Column N - unit group
- Dropped Column M - community type description 
- Changed Column L - list community types comma separated 

Unit Group Export: 
- Drop Column C - Unit Group ID (no group ID in Core)

**Comment by ColinBuyck** [comment]
Ready for QA!

**Comment by sarahlazarich** [comment]
@ColinBuyck -- only note here is that I don't see a "Leasing Agent State" column, which is included in the mock up.

**Comment by sarahlazarich** [comment]
@ColinBuyck -- only note here is that I don't see a "Leasing Agent State" column, which is included in the mock up.

**Comment by sarahlazarich** [comment]
@ColinBuyck -- only note here is that I don't see a "Leasing Agent State" column, which is included in the mock up.

**Comment by sarahlazarich** [comment]
@ColinBuyck -- only note here is that I don't see a "Leasing Agent State" column, which is included in the mock up.

**Comment by ColinBuyck** [comment]
Good catch! I can make a cleanup PR now. Also noticing that Leasing Agency Mailing/Pickup don't include State on the mockup, am I good to add those in as well?

**Comment by sarahlazarich** [comment]
yeah, if it's not a big additional life that would be good!

**Comment by ColinBuyck** [comment]
Fix is in @sarahlazarich!

**Comment by sarahlazarich** [comment]
this looks good!
