### ISSUE TITLE
Add Preference data to the application data to Data Studio 

### ISSUE THREAD

**Issue by ludtkemorgan** [bloom-housing/bloom#3300]
The Data Studio setup for the application data currently doesn't have the preference data. The data studio setup was in #1509 but we need to add it to the dataset so that we have the full application info available.

Since the preferences are dynamic and not a set field, we will need to get the possible preferences to dynamically create the columns. One option is to query the multiselect endpoint to get the list of all preferences then use that data to create the fields in the `getFields` function. The column name will then be something like `{preferenceName}-{preferenceAnswer}` with the type being a boolean (has selected that value). This means that all preference and option combos will be columns and the consumer will need to add only the preferences they care about to the report.

Tech details:
- DataStudio link: https://script.google.com/home/projects/14EFUavOl2XBIldvLgg_lNzyhAkZW-OBQg7yJlAht_XRSuUDXkMepWjVY
- field from rawApplicationsList endpoint: `application_preferences`
- Endpoint to get all preferences: `/multiselectQuestions`

**Comment by ludtkemorgan** [comment]
@YazeedLoonat I don't know the best way to do code review on this. Maybe you could take a look at the latest data studio code: https://script.google.com/home/projects/14EFUavOl2XBIldvLgg_lNzyhAkZW-OBQg7yJlAht_XRSuUDXkMepWjVY/edit. This has the preference data added. 

It got a little bit more complicated since there were limits on the keys of the columns (length and special characters). So I have to use the ids and then re-check them against the text

**Comment by YazeedLoonat** [comment]
Hey @ludtkemorgan looks really good! nice work! 
I made like 1-2 tiny changes around a comment having a misspelling and I renamed a variable or two to make it more readable

Correct me if I'm wrong: I think right now we are querying the multiselect question endpoint twice. 

if thats the case how would you feel about storing the first call into a variable or into the storage (like username/password/token) so we can just reference it later instead of calling twice 


other than that this is super sick!

**Comment by ludtkemorgan** [comment]
> Hey @ludtkemorgan looks really good! nice work! I made like 1-2 tiny changes around a comment having a misspelling and I renamed a variable or two to make it more readable
> 
> Correct me if I'm wrong: I think right now we are querying the multiselect question endpoint twice.
> 
> if thats the case how would you feel about storing the first call into a variable or into the storage (like username/password/token) so we can just reference it later instead of calling twice
> 
> other than that this is super sick!

Thanks @YazeedLoonat for taking a look. I just made it a local variable so that if the function is called a second time it just grabs the saved value and it seems to work. I'm gonna close this ticket
