### ISSUE TITLE
Align site header with Detroit 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#3310]
At the moment, Detroit has local changes to the SiteHeader component that are preventing Detroit from uptaking the SiteHeader in UIC.

At high level it looks like the vast majority of the differents are in styling, so it would require V2-ifying the component.

The SiteHeader is a large layout-based "component" but I still think there's benefit in V2-ifying these pieces even if we end up pulling them into public/partners locally to reduce merge conflicts and be able to keep Detroit up to date.

**Comment by emilyjablonski** [comment]
QA Notes:

Behavior / UI should be identical in the SiteHeader / no regressions

You can compare the SiteHeader stories on the [deploy preview](Behavior / UI should be identical in the SiteHeader to how it is on dev

Compare each existing SiteHeader story on desktop and mobile to the dev Storybook and ensure there is no regression
Link to core locally and ensure there is no regression) to what we have on [dev](https://storybook.bloom.exygy.dev/)

**Comment by emilyjablonski** [comment]
QA Notes Uptake:

There should be no regressions in the SiteHeader - but there will be a few visual differences:
[Known differences
](https://docs.google.com/document/d/1HclfvH4Fz_F5z_spnv9QwzmSNZIJi9BL8m4TRxf6tiE/edit?usp=sharing)

Compare dev to production on public and partners at all 4 breakpoints.

You should also now have the skip to main content feature!

**Comment by sarahlazarich** [comment]
QA'd this at https://detroit-public-dev.netlify.app on all pages and I think this looks good, closing!
