### ISSUE TITLE
Align Modal component with Detroit updates

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#3312]
At the moment, Detroit has local changes to the Modal component that are preventing Detroit from uptaking the Modal in UIC.

For the most part it looks like the changes are improvements in Detroit that need to be brought over into core around how we are using the Overlay component within Modal.

**Comment by kathyccheng** [comment]
Keep track of accessibility video pop up modal

**Comment by emilyjablonski** [comment]
QA Notes: Ensure there are no regressions on desktop or mobile in our Modal [stories](https://storybook.bloom.exygy.dev/?path=/story/overlays-modal--basic-modal&knob-Action%201%20Label=Cancel&knob-Action%202%20Label=Submit&knob-Backdrop=true&knob-Button%20Label=Open%20Modal&knob-Content=Lorem%20ipsum%20dolor%20sit%20amet,%20consectetur%20adipiscing%20elit,%20sed%20do%20eiusmod%20tempor%20incididunt%20ut%20labore%20et%20dolore%20magna%20aliqua.%20Leo%20a%20diam%20sollicitudin%20tempor%20id%20eu.%20Porttitor%20lacus%20luctus%20accumsan%20tortor.%20Viverra%20mauris%20in%20aliquam%20sem%20fringilla.%20At%20augue%20eget%20arcu%20dictum.%20Penatibus%20et%20magnis%20dis%20parturient%20montes%20nascetur%20ridiculus%20mus%20mauris.%20Velit%20euismod%20in%20pellentesque%20massa%20placerat%20duis%20ultricies%20lacus%20sed.%20Aliquam%20vestibulum%20morbi%20blandit%20cursus%20risus.%20Tellus%20at%20urna%20condimentum%20mattis%20pellentesque%20id%20nibh.%20Interdum%20consectetur%20libero%20id%20faucibus.%20Platea%20dictumst%20vestibulum%20rhoncus%20est%20pellentesque%20elit%20ullamcorper.%20Tristique%20senectus%20et%20netus%20et%20malesuada.%20Ultrices%20neque%20ornare%20aenean%20euismod%20elementum.%20Tellus%20elementum%20sagittis%20vitae%20et%20leo%20duis.%20In%20egestas%20erat%20imperdiet%20sed%20euismod%20nisi%20porta.%20Nisl%20purus%20in%20mollis%20nunc%20sed%20id%20semper%20risus.%20Ac%20turpis%20egestas%20sed%20tempus%20urna%20et%20pharetra%20pharetra.%20Nibh%20mauris%20cursus%20mattis%20molestie%20a%20iaculis%20at%20erat%20pellentesque.%20Ultricies%20mi%20eget%20mauris%20pharetra%20et%20ultrices.%20Enim%20facilisis%20gravida%20neque%20convallis%20a%20cras%20semper%20auctor.%20Risus%20pretium%20quam%20vulputate%20dignissim%20suspendisse%20in%20est%20ante.%20Cursus%20vitae%20congue%20mauris%20rhoncus%20aenean%20vel.%20In%20vitae%20turpis%20massa%20sed%20elementum%20tempus%20egestas%20sed.%20Blandit%20libero%20volutpat%20sed%20cras%20ornare%20arcu.%20Sapien%20faucibus%20et%20molestie%20ac.%20Duis%20ut%20diam%20quam%20nulla.%20Non%20nisi%20est%20sit%20amet%20facilisis%20magna.%20Maecenas%20ultricies%20mi%20eget%20mauris%20pharetra.%20Risus%20nec%20feugiat%20in%20fermentum%20posuere%20urna%20nec%20tincidunt%20praesent.%20Enim%20diam%20vulputate%20ut%20pharetra%20sit%20amet%20aliquam%20id%20diam.%20Ultricies%20mi%20quis%20hendrerit%20dolor.%20In%20aliquam%20sem%20fringilla%20ut%20morbi%20tincidunt.%20Leo%20a%20diam%20sollicitudin%20tempor%20id%20eu%20nisl.%20Rhoncus%20urna%20neque%20viverra%20justo.%20Vulputate%20sapien%20nec%20sagittis%20aliquam%20malesuada%20bibendum%20arcu%20vitae%20elementum.%20Nisi%20scelerisque%20eu%20ultrices%20vitae%20auctor.%20Consequat%20mauris%20nunc%20congue%20nisi.%20Id%20diam%20vel%20quam%20elementum%20pulvinar%20etiam.%20Cras%20ornare%20arcu%20dui%20vivamus.%20Eu%20turpis%20egestas%20pretium%20aenean%20pharetra.%20Lobortis%20feugiat%20vivamus%20at%20augue%20eget%20arcu%20dictum%20varius.%20Massa%20enim%20nec%20dui%20nunc.%20Montes%20nascetur%20ridiculus%20mus%20mauris%20vitae%20ultricies%20leo%20integer.%20Arcu%20risus%20quis%20varius%20quam%20quisque%20id%20diam.%20Et%20magnis%20dis%20parturient%20montes%20nascetur%20ridiculus%20mus.%20Sed%20adipiscing%20diam%20donec%20adipiscing%20tristique%20risus%20nec%20feugiat%20in.%20Porttitor%20rhoncus%20dolor%20purus%20non%20enim%20praesent.%20Arcu%20non%20sodales%20neque%20sodales%20ut.%20Aenean%20et%20tortor%20at%20risus%20viverra.%20Aliquet%20sagittis%20id%20consectetur%20purus.%20Suscipit%20tellus%20mauris%20a%20diam%20maecenas.%20Pharetra%20sit%20amet%20aliquam%20id%20diam%20maecenas%20ultricies%20mi.%20Tellus%20id%20interdum%20velit%20laoreet.%20Arcu%20cursus%20vitae%20congue%20mauris.%20Sem%20integer%20vitae%20justo%20eget%20magna%20fermentum%20iaculis%20eu.%20Morbi%20tristique%20senectus%20et%20netus%20et%20malesuada%20fames.%20Bibendum%20arcu%20vitae%20elementum%20curabitur%20vitae%20nunc%20sed%20velit%20dignissim.%20Sed%20felis%20eget%20velit%20aliquet.%20Risus%20nec%20feugiat%20in%20fermentum%20posuere%20urna%20nec%20tincidunt%20praesent.%20Vitae%20sapien%20pellentesque%20habitant%20morbi%20tristique%20senectus%20et%20netus%20et.%20Sit%20amet%20mattis%20vulputate%20enim%20nulla%20aliquet%20porttitor.%20Amet%20dictum%20sit%20amet%20justo%20donec.%20Mauris%20augue%20neque%20gravida%20in.%20Sed%20vulputate%20mi%20sit%20amet%20mauris%20commodo%20quis%20imperdiet%20massa.%20Faucibus%20turpis%20in%20eu%20mi%20bibendum%20neque%20egestas%20congue.%20At%20ultrices%20mi%20tempus%20imperdiet%20nulla.%20Et%20leo%20duis%20ut%20diam%20quam%20nulla%20porttitor%20massa%20id.%20Natoque%20penatibus%20et%20magnis%20dis%20parturient%20montes%20nascetur.%20Nunc%20vel%20risus%20commodo%20viverra%20maecenas.%20Enim%20lobortis%20scelerisque%20fermentum%20dui%20faucibus%20in%20ornare%20quam%20viverra.%20Est%20ante%20in%20nibh%20mauris%20cursus%20mattis%20molestie%20a%20iaculis.%20Habitant%20morbi%20tristique%20senectus%20et%20netus.%20Integer%20feugiat%20scelerisque%20varius%20morbi%20enim%20nunc.%20Venenatis%20lectus%20magna%20fringilla%20urna.%20Nunc%20vel%20risus%20commodo%20viverra%20maecenas%20accumsan.%20Quam%20lacus%20suspendisse%20faucibus%20interdum%20posuere.%20Velit%20euismod%20in%20pellentesque%20massa%20placerat%20duis%20ultricies.%20In%20metus%20vulputate%20eu%20scelerisque%20felis%20imperdiet%20proin.%20Convallis%20convallis%20tellus%20id%20interdum%20velit%20laoreet%20id.%20Vitae%20elementum%20curabitur%20vitae%20nunc%20sed%20velit%20dignissim%20sodales%20ut.%20Eget%20nunc%20scelerisque%20viverra%20mauris.%20In%20nisl%20nisi%20scelerisque%20eu%20ultrices.%20Pretium%20vulputate%20sapien%20nec%20sagittis%20aliquam%20malesuada%20bibendum%20arcu.%20Eget%20est%20lorem%20ipsum%20dolor%20sit%20amet%20consectetur.%20Auctor%20urna%20nunc%20id%20cursus%20metus%20aliquam.%20Pellentesque%20habitant%20morbi%20tristique%20senectus%20et%20netus%20et%20malesuada%20fames.%20Etiam%20erat%20velit%20scelerisque%20in%20dictum.%20Sodales%20neque%20sodales%20ut%20etiam%20sit%20amet%20nisl%20purus.%20Interdum%20consectetur%20libero%20id%20faucibus%20nisl%20tincidunt%20eget%20nullam.%20Sed%20turpis%20tincidunt%20id%20aliquet.%20Duis%20at%20consectetur%20lorem%20donec%20massa.%20Egestas%20congue%20quisque%20egestas%20diam%20in.%20A%20erat%20nam%20at%20lectus%20urna%20duis.%20Rhoncus%20dolor%20purus%20non%20enim%20praesent%20elementum.%20At%20imperdiet%20dui%20accumsan%20sit%20amet%20nulla.%20Leo%20urna%20molestie%20at%20elementum%20eu%20facilisis%20sed%20odio.%20Molestie%20nunc%20non%20blandit%20massa%20enim.%20Egestas%20egestas%20fringilla%20phasellus%20faucibus%20scelerisque%20eleifend%20donec%20pretium%20vulputate.%20Mollis%20nunc%20sed%20id%20semper%20risus%20in%20hendrerit%20gravida.%20Nam%20libero%20justo%20laoreet%20sit%20amet%20cursus.%20Id%20neque%20aliquam%20vestibulum%20morbi%20blandit.&knob-Title=Modal%20Title)
