### ISSUE TITLE
Some Listing columns produce migration spam

### ISSUE THREAD

**Issue by lisunshiny** [bloom-housing/bloom#3316]
Two columns in the Listing table, `afs_last_run_at`, and `last_application_update_at`, always produce migrations. 

These two columns are  type `timestamptz` and have a default value of `1970-01-01`. These two things together seems to be the cause of this. I tried making a test field that had the same column config to confirm.

### repro
That is, if a column is configured like this
```ts
  @Column({ type: "timestamptz", nullable: true, default: "1970-01-01" })
```

and you call `yarn db:migration:generate -n migration-1`, you get this
```
        await queryRunner.query(`ALTER TABLE "listings" ADD "liann_test_tz_field" TIMESTAMP WITH TIME ZONE DEFAULT '1970-01-01'`);
```

Then call `yarn db:migration:run` which executes migration-1, there are no errors. 

Then run `yarn db:migration:generate -n migration-2` AGAIN (migration 2), with no code changes. You get this which is weird:

```
        await queryRunner.query(`ALTER TABLE "listings" ALTER COLUMN "liann_test_tz_field" SET DEFAULT '1970-01-01'`);
```

Then if you call `yarn db:migration:run` which executes migration-2, there are no errors.

Was it just a one-time weirdness? Nope. If you call `yarn db:migration:generate -n migration-3`, with no code changes. You **still** get this line

```
        await queryRunner.query(`ALTER TABLE "listings" ALTER COLUMN "liann_test_tz_field" SET DEFAULT '1970-01-01'`);
```
and even if you apply these changes you'll always get this line.

### investigation

* typeorm was not upgraded between the adding of these fields and now, so it is not related to upgrades.

* `afs_last_run_at` and `last_application_update_at` are the only columns that are configured in this specific way in the codebase

* This bug around `timestamptz`  + Postgres opened against TypeORM seems relevant. It could possibly be a bug within TypeORM which does typecasting in a way that causes it to think that a migration is needed on this column even though one isn't.
  * https://github.com/typeorm/typeorm/issues/838
 

### possible mitigation

This worked for me -- on my test branch, I tried configuring the column with a default timezone as well. 

```
  @Column({ type: "timestamptz", nullable: true, default: "1970-01-01 00:00:00+00" })
```

It did not change the initial migration
```
        await queryRunner.query(`ALTER TABLE "listings" ADD "liann_test_tz_field_with_explicit_timestamp" TIMESTAMP WITH TIME ZONE DEFAULT '1970-01-01 00:00:00+00'`);
```

But it also did not produce additional migration spam! This is a promising change but I will leave it to be handled separately from #3306.

**Comment by emilyjablonski** [comment]
@ludtkemorgan @YazeedLoonat Is this already resolved?

**Comment by ludtkemorgan** [comment]
> `yarn db:migration:generate -n migration-1`,

This issue still exists, even with the updates to typeorm
