### ISSUE TITLE
Unit / Integration Tests - Coverage Report

### ISSUE THREAD

**Issue by sarahlazarich** [bloom-housing/bloom#3324]
Can we please run a coverage report for unit and integration tests to see what % of our site is covered?

Unit Tests:
- Backend 
- UI Components

Integration Tests: 
- Backend 
- Public
- Partner

**Comment by ludtkemorgan** [comment]
### BACKEND
Overall:
- % Stmts = 77.09 
- % Branch = 54.6 
- % Funcs = 65.77 
- % Lines = 76.05 

unit:
- % Stmts = 64.67 
- % Branch = 30.37 
- % Funcs = 21.55 
- % Lines = 64.07

e2e:
- % Stmts =  76.2
- % Branch = 50.19 
- % Funcs = 64.62 
- % Lines = 75.18

**Comment by ludtkemorgan** [comment]
### UI - Components
- % Stmts = 80.82
- % Branch = 57.07
- % Funcs = 60.44
- % Lines = 82.14

**Comment by ludtkemorgan** [comment]
### Public
Integration:
- Statements   : 81.72% ( 1229/1504 )
- Branches     : 68.71% ( 727/1058 )
- Functions    : 77.6% ( 343/442 )
- Lines        : 82.41% ( 1199/1455 )

unit:
- Statements   : 20.39%
- Branches     : 9.71%
- Functions    : 15.04%
- Lines        : 20.23%

**Unit tests were only recently introduced so there are only 6 tests suites and 12 total tests

**Comment by YazeedLoonat** [comment]
### Partner
Integration:
- Statements   : 67.69% ( 1852/2736 )
- Branches     : 58.9% ( 1155/1961 )
- Functions    : 57.7% ( 487/844 )
- Lines        : 68.71% ( 1785/2598 )

**Comment by sarahlazarich** [comment]
Thank you, Morgan!
