### ISSUE TITLE
Test Coverage - Critical User Flows (Core)

### ISSUE THREAD

**Issue by sarahlazarich** [bloom-housing/bloom#3325]
**Goal / Description:** Identify which flows are not covered by integration OR unit tests, and create issues for flows that do not have coverage. 

**Additional Detail:**  Check to see which of the flows below are covered by tests, and mark in the sheet  [here](https://docs.google.com/spreadsheets/d/1JXXMvLhaoEkYVOvqSEi0s2kwvCVHuF7R-rjcwdz1wpk/edit#gid=1445610402) which flows are covered. For flows that don't have a test, please make an issue and link it in the ticket.  Please follow the structure of this [example ticket](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/bloom-housing/bloom/3364), and link to the testing epic, and testing label. 

**Acceptance Criteria:** 

- All flows in the spreadsheet above have their coverage indicated in the sheet
- Flows without coverage have had a ticket made

**Comment by ludtkemorgan** [comment]
@sarahlazarich The last partner tickets have been created

**Comment by sarahlazarich** [comment]
Thank you morgan!
