### ISSUE TITLE
Spike - Explore configuration options for Bloom Core 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#3334]
Take a look at our current approach for configuration - feature flags 
We have similar systems for front end + back end, take that into consideration
Consider options for dynamic, not requiring re-deploy 
Research other practices
Product a technical design doc for how we might expand our configuration infrastructure - if front end and back end diverge considerably, could consider different docs for each

**Comment by ludtkemorgan** [comment]
The design doc is ready to review: https://docs.google.com/document/d/1vRvfEW5xQVU5WlND6j8Pbr1BPP5I5sdffzE4PkOBODc
