### ISSUE TITLE
UISeeds - Grid Component

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#3339]
Transfer the `GridSection` component from UIC to UISeeds (rename it to Grid!). ([Audit Link](https://www.notion.so/exygy/Modal-5752c7241c7b490b871cdfc2c6f5580a?pvs=4)) ([Figma Docs Link](https://www.notion.so/exygy/Grid-Section-66b7a0dbbebf4f7ca775953fc21fd3d3?pvs=4))

* Needs V2 styles

**Comment by emilyjablonski** [comment]
* "Make sure the grid can be navigated using keyboard-only controls, with each column having a clear focus state." - content shouldn't be focusable, so I think we might need to remove this piece or reword it

**Comment by jaredcwhite** [comment]
Closing in favor of https://github.com/bloom-housing/ui-seeds/issues/32
