### ISSUE TITLE
SMC content updates to the resources page

### ISSUE THREAD

**Issue by ludtkemorgan** [bloom-housing/bloom#3342]
San Mateo has request the following changes to the /additional-resources page

1. Update the “Housing Authority of the County of San Mateo” tile with new link
    - This current links to a broken page
    - New link: https://www.smcgov.org/housing/apply-housing-authority-waiting-lists
2. Remove the “Affordable Rental Housing List” tile
3. Change “Housing Choices” link
    - New link: https://www.housingchoices.org/ 

QA Notes:
These changes should be seen in the dev SMC site: https://smc.bloom.exygy.dev/

**Comment by sarahlazarich** [comment]
QA'd and looks good, thank you.
