### ISSUE TITLE
Core - Public Multiple Photos

### ISSUE THREAD

**Issue by sarahlazarich** [bloom-housing/bloom#3345]
**User Story:** 

As a resident
I want to see multiple photos for a listing
So that I can get more details about the unit I might be applying for

**Additional Detail:** 
Design asset required? Yes
https://www.figma.com/file/6rWMvZSz1YJmZteInX7rpZ/Multi-Image-Gallery?node-id=4-46

On Partners Portal, there are no major design changes, but the experience should mirror the Detroit experience, shown below. 
![image.png](https://images.zenhubusercontent.com/637d0ad803d649bd438df415/f4a0eb8b-ddd4-4e34-b2ae-eb6010a9eaac)

**Technical Notes:** 
Change to UI component required? Yes

**Acceptance criteria:** 

- When I am on a listing detail page that has multiple photos added, then I will see the grid with the primary photo first
- When I click on the see more, then I will see a modal that will show all of the photos
- When I am on the browse listings page, the primary photo should be the primary photo that I have set
- On the partners portal, I see a note in the photo upload feature that I can only upload X pictures. 

QA review instructions: 
- TBD

**Comment by sarahlazarich** [comment]
Making this ticket to pull in the Detroit issue [1343](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/cityofdetroit/bloom/1343) back in to Core. Design assets and technical details for core version to come.

**Comment by eajensenwa** [comment]
@KrissDrawing re our slack conversation: at least one listing photo is required to publish on Bloom Core, so a default image is not needed here.
![Screenshot 2023-04-12 at 9 01 08 AM](https://user-images.githubusercontent.com/38386896/231524015-b57abcc6-38fb-4d86-95e0-497d32594faa.png)

**Comment by KrissDrawing** [comment]
QA notes:
Now on partners site we can add multiple photos to listing, after clicking add photo drawer will appear where we can upload few photos. (they will be saved after saving whole listing).
On public site image component have different states for 1,2,3 and 4+ images.
For 3 and 4+ images it will be placed differently on mobile than on desktop.
After clicking image component with 2 or more images it will open modal. For it spacings and placement of close button will be different for mobile and desktop

There are a few known issues in follow-up tickets:
https://github.com/bloom-housing/ui-components/issues/108
https://github.com/bloom-housing/bloom/issues/3435

**Comment by sarahlazarich** [comment]
This looks good! thanks Kris.
