### ISSUE TITLE
Spike: Backend Overhaul

### ISSUE THREAD

**Issue by YazeedLoonat** [bloom-housing/bloom#3370]
This is a spike to figure out the best approach forward with the typeORM upgrade https://github.com/bloom-housing/bloom/issues/3184 . 

The outcome of this should be a technical doc that lays out 3 pathways:

1) what it would look like to switch away from a scope of request of the various services on the backend

2) what it would look like to switch away from the circular dependencies that currently happen on the backend (modules needing a module that needs the first module is common around both Auth and Listing modules)

3) what it would look like to overhaul the backend with the new ORM selected in: https://github.com/bloom-housing/bloom/issues/3367

the doc should go over both the work that needs to be done, and maybe a breakdown of complexity

**Comment by YazeedLoonat** [comment]
Technical Design Doc available: https://docs.google.com/document/d/1OhXv5CB72YVRyBF9sb4LAO3k8oy449uIWKaJ2kBUXTQ/edit#

**Comment by sarahlazarich** [comment]
can close this since we discussed as a team - will discuss follow up tickets.
