### ISSUE TITLE
Searching on the applications table causes the page to crash

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#3377]
In dev and production, searching the applications table in partners is causing the page to crash. It seems like you have to query a string that has a space in it.

**Comment by KrissDrawing** [comment]
QA notes: Go to listing applications tab (e.g. https://partners.bloom.exygy.dev/listings/d60aea19-9e5f-453d-83f2-3c88084de661/applications)
- It will search by: first name, last name, email, phone (and all in that certain order, space separated), so typing "last name first name" won't work. 
- Same for alt contact
- we can search also by application number

**Comment by sarahlazarich** [comment]
This looks good!
