### ISSUE TITLE
Replace JSONPath query with proper query parameters

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#338]
As we move from our temporary JSON listings storage to everything being properly normalized in a database, it should also be a good opportunity to bring more structure to the query parameters in the REST API endpoints for listings.

AFAIK, the only parameters we're using at this point are City and County for geographical narrowing from the common listings service, so that would be a reasonable starting point. Chances that we'll want to allow a wider range of parameters are basically 100%, but I don't think there's any hurry to maximize the number of options.

**Comment by emilyjablonski** [comment]
@seanmalbert I think we can close this :)
