### ISSUE TITLE
Remove all references to our current jurisdictions (HBA and Detroit) in core

### ISSUE THREAD

**Issue by ludtkemorgan** [bloom-housing/bloom#3387]
Due to the way we have setup most of the seeded data, there are a lot of references to specific jurisdictions in the code base of Bloom Core. There is nothing wrong with having these references in it of itself, however, it can cause some issues in our dev environments and as we expand to more jurisdictions we will want it to be more agnostic.

Issues with having the references:
- Since we haven't copied all of the data from the jurisdiction specific repos some of our seeded data is not accurate to what it would actually be,
  - e.g only some jurisdiction translations have been copied over, but some properties rely on those jurisdictions so there can be edge cases that expose this lack of data
- If people were to fork this repo, they would have references to real jurisdictions they don't care about.
- It's good practice to have test data be more test like for the specific usecase
  - e.g our seeded data references old properties (Coliseum or Archer) rather than the use case it was intended for

Steps that should be taken:
- Create fake jurisdictions in `jurisdictions.ts` (jurisdictions for seeding)
- Find all references to the current four jurisdictions in the seeded data and replace them with the new jurisdictions
- Go through all of the seed data files and make them less specific to actual properties
  - Change all phone numbers, emails, and potentially addresses to more generic things
- Clean up tests to remove references to the current jurisdictions

Potential steps that could be taken:
- Take a holistic view at our seeded data and see what could be deleted or drastically change

By the end of this task theoretically all references to "Alameda", "San Jose", "San Mateo", and "Detroit" are removed from the code base (minor exceptions for change logs and such)

**Comment by sarahlazarich** [comment]
related to https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/bloom-housing/bloom/3466

**Comment by sarahlazarich** [comment]
@ludtkemorgan is this covered by the other ticket, or are we good to close here?

**Comment by ludtkemorgan** [comment]
@sarahlazarich I think this can be closed since we will cover it in Prisma
