### ISSUE TITLE
Lay out a plan for integrated analytics in the Partners Portal

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#339]
Not for immediate action, but there have been a number of requests from property managers and other stakeholders to get information about listing views, applications, etc. directly. Feedback on applications should be pretty straight-forwards since all of that will already be in the database, but we should also have a strategy for listing views and other things currently captured only in Google Analytics.

**Comment by kathyccheng** [comment]
Going with Google Data Studio
