### ISSUE TITLE
Uptake FieldValue Component in Bloom-Core

### ISSUE THREAD

**Issue by sarahlazarich** [bloom-housing/bloom#3396]
**Description:** Uptake component into Bloom Core

**Links:**

**Acceptance criteria:**

**QA review instructions**

This component is primarily used on:

- the review step of the Listing Application Form on the public site
- the read-only preview of listing data on the Partners site (aka before you try editing the listing)

There are expected visual differences in this new component. You can compare the pages above in dev and production to ensure all the data is displaying.

**Comment by sarahlazarich** [comment]
@emilyjablonski - is this for design QA? Can you tag the person who should QA this please?

**Comment by emilyjablonski** [comment]
@sarahlazarich Anyone can QA!

**Comment by sarahlazarich** [comment]
ok, took a look - lgtm
