### ISSUE TITLE
Add updated timestamp and is_waitlist_open to the baseView

### ISSUE THREAD

**Issue by ludtkemorgan** [bloom-housing/bloom#3398]
There are two fields that the doorway team would like to have access to on the /listings endpoint. Rather than having them have to hit the full view version, we can just add these two fields to the response in the base view.

Fields:
- updatedAt
- isWaitlistOpen
- neighborhood

All of these fields are on the listings table itself so should not require a change to our overall db query

*Note*: neighborhood was added to this ticket on 04/13

QA Notes:
- This will have no impact to the front-end. However, the three new fields should appear in the /listings endpoint here: https://bloom-backend-main.herokuapp.com/listings?view=base&limit=all&filter[0][$comparison]==&filter[0][jurisdiction]=ce4d2332-2a00-4129-a7da-8c98d2968f79&filter[1][$comparison]==&filter[1][status]=active&orderBy[0]=mostRecentlyPublished&orderDir[0]=DESC

**Comment by sarahlazarich** [comment]
@ludtkemorgan - I don't see "updatedTimestamp" in that output. Is it meant to be updatedAt?

**Comment by ludtkemorgan** [comment]
> @ludtkemorgan - I don't see "updatedTimestamp" in that output. Is it meant to be updatedAt?

Correct. I'll update the description of this story

**Comment by sarahlazarich** [comment]
Sweet, in that case, this passed!!
