### ISSUE TITLE
Translations - 64 character error message

### ISSUE THREAD

**Issue by sarahlazarich** [bloom-housing/bloom#3416]
Translate the error string "Must not be more than 64 characters." in Core, and all jurisdictions.

English: Must not be more than 64 characters.

HBA:
- Tagalog: Hindi dapat higit sa 64 na character.
- Spanish: No debe tener más de 64 caracteres.
- Vietnamese: Không được nhiều hơn 64 ký tự.
- Chinese: 不得超过 64 个字符

**Comment by KrissDrawing** [comment]
QA notes: go for example to create-account (https://bloom.exygy.dev/create-account) -> type in first name with more than 64 characters, click create account. Now error should appear.

**Comment by sarahlazarich** [comment]
this looks good!

**Comment by sarahlazarich** [comment]
this looks good!
