### ISSUE TITLE
SMC - Open Listing Selection Criteria Not Saving

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#3418]
The property manager for Montara in SMC, an open listing, needs to update their building selection criteria link. However, when they go in to change the link and click "save", the changes do not appear. This issue has been replicated by Exygy staff. The link should be changed to: https://bridgehousing.com/1-montara-cvr-ltr_4-19-2023/. It is currently a PDF: https://res.cloudinary.com/exygy/image/upload/housingbayarea/1.Montara-Cvr-Ltr_4.12.2023_hyeens.pdf

This is a medium priority issue. 

**QA NOTES**
Go in to edit or create a listing
upload a file for the building selection criteria
this should save correcty
go back in to edit the listing and switch the building selection criteria to be a url
this should save correctly now too

**Comment by sarahlazarich** [comment]
this looks good! thanks.

**Comment by sarahlazarich** [comment]
this looks good! thanks.
