### ISSUE TITLE
Building Selection Criteria URL Not Working for Certain URLs

### ISSUE THREAD

**Issue by ColinBuyck** [bloom-housing/bloom#3422]
When saving a URL for Building Selection Criteria, the link on the public side doesn't work correctly with some urls. For example, when entering www.example.com it appends the building selection url to the end of the listing id and results in the same page. 

Technical Notes:
- Seems related to whether url starts with https
- 

<img width="866" alt="Screenshot 2023-05-01 at 11 25 50 AM" src="https://user-images.githubusercontent.com/53269332/235506152-c7cc729b-d2b4-4e15-b881-25da61735cc2.png">

**Comment by sarahlazarich** [comment]
In order to fox this, we should: 
- require the url to begin with https:// or http://
- update the error validation message to say "url requires https:// or http://"

**Comment by emilyjablonski** [comment]
We have one URL field with an https validation currently (leasing management website in Detroit) and one field with a more generic URL validation (open house URL field).

**Comment by KrissDrawing** [comment]
QA Notes: validation for url field has 2 errors, one for `https://` missing and one for invalid url structure. Submitting empty URL should NOT throw an error.
On partners site in listing create / edit there are 2 URL fields to check:
- building selection criteria
- open house
Another 2 are on `/settings` page, when adding / editing preference:
- add preference URL
- add option URL

aside of that there is one more URL field in listing (digital application URL) but this one will be handled in another task

**Comment by sarahlazarich** [comment]
lgtm!
