### ISSUE TITLE
AC: Old Lottery Results Still Showing on Relisting

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#3425]
City Center Apartments, in AC, is reopening their waitlist, but has published lottery results from 2021 still up on their listing. And, there appears to be no way to delete these results or hide them from public view on the Partners Portal, so AC has gotten several user support requests from applicants who are confused about whether or not this listing is available. Can we manually take down the lottery results or hide them on this listing?

This is a medium priority issue. 

https://housing.acgov.org/listing/02a8bfc3-c6bc-4a79-ba65-0e529708c025/city_center_apartments_38631_fremont_blvd_fremont_ca

**Comment by YazeedLoonat** [comment]
Ended up running the following query to give a temp fix, this needs to be looked at further

```
SELECT
    l.id,
    l.result_id,
    l.result_link,
    l.name,
    le.*
FROM listings l
    LEFT JOIN listing_events le ON le.listing_id = l.id
WHERE l.id = '02a8bfc3-c6bc-4a79-ba65-0e529708c025';

DELETE FROM listing_events
WHERE listing_id = '02a8bfc3-c6bc-4a79-ba65-0e529708c025';

SELECT
    l.id,
    l.result_id,
    l.result_link,
    l.name,
    le.*
FROM listings l
    LEFT JOIN listing_events le ON le.listing_id = l.id
WHERE l.id = '02a8bfc3-c6bc-4a79-ba65-0e529708c025';
```
