### ISSUE TITLE
[bug] Multiple photo can cut off the delete button

### ISSUE THREAD

**Issue by ludtkemorgan** [bloom-housing/bloom#3435]
When adding multiple photos to a listing, if the image name is long enough the farthest right column (delete buttons) is off of the screen. It is still accessible by scrolling right, but there is no indication that you can do that so it appears like the delete button is missing
![image](https://github.com/bloom-housing/bloom/assets/42942267/2a2a8c11-9148-476e-8ab0-e494625d7bf0)

This exists in Detroit along with bloom core.

**Comment by sarahlazarich** [comment]
@eajensenwa or @slowbot - can you provide some guidance on preferred behavior for this table?

**Comment by sarahlazarich** [comment]
tentative plan is to remove file name column from this view -- @slowbot let us know if there are risks there.

**Comment by KrissDrawing** [comment]
QA Notes: go to partners site. In listing, images details table should not have file name.
on edit / create listing both photo tables should not have file name (one in listing photo section, second after click edit photos).

**Comment by sarahlazarich** [comment]
What env should this be tested in? Looked at Detroit and HBA Partners staging and still saw the file name -- 
![Screenshot 2023-06-27 at 9.25.15 AM.png](https://images.zenhubusercontent.com/637d0ad803d649bd438df415/abc609c4-bbf1-45a9-9929-18b6dc29daee)![Screenshot 2023-06-27 at 9.26.52 AM.png](https://images.zenhubusercontent.com/637d0ad803d649bd438df415/eca7e3d5-e2f2-4a03-9f01-9202d6e7d5ab)

**Comment by sarahlazarich** [comment]
oh great. it looks good there then
