### ISSUE TITLE
No Image Fallback

### ISSUE THREAD

**Issue by ColinBuyck** [bloom-housing/bloom#3436]
Although it should be a blocked path, it would be helpful to have some sort of image fallback if the listing image fails or doesn't exist for any reason. At the moment, the following is displayed if the image is not present
<img width="1440" alt="Screenshot 2023-05-09 at 10 51 50 AM" src="https://github.com/bloom-housing/bloom/assets/53269332/26d79c1d-a352-4964-82ed-526a19c39838">

**Comment by sarahlazarich** [comment]
Design to generate placeholder image.

**Comment by sarahlazarich** [comment]
@slowbot or @eajensenwa - just checking in to see if you were able to generate a placeholder image for this? Hoping to pull this in next sprint!

**Comment by eajensenwa** [comment]
@sarahlazarich placeholder image attached!
![CoreDefaultPlacehoder](https://github.com/bloom-housing/bloom/assets/38386896/230c5852-c828-4b73-be50-051e8bf79855)

**Comment by KrissDrawing** [comment]
QA Notes: It's tricky as it shouldn't be possible to get invalid / empty photo, so it technically has to be broken. I don't know how to QA it for multiple photos, but there are a buch of listings either with no photo, or invalid, for example this one: https://bloom.exygy.dev/preview/listings/31317d80-2d62-4e43-9e87-4fa6f0e8c649

**Comment by sarahlazarich** [comment]
tough to QA, but i think this makes sense -- ty!
