### ISSUE TITLE
Prisma: add permissions around new prisma endpoints

### ISSUE THREAD

**Issue by ludtkemorgan** [bloom-housing/bloom#3445]
All create, update, and get endpoints should have proper permissions added in the new Prisma format.

This ticket carries over all of the permissioning system that is in the current setup. Including Casbian. A follow-up ticket will look at the permission system holistically.

**Comment by sarahlazarich** [comment]
across 2 PRs, both tied to this issue 
creating casbian and authgaurds, carrying it over 
JA permission doesn't work well with casbian (there's a follow-up, user SWR)
