### ISSUE TITLE
Upgrade all Postgres versions to be in sync

### ISSUE THREAD

**Issue by ludtkemorgan** [bloom-housing/bloom#3449]
The deployed versions of the backend in Heroku are not on the same versions of Postgres. This is causing issues when we use a feature that is not supported by older Postgres versions. This means that features might work in one environment but not in another and won't get caught in the lower environments.

This issue is to upgrade all of the Postgres versions to the latest version we can. https://devcenter.heroku.com/articles/upgrading-heroku-postgres-databases.

Current versions:

[Bloom core](https://dashboard.heroku.com/apps/bloom-backend-main) - 14.6 - Will be tackled in #3245
[HBA staging](https://dashboard.heroku.com/apps/hba-0-3-alameda-staging) - 12.13
[HBA dev](https://dashboard.heroku.com/apps/hba-dev) - 14.6
[HBA prod](https://dashboard.heroku.com/apps/hba-0-3-alameda-prod) - 12.12
[Detroit dev](https://dashboard.heroku.com/apps/bloom-detroit) - 13.9
[Detroit prod](https://dashboard.heroku.com/apps/bloom-detroit-prod) - 13.9

*Warning: This will most likely require downtime to ensure no data is lost*

This is dependent on #3245 where a postgres version is chosen as long with a documentation of the process and how much downtime is necessary for the change

**Comment by ludtkemorgan** [comment]
@sarahlazarich this is no longer blocked and can be pulled into an upcoming sprint

**Comment by ludtkemorgan** [comment]
This needs to be addressed before April 30th as that is when Heroku will no longer support Postgres 12

**Comment by sarahlazarich** [comment]
Question: 
- Target version? We should all be in sync, not sure if heroku allows you to choose a version. If we have to also upgrade core, we should do that 
- Do we need everyone to up their local versions? Yes!

**Comment by sarahlazarich** [comment]
Assume we're just doing this for HBA, DT should also be updated but we have more time there.
