### ISSUE TITLE
Icon Uptake - List places where the Icon component is being used

### ISSUE THREAD

**Issue by sarahlazarich** [bloom-housing/bloom#3451]
Before we do our Icon Uptake, we need to list the places where the Icon component is being used to determine the best path for updating these. 

AC:
Places where Icon component is being used are listed out.

**Comment by sarahlazarich** [comment]
To discuss in next seeds grooming

**Comment by jaredcwhite** [comment]
I went ahead and decided to audit UIC for custom icon usage as well, just so we have that for future reference.

`spinner`:

- Button loading state
- Loading Overlay
  ![image](https://res.craft.do/user/full/a58ff28e-c601-813e-f05b-5ed087a3b601/doc/42BC07CA-84AE-44E6-AE92-83F2F160BB0E/689B675B-E8AF-44AC-AF3B-0DBD97763DE0_2/nfvApSQyZ0xtMPfJ3xqk8yDI2Zt9EaK9eBEz90lDFzAz/Image.png)

`phone`:

- Housing Counselor block
  ![image](https://res.craft.do/user/full/a58ff28e-c601-813e-f05b-5ed087a3b601/doc/42BC07CA-84AE-44E6-AE92-83F2F160BB0E/76D52F1B-F154-460D-91AD-BABE5D548452_2/On7mJBC1NyZ8rG8tekjxKOvqIJ5xWs9yAL7znABTBxwz/Image.png)

`globe`:

- Housing Counselor block
  ![image](https://res.craft.do/user/full/a58ff28e-c601-813e-f05b-5ed087a3b601/doc/42BC07CA-84AE-44E6-AE92-83F2F160BB0E/19F78827-F36B-482A-9B36-FCE5EA37BF4C_2/a2rpxIFgNxcPjiBxXNSjJiDP75YZCB01zN8kY8ZXFN4z/Image.png)

`plus`:

- Image Card (for multiple images)
  ![image](https://res.craft.do/user/full/a58ff28e-c601-813e-f05b-5ed087a3b601/doc/42BC07CA-84AE-44E6-AE92-83F2F160BB0E/65F9E1EE-B797-4021-A38B-A6BE29CCAD4B_2/42DH7AeaFRdjWxLyoI61QIiFo5zY8KxCeL5LtKZtUfQz/Image.png)

`search`:

- MultiSelect input
  ![image](https://res.craft.do/user/full/a58ff28e-c601-813e-f05b-5ed087a3b601/doc/42BC07CA-84AE-44E6-AE92-83F2F160BB0E/75B8966E-1B47-4491-A87C-5BCAF198652B_2/yzfrdXsDlzizyNcWlVlGUVGnqV8vFqGYfkN4gRD12k4z/Image.png)

`arrowDown`:

- Site Header
- Listing Detail header
- Content Accordion
  ![image](https://res.craft.do/user/full/a58ff28e-c601-813e-f05b-5ed087a3b601/doc/42BC07CA-84AE-44E6-AE92-83F2F160BB0E/D529835F-55B7-40FD-A39C-E3FB3A3DD872_2/SHKujng3IuU7CFzsc1RCMMmVeXnBhJnXYgeK2Rua0XEz/Image.png)

`close`:

- Drawer
- Modal
  ![image](https://res.craft.do/user/full/a58ff28e-c601-813e-f05b-5ed087a3b601/doc/42BC07CA-84AE-44E6-AE92-83F2F160BB0E/375A82A9-AEB0-4F9A-A957-25AA53046864_2/HFOGn2yownq3lAEVofBLjy9C9ln5Lv1USNbk9Ms3KTUz/Image.png)

`check`:

- Application Timeline
  ![image](https://res.craft.do/user/full/a58ff28e-c601-813e-f05b-5ed087a3b601/doc/42BC07CA-84AE-44E6-AE92-83F2F160BB0E/26235DFA-2621-4ECC-9BE2-5627987F903C_2/iKdmMQcrOYRSINapJB3SKkRZcB3q5lO4y1YLQzPrJRgz/Image.png)

`clock`:

- Listings Group
- Application Status
  ![image](https://res.craft.do/user/full/a58ff28e-c601-813e-f05b-5ed087a3b601/doc/42BC07CA-84AE-44E6-AE92-83F2F160BB0E/CE2FD3CD-CE71-48DA-9E43-C51200DCE4A7_2/2u8th1LRTY7UyZa203xzKMXjBEmzgtzVpE6RrMzla4Az/Image.png)

`closeSmall`:

- Site Header
- Content Accordion
  ![image](https://res.craft.do/user/full/a58ff28e-c601-813e-f05b-5ed087a3b601/doc/42BC07CA-84AE-44E6-AE92-83F2F160BB0E/69B807FF-5F49-41C0-B41B-E27A66C0FDA8_2/Q521XZR3qFrVVCu5qTmw9hjQl8wUhRfvzmOOLH63WQsz/Image.png)

`hamburger`:

- Site Header
  ![image](https://res.craft.do/user/full/a58ff28e-c601-813e-f05b-5ed087a3b601/doc/42BC07CA-84AE-44E6-AE92-83F2F160BB0E/5EF1CE94-DA16-460E-A28A-1AF6E78383DF_2/aF4XuSUz4AyMDA3LMOuysKCVXxJ0Oh5Lpm9Ky1KaDCgz/Image.png)
