### ISSUE TITLE
AC: Resource Card Updates

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#3457]
AC would like to make the following changes to their resource cards. This is a low priority issue. There are 10 changes, including removing one card and adding a new one. 

1. Remove "Independent Living" Card
![image.png](https://images.zenhubusercontent.com/628807cfd47647a5b2738c30/90ef2e03-5130-4a3e-8650-44f1283c386b)

2. Replace the URL of "AC Housing Secure" with https://www.ac-housingsecure.org/property-owner
![image.png](https://images.zenhubusercontent.com/628807cfd47647a5b2738c30/cf100d2b-9441-458a-b1fe-5329186d55dc)

3. Change the office hours details for Bay Area Community Services" to say: 
Walk in at 629 Oakland Avenue, Oakland
Office hours: 12-3pm Mon, Tues, Wed, Thur, Fri

4. For BOSS Community Services, update phone number to read 510-844-8580
![image.png](https://images.zenhubusercontent.com/628807cfd47647a5b2738c30/d358b18e-9950-4d20-9ea4-011bfcc77443)

5. Change Family Front Door where it says "Emeryville" to "Emeryville Families"

6. Update walk in info for Women’s Daytime Drop-In Center to read:
Walk in at 2218 Acton St. Mon
Office Hours: Wed, Fri 9am-2pm
![image.png](https://images.zenhubusercontent.com/628807cfd47647a5b2738c30/282d645b-2327-41b4-a06e-5392949f4beb)

7. For "Building Futures - West (San Leandro)" - update the phone number to 510-686-2332 and add walk in info below:
Walk in at 1840 Fairway Dr, San Leandro
Drop-in hours: 10am – 2pm Tue

8. For "Building Futures - West (Alameda)" - add the follow walk in information:
Walk in at 2500 Barbers Point Rd, Alameda
Drop-in hours:  10am – 12pm Mon
![image.png](https://images.zenhubusercontent.com/628807cfd47647a5b2738c30/67c7be43-1da7-49e8-be34-4343f175c1eb)

9. For "Fremont Family Resource Center" - add the following walk in information:
Walk in at 39155 Liberty St., Fremont, CA
(Millenium Room)
Drop-in hours Thurs 10-12 and 1-3pm
![image.png](https://images.zenhubusercontent.com/628807cfd47647a5b2738c30/22def959-eeb8-424e-bfc0-501d2ace8dc9)

10. Add a resource card with the following information:
Transitional Aged Youth 18-24 years old (Open to all Alameda County Youth)
Unsheltered Youth
Call Covenant House at 510-379-1010 (ask for the Wellness Center)
Walk in at 200 Harrison Street, Oakland
Drop-in hours Tues and Thurs 1-3pm
Youth are also able to go to adult and family access points.

**Comment by iph-97** [comment]
UPDATE to item #5: change "Emeryville" to "Emeryville Families Included"

![image.png](https://images.zenhubusercontent.com/628807cfd47647a5b2738c30/f4733ecb-a657-42b2-bc77-0213af9f4d5a)

**Comment by sarahlazarich** [comment]
Translations for the new resource card:

Filipino:

Transitional Aged Youth 18-24 years old (Bukas sa lahat ng Alameda County Youth)
Kabataang Walang Silungan
Tumawag sa Covenant House sa 510-379-1010 (humingi ng Wellness Center)
Maglakad sa 200 Harrison Street, Oakland
Mga oras ng pag-drop-in Martes at Huwebes 1-3pm
Nagagawa rin ng mga kabataan na pumunta sa mga access point ng adult at pamilya.

Chinese:

18-24 岁的过渡性青年（向所有阿拉米达县青年开放）
流浪青年
致电 510-379-1010 联系 Covenant House（询问健康中心）
走进奥克兰哈里森街 200 号
周二和周四下午 1-3 点上门服务
青少年也可以前往成人和家庭接入点。

Vietnamese:

Thanh niên trong độ tuổi chuyển tiếp 18-24 tuổi (Dành cho tất cả Thanh niên Quận Alameda)
Tuổi Trẻ Không Che
Gọi cho Covenant House theo số 510-379-1010 (yêu cầu Trung tâm chăm sóc sức khỏe)
Đi bộ tại 200 Harrison Street, Oakland
Giờ nhận phòng Thứ Ba và Thứ Năm 1-3 giờ chiều
Thanh niên cũng có thể truy cập các điểm truy cập dành cho người lớn và gia đình.

Spanish:

Jóvenes en edad de transición de 18 a 24 años (abierto a todos los jóvenes del condado de Alameda)
Jóvenes sin protección
Llame a Covenant House al 510-379-1010 (pregunte por el Centro de Bienestar)
Entra en 200 Harrison Street, Oakland
Horario de atención martes y jueves de 1 a 3 p. m.
Los jóvenes también pueden ir a los puntos de acceso para adultos y familiares.

**Comment by KrissDrawing** [comment]
@sarahlazarich Do we have translations for other changes? Or just leave them in english for now?

**Comment by sarahlazarich** [comment]
@KrissDrawing I missed those, I'll follow up with translations.

**Comment by sarahlazarich** [comment]
@KrissDrawing - see below! 

3. 
Walk in at 629 Oakland Avenue, Oakland
Office hours: 12-3pm Mon, Tues, Wed, Thur, Fri

Filipino
Maglakad sa 629 Oakland Avenue, Oakland
Mga oras ng opisina: 12-3pm Lun, Mar, Miyerkules, Huwebes, Biy

Vietnamese
Đi bộ tại 629 Oakland Avenue, Oakland
Giờ hành chính: 12-3pm Thứ Hai, Thứ Ba, Thứ Tư, Thứ Năm, Thứ Sáu

Chinese 
走进奥克兰奥克兰大道 629 号
办公时间：周一、周二、周三、周四、周五中午 12 点至下午 3 点

Spanish
Entra en 629 Oakland Avenue, Oakland
Horario de oficina: 12-3pm lunes, martes, miércoles, jueves, viernes

6. 
Walk in at 2218 Acton St. Mon
Office Hours: Wed, Fri 9am-2pm

Filipino
Maglakad sa 2218 Acton St. Mon
Mga Oras ng Opisina: Miy, Biy 9am-2pm

Vietnamese
Đi bộ tại 2218 Acton St. Mon
Giờ làm việc: Thứ Tư, Thứ Sáu, 9 giờ sáng - 2 giờ chiều

Chinese 
走进 2218 Acton St. Mon
办公时间：周三、周五上午 9 点至下午 2 点

Spanish
Entra en 2218 Acton St. Mon
Horario de oficina: miércoles, viernes 9am-2pm

(7)
Walk in at 1840 Fairway Dr, San Leandro
Drop-in hours: 10am – 2pm Tue

Filipino
Maglakad sa 1840 Fairway Dr, San Leandro
Mga oras ng pag-drop-in: 10am - 2pm Mar

Vietnamese
Đi bộ tại 1840 Fairway Dr, San Leandro
Giờ nhận phòng: 10 giờ sáng - 2 giờ chiều Thứ Ba

Chinese 
走进 1840 Fairway Dr, San Leandro
上门服务时间：周二上午 10 点至下午 2 点

Spanish
Entra en 1840 Fairway Dr, San Leandro
Horario de atención: 10 a. m. a 2 p. m.

(8)
Walk in at 2500 Barbers Point Rd, Alameda
Drop-in hours: 10am – 12pm Mon

Filipino
Maglakad sa 2500 Barbers Point Rd, Alameda
Mga oras ng pag-drop-in: 10am - 12pm Lun

Vietnamese
Đi bộ tại 2500 Barbers Point Rd, Alameda
Giờ nhận phòng: 10 giờ sáng – 12 giờ trưa Thứ Hai

Chinese 
走进 2500 Barbers Point Rd, Alameda
上门服务时间：周一上午 10 点至中午 12 点

Spanish
Entra en 2500 Barbers Point Rd, Alameda
Horario de atención: 10 a. m. a 12 p. m. lun.

(9)
Walk in at 39155 Liberty St., Fremont, CA
(Millenium Room)
Drop-in hours Thurs 10-12 and 1-3pm

Filipino
Maglakad sa 39155 Liberty St., Fremont, CA
(Millenium Room)
Mga oras ng pag-drop-in Huwebes 10-12 at 1-3pm

Vietnamese
Walk in tại 39155 Liberty St., Fremont, CA
(Phòng Thiên niên kỷ)
Giờ nhận phòng Thứ Năm 10-12 và 1-3 giờ chiều

Chinese
走进 39155 Liberty St., Fremont, CA
(千禧房)
周四 10 点至 12 点和下午 1 点至 3 点的上门服务时间 

Spanish
Entra en 2500 Barbers Point Rd, Alameda
Horario de atención: 10 a. m. a 12 p. m. lun.

**Comment by ludtkemorgan** [comment]
This has been merged and can be seen here: https://ala.bloom.exygy.dev/additional-resources

**Comment by sarahlazarich** [comment]
lgtm
