### ISSUE TITLE
Prisma: Actual useful Seed Data

### ISSUE THREAD

**Issue by YazeedLoonat** [bloom-housing/bloom#3466]
**What is this feature or what feature is this part of?**
Currently we don't have good seed data in the new prisma stuff
I think it would be funny if everyone made a listing and then I can just use that data

if people can just give me a json file or literally just this but filled out with useful data it would go a long way

**Comment by sarahlazarich** [comment]
Product to make some test listings. 

We are getting close to our row limit for seed data, need to cut it down to only useful test listings.

**Comment by seanmalbert** [comment]
Linking to convo from #3478: https://github.com/bloom-housing/bloom/pull/3478/files#r1230227715

**Comment by sarahlazarich** [comment]
@ludtkemorgan @YazeedLoonat can you please add QA notes + tag the person responsible or close this?

**Comment by ludtkemorgan** [comment]
This cannot be QA'd more than what it was during the PR process. It has been partially deployed to a testing environment in heroku and you can see the data populated here: https://bloom-prisma-96be10547db7.herokuapp.com/api. I will close this issue and add extra verification steps to later stories.
