### ISSUE TITLE
CORS_ORIGINS config variable is breaking deploy previews

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#3468]
At the moment on our core public site deploy previews, you can't apply for applications. We think the issue is bc the CORS_ORIGINS is looking for certain URLS and the deploy preview URLs are different every time.

Not sure what the solution should be (can we regex the value, or remove the check from dev?)

**Comment by YazeedLoonat** [comment]
I think there is a pastability to pull the CORS_ORIGIN check when the env is DEV and keep it around for when the ENV is prod 

I think the other option is to change 
`app.module.ts` line ~49 to work with a reg ex solution

**Comment by emilyjablonski** [comment]
Not ready for QA yet post-merge

**Comment by emilyjablonski** [comment]
QA Notes
Ensure that the first page of starting an application after clicking `Apply Online` fully loads in a deploy preview (ex: https://deploy-preview-3611--bloom-demo-public.netlify.app)

**Comment by emilyjablonski** [comment]
@sarahlazarich we don't have mandatory accounts anywhere, that behavior is what happens when the preview isn't working - our apps having the listing image and apply buttons on that page - not sure why the preview isn't working anymore will take a look!

**Comment by emilyjablonski** [comment]
sorry it was just the wrong link! this should work: https://deploy-preview-3564--bloom-exygy-dev.netlify.app/applications/start/choose-language?listingId=285b6ec8-16fe-4561-b44f-b2c438d3e76c

**Comment by sarahlazarich** [comment]
awesome, that works!
