### ISSUE TITLE
Standardize on primary keys for important objects

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#348]
As we move to put everything in the database, we have a couple of different object ID standards in progress, and I think we'd benefit from standardizing on one method across the board. Ideally this will be something that can be reasonably consistent from the database the whole way through to the front end, including being URL friendly for things like listings.

Leading options that I see are:

1. **UUIDs in the DB; Hashed UUIDs from the API.** The first set of TypeORM migrations is already set up for UUIDs as database primary keys, and that's certainly easy enough to continue as the DB pattern. We could also hash them for front-end / external use, perhaps [as described here](https://medium.com/@huntie/representing-a-uuid-as-a-base-62-hash-id-for-short-pretty-urls-c30e66bf35f9), or any other reasonable variant thereof.

2. **Integers in the DB; HashIDs from the API.** This would involve changing the existing DB objects  to auto incrementing integer IDs, and then using [Hashids](https://hashids.org/) of those internal integer IDs from the API out. Seems like an easy enough change now, but would get harder over time.

In either case, I think we'll end up getting rid of the current nanoid solution, though I guess there's a potential 3rd option where we use those as primary keys the whole way through. That seems less appealing since there's no real postgres support for it and I don't think a string primary key would be as performant as an integer or UUID there, but I'm open to discussion if someone thinks it's a good option.

Benefits of switching to option 2 from my perspective are: 

- We could have shorter Hashids for most objects than if we had to encode a whole UUID, in most cases much shorter. This should be nicer for debugging, and more URL friendly in those cases where that matters.

- I think it's easier to debug at the database layer when you can just type a relatively short integer rather than having to copy/paste a UUID.

Benefits of staying with option 1 are:

- Things are ~guaranteed globally unique at the DB layer, so we're set up for any sort of future multi-master DB scenario. (I think this need is unlikely, but theoretically possible.)

- Slightly simpler hash function implementation since there's no effort needed to protect the salt. (If we're using sequential integers, I think we'd want the hash salt in a env variable so it's not in the Open code. I realize Hashids aren't crypto strong anyway, but we should at least make  reasonable efforts to keep the public IDs opaque).

Personally, I think the benefits of option 2 outweigh the costs, but reasonable people can disagree so I'd like to invite feedback from @pbn4 @software-project @bencpeters and @jaredcwhite. Once everyone weighs in, then we'll assign this for implementation.

**Comment by bencpeters** [comment]
I think option 2 sounds good. The only thing I think we lose from a debugging standpoint is the ability to easily look up database records from an API path/request log without reverse hashing (although if we're hashing the UUIDs anyway this benefit is fairly moot).

**Comment by jaredcwhite** [comment]
@bk3c One thing I've always liked about the Stripe API is they have a prefix for each id to indicate the object type. If we were to do that we'd have something like "lis_8Ha9Nw9f8B", "unit_qu2N5fjsnf", etc. Is that something that could work along with the hashids?

**Comment by pbn4** [comment]
> In either case, I think we'll end up getting rid of the current nanoid solution, 

Where do we use nanoid on the backend? I'm unable to find it. 

> UUIDs in the DB; Hashed UUIDs from the API. The first set of TypeORM migrations is already set up for UUIDs as database primary keys, and that's certainly easy enough to continue as the DB pattern. We could also hash them for front-end / external use, perhaps as described here, or any other reasonable variant thereof.

Why hash them for the API? UUIDs are not enumerable so no one will be able to deduce e.g. how many applications were submitted. I consulted internally and there is no security benefit from doing that. With UUIDs being primary keys in the DB we only need to make sure users do not use them directly on the frontend e.g. save a link with an encoded UUID, because those could (theoretically) change in the future, e.g. when we migrate the DB. With Hashed UUIDs which are computed from the primary key we are not getting rid of this problem in any way. I'd go with what we already have and use slugs where necessary.

**Comment by kathyccheng** [comment]
I think we decided not to pursue this path for now, closing
