### ISSUE TITLE
Backend crashing on application flagged sets endpoint

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#3491]
Periodically, we are getting what looks to be like a memory issue on the application flagged sets endpoint in production

https://exygy.slack.com/archives/C0514782RK8/p1685567639773479

**Comment by sarahlazarich** [comment]
Per convo with @ludtkemorgan - can't repro, no jurisdictions have reached out to us about this. Moving to backlog. 

https://exygy.slack.com/archives/C01Q4QG5R8Q/p1686681584442719
https://exygy.slack.com/archives/C02G1S19QA2/p1686684604007299

**Comment by ColinBuyck** [comment]
Closing per memory improvements with prisma
