### ISSUE TITLE
Listing updated_at field doesn't truly reflect listing updates

### ISSUE THREAD

**Issue by ludtkemorgan** [bloom-housing/bloom#3495]
The `updated_at` field on the listings table is automatically updated whenever a field is updated on row. For a majority of cases this makes sense, however there is a field called `last_application_update_at` that gets updated every time an application is submitted. This causes confusion on the listings page in partners as we expose that field and imply it is when the listing was last updated.

![image (3)](https://github.com/bloom-housing/bloom/assets/42942267/2b363a08-27ff-4a48-8c29-d39c61910d0f)

Solution options:
1. Add new field in the listings table that is the true last updated time and use this field to display on the front-end
2. Don't update the updated_at field when only the `last_application_update_at` field was updated (might be hard to customize this workflow)
3. Hide this field from the front-end. Would need product and client approval

**Comment by sarahlazarich** [comment]
Context - https://exygy.slack.com/archives/C02G1S19QA2/p1685549894314929

**Comment by sarahlazarich** [comment]
go with option 3 for now, long term go with option one using prisma

**Comment by sarahlazarich** [comment]
follow up tracked [here](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/bloom-housing/bloom/3523)

**Comment by KrissDrawing** [comment]
QA Notes: on https://partners.bloom.exygy.dev/ go to listing, 1st section will now have only `listing id` and `Date Created`

**Comment by sarahlazarich** [comment]
looks good!
