### ISSUE TITLE
Bug - Listings not closing 

### ISSUE THREAD

**Issue by sarahlazarich** [bloom-housing/bloom#3499]
We are running in to a caching issue that is preventing jurisdictions from moving listings to closed. See conversations below. 

https://exygy.slack.com/archives/C02G1S19QA2/p1685559921896999
https://exygy.slack.com/archives/C02G1S19QA2/p1686070959678699

Initial findings:
- Cache purging calls were recently switched from partners to the backend
- Purge calls were correctly made after listing closed on June 5th and no errors in the logs
- Potentially there is an issue with the way the proxy is setup with the same change from the first bullet point

**Comment by ludtkemorgan** [comment]
This was merged and now in dev. I will do some testing on the cron job to make sure it works before pulling over to HBA

**Comment by sarahlazarich** [comment]
@ludtkemorgan has this been QA'd? Can we close?

**Comment by ludtkemorgan** [comment]
@sarahlazarich It was QA'd, but I'm hoping I will see if a production listing is closed. I think we can close it but I'll keep a note to monitor when the next listing on prod closes
