### ISSUE TITLE
SJ + SMC: Update "Housing Choices" Resource Card

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#3501]
For both SJ and SMC, the Housing Choices resource card needs to have the following links corrected:

“Housing Choices” header link to: https://www.housingchoices.org/
“Submit a request for Housing Choices Services”: link to: https://housingchoices.my.site.com/interestform/s/

![image.png](https://images.zenhubusercontent.com/628807cfd47647a5b2738c30/b90789f9-0666-4373-896b-cdcefc4a31d1)

This is a low priority issue.

**Comment by ludtkemorgan** [comment]
This has been verified and released to production
