### ISSUE TITLE
Add backend validation for URL fields

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#3510]
Currently on the listing form, field validation is passed backend --> frontend. We currently don't have any validation on URL fields. We should add the IsUrl decorator to ensure URL fields are properly formatted including requiring the protocol.

**Comment by sarahlazarich** [comment]
@emilyjablonski to add fields that need validation in

**Comment by emilyjablonski** [comment]
* Open house event
* Building selection criteria
* Settings - preference url
* Settings - preference option url
* Online application url

**Comment by KrissDrawing** [comment]
QA Notes: For 
- Open house event
- Building selection criteria
- Settings - preference url
- Settings - preference option url

it should work as before cause there is frontend validation, so without tricks we shouldn't be able to get backend error.

Only digital application will change it's behaviour, and should throw same errors as other fields (so 1 for missing https:// and other for invalid page).
So on partners page https://partners.bloom.exygy.dev pick a listing and edit it (or create new one) in application process select `yes` in `is there digital application` and then `no` in common application field. The field that appear will now have validation triggered on listing save. Also now it won't reset on save and will send correct application type.

**Comment by sarahlazarich** [comment]
this looks good!
