### ISSUE TITLE
SJ: Listings Export show different submission times

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#3518]
Mabuhay Courts in SJ reported that when they exported their applications, the times showing on electronic submissions were different on the export than in the Portal. It appears the export is about 7 hours ahead exactly of the Portal display, so this could potentially be a time zone issue. We have been able to replicate this issue. This is a medium priority ask. 

![image.png](https://images.zenhubusercontent.com/628807cfd47647a5b2738c30/6f0ede89-3ec2-4139-8740-2bee5e356659)
![Screenshot 2023-06-20 at 4.28.56 PM.png](https://images.zenhubusercontent.com/628807cfd47647a5b2738c30/7c28e896-1358-4a3f-b038-a499bef92ba6)

QA Notes: https://partners.bloom.exygy.dev/ and https://partners.housingbayarea.bloom.exygy.dev/sign-in

1. Log in
2. Select any listing that has applications
3. Check a listings submission date by clicking its application number
4. Then export applications and ensure that the application submission is the same (timezone adjusted)

**Comment by ludtkemorgan** [comment]
Initial findings: electronic applications are saved in the DB with UTC time. The most likely scenario is we need to convert it to the correct timezone.

**Comment by sarahlazarich** [comment]
lgtm
