### ISSUE TITLE
Cannot delete household member from an application

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#3525]
https://images.zenhubusercontent.com/197330191/a8dbfda2-05ee-4ac8-bb16-c16c18c2bcf5/cannot_delete_household_member.mov

**Comment by KrissDrawing** [comment]
QA notes: on https://bloom.exygy.dev/ go to listing, Start application -> in household section select `other people will live with me` -> after adding household member it should be possible to remove it from `edit` form.

**Comment by sarahlazarich** [comment]
it works!!!!!!!!!!!!!!!!!! looks great.
