### ISSUE TITLE
Doorway - dev site appears in search results 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#3531]
As a user
I don't want to see the dev site in Google search results
So that I don't get confused 

**Acceptance Criteria**
When I google "Doorway Housing Portal"
Then I will no longer see the dev site in search results 

**Notes** 
* Possibly remove from crawling
* Switch URL's for the dev site?

**Comment by ludtkemorgan** [comment]
This has been implemented by removing the dev housingbayarea.org url from the pipeline. It is no longer appearing in searches and if it does the link is not something users can do anything with.

**Comment by sarahlazarich** [comment]
I'm still seeing this in searches but the link doesn't go anywhere![Screenshot 2023-07-11 at 3.25.44 PM.png](https://images.zenhubusercontent.com/637d0ad803d649bd438df415/83a90fed-cfd0-4bc2-83ae-5ab7c407a3c9)![Screenshot 2023-07-11 at 3.25.52 PM.png](https://images.zenhubusercontent.com/637d0ad803d649bd438df415/1243b9a4-005c-41ec-99b6-80bf9d64c286)

**Comment by ludtkemorgan** [comment]
@sarahlazarich It appears to only sometimes appear in searches so it has been hard to test. Hopefully Google will figure out that the site doesn't exist anymore after some time. 

However, it leading to nowhere is expected as that site is no longer deployed to that url and it should mitigate people from getting to our dev site from google.

**Comment by sarahlazarich** [comment]
Ok, so it seems like we're good for now since the link doesn't lead to anywhere!
