### ISSUE TITLE
Doorway - Translations Fixes

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#3532]
Doorway - Repo 
https://github.com/metrotranscom/doorway/issues/245

[Google Audit](https://docs.google.com/spreadsheets/d/15fiMtSNTMZPghrszS7uw4CEk7F4_8HrK4uQsTN3btEQ/edit#gid=1286130834)
[Stakeholder Request] (Original Bug Bash Notes - Rows 3-4)  (https://docs.google.com/spreadsheets/d/15fiMtSNTMZPghrszS7uw4CEk7F4_8HrK4uQsTN3btEQ/edit#gid=226682897)

Google and BAHFA both raised some translation issues. 

The following filter options home page and the listings filter form are not translated: 
- "Any"
- "Studio"
- "(For San Francisco listings, please go to DAHLIA)"

The Spanish translation of "Bay Area Housing Finance Authority (BAHFA)." in the welcome banner on the homepage is incorrect.
- Current translation:  "Autoridad para la Financiación Inmobiliaria del Área de la Bahía (BAHFA)."
- Correct translation: "Autoridad para la Financiación de la Vivienda del Área de la Bahía (BAHFA)."

QA Notes:
https://dev.housingbayarea.mtc.ca.gov/

Start on the homepage and change the language
Notice that "Any", "Studio" and the Dahlia field note all have translations
Go to the listings page
Change the language and then open the filter form, checking for those same three translations
Repeat step 4 for each of the languages

**Comment by iph-97** [comment]
"Any"
- Es: Cualquier
- Vi: Bất kì
- Zh: 任何
- Tl: Anuman

"Studio"
- Es: Estudio
- Vi: Studio
- Zh: 單房公寓
- Tl: Studio

"(For San Francisco listings, please go to DAHLIA)"
- Es: (Para listados de San Francisco, vaya a DAHLIA)
- Vi: (Đối với danh sách San Francisco, vui lòng truy cập DAHLIA)
- Zh: （欲了解舊金山列表，請前往 DAHLIA）
- Tl: (Para sa mga listahan ng San Francisco, mangyaring pumunta sa DAHLIA)

**Comment by ColinBuyck** [comment]
@sarahlazarich Ready to QA 🪂

**Comment by sarahlazarich** [comment]
Looks great!
