### ISSUE TITLE
Doorway - Accessibility Contrast Issues 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#3533]
Rows 2-9 
https://docs.google.com/spreadsheets/d/15fiMtSNTMZPghrszS7uw4CEk7F4_8HrK4uQsTN3btEQ/edit#gid=0

QA Notes: https://dev.housingbayarea.mtc.ca.gov/
Using inspect element or the WAVE accessibility tool, verify each of the Exygy recs are accurately reflected. Note that the Paper Application piece may be difficult to demonstrate but the PR includes a video demonstrating the PR's effectiveness in resolving that issue.

**Comment by eajensenwa** [comment]
@ColinBuyck @sarahlazarich Updated colors have been added to column H (Exygy recs)

**Comment by sarahlazarich** [comment]
lgtm!
