### ISSUE TITLE
Doorway - Logo should show on search results 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#3534]
When I google Doorway Housing Portal and see the results 
Then I should see the logo before the results 

![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/5a51df36-8fc9-4808-94f2-6e0ccef087f1)

**Comment by sarahlazarich** [comment]
Looks like this has been fixed, and the logo is showing up in search results
