### ISSUE TITLE
AC: Resolved Duplicates Reverted to Pending

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#3535]
The leasing agent for Bayview, a Greystar property in AC, reported that all 325 of their resolved duplicates had reverted to Pending. They would like to revert them back to the resolved state if possible. We should also determine why this occurred. This is a high priority issue as it is blocking their progress.

![image.png](https://images.zenhubusercontent.com/628807cfd47647a5b2738c30/84072594-fa6c-4ab1-867a-53bf227fc173)

**Comment by YazeedLoonat** [comment]
```postgres
UPDATE application_flagged_set
SET status = 'resolved'
WHERE listing_id = '0e2a6605-d676-40a0-8aeb-b9191caff5ef'
    AND id IN (
        SELECT
            x.application_flagged_set_id
        FROM application_flagged_set_applications_applications x
            LEFT JOIN applications a ON a.id = x.applications_id
        WHERE a.review_status = 'valid'
    );
```

should resolve the existing data, still exploring to figure out why this happened

**Comment by YazeedLoonat** [comment]
Okay I think I was able to replicate this using the following steps:
https://partners.bloom.exygy.dev

- find a listing that has some flagged sets
- go into one of the sets and resolve that set (mark at least one of the applications in the set as valid)
- create a new application that should be a part of the set (on that listing)
- either wait for the afs cronjob to run (not recommended) or using the swagger page use the `/process` endpoint
- head back into the listing's flagged sets page and notice the flagged set is now marked as pending again

**Comment by YazeedLoonat** [comment]
1. figure out why 300+ afs were afffected when only a handful of new applications were created

2. figure out if any other afs sets were affected similarly

**Comment by YazeedLoonat** [comment]
Updated postgres script:

```sql
UPDATE application_flagged_set
SET status = 'resolved'
WHERE listing_id = '0e2a6605-d676-40a0-8aeb-b9191caff5ef'
    AND id IN (
        SELECT
            x.application_flagged_set_id
        FROM application_flagged_set_applications_applications x
            LEFT JOIN applications a ON a.id = x.applications_id
        WHERE a.review_status = 'valid'
    )
    AND afs.id NOT IN ('53bdfcb9-8ad4-4689-abaa-fd504c56768f', 'f77a90c6-d487-4de5-84ab-7c05b269aae0');
```

**Comment by YazeedLoonat** [comment]
Hey @ludtkemorgan when you get a chance can you peep the script above and if it looks good to you I can run on prod

**Comment by ludtkemorgan** [comment]
@YazeedLoonat the script looks good. The only update I needed to do to get it to work locally was to update the first line to `UPDATE application_flagged_set afs` (the `afs` is needed in the last line)

**Comment by YazeedLoonat** [comment]
This has been run and should be good for qa

**Comment by sarahlazarich** [comment]
There are still a few pendings on this listing. @YazeedLoonat is that an issue or expected?

**Comment by YazeedLoonat** [comment]
Hey @sarahlazarich a few of those are expected, 2 of the 4 new applications created should have triggered flagged sets, which accounts for 2 of the pending, and any other pending were previously unresolved or are otherwise new

**Comment by sarahlazarich** [comment]
great, closing
