### ISSUE TITLE
SMC: Listing Edits not Saving, Receiving Error Message

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#3538]
The property manager for Station Park Green, a closed listing in SMC, was trying to edit their listing and kept receiving an error message. When trying to replicate, staff noticed that some information changed or displayed incorrectly (i.e. "Year Built" switching from 2018 to 2021). This is a medium priority issue. 

![image.png](https://images.zenhubusercontent.com/628807cfd47647a5b2738c30/2c4dc386-09bf-4fc2-a31f-4add3abdd865)

**Comment by sarahlazarich** [comment]
Did we get a chance to see if this issue was resolved?

**Comment by sarahlazarich** [comment]
Property manager was able to make updates + save! closing out

**Comment by sarahlazarich** [comment]
Property manager was able to make updates + save! closing out
