### ISSUE TITLE
Doorway - Welcome Banner Content Updates

### ISSUE THREAD

**Issue by sarahlazarich** [bloom-housing/bloom#3541]
Row 5: 
https://docs.google.com/spreadsheets/d/15fiMtSNTMZPghrszS7uw4CEk7F4_8HrK4uQsTN3btEQ/edit#gid=226682897

**Description:** 

On the doorway home page, we want to update the Welcome banner (see below) to say that more listings are coming soon.  
![Screenshot 2023-07-10 at 3.47.08 PM.png](https://images.zenhubusercontent.com/637d0ad803d649bd438df415/9299b2fe-1e8d-4b3a-ab1f-eb27b0731ea8)

Please update the copy to the following: 
Welcome to the Doorway Housing Portal
The portal provides a central place for housing seekers to find and apply for affordable housing throughout the Bay Area.
We're just getting started and will be adding more listings soon!
The Doorway Housing Portal is a program of the Bay Area Housing Finance Authority (BAHFA).

QA Notes
Start here: https://dev.housingbayarea.mtc.ca.gov/
1) Scroll down to the area picture above.
2) Ensure that the new string is present in each of the languages.

**Comment by sarahlazarich** [comment]
@ColinBuyck -- We just spoke with Barry, and he'd like us to keep "Bay Area Housing Finance Authority (BAHFA)" in English by default since it's a proper noun, regardless of what language the user is viewing the page in. Can we do that? Apologies for this!

**Comment by ColinBuyck** [comment]
@sarahlazarich That's no problem! Made those changes and just merged it. Let me know what you think!

**Comment by sarahlazarich** [comment]
This looks good - thank you!
