### ISSUE TITLE
SJ: Add 2023 AMI Tables

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#3548]
New AMI tables are available for addition to the San Jose portal. They are on this [spreadsheet](https://docs.google.com/spreadsheets/d/19xat2CAHME04XwQ8PCbVIPr2LIV8ltGAKLCK_JF-nGM/edit?usp=sharing) under the tabs "SJ - HUD" and "SJ - TCAC". This is a medium priority request.

**Comment by ColinBuyck** [comment]
These are now on [staging](https://partners.housingbayarea.bloom.exygy.dev/) if you want to QA before prod @iph-97 or @sarahlazarich!

**Comment by sarahlazarich** [comment]
![image.png](https://images.zenhubusercontent.com/637d0ad803d649bd438df415/282b1e50-1e25-43d8-9329-95ef2cfa05f9)
I'm not seeing these in staging @ColinBuyck

**Comment by ColinBuyck** [comment]
@sarahlazarich Looks like you're on Foster's Landing here which is a San Mateo county listing. If you look at a listing that is for San Jose or one that doesn't have a Jurisdiction specified yet, you should see them 🦞 let me know if that's still not the case though!

**Comment by sarahlazarich** [comment]
oh great! brain fart, thanks.
