### ISSUE TITLE
Core - Change "Minimum Income" to "Monthly Minimum Income" in Partners

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#3567]
Please adjust the "minimum income" field in the Partners lasting detail page when adding a unit to read "minimum monthly income." This is the result of several property managers making the same mistake in this field by populating it with annual incomes.

**Comment by KrissDrawing** [comment]
QA Notes: go to edit listing in partners site -> add unit -> select fixed amount first label should be `Minimum Monthly Income`.
In listing details page click `view` on unit that has above filled. It should also have `Minimum Monthly Income` now.

**Comment by sarahlazarich** [comment]
this looks good to me!
