### ISSUE TITLE
Uptake - Grid 

### ISSUE THREAD

**Issue by sarahlazarich** [bloom-housing/bloom#3575]
Uptake [grid](https://www.notion.so/exygy/dfe3d376622042ceb5ced1fed661ced0?v=ac0074c6c34e488b980f0e227a8cf661&p=66b7a0dbbebf4f7ca775953fc21fd3d3&pm=s)

**Comment by jaredcwhite** [comment]
## Grid component

Zeroheight: https://zeroheight.com/5e69dd4e1/p/76600d-grid/b/93a6d7
Storybook: https://storybook-ui-seeds.netlify.app/?path=/story/layout-grid--grid-example

## Possible places to use it:

Replacing `<GridSection />`. Lots of views and editing interfaces on the Partners site, like:
<img width="946" alt="image" src="https://github.com/bloom-housing/bloom/assets/658496/f5e98f5d-bbd0-4dc7-ab31-1163bfb4f5ba">
(might want to pull Heading in simultaneously)

Maybe a way to replace the public site's "Listing Row" with a more generic flexible setup?
<img width="1054" alt="image" src="https://github.com/bloom-housing/bloom/assets/658496/1a7501ef-42ae-4c0f-b65d-52d4cf122943">

Any other "info card grid" scenarios, like:
<img width="682" alt="image" src="https://github.com/bloom-housing/bloom/assets/658496/a6a4b6db-9aa6-43dc-a655-1576d65c4e27">

**Comment by jaredcwhite** [comment]
@slowbot So this was what I was alluding to on our last design huddle. There's some grid presentation of data on Partners which looks something like this:

<img width="913" alt="image" src="https://github.com/bloom-housing/bloom/assets/658496/8ac16a90-6a14-43a2-94fb-374e3e6fe30c">

But I'm wondering if I need to replicate the exact layout of all this stuff or make some adjustments to column/row arrangements where it makes sense. For example, the new version could take up less space and look more balanced as so:

<img width="913" alt="image" src="https://github.com/bloom-housing/bloom/assets/658496/5ebff88e-33bf-4399-8ace-de4cde4bfa56">

Happy to try a first pass at tweaking this stuff, or if we just need to stick with what's there for now and wait for a more official design review, let me know.

**Comment by jaredcwhite** [comment]
BTW, just to provide more context on what this update will result in once I submit a PR, there's also Seeds update of Heading, HeadingGroup, and Card in some places to support the updated Grid layouts.
