### ISSUE TITLE
Status fields and migration

### ISSUE THREAD

**Issue by sarahlazarich** [bloom-housing/bloom#3578]
The listings approval process results introduces new statuses.

Currently a listing can have the following statuses:
- Active
- Pending
- Closed

With this new feature, we need the following 5 statuses:

- Pending
- Pending Review
- Changes Requested
- Active
- Closed

Notes from Morgan:

I think we will have to tackle the statuses in a slightly different way for a few reasons. If we were to run a migration of the statuses it would require a simultaneous release of all of the frontends as well. Any delay or failure on one of those releases would mean the front-ends would break since they are still expecting the old statuses. Also, the migration plan would make it harder to have everything behind a feature flag.

Because of this I think we might need to have the old incorrectly named statuses around for at least a while. We can add the two new statuses, but "open" would have to stay as "active" and "draft" would stay as "pending". This might cause some confusion from a code perspective but it should theoretically reduce the complexity. Finally, after the feature has been fully released and feature flag is on for a while we could migrate to the new names. That would require the front end to handle both the new and old status name, run the migration, and lastly change the front-end to only have the new statuses

Another option would be to add the 4 new statuses to the DB but keep the old three in the system as well. The new flow would follow the new status names and the old flow will use the old statuses. Then when we are ready to turn on the feature we run a migration of all the existing listings. The main thing to keep in mind with this option is that the front-end, especially the public site, would need to handle both. For example when we call the backend for the open listings we would need to request for both "open" and "active" listings.

We can discuss this more in tomorrow's backlog grooming

**Comment by emilyjablonski** [comment]
QA Notes:

There is nothing to QA here from the product perspective, it can be closed on merge.
