### ISSUE TITLE
Feature branch + feature flag

### ISSUE THREAD

**Issue by sarahlazarich** [bloom-housing/bloom#3579]
Feature Branch: Create branch off of Bloom Core that Listings Approval PRs will be merged into while development is ongoing

Feature Flag: For now, this can be handled via environment variables since a more sustainable DB approach for feature flags needs to be implemented [here](https://github.com/bloom-housing/bloom/issues/1287)

Notes from Morgan: 
Putting my notes down here for Ways we can handle the feature flag and/or the the feature branch

There are at least two options for having the feature flag on the partner site

Feature flag only on the partner site:
- When listing is “Active” status or a new listing the page should have two submit buttons but only display one of them. One is the existing one and one is the new one
- Display the corresponding submit button depending on the state of feature flag (on = new button, off = old button)
- The new button points to a new backend endpoint and no change to the old one
- Old button will continue to send it to approved status and new button will set it to new status
- If the listing is “Pending approval” status show new page and new flows including using a new backend endpoint
- Same thing with the “Changes Requested” status
- The “Active” status page should work as is. Any slightly different changes will only appear if the env variable is turned on.

Feature flag on partner and update backend:
- Same as above but instead of calling a new endpoint add a new passed in param to the existing endpoint. This would determine the internal code flow per request.
- We also have the ability to do this with or without a feature branch:

With feature branch:
- Git branch
- Netlify deployed version of partner site
- New environment variable set to true
- Heroku deployed version of backend
- Need a new database
- Might want to have a proxy setup as well
- Frequent syncing of main branch into feature branch
- Without feature branch:

Netlify deployed version of partner site
New env variable set to true
Point to existing backend
All commits need to be flushed out before merging and make sure no new changes are outside of the feature flag

**Comment by emilyjablonski** [comment]
No QA needed here
