### ISSUE TITLE
SMC and Alameda: Add 2023 AMI Charts

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#3588]
AMI Charts for San Mateo County are available on this [spreadsheet](https://docs.google.com/spreadsheets/d/19xat2CAHME04XwQ8PCbVIPr2LIV8ltGAKLCK_JF-nGM/edit?usp=sharing) under "SMC - HUD" and "SMC - TCAC".  

Alameda: A property in Oakland has requested to add the city's AMI charts, included in this [spreadsheet](https://docs.google.com/spreadsheets/d/19xat2CAHME04XwQ8PCbVIPr2LIV8ltGAKLCK_JF-nGM/edit?usp=sharing) under "Oakland". 

QA NOTES:
on hba we should have the 2 new SMC ami charts available

and on doorway we should have the new oakland ami chart

**Comment by ludtkemorgan** [comment]
The SMC ami charts are in staging: https://partners.housingbayarea.bloom.exygy.dev/

**Comment by sarahlazarich** [comment]
lgtm!
