### ISSUE TITLE
SMC: Remove SMC Housing Search from Resources Page

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#3603]
San Mateo County is no longer contracting with Emphasys to maintain the SMC Housing Search Page, so now this resource card links to the general 'myhousingsearch.com' site. SMC would like the card removed to reduce confusion. This is a low priority issue. 

![image.png](https://images.zenhubusercontent.com/628807cfd47647a5b2738c30/db70af5c-b444-4e90-9267-c1f41d4bb61b)

**Comment by KrissDrawing** [comment]
QA Notes: https://smc.bloom.exygy.dev/additional-resources first section will now have only 2 cards

**Comment by sarahlazarich** [comment]
lgtm!
