### ISSUE TITLE
AC: Add 2023 Oakland AMI Chart

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#3604]
A property in Oakland has requested to add the city's AMI charts, included in this Google Doc under "[Oakland](https://docs.google.com/spreadsheets/d/19xat2CAHME04XwQ8PCbVIPr2LIV8ltGAKLCK_JF-nGM/edit?usp=sharing)". This is a medium priority request.

**Comment by sarahlazarich** [comment]
Closing, consolidated with https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/bloom-housing/bloom/3588
