### ISSUE TITLE
Bug: Error message for invalid units is not accurate

### ISSUE THREAD

**Issue by ludtkemorgan** [bloom-housing/bloom#3605]
**Describe the bug**
When there is an issue with one of the added units, especially around the AMI chart, the error doesn't happen until you try to save the listing. It also just highlights the "Add Unit" button and says "This field is required" when it's actually an issue with one of the existing units.

Example: 
![image](https://github.com/bloom-housing/bloom/assets/42942267/013e2f7c-98ef-4a92-b540-b9b299d8cbb9)
The "Two Bedroom" unit has an issue but the error is highlighting the "Add Unit" button.

**To Reproduce**
1. Go to a listing in the partner site
2. Click on "Add unit"
3. Add the bare minimum for the unit. (unit type)
4. Select an AMI chart but not the percentage and enter a value in one of the "MAXIMUM ANNUAL INCOME" rows
![image](https://github.com/bloom-housing/bloom/assets/42942267/b0cf03eb-95b5-4c63-8b1a-46893f5437a7)
6. Save and Exit the Unit drawer
7. Save the listing and error will appear

Ideally the incorrect unit row would be highlighted instead of the button. But even more ideally the error would happen on trying to save the unit rather than the listing

**Comment by sarahlazarich** [comment]
Change validation - make user unable to save unit add with errors, so show the errors after each unit added 
Will need design sign off once implemented, as a final check on the flow.

**Comment by emilyjablonski** [comment]
QA Notes
Follow the flow in the ticket description and ensure an error is popped on the ami percentage if it isn't filled out.

Also follow this additional buggy flow:
* Open the unit drawer
* Hit save without filling anything out - the unit type dropdown should error
* Enter a unit type, then select an ami chart
* Ensure the ami percentage dropdown populates (it wasn't!)

**Comment by emilyjablonski** [comment]
@sarahlazarich just a reminder to check in about if it's valid for users to save an ami chart on an individual unit with any of the values missing

**Comment by sarahlazarich** [comment]
this lgtm!
