### ISSUE TITLE
CSV export not working if the file is too big

### ISSUE THREAD

**Issue by ludtkemorgan** [bloom-housing/bloom#3610]
When exporting the applications from the The Berkeley Place property the following error occurs
![Screenshot 2023-08-11 at 10 22 47 AM](https://github.com/bloom-housing/bloom/assets/42942267/3fe4d1e2-f7a3-45ca-bab0-7c6152e09d08)

This is happening because there are over 6,000 applications making the downloadable CSV too big of a file. Specifically it is hitting the limit on Netlify's backend. Since we use the /api/adapter endpoint to hit the backend the file has to get routed through Netlify.

**To Reproduce**
1. Go to the Berkely Place property [here](https://partners.housingbayarea.org/listings/2b91aadd-a76a-4515-aca3-4502776462eb/applications) 
2. Click on the applications tab and click on "Export"
3. The download will fail

Solutions:
- Email the CSV file instead of downloading it
- Focus on the application export for now 

**QA NOTES**
log in to the partner site
navigate to a listing with applications
head to the applications tab
click the export button
the toast at the top right should inform you that an email was sent to the logged in user's email

the email should match the screenshot in the ticket and come with an attached csv of the application data

**Comment by sarahlazarich** [comment]
Email copy is here:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaE8vIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--55661ced41af924dc4cb85172cce7d33d7f04b6a/image.png)
