### ISSUE TITLE
Empty due date still showing section

### ISSUE THREAD

**Issue by sarahlazarich** [bloom-housing/bloom#3630]
Empty due date still showing section#296
On listings where there is no due date, the "empty due date" section is still showing.

Ex.
[Alameda Listing](Alameda Listing)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb0ZWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--87f7afd65a1ec96f532b5460f4e2e15f438b949f/image.png)

AC:
When there is not a due date on a listing, the grey box should not show in Core or Doorway.

Notes: 
- We know there are larger questions about the listings UX here. For the sake of fixing this bug, lets remove the box where there's no due date for now, and we're going to open a separate ticket to reevaluate the UX of filling out a listing in general.
- This may require a UIC change -- may need an extra step to pull this over to doorway from core if it is.

**Comment by sarahlazarich** [comment]
https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/metrotranscom/doorway/296

**Comment by KrissDrawing** [comment]
QA notes: should be hidden for core `How is the application review order determined?` = `lottery` + no `Application Due Date` the one on bottom in Application process for example: https://bloom.exygy.dev/preview/listings/dd74406f-4ef4-4484-8c22-a5c512427781 
Should work also in doorway for same parameters https://dev.housingbayarea.mtc.ca.gov/ (but for some reason can't edit listing for now to get it)

**Comment by sarahlazarich** [comment]
lgtm
