### ISSUE TITLE
Use the primary variant of tags in partners

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#3633]
Currently in partners for status tags, we are sometimes using the light primary variant and sometimes the darker secondary variant. We need to use the lighter primary version everywhere in partners for status tags.

https://deploy-preview-59--storybook-ui-seeds.netlify.app/?path=/story/text-tag--tag-variants

**Comment by emilyjablonski** [comment]
QA Notes
Ensure when a listing is in an open or closed state that the pill is the primary / lighter version

**Comment by sarahlazarich** [comment]
@emilyjablonski what env should we QA at? Are you looking for product or design QA here?
