### ISSUE TITLE
Paper App Download Experience

### ISSUE THREAD

**Issue by sarahlazarich** [bloom-housing/bloom#3634]
**Description**

An issue came to Barry through a prior public email, about the user not realizing they needed to select a language for the paper application. This user clicked download paper, but didn't realize they needed to click "English" to continue.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdWxjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9be61264112f0cb947d0eb9cb73ee966713055bb/image.png)

**Design Recommendations**

- If the paper application is only offered in one language, the file download should automatically begin once the download application button is selected; the user should not need to make an additional language selection.
- If 2+ languages are available, a modal overlay including the list of languages should appear when the download application button is selected.
- Once the user selects a language, the application should open up in a new window where the user can download as a pdf file.

[Design Asset](https://www.figma.com/file/Kcsf148FqeUqMNeMo54BsW/Ad-Hoc-Feature-Enhancements?type=design&node-id=1946-2617&mode=design)

**Comment by sarahlazarich** [comment]
Translations: 

choose a language 
- Spanish: elige un idioma
- Vietnamese: chọn một ngôn ngữ
- Tagalog: pumili ng wika
- Chinese: 选择一种语言

download
- Spanish: descargar
- Vietnamese: Tải xuống
- Tagalog: download
- Chinese: 下载

**Comment by sarahlazarich** [comment]
@eajensenwa - question here about the "download" link. We realized that the current behavior is not actually downloading the file, but is opening in a new tab. Should we update the language on that, or change the behavior?

**Comment by emilyjablonski** [comment]
QA Notes
https://bloom.exygy.dev/
Ensure that if a listing has only one paper application added that the download application link does not open a modal and just opens that paper upload.

Ensure that if a listing has multiple paper applications uploaded that a modal pops with the options of each language, and that hitting the confirm button opens the respective paper app.

**Comment by eajensenwa** [comment]
@sarahlazarich the ideal behavior would be direct download over opening up in a new window. If that capability is browser dependent and not in scope here, I think its ok to leave the language as is since the final action is to download the file

**Comment by sarahlazarich** [comment]
this looks great :)
