### ISSUE TITLE
SJ: Manual Email Notifications

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#3641]
San Jose has opted to set up manual notification sign ups in anticipation of transitioning their list to the automatic email sign ups from DHP when the time occurs. They have their sign up link here: https://visitor.r20.constantcontact.com/manage/optin?v=001r_jNiEsXMVm9HknnNzejPdhJuzSzDWGSt3l3TR90sZU6CeSEqALl76qTkpBRCXcol-hUgzG0aN5s1SgB-z47_OlAbsj_YcXo5Po5Qd66ZO2d2gCKYNJFoYSmcLNNajMxOjA8W3kfPfHh0gFEn5laTw8Tic9GdBl_ This is a low priority request.

**Comment by ludtkemorgan** [comment]
This has been added and deployed to [San Jose](https://housing.sanjoseca.gov/).
