### ISSUE TITLE
Application download error message

### ISSUE THREAD

**Issue by sarahlazarich** [bloom-housing/bloom#3649]
Description:

When an application export fails, the error message that shows up has an incorrect email address. We do not currently have a support email address that is being monitored by Exygy.  Can we please update the message to say "There was an error. Please try again, or contact support for help."

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaEczIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1dbcdd70067ea03f901af9e37a82e8553b760c46/image.png)

**Comment by emilyjablonski** [comment]
QA Notes
Turn off network connection when attempting to export to confirm the new error message text. This either needs to be QA-ed by another engineer, or I can pair with product/design to show y'all how to test the error message.

**Comment by sarahlazarich** [comment]
lgtm!
