### ISSUE TITLE
AC: Resolved Duplicates Moved Back to Pending

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#3660]
The property manager for Casa Suenos in AC reported: "Something seemed to have happened on the Partners Portal. We reviewed about 150 flagged sets today, but around 5PM the system seemed to have reset all the progress and reverted back to showing all flags as pending and one resolved (the one I was reviewing around 5PM). Is there a way for the system to remember the progress we've made without having to go back through the flags? This project has 765 unresolved flags at the moment." It seems that some sets still have applications marked as valid, so maybe the status was the only thing that changed. Can we determine why this happened and if we can undo it? This is a high priority issue.

**Comment by YazeedLoonat** [comment]
This was related to: https://github.com/bloom-housing/bloom/issues/3535

153 records got updated from running that script

**Comment by sarahlazarich** [comment]
This issue was fixed per slack comments
