### ISSUE TITLE
AC: Income Limits Not Allowing Applicants to Apply

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#3675]
AC applicants are getting red lights on the income question. This is happening for the Poppy and potentially the other two listings live on the site. This is a high priority item. [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekVwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aaeff1709e1ebca0354e73653875622c61892695/image.png)

**Comment by ludtkemorgan** [comment]
The disabling of income validation for HBA was accidentally undisabled back in June. This was put back in place and has been released to all HBA sites
