### ISSUE TITLE
AC: Casa Suenos Applications not Exporting

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#3683]
Kimberly from EIR reported this error message appearing when they attempted to download applications for Casa Suenos. I was able to replicate the issue. This is a medium priority issue. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2xHQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f1df002ece3435390c2402e50ca7c8c8f9bd512c/Suenos%20Error.png)

**QA NOTES**
this is up and available on: https://partners.bloom.exygy.dev/sign-in

**Comment by iph-97** [comment]
UPDATE: the CSV export came through to email as expected, so I am amending this ticket. The error message should not appear if the export is working, as that is confusing to applicants. Also the formatting of the export email was appearing oddly (see image). [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd05IQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--26a7753420af0216a67576277ea431e175049551/Screenshot%202023-10-17%20at%205.27.55%20PM.png)

**Comment by sarahlazarich** [comment]
lgtm!
