### ISSUE TITLE
Handle the case where a listing string is null

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#369]
Right now the build has problems dealing with listing values that return `null`. Even worse, it seems to work ok if you do a dev build, but it fails when you do an `export` when trying to call `.replace` in next.config.js.

I'm open to solving this by adding tooling to make sure we never get into this situation, but I think we're probably better off making the evaluation less brittle so that it can still build with just the one value blank if there's not a string to fill in there.

**Comment by bk3c** [comment]
(cc: @pbn4 since you were also in the middle of this, if you have any thoughts)

**Comment by seanmalbert** [comment]
Not sure this is still relevant.
