### ISSUE TITLE
Geocoding - Surface in Application Summary 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#3693]
As a property manager, 
I want to see the additional preference information in the application summary 
So that I can double check 

**Acceptance Criteria** 
When I click into application details in the application tab, then I should see additional information for the preference underneath whether I claimed preference or not 

**Notes**
* Show: Address (Show address details), Name of Address Holder (show name), Relationship Address Holder (show relationship text), Passed Address Check (show Yes, No, Error) 

**Designs** 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1J2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e59724e324723fd3a7c3624a008c8018abe72cc7/image.png)

**Comment by kathyccheng** [comment]
@slowbot can you take a look at how to adjust the design to accommodate new information here?

**Comment by kathyccheng** [comment]
Maybe this already exists

**Comment by KrissDrawing** [comment]
It should undergo QA after the entire geocoding process is complete
