### ISSUE TITLE
Visual issues with Preference editor after Seeds Grid uptake

### ISSUE THREAD

**Issue by jaredcwhite** [bloom-housing/bloom#3698]
Found this while spot checking just after merge… 😬

The Preference form in the drawer after going to [Settings](https://partners.bloom.exygy.dev/settings) is messed up. Some columns are missing, spacings are off, and the wide buttons and dropdowns look weird. See the before and after:

![image](https://github.com/bloom-housing/bloom/assets/658496/560527b5-1bc4-4297-9fa1-9c71de4d7522)
![image](https://github.com/bloom-housing/bloom/assets/658496/ab3f95cb-5ec8-4cc0-9347-bdf37b9cfcce)

**Comment by emilyjablonski** [comment]
Might check the individual option drawer as well after clicking on the edit button

**Comment by jaredcwhite** [comment]
I believe this is addressed now in #3677. Will want to double-check.
