### ISSUE TITLE
Unexpected Spacing Within Edit Preferences Drawer

### ISSUE THREAD

**Issue by ColinBuyck** [bloom-housing/bloom#3704]
The Add Option button seems too close to the questions below it.  
<img width="1440" alt="Screenshot 2023-11-07 at 11 07 50 AM" src="https://github.com/bloom-housing/bloom/assets/53269332/12b25739-61a7-44cf-81f5-37b65e725bcb">

**Comment by jaredcwhite** [comment]
Yeah, this was described in #3698

**Comment by jaredcwhite** [comment]
Fixed: https://github.com/bloom-housing/bloom/issues/3698#issuecomment-1840109163
