### ISSUE TITLE
Geocoding - translations

### ISSUE THREAD

**Issue by ludtkemorgan** [bloom-housing/bloom#3710]
We will need the following translations for all languages that we support:

- "Qualifying Address"
- "Full Name of Address Holder"
- "Relationship to Address Holder"

**Comment by iph-97** [comment]
Google translations have been approved by both AC and SJ staff.

Qualifying Address
- Spanish: dirección calificada
- Filipino: kwalipikadong address
- Traditional Chinese: 合格地址
- Vietnamese: địa chỉ đủ điều kiện

Full Name of Address Holder
- Spanish: Nombre completo del titular de la dirección
- Filipino: Buong Pangalan ng May-ari ng Address
- Traditional Chinese: 地址持有人的全名
- Vietnamese: Tên đầy đủ của người giữ địa chỉ

Full Name of Address Holder
- Spanish: Relación con el titular de la dirección
- Filipino: Relasyon sa May-ari ng Address
- Traditional Chinese: 與地址持有人的關係
- Vietnamese: Mối quan hệ với người giữ địa chỉ

**Comment by ludtkemorgan** [comment]
Additional translation:

English: "Since there are multiple options for this preference, you’ll need to verify multiple addresses."
Spanish: "Dado que existen varias opciones para esta preferencia, deberá verificar varias direcciones."
Filipino: "
Dahil maraming opsyon para sa kagustuhang ito, kakailanganin mong i-verify ang maraming address."
Vietnamese: "Vì có nhiều tùy chọn cho tùy chọn này nên bạn sẽ cần xác minh nhiều địa chỉ."
Traditional Chinese: "
由於此首選項有多個選項，因此您需要驗證多個位址。"

**Comment by emilyjablonski** [comment]
@iph-97 Just checking to see if the `Qualifying Address` strings were translated with the appropriate uppercase on each word?

**Comment by iph-97** [comment]
@emilyjablonski thank you! Confirmed the correct uppercase below. I just directly copied from Google translate.

Spanish: Dirección calificada
Filipino: Kwalipikadong Address
Traditional Chinese: 合格地址
Vietnamese: Địa chỉ đủ điều kiện
