### ISSUE TITLE
Prisma - create migration script to convert existing data

### ISSUE THREAD

**Issue by ludtkemorgan** [bloom-housing/bloom#3734]
In order to get the new Prisma backend to work with our existing jurisdictions we will need to convert the data from the jurisdictions databases to conform to the new database layout.

A majority of the database looks identical to the old database but there are a couple of subtle differences that will require manipulation of the data.

This ticket will require a deep dive into the data to see what exactly needs to be changed and the following should be considered:
- mapping tables that are setup different in Prisma vs TypeORM
- Enum types
- other types

**Comment by YazeedLoonat** [comment]
completed
