### ISSUE TITLE
AC: Applicant Unable to Enter Income

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#3735]
A user in AC reported the following issue. I am following up about device and browser, but I was not able to replicate it. They reported trying to enter $500 monthly income, which worked when I tried it. Could we check the logs and see if anything has been thrown up? Thanks! This is a high priority issue :red_circle:.

" Im trying to apply for the housing list at Identity Logan Park II in Berkeley, CA using the ACHA online portal , but when I get to the income portion it does not allow me to move forward no matter what figure I put in. I am on Section 8 which was a previous question, however I tried putting in my monthly and annual income and it would not let me. The deadline for this process is 11/29/2023 so a prompt response would be greatly appreciated."

**Comment by sarahlazarich** [comment]
resolved via https://exygy.slack.com/archives/C02G1S19QA2/p1701191052029469
