### ISSUE TITLE
Padding issue on address verification page

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#3744]
<img width="519" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHd1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7a3a6227664f92093f9e037edfac7333e241427d/Screenshot%202023-12-04%20at%203.18.51%E2%80%AFPM.png" alt="Screenshot 2023-12-04 at 3.18.51 PM.png" />
<img width="516" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODB1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1e3a3c11f24abfd164586e9dfc546735ea201476/Screenshot%202023-12-04%20at%203.17.03%E2%80%AFPM.png" alt="Screenshot 2023-12-04 at 3.17.03 PM.png" />

**Comment by emilyjablonski** [comment]
QA Notes: Ensure there is padding on the address verification page in the application on the address for the main applicant.

**Comment by sarahlazarich** [comment]
lgtm!
