### ISSUE TITLE
AC: Empty Duplicates Appearing on Listing

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#3748]
The property manager for Identity Logan Park II in Alameda County has resolved all of their duplicates, but there are four remaining duplicates sets that appear empty of data. You can't click on them, so they can't be resolved. These empty applications don't seem to appear in the main application DB view on Partners or in the application CSV export. This is a medium priority issue. 

<img width="1659" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjh5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--21d744118cab46aa01c5a1b440a1842ac2817daa/Screenshot%202023-12-05%20at%208.28.48%E2%80%AFAM.png" alt="Screenshot 2023-12-05 at 8.28.48 AM.png" />

**Comment by sarahlazarich** [comment]
https://exygy.slack.com/archives/C02G1S19QA2/p1701783201799459
