### ISSUE TITLE
Mandated Accounts Feature Flag

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#3752]
We need a feature flag for mandated accounts related changes. This will make it easier to develop and toggle on/off when desired.
Follow the standard process for implementing flag by creating a new environment variable for feature flag and using flag to toggle related components

Acceptance Criteria:
- We can toggle the environment variable on and off by changing the .env file.

**Comment by cade-exygy** [comment]
- Create a new environment variable for feature flag

**Comment by cade-exygy** [comment]
- We need a feature flag for mandated accounts related changes. This will make it easier to develop and toggle on/off when desired.
- Follow the standard process for implementing flag by creating a new environment variable for feature flag and using flag to toggle related components
