### ISSUE TITLE
Spike - Application Export Security

### ISSUE THREAD

**Issue by sarahlazarich** [bloom-housing/bloom#3755]
It came up in a security conversation with Glenn that we may need a way to either 
- Move back to the direct download of the email 
- encrypt the file as it's sent? Let's discuss this.

**Comment by sarahlazarich** [comment]
Per Glenn: If we wanted to continue using email as our method of communication of the applicant lists, we could use AWS Signed URLS which would allow for encription of the file when transmitted to the agent and also allow us to set an expiration date for the file.

**Comment by sarahlazarich** [comment]
Timebox to ~a day 
How much dev effort would this be?

**Comment by YazeedLoonat** [comment]
Update: With prisma we are going to be able to switch back to a direct download!

**Comment by sarahlazarich** [comment]
@YazeedLoonat can we verify that this is also true with the lottery export (cc @emilyjablonski) ? 

Also, do we know at what point we'll have to email these again in Prisma? Are we close to that point?

**Comment by sarahlazarich** [comment]
Is there QA to do here @YazeedLoonat @emilyjablonski

**Comment by YazeedLoonat** [comment]
Hey @sarahlazarich sorry just getting to this today: lottery export (cc @emilyjablonski) from my understanding of what sean did for the application export the lottery export should also be able to do a direct download


`Also, do we know at what point we'll have to email these again in Prisma? Are we close to that point?`
With all the changes to how these are generated, I'm unsure, I know sean was able to generate and send these with the following: `good morning, with the latest updates to the application csv branch, with 10k applications, on average I have it taking under 4s to send a file that's under 4mb.`

which is MILES ahead of what typeorm could do. So we may be set for the foreseeable future basically

**Comment by sarahlazarich** [comment]
Ok, great. Thank you!
