### ISSUE TITLE
Pass in redirectURL to email service for Forgot Password and Confirm Account

### ISSUE THREAD

**Issue by cade-exygy** [bloom-housing/bloom#3760]
After the user creates an account we want to ensure that the confirm account email contains a link that will redirect the user to the listing's application page.

The same should happen for the Forget Password email

**Comment by sarahlazarich** [comment]
What's the best way to get that redirect URL into this email URL, changes needed to email service?
We'd need to change the email service to also take in the incoming URL and pass it through

**Comment by sarahlazarich** [comment]
YL suggestion: TypeORM controller for users is a mess, maybe look also at the Prisma version which is much cleaner
