### ISSUE TITLE
Change how Change Password link works in Forgot Password email

### ISSUE THREAD

**Issue by cade-exygy** [bloom-housing/bloom#3768]

**Comment by sarahlazarich** [comment]
Technically we have this, but would require us to disassemble the reset token, which YL does not reccomend 
In the case that the token is expired, and a user clicks the link, what do they see? 
- you click the link, go to the page, it says token is expired, and makes you re-enter your email go through it all again 
- Based on that, we're probs ok for forget password 
- (Can we verify this though?)

**Comment by cade-exygy** [comment]
This ticket can probably be deleted. I will confirm based on results of #3760
