### ISSUE TITLE
SJ: Listing Browse Image Not Displaying

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#3770]
I noticed that the listing image on the browse page in SJ for Japantown senior is not displaying. The image seems to work fine on the listing details page. This is the only listing with this problem in SJ. This is a low priority issue. 

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1JVQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aab8048489d8775d2acafffa69dcce0866a0ae2b/Screenshot%202023-12-12%20at%205.06.22%E2%80%AFPM.png" alt="Screenshot 2023-12-12 at 5.06.22 PM.png" />

**Comment by YazeedLoonat** [comment]
Hey! So this was a listing originally created in 2021 and the image was in the wrong spot in cloudinary

I reuploaded the image for em and looks like that fixed the issue, lemme know what you think!

**Comment by sarahlazarich** [comment]
lgtm!
