### ISSUE TITLE
Email Template Export 

### ISSUE THREAD

**Issue by sarahlazarich** [bloom-housing/bloom#3776]
Description: We discovered an issue with our automatic notifications in Doorway, we realized that the emails being sent did not have translations. When running Barry past a few options for translating the body of the email, and this is what we landed on.  We want to change the template of the email itself to show the “View Listing & Apply” button multiple times, once in each language option. Depending on the button that the user picks, they would be brought to the listing page in the appropriate language.  A screenshot of the current template is attached.

[Template Design](https://www.figma.com/file/0Rj4I74uO1UTBkHzDR25UD/Automated-Email-Templates?type=design&node-id=2209-1584&mode=design&t=nQEsAO0bCOaHuK2Q-0)

AC:
- Doorway listing notification shows the attached design
- When a user clicks on a button, they're directed to a link in the appropriate language

**Comment by KrissDrawing** [comment]
@sarahlazarich I don't have access to figma file from this task.

**Comment by sarahlazarich** [comment]
@eajensenwa or @slowbot - can you add kris here?

**Comment by ludtkemorgan** [comment]
@KrissDrawing The way that I would go about testing this is to change the part of the code from `this.govSend` to `this.send`. The send function requires a passed in email so I'd recommend hardcoding your own email while testing. And then when it looks good change it back to `this.govSend` and create a PR. Both myself and Colin are able to test in the gov delivery staging environment. That is how we did it while testing the template last time and hopefully it still works. Let me know if you run into issues

**Comment by KrissDrawing** [comment]
QA Notes: Tbh not sure if this can be tested. Locally it was tested by sending template for hardcoded email, which on dev is not possible.

@ludtkemorgan will that somehow work on dev env?

**Comment by sarahlazarich** [comment]
@ludtkemorgan sent me a test, it looks good
