### ISSUE TITLE
Prisma - Update Doorway combine listing after HBA deployment

### ISSUE THREAD

**Issue by ludtkemorgan** [bloom-housing/bloom#3779]
The Doorway repo uses a different flow to get listings than either Core or HBA. It stores listings locally but also calls the three HBA sites asynchronously to get their listings and store them in a separate database table as JSON.

Because of this after we deploy our changes to HBA, Doorway will start running into missing data on the fields that have had a name change (either unintentionally or not). And in order to prevent a loss of listings on Doorway we will need to update Doorway code to handle both the new and old versions of the models.

This can be done either while grabbing the data (combined-listing-transformer.ts) from the database or before saving it via the cron job.

**Comment by sarahlazarich** [comment]
We need to be able to handle both models - bc we will need this live before doorway os officially on Prisma 
Person who picks this up will need to ID fields that actually need to be changed, ML or YL can help
