### ISSUE TITLE
Draft Listing Applications Not Blocked

### ISSUE THREAD

**Issue by ColinBuyck** [bloom-housing/bloom#3780]
A property in SMC recieved applications despite being in draft status. Currently, users are able to get to the draft listing's detail page if they hit the url directly and then apply from that point.

Ideally, applications would block users from being able to do this while not inhibiting the preview listing experience for partners.

QA: https://partners.bloom.exygy.dev/sign-in, bloom.exygy.dev

1. Go to partners and find the id of a draft listing
2. Go to a public listing and alter the url to just have the draft listings id
3. Notice that the apply online button is disabled
4.  Then go back to the partner's page of the draft listing, hit preview, and try to go through the application flow from there.
5. You will be redirected right before submission.

**Comment by sarahlazarich** [comment]
lgtm!
