### ISSUE TITLE
Geocoding - Preference Set Up - Fixed Layers

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#3783]
As an admin, 
I want to be able to add GIS layers for geocoded preferences
So that I can specify a qualifying boundary for a preference program

**Acceptance Criteria** 
* When I am setting up a preference sub-option and I select that I will want to collect addresses, then I will now also see the option to do so with a GIS map in addition to a fixed radius 
* When I click on with a GIS map, then I will see a dropdown where I can select all available layers within my jurisdiction 

**Notes**
* Back end work needed to support this 
* Need a way to store that this is fixed boundary, not radius query and the right map layer 
* Need a way to store the layers in our DB that will speak to MTC's map index 
* Need to save to a preference sup-option the right GIS layer so the system can pass the right information along to the MTC endpoint once the applicant adds and saves an address 

Backend notes:
* New table is needed that stores the names of map layers
  * Only required fields are name, id, and jurisdiction id
* New backend endpoint to query the list of layers. With an optional query param of jurisdiction id
* Multiselect-option should add a new field that can store the id of the map layer
* We can use dummy data now for populating the table for testing

**Designs** 
https://www.figma.com/file/Ne8jOyPpCBvlAhyaRlXgTq/Geocoding?type=design&node-id=1143-5732&mode=design&t=GTW1NNcBl88Zpa21-0

<img width="1064" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDE0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--acf1133bfa9d84092902ce5e04ef31d7d0243328/image.png" alt="image.png" />

https://www.figma.com/file/Ne8jOyPpCBvlAhyaRlXgTq/Geocoding?type=design&node-id=1143-6063&mode=design&t=GTW1NNcBl88Zpa21-0

<img width="1114" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNU40QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e997edef08d69c916df71abdfca667af72321866/image.png" alt="image.png" />

**Comment by KrissDrawing** [comment]
@kathyccheng what should happen on `contact us` click ?

**Comment by kathyccheng** [comment]
LGTM
