### ISSUE TITLE
AC: Listing Preview throwing up 404 Error

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#3794]
I created new preferences for the City of Berkeley for Maudelle Miller Shirek (AC), which includes 2 geocoded preferences (ofc they aren't geocoded yet). I added them to the listing, but when I try to preview I get this 404 error. I was able to replicate this error with other listings that do not have preferences, even after logging out and logging back in. Is something amiss with the preview feature? This is a medium priority issue :large_yellow_circle:. <img width="1511" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXlnQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eef3fe2c25f7a27000ca5cfcdbf5d39e31513d2c/Screenshot%202024-01-05%20at%209.02.28%E2%80%AFAM.png" alt="Screenshot 2024-01-05 at 9.02.28 AM.png" />

**Comment by YazeedLoonat** [comment]
created 2 prs, one for core and 1 for prisma
