### ISSUE TITLE
AC: Preference URLs not Appearing on Preference Application Screens

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#3795]
After adding some new preferences, four of which include URLs, I don't see the URL when I test preview the application. Shouldn't it appear somewhere in the preference description? If not, where is it? This is a medium priority issue :large_yellow_circle:.
<img width="869" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTZoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--42c23453f3b6e92f403da9edc0d7d83744777f41/image.png" alt="image.png" />
<img width="1201" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOStoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7a7804f3f69798f9bd411dee87e541cf70c79560/image.png" alt="image.png" />

**Comment by sarahlazarich** [comment]
i believe this was pulled in
