### ISSUE TITLE
Surface URL in preferences on application

### ISSUE THREAD

**Issue by sarahlazarich** [bloom-housing/bloom#3799]
We want to surface the url that an admin is able to add when making a preference on the actual application, as well as on the listing detail page. Currently, the url is only surfaced on the detail page of the listing, but not presented to a housing seeker when they’re given the option to claim that preference. We would like it to be be visible on that screen as well. 

[Notion Ticket](https://www.notion.so/exygy/Surface-URL-in-application-0a5133111118421e8661ed83175e8a12?d=773553ca16654700a026bea311226d5d#f9e49b312b0f4bc4b3a01c31ed002269)
[Designs](https://www.figma.com/file/Ne8jOyPpCBvlAhyaRlXgTq/Geocoding?type=design&node-id=1143-3892&mode=design&t=InUrNy7sG9bQb0hF-0)

**Comment by sarahlazarich** [comment]
I see the links! My question though is about the formatting -- are we expecting those grey lines between the preferences @KrissDrawing ? 
<img width="404" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1hkQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--40a05df160cdd121d86a0e6c54e86fc0671fb62b/Screenshot%202024-01-18%20at%203.58.42%E2%80%AFPM.png" alt="Screenshot 2024-01-18 at 3.58.42 PM.png" />

**Comment by KrissDrawing** [comment]
The lines are there since 2022, so i guess it's design decision if we want to remove them. 
But here is an issue with padding, that for some reason is not applying (even though i can see tailwind class on that element, and locally it looks good)

**Comment by kathyccheng** [comment]
Okay let's close!
