### ISSUE TITLE
SJ/SMC: AMI Levels not Appearing when Adding Units

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#3804]
I have now received two reports from property managers, one in SMC and one in SJ, that say they can't select an AMI level for their units. They select an AMI chart, but then the level drop-down does not populate. This happened for 888 San Mateo and Buena Vista Midtown. I could not replicate this issue, so I just went in and helped set up the units. However, since this has now been reported twice, I'd like to make sure there isn't a bigger issue cropping up. This is a medium priority item :large_yellow_circle:. 
<img width="565" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2EwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--00ac90930ab5773003fb458fa2942aa00a7fbfd4/image.png" alt="image.png" />

**Comment by sarahlazarich** [comment]
log in issue per https://exygy.slack.com/archives/C02G1S19QA2/p1704895852273609
