### ISSUE TITLE
Bug - Paper Application not saving lat long 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#3810]
When I enter in an address for a geocoding preference in a paper application, 
The CSV output will just show Needs Manual Verification 
It looks like when run from the paper application, the address isn't generating a lat/long for the within radius query 

Notes
* Similar logic as the partner edit listing page should be used (BuildingDetails.tsx) to get the lat long of the address
* When an address is entered a lat long should be calculated and sent as part of the address on the submission
* Decided in grooming to go with Map UI option, Morgan to look in to cost 

Questions:
* Do we need to show something on the UI to signify if the address was recognized? Does it have to be a map?

**Comment by sarahlazarich** [comment]
Questions: 
- will adding the map have an additional cost? ML to look into it

**Comment by ludtkemorgan** [comment]
We are only currently using a fifth of our mapbox limit on the free tier so it should not be an issue to add this additional functionality

**Comment by ludtkemorgan** [comment]
@kathyccheng this is now testable in the the bloom core environment https://partners.bloom.exygy.dev/

**Comment by kathyccheng** [comment]
@ludtkemorgan when I tried it on an existing listing, it didn't seem to work, but when I created a new listing it seemed to work. Is there anything going on there?

**Comment by kathyccheng** [comment]
LGTM
