### ISSUE TITLE
AC: Household Size Error Message Appearing on Application

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#3815]
An applicant reported this error message for Jordan Court in AC. This is for a studio, which has a max of 2 people, and the applicant said they were a single-person household, so this message is not only wrong but also shouldn't be there in the first place. This is a high priority issue.

<img width="500" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnZQQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f42fe84d21bb81a2f82f899c886bde5b5b6c79b3/image.png" alt="image.png" />

**Comment by YazeedLoonat** [comment]
```sql
UPDATE listings
SET household_size_min = 0, household_size_max = 0
WHERE name = 'Jordan Court';
```
