### ISSUE TITLE
Accounts - Passwordless log-in

### ISSUE THREAD

**Issue by sarahlazarich** [bloom-housing/bloom#3818]
User Stories: 
As an applicant logging back into to my account on Public Portal,
I want to be presented with an option to log in with a code sent to my email 
So that I can access my account without my password if I need to. 

AC: 
- Build the ability for public account users to log-in using a code sent to their email if they do not want to 
 
Notes:
- This should be both Core and Doorway, toggled off in Core 
- This should only be implemented on sign-in flow, the sign-up (first time a user creates an account) flow will still require user to set a password 
- We are NOT offering SMS as a part of this features MVP 
  
Prototype (Both Core & Doorway): https://www.figma.com/proto/2LSD4B4yBIxAUGbZQCVOCv/Passwordless?page-id=2806%3A6753&type=design&node-id=2806-6755&viewport=277%2C566%2C0.02&t=MyLeNDQeNULtGjan-1&scaling=min-zoom&starting-point-node-id=2806%3A6755&show-proto-sidebar=1

New copy (pending final designs): 
- Enter your email and we'll send you a code to log in 
- Get code to sign in 
- Use your password instead 
- Get a code instead 
- We sent your code to your email to finish signing in. Be aware, the code will expire in 1 hour. 
- Your code 
- Didn't receive your code? 
- Use a code to sign in for added security

**Comment by sarahlazarich** [comment]
Only pertains to user accounts on the public side 
Start in Doorway - Might require extra design work to make it toggleable 
- Pull the Core flow right in in early April after 
- Going to be blocked on Prisma BE - start FE work in the meantime, but just a callout
- when we pick this up and break down the tasks, if there's not a ton of FE work, maybe go the path of doing it in Core and making it toggleable (will add additional time) 
- Can we do the FE and mock the API calls? For speed, and also considerations around how we log users in (currently have 2 ways to log in, and we're adding a third) 
- Might need a design doc here

**Comment by emilyjablonski** [comment]
QA Notes

We can't QA this in dev because we don't have the passwordless flags on, but I can demo this locally or QA once we're in Doorway.
