### ISSUE TITLE
Google dropping support for 3rd party cookies

### ISSUE THREAD

**Issue by YazeedLoonat** [bloom-housing/bloom#3821]
Google is moving towards removing 3rd party cookies:
https://developers.google.com/privacy-sandbox/3pcd
https://blog.google/products/chrome/privacy-sandbox-tracking-protection/

We need to verify that if 3rd party cookies are turned off, a public site user and a partner site user can both go through their regular flow (log in, log out, perform actions). 
- If, after doing this testing, those flows still work, we won't need to make  any changes and we're good to go. 
- If we discover that those flows don't work with third party cookies removed, we'll need to come together and figure out a path forward.

**Google has already turned it off for 1% of users so we should probably get moving on this sooner rather than later as they continue to turn it off for users**

**Comment by mcgarrye** [comment]
We do not need to make changes to core/hba

**Comment by mcgarrye** [comment]
Doorway does not need any changes
