### ISSUE TITLE
Bug - Exclusive Preference Option should allow for additional information 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#3830]
When I set up a preference that uses the exclusive option vs the multiselect option (the preference page in the applications renders radio buttons instead of check boxes), 
And I add additional information to be collected (like address or geocoding checks), 
Then right now those questions won't show up when I get to the preference page in the application flow 
It should show up under the radio option the same way it would in the multi select 

<img width="716" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTc5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d72a8d78d0c01aea779fc886f082842484ebc777/Screenshot%202024-01-25%20at%2011.46.50%E2%80%AFAM.png" alt="Screenshot 2024-01-25 at 11.46.50 AM.png" />

**Comment by KrissDrawing** [comment]
QA Notes:
For it to be visible we need preference with all options selected to `exclusive`, and some / all of it having `Do you want to collect address information?` set to `yes`.
Then on application process it will show address fields when radio option selected.

**Comment by sarahlazarich** [comment]
this looks good to me - @kathyccheng you might have more context here tho
