### ISSUE TITLE
Fix placement of URL link 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#3834]
The URL link should be placed under the preference description, not in the top section. See "Maps" link in image below, that should go under where it says "Lives/Works in Berkeley" descriptor text

<img width="628" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWYvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d8ce7ee4a4256f9d45de5f7857919a0cd2532ab5/image.png" alt="image.png" />

See updated design asset here: https://www.figma.com/file/Ne8jOyPpCBvlAhyaRlXgTq/Geocoding?type=design&node-id=1703-451&mode=design&t=UVqyCbKXXyqdbyE1-0

**Comment by kathyccheng** [comment]
@KrissDrawing sorry I didn't catch this earlier!

**Comment by KrissDrawing** [comment]
QA Notes: On www.bloom.exygy.dev fill application (for example: `Test: Default, Two Preferences`) on preference step url will be in correct position

**Comment by sarahlazarich** [comment]
The link is now in the preference description - so I think this lgtm, closing 
<img width="567" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVZXQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5a33307f23eea79bc6acc8154b61844a26da0419/image.png" alt="image.png" />
