### ISSUE TITLE
Bug - commas in preference sub option description leading to additional fields not showing up 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#3836]
When I set up a preference and it has multi-select options (checkboxes vs radios)
If I have commas in the description text for the preference sub option, 
Then the additional fields requested (like address or name) don't show up on the preference page in the application flow

**Comment by sarahlazarich** [comment]
@ludtkemorgan @emilyjablonski can we add QA notes here?

**Comment by sarahlazarich** [comment]
@emilyjablonski please add QA notes
