### ISSUE TITLE
Create Account Confirmation Timeout Modal does not work

### ISSUE THREAD

**Issue by cade-exygy** [bloom-housing/bloom#3846]
If create an account, hit resend confirmation, and then click on the FIRST email, you should see a timeout modal, which is currently not working on full. 

<img width="1123" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFVUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6e3e35499e248b12d15271476d88971d9e682d92/Screenshot%202024-01-30%20at%205.46.43%E2%80%AFPM.png" alt="Screenshot 2024-01-30 at 5.46.43 PM.png" />
<img width="1541" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFlUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--af6a9e1c5418e9efa6c9b0a309e28b8d1d64bad2/Screenshot%202024-01-30%20at%205.47.01%E2%80%AFPM.png" alt="Screenshot 2024-01-30 at 5.47.01 PM.png" />

@sarahlazarich This bug is existing in main currently, but it does potentially block one MA flow from redirecting properly. This flow is an edge case.

**Comment by emilyjablonski** [comment]
This is a duplicate: https://github.com/bloom-housing/bloom/issues/3663

**Comment by sarahlazarich** [comment]
Open question for design
- toast behavior, can reuse from other flows 

Pick up as a part of the passwordless epic 
@sarahlazarich to Link to passwordless notion for @eajensenwa

**Comment by sarahlazarich** [comment]
Probably won't be fixed with prisma, it's making the wrong kind of request 
Whoever picks this us will need to test it on prisma 
Should be hitting resend email, not the confirm endpoint
