### ISSUE TITLE
AC: Applicants Receiving 2 Confirmation Emails for 1 Application

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#3849]
Got an interesting report from applicants in AC from our Maudelle Miller property/geocoding pilot. These two applicants both reporting receiving two confirmation emails back-to-back, resulting in their applications being flagged as duplicates. In the system, it looks like one of them does have two applications submitted within one minute, but the other (Mia Stewart) only has one application that I can see. Can we check to see if the system is inadvertently generating duplicate applications? This is a medium priority issue :large_yellow_circle:. 

Mia.Stewart19@gmail.com
amayoral986gmail.com

**Comment by sarahlazarich** [comment]
Closing - seems like user error per https://exygy.slack.com/archives/C02G1S19QA2/p1706732136367479
