### ISSUE TITLE
Upgrade to react-hook-form v6

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#385]
See https://github.com/react-hook-form/react-hook-form/releases, and note than many of the changes are listed in the RCs.

I don’t think there’s any specific hurry to upgrade, but if nowish is a convenient time to do it before we make more migration work for ourselves, I’m open to moving quickly more quickly than I otherwise might since we have the whole month for any small issues upstream to settle down. 

It looks like there are relatively few breaking changes, but do we have an opinion on how much work there would be to make sure our patterns were aligned with this latest?

**Comment by jaredcwhite** [comment]
I had to make a couple of small changes, but otherwise this appears to be a pretty seamless upgrade.
