### ISSUE TITLE
AC: Geocoded Preference Responses not Translating Back to English

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#3856]
Flagging some issues with the application for Maudelle Miller Shirek, our geocoding pilot in AC (relatively minor but flagging as high priority :red_circle: due to the importance of this pilot).

Some preference question response are appearing in the export not in English. This is happening for most of the preference questions, where some responses persist in Spanish, Filipino, etc. It looks like this is only happening for the preferences, the other responses from those applicants are in English.

**Comment by sarahlazarich** [comment]
closing based on https://exygy.slack.com/archives/C02G1S19QA2/p1707140129651329
