### ISSUE TITLE
AC: Geocoding Responses with Inconsistent Punctuation

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#3857]
Flagging some issues with the application for Maudelle Miller Shirek, our geocoding pilot in AC (relatively minor but flagging as high priority :red_circle: due to the importance of this pilot).

Some preference responses end with periods and some do not, meaning it's difficult to sort the excel spreadsheet because they register as two different response (i.e. "Yes I am qualified" vs "Yes I am qualified."). I'm happy to help with manually cleaning the export, but I want to see why this might be occurring.

**Comment by sarahlazarich** [comment]
Per https://exygy.slack.com/archives/C02G1S19QA2/p1707140129651329, I think this is closed.
