### ISSUE TITLE
Factor allApplicationClosed logic out of Hero component?

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#386]
We could also solve this by having another component with different logic instead, but when I went to use the Hero ui component for my fake Partners home page, I was surprised to fund the no listings logic baked into the component itself.

I think we might be better served by having the component take a more purpose-neutral (optional) property like `subtitle` or something similar sounding, and then move the conditional based on listings up to the parent page/component.

Definitely not urgent, but does this kind of separation between UI and logic make sense in terms of direction?

**Comment by jaredcwhite** [comment]
It looks like the `listings` prop is optional and you can just pass a child element into Hero for a subtitle. I do agree though in the long run the listings-specific code should probably be in a separate component.

**Comment by ludtkemorgan** [comment]
@emilyjablonski This seems to be kind of documented in the [ui-c audit](https://www.notion.so/exygy/2c7d19ed7deb46f98a31e785d6ddce06?v=45e8cda4be254973b596e302d276122c&p=d41c66ac30864f59bead958dd1fd6b2d&pm=s). Are you ok if I close this issue and we will come up with the best long term solution for this in the ui-seeds?
