### ISSUE TITLE
SMC: Update URL for Haven Connect Resource Card

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#3864]
We have a content change request for the SMC resource page. We need to update the URL for the Haven Connect Resource card. See request from Haven Connect staff below. This is a low priority issue :large_green_circle:. 

"You currently have a link to our old properties page here: 
https://smc.housingbayarea.org/additional-resources

This goes to a URL that will be sunset on 2/16/24. The old subdomain was apply.havenconnect.com but that URL is already being redirected to our new properties page. 

If you can update the URL to 
https://app.havenconnect.com/properties that would be much appreciated!"

**Comment by emilyjablonski** [comment]
QA Notes:
You can test this fix on SMC staging: https://smc.bloom.exygy.dev/
