### ISSUE TITLE
[Partners] Catch unauthenticated users and redirect to login page

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#387]
There's currently a login page for partners, but the routing logic doesn't enforce that you have to go there if you're not logged in. Other than the Privacy Policy and maybe some other tangential pages, everything should require the user to be authenticated before they see anything, and get redirected otherwise.

If it's more expedient to redirect literally 100% of pages to the login screen rather than make any exceptions, that's probably fine for the short-medium term.

**Comment by bencpeters** [comment]
That sounds good. We can enforce that at the top level, since the `UserProvider` is at the root of the tree and initializes log-in status on initial load. Maybe I'll add a whitelist of paths to skip checks for too...
