### ISSUE TITLE
Update handling of environment variables based on Next.js 9.4

### ISSUE THREAD

**Issue by jaredcwhite** [bloom-housing/bloom#388]
Somehow I didn't notice this before — Next.js 9.4 improved the way it handles environment variables and also determining which ones remain server/build-time only and which ones get promoted to the client-side. https://nextjs.org/docs/basic-features/environment-variables

We could adopt this new convention which would significantly simplify our config file.

**Comment by bk3c** [comment]
Yeah, I have a local version that takes out all the .env xargs stuff since that wasn't happy when I was reviewing #358 yesterday. I can put it up in a PR as soon as I get the documentation modified. @jaredcwhite if you want to take on the next.config.js etc parts, feel free at your convenience.
