### ISSUE TITLE
AC: Add 15% AMI to Oakland

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#3888]
AC has requested the addition of a 15% AMI level to the most recent Oakland AMI Chart. I have added this to the 'Oakland' tab of the income limits sheet: https://docs.google.com/spreadsheets/d/19xat2CAHME04XwQ8PCbVIPr2LIV8ltGAKLCK_JF-nGM/edit?usp=sharing. This is a low-priority issue, pending any timing updates from the client.

**Comment by ludtkemorgan** [comment]
This has been updated to have the values listed in the spreadsheet for 1 through 3 and then $19,980 for the remaining values. It can be tested in [prod](https://partners.housingbayarea.org/) by adding a unit with ami chart "Oakland 2023" and % of 15.
