### ISSUE TITLE
requestedChangesUser shouldn't be returning a full user

### ISSUE THREAD

**Issue by YazeedLoonat** [bloom-housing/bloom#3889]
We should change the Backend field of `requestedChangesUser` on the listing object to just be the `first name` + `last name` of the user. Currently we are returning a LOT of data that doesn't need to be sent to the front end for that string concatenation

We'll also need to update usage of `requestedChangesUser` on the partner and public sites so they just use that changed field

**Comment by sarahlazarich** [comment]
@mcgarrye is there product QA required here?

**Comment by mcgarrye** [comment]
> @mcgarrye is there product QA required here?

Nope!
