### ISSUE TITLE
Passwordless - FE

### ISSUE THREAD

**Issue by sarahlazarich** [bloom-housing/bloom#3892]
[Designs](https://www.figma.com/file/2LSD4B4yBIxAUGbZQCVOCv/Passwordless?type=design&node-id=2900-22910&mode=design)
[Notion](https://www.notion.so/exygy/Designs-Passwordless-Log-in-0272e3223a7341fa9de3310b5463ab23)

User Stories: 

As an applicant logging in to my account on Public Portal,
I want to be presented with an option to do a passwordless log-in, 
So that I can access my account without my password if I need to. 

AC: Build out FE screens for allowing 
- Allow users to sign up and in without needing to create a password
- Provide options to do so with phone or email
- Allow users to setup a password as a backup

Note: We only have DW designs, but differences between Core + DW are notated in the design.

**Comment by emilyjablonski** [comment]
QA Notes:

This went into core but because it is using an environment variable it cannot be QAd on dev. Happy to demo locally if needed.
