### ISSUE TITLE
User attempting to login with unconfirmed account gets generic error

### ISSUE THREAD

**Issue by YazeedLoonat** [bloom-housing/bloom#3912]
**What is this feature or what feature is this part of?**
Currently when a public user attempts to login but their account is unconfirmed they get a very generic error. its not clear to them whether they input their info wrong, or if there was something else wrong.

We should change that to make it more clear what steps they can take

**Describe the solution you'd like**
We probably want to point them to look for the email, or give them a way to re-request a confirmation email

**Additional context**

**What is the acceptance criteria/definition of done?**
For eng: `catchNetworkError.ts` in `shared-helpers` is where this occurs. 
For PM/Design: We probably want the wording on what to display and also translations for the various languages we support

**Comment by YazeedLoonat** [comment]
current flow:
1. No user
2. User is locked already
3. Account is unconfirmed
4. Password is outdated
5. Password is valid

target flow:
1. No user
2. User is locked already
3. Password is valid
4. Account is unconfirmed
5. Password is outdated

**Comment by sarahlazarich** [comment]
Longer term - can we get design/research eyes on this?
