### ISSUE TITLE
AC: Application Export not Working

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#3935]
Our partners in AC reported that they are unable to export applications data for Ancora Place, it has consistently thrown up an error. I was able to replicate this issue. Potentially related, other listings' data is exporting via a download in browser, rather than sending via email. This is a high priority issue.
<img width="1684" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHJOQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--96e70c774538b4b63bc0b9b8a8b651081b716c94/image.png" alt="image.png" />

**Comment by sarahlazarich** [comment]
2 issues: 
- shouldn't export until preference issue is fixed, need to check on geocoding behavior.
- Memory issue 
- 10 second timeout happened here, not the memory call. Browser has a timeout, need to check on that

**Comment by sarahlazarich** [comment]
test to see how long the call is locally - if it's a 10sec timeout and this is taking 12 could be an easy fix
