### ISSUE TITLE
AC: HACA Banner on Homepage

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#3958]
AC has requested a banner on their homepage advertising the County's open application window for Section 8 vouchers. They want the banner only live from April 2nd through 11pm PST April 5th. It should say: "The Alameda County Housing Authority (HACA) will be opening its waitlist April 2 through April 5. Find out more at www.haca.net." They would like "County" underlined if possible. This is a low priority request. 

es: La Autoridad de Vivienda del Condado de Alameda (HACA) abrirá su lista de espera del 2 al 5 de abril. Obtenga más información en www.haca.net.

zh: 阿拉米達縣住房管理局 (HACA) 將於 4 月 2 日至 5 日開放候補名單。了解更多信息，請訪問 www.haca.net。

vi: Cơ quan Quản lý Nhà ở Quận Alameda (HACA) sẽ mở danh sách chờ từ ngày 2 tháng 4 đến ngày 5 tháng 4. Tìm hiểu thêm tại www.haca.net.

tl: Ang Alameda County Housing Authority (HACA) ay magbubukas ng waitlist nito Abril 2 hanggang Abril 5. Alamin ang higit pa sa www.haca.net.

QA: https://ala.bloom.exygy.dev/
Ensure the banner is showing appropriately with the content outlined above.

**Comment by sarahlazarich** [comment]
lgtm @ColinBuyck
