### ISSUE TITLE
Investigate use of React Query or SWR to manage server data

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#396]
Not sure if our use cases are yet complicated enough to use either of these, but both look promising:

- https://github.com/tannerlinsley/react-query
- https://github.com/vercel/swr

**Comment by jaredcwhite** [comment]
I did some research on both libraries, and I'm still a little fuzzy on what the full scope of benefits are, but my impression is that they become useful when lots of different bits of data are coming in from various sources and you sort of need a way to coordinate them and cache them across components on a page and subsequent renders. Given what we're doing with static generation along with a pretty simple API as a single source of truth, they're probably overkill—at least at this juncture.

**Comment by jaredcwhite** [comment]
I'm realizing now I'm thinking solely in terms of the public site & Next.js—perhaps the partners portal will have a different set of requirements where this becomes more relevant.

**Comment by bk3c** [comment]
Note that SWR now seems to be [the "official" way to do client side data fetch for NextJS](https://nextjs.org/docs/basic-features/data-fetching#fetching-data-on-the-client-side). I tried it out in #500, and it actually seems pretty straight forward to use, including wrapping axios if we want.
