### ISSUE TITLE
Custom Online Application URL Missing Validation

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#3972]

**Comment by sarahlazarich** [comment]
If you select a custom url for an app, the field will take any string but you'll get a page not found if you enter anything that isn't https or http, we did some work on this (Link Kris' PR), but it wasn't carried over in Prisma. 
- Can also we open this up to other urls on Doorway?

**Comment by KrissDrawing** [comment]
QA Notes: on partners https://partners.bloom.exygy.dev/ when creating / editing listing with incorrect url for digital application (no protocol / invalid url) it should throw errors.
Also it should work as before for other url fields as they are validated on frontend (listing open house / listing Building Criteria Selection / preferences - options)

**Comment by sarahlazarich** [comment]
lgtm
