### ISSUE TITLE
SMC: Listing Approval Error for J-Admins

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#3996]
Our partners in SMC were trying to approve the Azara listing this am but came across an error message when they clicked 'approve and publish.' They were unable to publish the listing. I logged in and tried to publish the listing, and found that when I clicked the button nothing happened. But when I entered the edit view, then clicked the button, the listing was published but the error was still raised. This is a medium priority issue :large_yellow_circle:. 
<img width="1536" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2d3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3220d264c6346a25622cc0216ce0725ee659edb3/image.png" alt="image.png" />

Technical Summary:
1. Format multiselect data correctly from frontend to avoid null error
2. Investigate why null error doesn’t block submission from edit flow but does through approve and publish flow. This is the data directly from the backend?!
3. Why does backend accept that anyway? If error is coming from code from service file, then the backend isn’t properly validating (maybe default-validation-pip-options.ts)
4. Frontend should always indicate to user if there are field errors when they click approve and publish
5. Check with Product about the field validation between draft -> pending review versus pendingReview -> open. Should it be the same standard or are there cases when users would want feedback on a a partial listing

I think number one is the direct fix to this support issue and I’d estimate it at a 2. Think I could have a fix out today! The secondary issue of not seeing anything that Izzie mentioned is captured in point 4 and I think should be its own ticket (I estimate this to be a 2 as well). Finally, points 2,3, and 5 could be their own ticket or split up, would want feedback from the team there. They would be an investigation to align the various listing actions we now support to be more consistently validated on the frontend and backend. Altogether, I’d put those remaining points roughly at a 3/5 estimate.

**Comment by ColinBuyck** [comment]
QA Notes to Address the First Point: https://partners.housingbayarea.bloom.exygy.dev/sign-in
Opening a partners user window and a separate admin user window. Find a listing that has all its required fields filled out correctly and submit it for review by the partners user. Then on the admin session, click "Approve and Publish" and the listing should successfully publish.

**Comment by ColinBuyck** [comment]
Issue partially completed and other issues made for the results of the investigation
