### ISSUE TITLE
SJ: Update Resource Card Link

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#4000]
San Jose has noticed a broken link on their How it Works page. Under section 2, "Find your Eligibility", the link for "Tables for San Jose" directs to an empty page on the city website. It should be replaced with: https://www.sanjoseca.gov/your-government/departments-offices/housing/data/income-and-rent-limits/affordable-rental-housing

This is a low priority request.

 <img width="1398" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDFBQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5a50108067edcc4bd5dfb98ea0001cd9d456161f/Screenshot%202024-04-08%20at%208.25.50%E2%80%AFAM.png" alt="Screenshot 2024-04-08 at 8.25.50 AM.png" />

QA: https://sj.bloom.exygy.dev/how-it-works
Go to the link above, expand the eligibility section, and click "Tables for San José are provided here."

**Comment by sarahlazarich** [comment]
lgtm
