### ISSUE TITLE
Script to Send All Failed Emails Once Sendgrid Issues Resolve

### ISSUE THREAD

**Issue by ColinBuyck** [bloom-housing/bloom#4001]
As part of remediation for sendgrid locking, we should send critical emails that failed to send during this period. This will be a node script that is run locally to Doorway, HBA, and Detroit (may need slight alterations. Cases that should be covered include:

- user created on the public site confirmation emails
- users invited on the partner site invitation emails
- public site application creation confirmation emails resent 

Technical notes:
Resource on connecting to heroku postgres: https://devcenter.heroku.com/articles/connecting-heroku-postgres#connecting-in-node-js

**Comment by sarahlazarich** [comment]
lgtm

**Comment by sarahlazarich** [comment]
closing out
