### ISSUE TITLE
AC: Edit Common App Income Question

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#4020]
Our partners in AC have requested a minor content change to the income question on the common app in the hopes it will encourage more accurate responses. This is a low priority request. 

Update: Add up your total gross household income before taxes and deductions from wages, benefits and other sources from all household members.

Original: Add up your total gross (pre-tax) household income from wages, benefits and other sources from all household members.

**Comment by sarahlazarich** [comment]
@sarahlazarich to add translations

**Comment by sarahlazarich** [comment]
Spanish: Sume el ingreso bruto total de su hogar antes de impuestos y deducciones de salarios, beneficios y otras fuentes de todos los miembros del hogar.
Chinese: 將所有家庭成員的稅前家庭總收入以及工資、福利和其他來源的扣除額相加。
Filipino: Isama ang iyong kabuuang kabuuang kita ng sambahayan bago ang mga buwis at mga bawas mula sa sahod, mga benepisyo at iba pang mapagkukunan mula sa lahat ng miyembro ng sambahayan.
Vietnamese: Cộng tổng thu nhập gộp của hộ gia đình bạn trước thuế và các khoản khấu trừ từ tiền lương, phúc lợi và các nguồn khác từ tất cả các thành viên trong gia đình.

**Comment by sarahlazarich** [comment]
lgtm!
