### ISSUE TITLE
AFS data touch up

### ISSUE THREAD

**Issue by YazeedLoonat** [bloom-housing/bloom#4023]
Currently we have data in the system that needs to be touched up.

1. We need to trim applicant first name/last name, and household member first name/last name. as sometimes ` ` have been sneaking into those fields

2. We need to convert the birth day and birth month fields to be numbers, and on save

these need to be fixed during application create and update, as well as updates to existing data via a migration

**QA NOTES**
on the front end if you apply to a listing and put a name like `fname ` as the first name, `lname ` as the last name, `01` as birth month, `02` as birth day then the data should get saved in the db (and displayed on the front end) as `fname`, `lname`, `1`, `2`

**Comment by sarahlazarich** [comment]
<img width="1021" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeStKQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--233a5b382b20c800a4fd99e76a15219c88d931bf/image.png" alt="image.png" />
 I'm not sure if this is working as expected?

**Comment by sarahlazarich** [comment]
chatted w yazeed - lgtm
