### ISSUE TITLE
Jurisdictional Admin Deleting User Causes Errors

### ISSUE THREAD

**Issue by mcgarrye** [bloom-housing/bloom#4024]
For the delete function in the user service, we don't do any joins when we load the [target user](https://github.com/bloom-housing/bloom/blob/main/api/src/services/user.service.ts#L294). When a jurisdictional admin goes to delete a user in the partner portal, it runs through a check on [jurisdiction](https://github.com/bloom-housing/bloom/blob/main/api/src/services/user.service.ts#L808-L811). Instead of failing the check and throwing a forbidden error, the code breaks because jurisdictions was not loaded through joins for the target user. The authorizeAction function fails and throws an error that appears on the frontend, however it does not stop the deletion from being executed once it returns. Thus jurisdictional admins could potentially delete any user directly through the api.

**Comment by sarahlazarich** [comment]
Was able to delete a user as a jadmin at https://partners.bloom.exygy.dev/users -- If that's the right check for product, @mcgarrye , lgtm.
