### ISSUE TITLE
AC: 'Special Notes' Field Formatting Incorrectly

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#4030]
We received a report from AC that the preview on Fremont Family is formatting oddly in the 'special notes' field. Can we figure out a way to fix this? This is a medium priority request. 

<img width="1555" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3AxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a8b2d4fe448f7a8700fa2c39dd34e7bc67f69d38/Formatting%20Fremont.png" alt="Formatting Fremont.png" />

**Comment by ColinBuyck** [comment]
Resolved but flagging https://github.com/bloom-housing/bloom/issues/3788 as the underlying issue
