### ISSUE TITLE
SJ/SMC: GA Not Tracking

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#4031]
I'm pulling some GA data and saw that the page views disappear from SMC and SJ end of Jan/beginning of Feb. I'm confident we've had at least one visitor since then, so I'm not sure what happened. AC and Doorway seem unaffected, but I'm concerned we've lost some data. This is a high priority issue :red_circle:.

<img width="1282" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWg1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7c91c6a0346dcdddd5b759a9c6146a7090855091/image.png" alt="image.png" />

**Comment by sarahlazarich** [comment]
This was fixed i believe
