### ISSUE TITLE
Lotteries - Tab and empty state (FE)

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#4046]
https://www.figma.com/file/PAeCVANDmGdTz2Y53ouErM/Lotteries?type=design&node-id=3235-29419&mode=design&t=f8IRd445tNekl1aK-0

Add a tab to the partners view and mock out the empty state and the history log. We can use mock data in the history log to get the layout right. Other screens show examples of multiple entries.

Q: What does mobile look like?

**Comment by emilyjablonski** [comment]
QA Notes:

This cannot be QAd in dev because of the feature toggle. If needed we can make a new Netlify environment or demo locally.

**Comment by emilyjablonski** [comment]
@sarahlazarich Ready to QA in Doorway staging

**Comment by sarahlazarich** [comment]
@emilyjablonski one thing I'm noticing here is that the lottery "new" tag is present here but not in the designs. I think that was something we had descoped!  

<img width="1034" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0NsQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--324ba754cb81111575d188267728cb526ae14f01/image.png" alt="image.png" />

**Comment by sarahlazarich** [comment]
Also noticing that our buttons in staging are rectangles 

<img width="1256" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0dsQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7a6f3f1734db601b93b394622e7ed064eba72893/image.png" alt="image.png" />

vs ovals in the design 

<img width="522" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0tsQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--93b5495b8799129dd3b918e638d339e303c63291/image.png" alt="image.png" />

Not sure if that's an expected diff w the figma but wanted to call it out!
