### ISSUE TITLE
Lotteries - Adding application to closed & post-lottery listing warning (FE)

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#4047]
As an Admin attempting to add a new application to a closed listing before a lottery is run,  
I want be asked to confirm this action through a confirmation dialog,
So that I have a check to make sure that I am aware that I am adding apps to a closed listing. 
- https://www.figma.com/design/PAeCVANDmGdTz2Y53ouErM/Lotteries?node-id=3273-40225&t=9u8qrlOBpBfzc62a-0

As an Admin attempting to add a new application to a closed listing AFTER a lottery is run,  
I want to see a confirmation dialog reminding me that this will require me to re-run a lottery, 
So that I am aware of the implications of this action. 
- https://www.figma.com/design/PAeCVANDmGdTz2Y53ouErM/Lotteries?node-id=3235-28349&t=t8MKoEc9mZSCjfeS-0

Q: We currently have this mocked on the application list view - should it also be on the add application view?

Notes: 
- Only Admins should be able to add paper applications. 

AC: 
- As an Admin, when I add applications to any closed listing, I want to be required to confirm through a dialog. I should not be able to proceed without confirming. 
- When I attempt to add applications to a closed listing BEFORE the lottery is run, I want to be see a modal reminding me that the listing is closed. 
- When I attempt to add applications to a closed listing AFTER the lottery is run, I want to be see the modal letting me know that I will be required to re-run the lottery as a result of this action.

**Comment by sarahlazarich** [comment]
Will need to add some indication that we're post-lottery - timestamp?
Mock it out until the BE work is done

**Comment by emilyjablonski** [comment]
QA Notes
Visit an open listing and click the add application button and ensure you go straight to the application form.
Visit a closed closed and click the add application button and ensure the closed listing modal from the [design](https://www.figma.com/design/PAeCVANDmGdTz2Y53ouErM/Lotteries?node-id=3235-37543&t=BUWB2SeiXVzj60ex-0) is shown (confirmed with design this will show regardless of whether or not lotteries is on).
There is a new backend field lotteryLastRunAt that is not currently used by the backend. If that field is not null, the lottery run modal from the [design](https://www.figma.com/design/PAeCVANDmGdTz2Y53ouErM/Lotteries?node-id=3235-28349&t=P7k2YlCnvTwanwbW-0) is shown. This will not be QA-able in an environment until the backend work is complete but I can demo locally if needed.

**Comment by emilyjablonski** [comment]
@sarahlazarich The closed listing version of this is now QA-able in Doorway staging, but we don't yet have a way to get the post-lottery state

**Comment by sarahlazarich** [comment]
@emilyjablonski - This looks good, but I did realize that the [copy](https://docs.google.com/document/d/130OuxoQnKnukoVr_SPQq57A0JZ4vycdcS9q0EX2Gkso/edit) wasn't linked at this point, that's my bad. 

Can we update the modal to say "This listing has closed. Are you sure you want to add a paper application?" per the copy?

**Comment by emilyjablonski** [comment]
<img width="490" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1NxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c718bf0c72183b9d41733088dd2a43ebdf930c25/Screenshot%202024-07-02%20at%2012.18.57%E2%80%AFPM.png" alt="Screenshot 2024-07-02 at 12.18.57 PM.png" />
Could be missing something but that looks like the existing copy? @sarahlazarich

**Comment by sarahlazarich** [comment]
this lgtm!
