### ISSUE TITLE
Lotteries - Run and Export FE

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#4048]
As an Admin user running a lottery, I want to be prompted to confirm the action before I do so.  
- If there are no unresolved duplicates, I want to be shown the [generic confirmation modal](https://www.figma.com/file/PAeCVANDmGdTz2Y53ouErM/Lotteries?type=design&node-id=3235-29730&mode=design&t=f8IRd445tNekl1aK-0)
- If there are unresolved duplicates, I want to be confronted with the [unresolved duplicates modal](https://www.figma.com/file/PAeCVANDmGdTz2Y53ouErM/Lotteries?type=design&node-id=3246-37626&mode=design&t=f8IRd445tNekl1aK-0)

As an Admin who has run the lottery, I want to see the data I need to export in my lottery tab
- The state of the page should update to show the Export button and release & retract buttons ([design](https://www.figma.com/design/PAeCVANDmGdTz2Y53ouErM/Lotteries?node-id=3235-29507&m=dev))
- If I press export, I want to see the [export modal](https://www.figma.com/file/PAeCVANDmGdTz2Y53ouErM/Lotteries?type=design&node-id=3235-29604&mode=design&t=f8IRd445tNekl1aK-0). A record of my export should be saved. 

As an Admin that is re-running the lottery, I want to be prompted to confirm the action with the [re-run lottery modal](https://www.figma.com/file/PAeCVANDmGdTz2Y53ouErM/Lotteries?type=design&node-id=3235-29267&mode=design&t=f8IRd445tNekl1aK-0) before I do so.

Note: 
- A record of the running and re-running of the lottery will need to be surfaced in the history log. 
- Eventually this will be restricted to just Admin users

AC: 
- Only Admin users should have the ability to run a lottery or export results before they're released.
- When an Admin clicks on run lottery, and there are no unresolved duplicates, they will need to confirm that they have already added applications. 
- When an Admin clicks on run lottery, and there are unresolved duplicates, the system will surface that there are unresolved duplicates and how many there are in the modal.  They will need to confirm that they want to continue without resolving. 
- When an Admin runs a lottery, a card with “export” action should replace the run lottery functionality with the appropriate copy.

**Comment by sarahlazarich** [comment]
Hi - copy for these is linked [here](https://docs.google.com/document/d/130OuxoQnKnukoVr_SPQq57A0JZ4vycdcS9q0EX2Gkso/edit#heading=h.z2we68wtdnff)

**Comment by emilyjablonski** [comment]
QA Notes

For an admin on a closed listing with a lottery, clicking run lottery for the first time:

If there are no unresolved duplicate sets, show the regular confirm modal ([Figma](https://www.figma.com/design/PAeCVANDmGdTz2Y53ouErM/Lotteries?node-id=3345-8581&t=YJpMBWGEZbaauHjn-0))

If there are unresolved duplicate sets, show the duplicate version of the confirm modal ([Figma](https://www.figma.com/design/PAeCVANDmGdTz2Y53ouErM/Lotteries?node-id=3345-8637&t=YJpMBWGEZbaauHjn-0))

Confirmed that we should change duplicate --> duplicate sets

**Comment by emilyjablonski** [comment]
QA Notes (Export PR)
With the toggle on on a closed listing with a lottery, after clicking through the run lottery button and modal, clicking on export should open the export modal.

This is from the Figma, but the copy should remove the preference wording if the listing has no preferences.

**Comment by sarahlazarich** [comment]
this lgtm!
