### ISSUE TITLE
Lotteries - Temporary tag on tabs (FE + BE)

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#4050]
https://www.figma.com/file/PAeCVANDmGdTz2Y53ouErM/Lotteries?type=design&node-id=3235-28401&mode=design&t=f8IRd445tNekl1aK-0

Add a temporary "new" tag on the lotteries tab. It should disappear after having been opened the first time. We have a similar functionality on an alert on the duplicates page. May require a seeds change.

**Comment by sarahlazarich** [comment]
closing - this has been deprioritized
