### ISSUE TITLE
Lotteries - History log (FE + BE)

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#4052]
https://www.figma.com/file/PAeCVANDmGdTz2Y53ouErM/Lotteries?type=design&node-id=3235-29164&mode=design&t=srolHIDM18Eg99fe-0

We may need to add more entries in our activity log around changing listing statuses and lottery actions so that we can show all of the actions in the designs in the history panel.

We will need to fetch the events we need and show them in the right panel.

**Comment by sarahlazarich** [comment]
Easiest to do this later

**Comment by emilyjablonski** [comment]
A partner user will not see running / re-running, they will only see closed --> released

**Comment by emilyjablonski** [comment]
QA Notes
You can test this on the frontend with an admin user and perform all the actions, and then log-in as a partner user once the lottery is released and ensure you can only see the events you are supposed to see.

The re-run button is not currently hooked up, so I was unable to test that flow through the UI but it is covered in tests.

**Comment by emilyjablonski** [comment]
^ @sarahlazarich I would consider this separate from the history log, could we do this as part of the copy pass?

**Comment by sarahlazarich** [comment]
@emilyjablonski yeah that works for me !
