### ISSUE TITLE
Lotteries - Export with stored general rank ordinal (BE)

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#4055]
As a user running the lottery on Doorway, 
I want to be able to generate a randomized rank for each valid application, and export into a csv
So that I can use this spreadsheet to review lottery results. 

Notes: 
- This should follow the format of the ["General Rank" tab](https://docs.google.com/spreadsheets/d/1dX9ehAq3pdMpmhNq1arWV2bwjHBFMy6xAbcPGhLVHOY/edit#gid=520192447)
- Final form of this export will be a spreadsheet, but we will address that in a later ticket 
- This is just for the raw rank generation + tab in the export. The preference filtering will happen in a [later ticket. ](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/bloom-housing/bloom/4056)
- As a part of this ticket, we should store the lottery run timestamp for areas where we need to store an indication of where the lottery was run [like this one](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/bloom-housing/bloom/4047)
- The file generation tickets should also include the connection to the front end, 

AC: 
- When I generate a lottery, I want each applicant to be assigned a random "raw rank"
- I want applications marked as duplicated to be excluded from the ranking / lottery results
- I want the results of the randomization to be stored (so that they can be surfaced in the applicant account eventually)
- I want to be able to export my results into a spreadsheet (csv for now) by clicking the "export" button from the lottery tab. 
- I want the timestamp of the lottery run to be stored as well 

**QA NOTES**
- create applications on a listing (or use a listing with existing applications)
- navigate to the listings' lottery tab
- you should be able to click the run lottery button and lottery results should get generated
- you should be able to click the export results button and get a csv spreadsheet with the lottery results

**Comment by sarahlazarich** [comment]
Questions: 
https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/bloom-housing/bloom/3728
https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/metrotranscom/doorway/449

Can we consolidate and close these?

**Comment by sarahlazarich** [comment]
For this ticket, just do a CSV - Emily has spreadsheet stuff into a separate ticket

**Comment by sarahlazarich** [comment]
Duplicates shouldn't be assigned ordinals 

For design: 
- for duplicates, what would an applicant see in their account?

**Comment by sarahlazarich** [comment]
New endpoint that's going to run the lottery (in general) 
For all apps to a listing with duplicates filtered out, give them a raw rank that we store 
CSV download should look like "General Rank" tab 

Randomization itself? What's the best way to handle?
- Are built in functions enough?
- Yes!

**Comment by sarahlazarich** [comment]
Few things I noticed in QA: 
- The column order doesn't match the sample export here. Can we update that so it does?
- Is looks to me like we're missing the Ethnicity column, as well as the "Alternate Contact Middle Name" from the application export as compared to the sample 

The diffs are outlined in the QA 7/25 and 7/25 order tabs [here](https://docs.google.com/spreadsheets/d/1iDQn7fOwQGGb1py8QfSSxosWx1Y62bdEd_9sVJhhnrc/edit?gid=1562888856#gid=1562888856 )

**Comment by sarahlazarich** [comment]
cc @YazeedLoonat @ludtkemorgan

**Comment by sarahlazarich** [comment]
I'm also not seeing this hooked up on the Partner side. When I hit export in Partners, nothing downloads.

**Comment by sarahlazarich** [comment]
Only note here - I tested as a Partner in Core and didn't get any demograohic information, which is expected, but heads up that Partners do receive demographic data in Doorway!
