### ISSUE TITLE
Lotteries - Export with filtered preference sheets (BE)

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#4056]
Blocked by: https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/bloom-housing/bloom/4055

As a user running the lottery on Doorway on a listing with prefrences,
I want to generate a randomized AND preference rank for each valid application, and export it into a spreadsheet
So that I can use this spreadsheet to review lottery results

Notes:
- The additional preference bucket should follow the format of the preference bucket tabs [here](https://docs.google.com/spreadsheets/d/1dX9ehAq3pdMpmhNq1arWV2bwjHBFMy6xAbcPGhLVHOY/edit#gid=1191380628)
- The preference bucket tabs should just be the raw rank tab, filtered for that specific preference. We don't need to do any additional randomization within these buckets. 
- The "Preference Bucket Rank" column should just be 1-the number of applicants in that column. It is just the rank of each  applicant within that preference. 
- The FE & BE should be connected as a part of this ticket

AC: 
- When I generate a lottery for a listing with a preference:
- I want to be able to export my results into a spreadsheet by clicking the "export" button from the lottery tab.
- I want to to download a spreadsheet instead of a CSV
- I want the raw rank tab to follow the AC [here](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/bloom-housing/bloom/4055)
- I want there to be a tab for each prefrence, which is the raw rank sheet filtered down to only applicants that claimed that preference
- I want there to be a new "preference rank" column, that is just the rank of the applicant within the prefrence bucket

**Comment by ludtkemorgan** [comment]
@sarahlazarich this is in Bloom core and can be tested. I created a listing with preferences and ran the lottery here https://partners.bloom.exygy.dev/listings/0967a809-6ca6-414c-87e5-87a9e4b3c612.
