### ISSUE TITLE
Lotteries - Release & retract lottery (BE)

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#4057]
As an Admin who is ready to release the lottery to Property Managers
I want to be able to release lottery results to PM accounts 
So that Property Managers could download results and begin processing lottery. 

Notes: 
- This ticket is for the BE portion of this 
- Potentially might adding a new field to the listings table 
- Need to know if the lottery was approved or not 
- When admin says it’s good to go, we need to indicate that in the DB to show on the partners side  

AC: 
- Admin can "release" the lottery, and push results to Property Managers for download
- Admin can "retract" the lottery, and pull results back from Property Managers (and later, applicants) if needed.

**Comment by sarahlazarich** [comment]
button that will toggle on & off the fields 
will need new BE fields depending on these buttons 
without the export itself this might be super small

**Comment by sarahlazarich** [comment]
Let's not release this yet, I'm seeing some stuff I want to talk through with @mcgarrye and/or @emilyjablonski

**Comment by emilyjablonski** [comment]
@sarahlazarich This was just the backend work, so I don't think there was something QA-able here

**Comment by sarahlazarich** [comment]
I'm just wondering if the modal behavior that I called out [here](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/bloom-housing/bloom/4142) was for this ticket or the other one?

**Comment by mcgarrye** [comment]
That work is not included in this commit
