### ISSUE TITLE
Lotteries - Partner export flow expiry (FE + BE)

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#4058]
https://www.figma.com/file/PAeCVANDmGdTz2Y53ouErM/Lotteries?type=design&node-id=3235-28945&mode=design&t=srolHIDM18Eg99fe-0

As a partner or jurisdictional admin on a listing where the lottery has been published, 
I want to see a banner on my portal indicating that the data will expire (45 days after listing clousure) 
So that I am aware that I need to download my data before that point. 

As a partner or jurisdictional admin on a listing where the lottery data has expired, 
I want to see an empty state with copy indicating that my data has expired, 
So that I understand what happened to the export. 

Notes: 
- We should use the data expiry work we did for the applicant table here.
- We may need designs for the empty state

AC: 
- As a partner or jurisdictional admin on a listing with published data, I want to see a banner indicating that my data will expire, and when
 - As a partner or jurisdictional admin on a listing where data has expired, I want to see an empty state explaining that my data has expired. 
 - As a partner or jurisdictional admin on a listing where data has expired, I should not be able to access the data through the UI

**Comment by sarahlazarich** [comment]
@mcgarrye copy here should read: 

(Header) No lottery data
(Body) Lottery data has expired for this listing and is no longer available for export. 

Here's a copy of the application export empty state as an example. 

<img width="1129" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXpBQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2b79374052bc8febe557a9b07d6c9aab36f28cc1/Screenshot%202024-07-08%20at%202.20.59%E2%80%AFPM.png" alt="Screenshot 2024-07-08 at 2.20.59 PM.png" />

**Comment by mcgarrye** [comment]
https://www.figma.com/design/PAeCVANDmGdTz2Y53ouErM/Lotteries?node-id=3528-20867&t=Fn6TV5lcbTvuSqrN-0
https://www.figma.com/design/Kcsf148FqeUqMNeMo54BsW/Ad-Hoc-Feature-Enhancements?node-id=2418-16131

**Comment by mcgarrye** [comment]
API access will be limited in a follow-up PR

**Comment by sarahlazarich** [comment]
@mcgarrye Scope change here - we actually want to revert to the original banner color and icon (from red --> yellow). Apologies for the change, we will try to limit this stuff in the future.

**Comment by sarahlazarich** [comment]
@mcgarrye I published lottery results on [this listing](https://partners.staging.housingbayarea.mtc.ca.gov/listings/0844528a-7f22-45d8-b0bc-881b000f0805/lottery), but I don't see a data expiry banner. <img width="1609" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFVKQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0a18651ddc70b83212fae897c1d1d1dafd54b3b4/Screenshot%202024-07-24%20at%204.02.46%E2%80%AFPM.png" alt="Screenshot 2024-07-24 at 4.02.46 PM.png" />

**Comment by sarahlazarich** [comment]
Am I looking in the wrong place?

**Comment by sarahlazarich** [comment]
<img width="1456" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeThQQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e3f13e33a382826e818e2b2f14c2defec1a53508/image.png" alt="image.png" />

Still not seeing the banner/changed state here. I am seeing that the data is expired for applications.  What am I missing?

**Comment by sarahlazarich** [comment]
was looking doorway, these changes are in core. lgtm

**Comment by sarahlazarich** [comment]
<img width="770" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0VUQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--56fdb6ee972325cf5552e44cfc16fb7363390ecf/image.png" alt="image.png" />
 I'm seeing this as an Admin when I run a lottery - that's not expected behavior for this
