### ISSUE TITLE
Application Confirmation Code Missing in Emails

### ISSUE THREAD

**Issue by ColinBuyck** [bloom-housing/bloom#4060]
When a user receives an application confirmation email, there is currently no confirmation code present. This exists in core, hba, and doorway.

**Comment by sarahlazarich** [comment]
The confirmation number is here! 

However, the listing button is coming through a little funky -- if we can't quickly fix it here, let's do it in a follow-up. 

<img width="157" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3VnQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a911798965d7e41bf774f9a145c3101af4a15ed2/image.png" alt="image.png" />
