### ISSUE TITLE
Script Runner to connect databases

### ISSUE THREAD

**Issue by sarahlazarich** [bloom-housing/bloom#4079]

**Comment by sarahlazarich** [comment]
We should have a new table to track when a script was ran 
Helper function to insert 
Helper function to see if it's been ran 
Endpoint
Controller
Service

**Comment by sarahlazarich** [comment]
be sure to document as a part of the PR - address security concerns

**Comment by sarahlazarich** [comment]
Leaving this open until @YazeedLoonat finishes documentation

**Comment by YazeedLoonat** [comment]
documentation has been created. Closing
