### ISSUE TITLE
Application Translated Text Fallback

### ISSUE THREAD

**Issue by ColinBuyck** [bloom-housing/bloom#4080]
It was discovered that when there isn't a translation for a preference option, it shows as blank rather than falling back to the english text. Preference options along with any other translated text on the application should always fallback since blank options are confusing and can block the user from progressing through the application.

Technical Notes:
- Fetch response shows untranslated text exists but text field doesn't exist

QA: See #4081

**Comment by sarahlazarich** [comment]
Qa on other one passed
