### ISSUE TITLE
AC: 2024 AMI Charts

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#4094]
AMI charts for AC are now available. You can find 3 [here](https://docs.google.com/spreadsheets/d/1WCMTRmkDU3EbNdJ1pKTGDLYnz6MmOBDzgLtF_Kh7kXY/edit#gid=0) labelled AC-HUD, AC-CA HCD, and AC-TCAC. They all should be named "Alameda County" + Source + 2024. This is a low priority request.

QA: https://partners.housingbayarea.bloom.exygy.dev/
The three new AMI Charts should be accurate in the units drawers of any Alameda listing.

**Comment by sarahlazarich** [comment]
lgtm
