### ISSUE TITLE
Add ability to search the application flagged set tables

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#4100]
QA Notes
Look at a closed listing with application flagged sets to see the new search bar which looks at first/last names on any application in the set. There are also some visual changes:

Pending Set
The information in the first column was duplicated in the next two columns. Now the duplicate information is removed and we are showing the names of all applicants in the first column since there really is no "primary applicant" in a set and it was really confusing to search for an applicant name and have a line appear that didn't show that applicant's name, but because the applicant was in the set. 
Before:
![Screenshot 2024-05-21 at 1 11 28 PM](https://github.com/bloom-housing/bloom/assets/65367387/4ca4e554-be6e-43a4-b5a8-fe367d66383b)
After:
![Screenshot 2024-05-21 at 1 11 33 PM](https://github.com/bloom-housing/bloom/assets/65367387/7406646e-e4fc-4933-b540-aedc970799eb)

Resolved Set
Similar changes, duplicate information is removed and all applicant names are being shown
Before:
![Screenshot 2024-05-21 at 1 12 00 PM](https://github.com/bloom-housing/bloom/assets/65367387/6a3a3f94-65a2-4348-ada8-89990d484d1c)
After:
![Screenshot 2024-05-21 at 1 12 14 PM](https://github.com/bloom-housing/bloom/assets/65367387/306d72e8-ff95-4572-a524-34a0e0c15dc0)

**Comment by sarahlazarich** [comment]
lgtm!
