### ISSUE TITLE
AC: PW Reset Workflow Errors

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#4101]
We received a report from an applicant in AC who tried to reset their password, but was unable to do so. They kept getting an error that their PW was too weak, but they were following the requirements. The applicant said, "I am having trouble logging into my account to see my waitlist status. I tried changing my password because I couldn't log in and each time I enter a new password of various strengths, this error message keeps popping up: "Password is too weak. Must be at least 8 characters and include at least 1 letter and at least one number." Please see screenshot attached." When I went to replicate this issue, I also ran into an error with a strong PW, but I got a generic "An error occurred." This is a high priority issue :red_circle:.<img width="814" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWNBQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0ee091755ee14a555b7be52493ed4395819bb630/Screenshot%202024-05-22%20at%208.39.34%E2%80%AFAM.png" alt="Screenshot 2024-05-22 at 8.39.34 AM.png" />

**Comment by emilyjablonski** [comment]
QA Notes
As part of this we also upped the security requirements from 8 characters / one number to 12 characters / one lowercase / one uppercase / one number / one special character. This should only apply to new passwords, which can be created on the public side by creating an account, updating your password in your account settings, or resetting your password, and on the parter side by confirming an account invitation.
* Try out passwords to see the regex is working as expected
* Try to login as seeded user `admin@example.com` and `abcdef` which should already have a currently-weak password to ensure existing users are okay
* Update a password w the four flows above and see the regex working

**Comment by sarahlazarich** [comment]
<img width="315" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDBhQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6b68af71da61ae6c0d0475931ac73f08bab153ae/image.png" alt="image.png" />
 @emilyjablonski seeing this error at https://ala.bloom.exygy.dev/create-account, which doesn't seem to match the spec. Am I looking in the right place?

**Comment by sarahlazarich** [comment]
this looks good!
