### ISSUE TITLE
AC: HCV Reserved Community Type

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#4113]
we got a request from Alameda for a new reserved community type for voucher holders. This is for a property going live in the next 2-3 weeks. They want the tag to be “HCV/Section 8 Voucher”, then the banner to say “Reserved for HCV/Section 8 Voucher Holder”. 

QA Notes: https://housing.acgov.org/ and https://partners.housingbayarea.org/
Log in to the partner site and add the new community type to a listing
Go to the public site and make sure it comes through properly (and is translated correctly)

**Comment by sarahlazarich** [comment]
Script for this in script runner - would just need to pull it out of Doorway

**Comment by sarahlazarich** [comment]
lgtm
