### ISSUE TITLE
SMC: All Preference responses say 'Claimed'

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#4123]
Noticed an issue on the application exports reported by property managers in SMC for Lume and Vasara. For all of their preferences, all of the responses appear as "Claimed", even when an applicant opted out (see here). We should fix this so other property managers don't accidentally give someone a preference they have not claimed - medium priority issue :large_yellow_circle:. But also we need to get the property managers a clean export so they can run their lottery - high priority issue :red_circle:.

**Comment by sarahlazarich** [comment]
this looks right to me https://partners.bloom.exygy.dev/listings/1bc2ff8f-36ee-4fca-a7cb-ab0a3566067a/applications? moving into "to release"
