### ISSUE TITLE
Postmark Section Not Showing

### ISSUE THREAD

**Issue by ColinBuyck** [bloom-housing/bloom#4135]
It looks like Postmark date for paper apps isn't coming through on Doorway (also reproducible in Core). See [this listing](https://staging.housingbayarea.mtc.ca.gov/listing/4916ba56-bfce-4435-803d-c00bff971ad7/test_lottery_kathy_20_lee_st_redlington_ca) as an example - "Are postmarks considered?" is marked as Yes, a paper app is attached, and we indicated a received by date & time, but that's not showing through on the public site.

With these conditions the postmark section should show on the partners side.

QA Notes https://partners.bloom.exygy.dev/ and https://partners.staging.housingbayarea.mtc.ca.gov/sign-in
Create a listing with "Are postmarks considered?" marked as Yes, a paper app attached, we indicated a received by date & time, and with both the mailing address and the drop-off address marked as same as the leasingAgentAddress... the submit application section should show on the public side with the corresponding postmark information.

**Comment by sarahlazarich** [comment]
lgtm
