### ISSUE TITLE
(Spike) Duplicates - Fixes

### ISSUE THREAD

**Issue by sarahlazarich** [bloom-housing/bloom#4139]
We've found that there are some issues with the way we're flagging duplicates in our system. Currently, once we have flagged an application in a set, we don’t check other rules for that application.  We currently check against two rules, name/DOB & email. We run the email check first, so that means we are more likely to run into a name/DOB issues
- The issue is laid out in detail in the [front end issues](https://docs.google.com/document/d/1wiR5INEHPrUofwLkdeRPHwj27huLQCK9tvXpaaR-Y7o/edit) here
- BE pre-design doc [here](https://docs.google.com/document/d/14DS6cTov36lZm8RLdmdvdvtAVTt53L-aJXthY9xtVCc/edit#heading=h.9ulwsk7053f)

Also, there is an issue with the times that we're running the duplicates job that is causing gaps in the applications that are screened. 

Outcome of this spike: 
- Rough outline of possible steps towards remediation & estimates 
- This doesn't need to be a full TDD, but need to start conceptualizing this for planning.

**Comment by sarahlazarich** [comment]
~2day timebox

Maybe split this into two? BE & FE?

**Comment by ludtkemorgan** [comment]
Here is a rough TDD for the duplicate fixes: https://docs.google.com/document/d/1h7zK3b466M2mfgj5vMjTaQKSL8STKUrH0t3MW-C1T4U/edit?usp=sharing

@sarahlazarich let me know if there is anything else you'd like to see in it
