### ISSUE TITLE
[backend/core] RFC Autogenerated axios client 

### ISSUE THREAD

**Issue by pbn4** [bloom-housing/bloom#414]
On the last meeting there was a discussion about an auto-generated API client. I finally managed to get one to work based on [swagger-axios-codegen](https://www.npmjs.com/package/swagger-axios-codegen). 

The client is generated based on swagger json which is available for download under `localhost:3001/api-json` when `core/backend` based API is running. Autogeneration script can be found [here](https://github.com/bloom-housing/bloom/blob/feature/terms_upstream/backend/core/generate-axios-client.ts).

To properly generate a client one must decorate a controller with @ApiTags and it's methods with @ApiOperation (only to give them nice names, because those autogenerated without operationId param will be a bit ugly) as e.g. [here](https://github.com/bloom-housing/bloom/blob/feature/terms_upstream/backend/core/src/applications/applications.controller.ts#L22).

Example client usage can be found [here](https://github.com/bloom-housing/bloom/blob/feature/terms_upstream/apps/public-reference/pages/applications/review/terms.tsx#L36). 

What do you think?

**Comment by bk3c** [comment]
@pbn4 I'll let others give feedback on the code-level mechanics, but I think this seems like it could be a good approach.

My one question is how would this kind of thing be impacted if we started using something like react-query or swr? See #396. Not sure that we'll go that route, but interested in the implications.

**Comment by pbn4** [comment]
@bk3c I looked at `react-query` and it will be compatible. See their [basic example](https://react-query.tanstack.com/docs/examples/basic) uses axios. SWR also seems to require user to provide a fetcher so that's the same case.

**Comment by kathyccheng** [comment]
Closing
