### ISSUE TITLE
AC: Can't Remove Community Types

### ISSUE THREAD

**Issue by ColinBuyck** [bloom-housing/bloom#4140]
The report from AC listing was that we cannot clear the “community type”. This is not a special community of any type but it’s labeled “Special Needs” and even though I try to remove that, it keeps coming back." 

Notes
-The immediate need was addressed due to @YazeedLoonat, deleting it from the db directly (feel free to add more detail here)
-This ticket is to understand why this occurred and prevent it from happening again without db intervention like this case

**Comment by ludtkemorgan** [comment]
This is in core and can be tested here: https://partners.bloom.exygy.dev/ by doing the following
Add a community type to a listing and save the listing. Then re-edit the listing and remove the reserved community type. The community type should no longer be on the listing
