### ISSUE TITLE
AFS job is failing to run

### ISSUE THREAD

**Issue by ludtkemorgan** [bloom-housing/bloom#4144]
The AFS job is failing to run in all environments because of this error:
```ERROR AFS_CRON_JOB failed to run. TypeError: Cannot read properties of null (reading 'toLowerCase')```

This is due to either the first or last name of an applicant not existing.

**Comment by ludtkemorgan** [comment]
This has been merged in core and the error is no longer in the logs. PR is ready to be merged in Doorway and HBA

**Comment by sarahlazarich** [comment]
@ludtkemorgan is there product QA here?

**Comment by sarahlazarich** [comment]
talked to ML, closing
