### ISSUE TITLE
Preview Listings Not Translating Completely

### ISSUE THREAD

**Issue by ColinBuyck** [bloom-housing/bloom#4147]
First noticed in Doorway, the preview for the listing is missing translations for the free response fields when switching to other languages. This issue has been discovered in Core as well so a fix should be made there and carried over to Doorway and HBA.

AC: The translations on the preview page should match the experience of the published listing.

QA: https://partners.bloom.exygy.dev/
Preview a listing from the partner's side and see that most if not all strings are translating with the exception of a few particular fields such as "or one month's rent may be higher for lower credit scores" which are known by Product

**Comment by sarahlazarich** [comment]
@ColinBuyck not sure if this is expected or if I'm losing track of my translation tickets here, but noticed that the preference isn't translated - For example, "Live in redlined neighborhood" [here](https://bloom.exygy.dev/zh/preview/listings/6e841e35-268b-41d1-b76f-30b475e0bab1)

Lmk if that's expected or if we need a follow up for that.

**Comment by sarahlazarich** [comment]
talked w @ColinBuyck, closing
