### ISSUE TITLE
Lotteries - Email Notifications (Applicant)

### ISSUE THREAD

**Issue by sarahlazarich** [bloom-housing/bloom#4160]

**Comment by sarahlazarich** [comment]
<img width="631" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUpQQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cd4904268cf588db4bff40f0ec1fd5ea57cae32f/image.png" alt="image.png" />
 translations still not updated here - does this have to do with the new copy?

**Comment by ludtkemorgan** [comment]
@sarahlazarich the missing translations you are seeing there are unrelated. But we do have several missing translations in the db. We could manually add the translations, but it would be easier to reseed the environment. https://exygy.slack.com/archives/C01Q4QG5R8Q/p1723583315826049

**Comment by sarahlazarich** [comment]
Okay this looks good! I'm going to open up a follow-up to address the new applicant copy.
