### ISSUE TITLE
Lotteries - Email Notification that results have been released to Partners

### ISSUE THREAD

**Issue by sarahlazarich** [bloom-housing/bloom#4161]
As a Partner user on a listing with a lottery 
I want to receive an email notification when results are released to my portal,
to that I can access the lottery results for publication. 

AC: 
- When lottery results are released by an admin, partners who have access to that listing should receive an email in the correct format.

**Comment by sarahlazarich** [comment]
Product/Design to get the email copy and template and link

**Comment by sarahlazarich** [comment]
Email results can go to partners and admins

**Comment by emilyjablonski** [comment]
QA Notes
Add a partner user and add them to a closed listing that has a lottery. As an admin, run and release the lottery. Ensure you receive the lottery released email. There isn't confirmed copy somewhere yet - this is filler / hopefully soon to be approved copy sent offline.

**Comment by sarahlazarich** [comment]
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUV6Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--94222592d1f1974aaa7af9ef5065dc3782bb8815/image.png" alt="image.png" />
 
It doesn't look like the translations are coming through here

**Comment by sarahlazarich** [comment]
Ok, got this!!!!! and it looks good.
