### ISSUE TITLE
(Pilot) Manual upload of lottery results

### ISSUE THREAD

**Issue by sarahlazarich** [bloom-housing/bloom#4171]
As an Admin posting the results of my lottery during our pilot,
I want to be able to manually upload a PDF of the lottery results to the listing page on the public site,
So that I can share out lottery results without having to use the automatic applicant communication.

As an applicant attempting to view the results of my lottery during our pilot,
I want to be able to access the results by clicking "View Listing" from my account page and downloading from there,
So that I can access my lottery results through portal. 

Notes: 
- We should be able to pull this over from Core. This is how HBA currently posts lottery results. 
- For the sake of the pilot, this will be the only way to post lottery results. There is no applicant communication scoped for pilot. 
- After the pilot, Doorway lottery listings that are opted out of the system lottery should be able to do this. 

AC: 
- As an admin, I should be able to manually upload a results PDF on my lottery listing 
- As an applicant, I should be able to download the PDF uploaded by the listing's admin

**Comment by sarahlazarich** [comment]
Is this on in Doorway or is it hidden?
If it's hidden, may need to update it for s3

**Comment by ludtkemorgan** [comment]
QA NOTES:
This only works if the show lottery toggle is turned on
- Go to the partner site and in a closed listing see that the "Post results" button is there when editing the listing
- Upload results and check that the "preview results" link appears
- Go to the public site and go to the listings page for the above listing. Check that the "Download Results" button is visible

**Comment by ludtkemorgan** [comment]
This was released in last week's release
