### ISSUE TITLE
Lotteries - Retract lottery

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#4188]

**Comment by emilyjablonski** [comment]
QA Notes
On a closed listing with a lottery as an admin, run and release a lottery. When released, the only action available to you should be a new retract button. Ensure the modal matches the [copy](https://docs.google.com/document/d/130OuxoQnKnukoVr_SPQq57A0JZ4vycdcS9q0EX2Gkso/edit#heading=h.gxdoimgubxbk), and that retracting it sends it back to the run state.

**Comment by sarahlazarich** [comment]
This looks good to me!
