### ISSUE TITLE
Lotteries - Releasing with new paper apps

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#4189]
As an Admin attempting to release a lottery, 
I want to be prompted to re-run if I have added added paper apps since running my lottery,
So that I don't accidentally release incomplete results.

Notes: 
- [Design](https://www.figma.com/design/PAeCVANDmGdTz2Y53ouErM/Lotteries?node-id=3299-33200&m=dev)
- [Copy Doc](https://docs.google.com/document/d/130OuxoQnKnukoVr_SPQq57A0JZ4vycdcS9q0EX2Gkso/edit#heading=h.ilfx1xnwk3z)

AC: 
- If new applications have been added after a lottery has been run (and the lottery has not yet been re-run), the system will require the user to re-run the lottery before they can release the lottery data.

**Comment by emilyjablonski** [comment]
QA Notes
I am confirming this w prod/design, but:
As an admin on a closed listing with a lottery, run the lottery. Add or update an application on that listing, and then try to release the lottery. You should get [this modal](https://docs.google.com/document/d/130OuxoQnKnukoVr_SPQq57A0JZ4vycdcS9q0EX2Gkso/edit?pli=1#heading=h.w2usczb0e7mi), though with just one OK button and the additional text about updating.

**Comment by sarahlazarich** [comment]
In addition to adding, what updates will prompt this modal? Any change to an app?

**Comment by sarahlazarich** [comment]
ok, awesome! lgtm, moving.
