### ISSUE TITLE
Fix empty arrow functions in alternate contact forms

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#420]
This is more of a linter issue than bug at this point, but I think the eslint is correctly complaining (even if it barely matters in this use case):

```
/Users/bk3c/projects/exygy/bloom/apps/public-reference/pages/applications/contact/alternate-contact-contact.tsx
  130:52  error    Unexpected empty arrow function                                @typescript-eslint/no-empty-function

/Users/bk3c/projects/exygy/bloom/apps/public-reference/pages/applications/contact/alternate-contact-name.tsx
  101:52  error    Unexpected empty arrow function                                @typescript-eslint/no-empty-function

/Users/bk3c/projects/exygy/bloom/apps/public-reference/pages/applications/contact/alternate-contact-type.tsx
  110:52  error    Unexpected empty arrow function                                @typescript-eslint/no-empty-function
```

See [the eslint docs here](https://eslint.org/docs/rules/no-empty-function) for their suggested fix of just wrapping the {} to ({}), which I think is the intent but I'm not sure so I'm filing this rather than just assuming.

Also, I'm not entirely sure how this got checked in the first time since the git hooks should prevent it (as they did for me when I was merging master to another branch), so if you can check your local environment to make sure the hooks are working that would be great. It's entirely possible we need to update that config somehow, which we can totally do if necessary.

**Comment by pbn4** [comment]
Precommit hooks do not run for me on a commit to a sidebranch. I have manually started `yarn lint` in our root directory and there are no errors now. By the way: we have 240 warnings.
