### ISSUE TITLE
Lotteries - Partners Cypress Suite

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#4206]
* Create a lottery listing
* As an admin, run the lottery
* As an admin, re-run the lottery
* As an admin, release the lottery
* As a partner, publish the lottery
* As an admin, retract the lottery
* As a partner, ensure you you cannot see data anymore

**Comment by sarahlazarich** [comment]
One big test that rolls through the whole flow, including status changes

**Comment by sarahlazarich** [comment]
I don't think this requires Product QA - but lmk if not @emilyjablonski !
