### ISSUE TITLE
Lotteries - Partner Export Terms

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#4210]
[Copy](https://docs.google.com/document/d/130OuxoQnKnukoVr_SPQq57A0JZ4vycdcS9q0EX2Gkso/edit?pli=1#heading=h.n9kz6ajsfrz)

**Comment by emilyjablonski** [comment]
QA Notes
On a closed listing with a lottery as a partner where the lottery has been published to public, export the lottery data and ensure you see a terms modal with [this copy](https://docs.google.com/document/d/130OuxoQnKnukoVr_SPQq57A0JZ4vycdcS9q0EX2Gkso/edit?pli=1#heading=h.n9kz6ajsfrz) (Doorway-specific references removed).

**Comment by sarahlazarich** [comment]
This looks goos!
