### ISSUE TITLE
Make lottery date a required field (BE)

### ISSUE THREAD

**Issue by sarahlazarich** [bloom-housing/bloom#4212]
As a user creating a listing that is using the system lottery,
The lottery date and time should be a required field,
So that I can not create a lottery listing without letting a user know when it will be run.

AC:
- For lottery listings opted in to the system lottery, the lottery date and time (both start and stop) should be required
- For listings that are not using the system lottery, the lottery date and time (both start and stop) should not be required 
- When making a listing, there should be an indication that the lottery date is required
- If a listing is attempted to publish without a lottery date, it should indicate that that field is required
- The lottery date/time should show up in the application export if applicable

**Comment by sarahlazarich** [comment]
We don't have a sense of conditional requirement on listing fields right now 
We could do this on the front end to look for the presence of the date if the type is lottery 
How could we do that on the BE? 
- We might want to split that into a BE + FE ticket 

On the BE -- 
Route 1: 
- Custom validator 
- More in line with our other validators 
Route 2: 
- Do it as a part of the actual service

**Comment by sarahlazarich** [comment]
Also include test writing

**Comment by sarahlazarich** [comment]
This looks good

**Comment by sarahlazarich** [comment]
Actually, noticing one thing, and I'm not sure if this is the UX flow we want - https://www.loom.com/share/f36d2246358f41dc9ff48aef5c7ad28a?sid=dc17b27b-324d-4be3-a7d9-910e95d4d50f 

Is this our typical pattern here? If you remove a part of the date field, then save, the whole thing doesn't save. Not sure if this is an error but is this the pattern we use?

**Comment by mcgarrye** [comment]
> Actually, noticing one thing, and I'm not sure if this is the UX flow we want - https://www.loom.com/share/f36d2246358f41dc9ff48aef5c7ad28a?sid=dc17b27b-324d-4be3-a7d9-910e95d4d50f
> 
> Is this our typical pattern here? If you remove a part of the date field, then save, the whole thing doesn't save. Not sure if this is an error but is this the pattern we use?

Good find. I just tested this in HBA staging where the new code has yet to be deployed and the same thing happened. If we want to fix, we should create a bug ticket
