### ISSUE TITLE
Lotteries - Opt in permissioning and copy

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#4221]
As an Admin on Doorway creating a listing with a lottery, 
I want to be able to "opt out" a listing from using the system lottery 
So that I can exempt certain listings from the automatic lottery. 

As a Partner on Doorway on the create or edit screen on a lottery listing,
I want to see if my listing has been opted in or out of the lottery,
So that I know if my lottery will be run by the system or if I will have to do it manually. 

Notes: 
- [Design](https://www.figma.com/design/PAeCVANDmGdTz2Y53ouErM/Lotteries?node-id=3345-7278&t=XeYvwRFLR4nl0xia-0)

AC: 
- Admins should be able to opt a listing in/out of the system lottery 
- The disclaimer text on Partners should be responsive to if it was opted in/out of the system lottery

**Comment by emilyjablonski** [comment]
QA Notes
As an admin, creating a listing that opts in to the lottery and view the listing as a partner to see the opt in text. Do the same for opting out. Save changes in both states as a partner to ensure the partner user is not able to update the value.

**Comment by sarahlazarich** [comment]
this looks good!
