### ISSUE TITLE
Lotteries - Re-run

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#4222]
The re-run modal should re-run the lottery

Add back in the re-run button when an admin is in a released to partners state using the new modal copy in [Figma](https://www.figma.com/design/PAeCVANDmGdTz2Y53ouErM/Lotteries?node-id=3794-29603&t=cqXh4M3ymmZWLAA0-0)

**Comment by emilyjablonski** [comment]
QA Notes
There is different copy in each of these three states.
(1) Lottery has been run
(2) Lottery has been released
(3) Lottery has been published

It will show for admins on every status after the lottery has been run, including in the released state.

**Comment by sarahlazarich** [comment]
This looks good to me - I don't think BAHFA has confirmed the copy here for the re-run after publication so I'll run that by them but don't anticipate issues.
