### ISSUE TITLE
Listing Cannot Be Edited After Lottery Result PDF

### ISSUE THREAD

**Issue by mcgarrye** [bloom-housing/bloom#4242]
**Describe the bug**
A listing that has had a lottery result pdf uploaded can no longer be edited after that.
This is because we do not delete and recreate the asset in the listing service update for the listingEvents.

**To Reproduce**
1. Go to a closed lottery listing that is opted out of lottery service
2. Upload lottery results pdf
3. Attempt to make an edit to the listing

**Expected behavior**
Edit should succeed.

**Additional context**

**QA NOTES**
will be available in: https://partners.bloom.exygy.dev/sign-in 
Create or edit a listing such that: 
- it is closed
- it is set to lottery
- the lottery not run through the partner site (you will manually upload lottery results)
- manually uploaded lottery results

go back in to edit the listing -> attempt to save -> it should now save

**Comment by sarahlazarich** [comment]
This is a Prisma issue - add an extra step to delete the PDF and re-add it or make it so it doesn't create a new PDF every time. 

This is maybe a misunderstanding of how jurisdictions are opening/closing listings? Why would they re-open that? Went over why

**Comment by sarahlazarich** [comment]
this looks good!
