### ISSUE TITLE
Lottery Result Upload Cannot Be Edited

### ISSUE THREAD

**Issue by mcgarrye** [bloom-housing/bloom#4243]
**Describe the bug**
Once a lottery result pdf has been uploaded to a listing, it cannot be replaced or deleted in the UI. The button is unresponsive to clicking.

**To Reproduce**
1. Go to closed lottery listing with a lottery result uploaded
2. Go into editing the listing
3. Attempt to click the edit button for the lottery results pdf
4. Nothing happens

**Expected behavior**
Should give options to replace or delete

**QA NOTES**
Create or edit a listing such that:
- the listing is closed, marked as running a lottery, marked as NOT running the lottery through the partner site

- upload lottery results

- go in to edit the listing and make sure you can edit the uploaded lottery results (delete results, switch to a different file, etc)

**Comment by sarahlazarich** [comment]
Is this a button issue or a BE issue? We don't know, might require a bit more investigation 
Did this ever work? ML is pretty confident it did, not sure if Prisma broke this or if it's just been broken since lottery work that we did

**Comment by sarahlazarich** [comment]
lgtm!
