### ISSUE TITLE
Lottery generation includes opt-out selections in preference tabs

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#4282]
<img width="1410" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2lWQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d5bc99b1de132f5dd1b642ae9ace7f60e9feac3d/Screenshot%202024-08-26%20at%203.18.17%E2%80%AFPM.png" alt="Screenshot 2024-08-26 at 3.18.17 PM.png" />

We're having applications show up w a preference rank, when that preference wasn’t claimed

**Comment by sarahlazarich** [comment]
At the moment, you're sometimes required to select 

Best option: 
- Not save that as claimed, but this is wonky, and making that change would require a bunch of changes 

Interim solution: 
- When we generate lottery, filter that out for now. But this is still just a patch and should pull in the better fix eventually

**Comment by ludtkemorgan** [comment]
QA Notes:
- Run the lottery on a listing where at least one application has "opted out" of a preference.
- The application where the preference was selected as "opt out" should not show in the tab for that preference but should still be in the main tab

**Comment by sarahlazarich** [comment]
lgtm
