### ISSUE TITLE
Provide preference data

### ISSUE THREAD

**Issue by callaghanc** [bloom-housing/bloom#43]
Provide preference data for listings via the listings service. Represent preferences as separate objects.

**Comment by jaredcwhite** [comment]
Basic JSON format:

```json
[
  {
    "ordinal": "1st",
    "title": "Certificate of Preference (COP)",
    "subtitle": "Up to 56 units available",
    "description": "For households with at least one member…",
    "links": [
      {
        "title": "Read More",
        "url": "https://domain.com"
      }
    ]
  },
  {
    "ordinal": "4th",
    "title": "Live or Work in San Francisco Preference",
    "subtitle": "Up to 11 units available",
    "description": "For households in which…",
    "links": [
      {
        "title": "Read More",
        "url": "https://domain.com"
      },
      {
        "title": "View Document Checklist",
        "url": "/checklist"
      }
    ]
  } 
]
```

**Comment by bk3c** [comment]
@jaredcwhite What is your vision for how this would localize?

**Comment by jaredcwhite** [comment]
@bk3c Well, I'm imagining the "real" backend will need to serve localized content (maybe all sorts of fields will need to support translations), so I'm not opposed to having specific text like "1st" coming over the wire. But if you'd prefer keeping all numbering as integers, I'm down.

**Comment by jaredcwhite** [comment]
I think I'll need some examples of real-world preferences to add to the data…the three listings currently on the regional staging (two in SJ, one in SMC) don't seem to have any preferences listed.
