### ISSUE TITLE
Lottery Duplicates - Remove "View Results" button for duplicate apps

### ISSUE THREAD

**Issue by sarahlazarich** [bloom-housing/bloom#4303]
Applications that have been marked as duplicates will not have lottery results. Because of this, they should not have the "view lottery results" button in thier applicant account.

**Comment by emilyjablonski** [comment]
QA Notes
Ensure the button only shows on a published lottery listing if the application has results (which it won't for a duplicate you confirm and exclude from the lottery).

**Comment by sarahlazarich** [comment]
thank you!
