### ISSUE TITLE
Applicant experience - preferences available not claimed

### ISSUE THREAD

**Issue by sarahlazarich** [bloom-housing/bloom#4308]
As an applicant looking at my lottery results in my account view, 
I want to see a relevant message if I have not claimed preferences 
So that I understand 

Notes: 
Design is here, copy is below! 
<img width="343" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODZvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9791a4bfbde41425d21df6983a79d98fba68cb7d/image.png" alt="image.png" />

Copy: 
[Header] Your lottery preference(s)

Lottery preferences for your application are shown below in priority order. If you do not qualify for any lottery preferences, you will be part of the general lottery category. The general lottery category is the last group
processed.

[Button] What are lottery preferences?

[Message] These results are based on the information you provided in your application. Preference el gibility is subject to change once your information is verified.

AC: 
- On a listing that has preferences, if I don't claim any preferences, I should see the design above

**Comment by emilyjablonski** [comment]
Verifying that the request here is already the current behavior
