### ISSUE TITLE
Lottery Duplicates - email to valid app only

### ISSUE THREAD

**Issue by sarahlazarich** [bloom-housing/bloom#4312]
As an applicant on Doorway who has submitted multiple applications, 
Only applications marked as valid should receive an email about my lottery results (& see lottery results in my account), 
So that I do not get confused by an email that says results are ready for an application that was opted out of the lottery. 

AC: 
- If I submit duplicate applications, I should only recieve a notification email for my valid applications.

**Comment by emilyjablonski** [comment]
QA Notes

Submit two applications while logged in under different email accounts, but use same name / dob, as a partner mark one as a duplicate, and after publishing the lottery ensure only the valid email received a notification.

**Comment by sarahlazarich** [comment]
lgtm!
