### ISSUE TITLE
Lottery email - publication notice to partners/admins

### ISSUE THREAD

**Issue by sarahlazarich** [bloom-housing/bloom#4316]
Bug: 
- When testing automatic publication, the "results were published to applicant account" went out to some, but not all, of the admins on core.

Expected Behavior: 
- All partners and Admins should get an email when lottery is published 

<img width="719" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzNGQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--535b73429821a88c845481ebaa263f740224cc59/image.png" alt="image.png" />

**Comment by emilyjablonski** [comment]
@sarahlazarich Do you have more details on how this was tested / what environment this was in?

**Comment by sarahlazarich** [comment]
Yeah - I believe @mcgarrye and I were testing at https://partners.bloom.exygy.dev/sign-in
