### ISSUE TITLE
Spike - AC: Display more than 10 Closed Listings

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#4348]
Only ten closed listings are being displayed on the public site, with the oldest being bumped from display when a newer listing closes. This is causing issues for applicants who want to check lottery results. AC has requested that we show 20 listings, and make sure that the most recently closed listings are the ones that are showing. 

This spike is to do some testing on what the max we can send to the frontend before we hit the max size here to be sure we can show 20 listings. 

**QA NOTES**
- head to the public site
- make sure up to 20 closed listings show

**Comment by sarahlazarich** [comment]
lgtm
