### ISSUE TITLE
Application export fails with null programs

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#4357]
`/app/dist/src/services/application-csv-export.service.js:190                                       const program = programs.find((preference) => preference.key === curr);`

We expected programs to always be at minimum the empty array `[]` 
if programs is coming across as `null` it causes breakages we didn't account for, the fix here will be to change this so that if programs is `null` we skip over this work so we no longer error

**Comment by emilyjablonski** [comment]
@YazeedLoonat Do you wanna add some more details here?

**Comment by YazeedLoonat** [comment]
added!
