### ISSUE TITLE
Storybook errors related to the User backend entity

### ISSUE THREAD

**Issue by jaredcwhite** [bloom-housing/bloom#437]
It looks like the `RequireLogin` test added to the ui-components package is causing Storybook errors now related to the import of the User entity from the backend-core package. I'm not sure if this will be an easy fix…I wonder if we'll need to import a shim to aid in testing similar to the Next.js frontend apps.

Something you could take a look at @bencpeters? Let me know if you have any questions.

**Comment by bk3c** [comment]
Fixed already.
