### ISSUE TITLE
Surface programs on listing

### ISSUE THREAD

**Issue by sarahlazarich** [bloom-housing/bloom#4399]
As a person creating a listing on Doorway,
I want to be able to surface programs on the listing detail page,
So that the program info can be accessible without having to go through the application.

[Copy](https://docs.google.com/document/d/1ojtuOrncD2-JD7SGBc4WMgtIt8oMVkQNPIe0op6-SN8/edit#heading=h.z2we68wtdnff) 
[Design](https://www.figma.com/design/Kcsf148FqeUqMNeMo54BsW/Ad-Hoc-Feature-Enhancements?node-id=3717-2118&t=mThh5Kvy1z2Mac3Y-0)

Notes:
- We need to be able to designate if a program is shown or not on the listing. Not all programs should be shown.
- Let's start with this, and designating if the listing should be shown on the listing by program.  We can explore doing the programs adding UI after if this goes as quickly as we anticipate. 

*QA NOTES*
by default the seeded data has programs set to show on the listing detail page of the public site

head to the public site select a listing with programs on it and you should get the new program section

make sure translations work for each of the languages

**Comment by emilyjablonski** [comment]
@YazeedLoonat This QA notes won't work in a deployed environment, yea?

**Comment by YazeedLoonat** [comment]
good call out @emilyjablonski ! there are listings on the core hosted env, after the scriptRunner script has been run and all programs are marked as do not show I would have to work with you @sarahlazarich to turn on some and get a listing set up for ya

**Comment by YazeedLoonat** [comment]
Hey @sarahlazarich this is ready for your 👀 as it currently stands all of the existing programs should be hidden on https://bloom.exygy.dev/

when you are ready to turn a program on to test with 
![image](https://github.com/user-attachments/assets/886c083b-9926-4363-8882-d4a5c6e98505)


that bottom one was created specifically to test this functionality 

lemme know what you think!

**Comment by sarahlazarich** [comment]
lgtm :)
