### ISSUE TITLE
Fork repo and deploy testing environment

### ISSUE THREAD

**Issue by ludtkemorgan** [bloom-housing/bloom#4419]
While we are bringing Detroit up to core we will need an intermediate repository to work against before we pull it over to Detroit's repo. Along with this we also need to have an environment where we can demo and test our changes

This Ticket will tackle the following:
- Create a new repo within bloom-housing github that is a fork of the core repo (the whole repo)
- Create a backend environment in Heroku and deploy from the newly forked repo
  - Create a new "mini" database 
  - Setup seeded data and create "Detroit" jurisdiction
  - Have it autodeploy from the main branch of the forked repo
- Create a public and partner site in Netlify
  - We can reference the demo sites https://app.netlify.com/sites/bloom-demo-public/overview and https://app.netlify.com/sites/bloom-demo-partners/overview for configuration

**Comment by sarahlazarich** [comment]
tests? Detroit is using jarvis - use circleci for now
that should be a part of this ticket (does it add a lot of points?) 
Seeded data - that's fine, all houses in CA for now

**Comment by ludtkemorgan** [comment]
QA Notes:
A new backend and partner/public site has been deployed with seeded data.
- https://bloom-detroit.netlify.app/
- https://bloom-detroit-partners.netlify.app/
