### ISSUE TITLE
Rename amiPercentage to maxAmiPercentage

### ISSUE THREAD

**Issue by akegan** [bloom-housing/bloom#445]
SF now has the concept of a minimum AMI for qualifying for a unit, so we now have to make the distinction between min and max AMIs. 

bloom core can support this by switching from amiPercentage to maxAmiPercentage when talking about eligibility for a unit.

**Comment by bk3c** [comment]
Seems like a relatively straight-forward change that should be easy enough for us to implement and doesn't have any obvious downsides. We'd definitely be open to a PR for this if you have the time and interest before we get to it.
