### ISSUE TITLE
Farsi in Alameda County 

### ISSUE THREAD

**Issue by sarahlazarich** [bloom-housing/bloom#4454]
Alameda County wants to add Farsi to add a translation option to their portal.  Izzie manually pulled all the static content on the page, but we want to make sure that nothing was missed. Is there a way to pull all the content and do a comparison programatically, or create a spreadsheet output that we could use to check against? 

https://docs.google.com/spreadsheets/d/1KVi5UQXdphO0f8FPEEZBqrPYxI5mDby6q-vf7_lf-DA/edit?gid=0#gid=0

**Comment by ludtkemorgan** [comment]
@sarahlazarich is this supposed to be in QA?

**Comment by sarahlazarich** [comment]
deprioritized for AC roll-in
