### ISSUE TITLE
Remove references to SMC on HBA portals 

### ISSUE THREAD

**Issue by sarahlazarich** [bloom-housing/bloom#4456]
We should remove references to SMC's portal on HBA now that it has been folded into Doorway.  

Notes: 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2lCQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--97de69cbf3bf89eac90f631323340419dabc53d9/image.png" alt="image.png" />

<img width="1786" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK21CQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f62ebeb921c67f6a18d57b305d1de0db5897f440/image.png" alt="image.png" />

<img width="1026" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3VCQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f0f9e856953cdc2fd19c0d8473b784f3d53b5b7f/image.png" alt="image.png" />

AC: 
- Remove San Mateo from AC footer 
- Remove San Mateo from SJ footer 
- SMC removed from The last section on [this doorway page](https://housingbayarea.mtc.ca.gov/help/get-started)

QA Notes:
- Footer on the public site shouldn't have link to SMC in Alameda and San Jose
- /get-started page shouldn't have any references to SMC

**Comment by ludtkemorgan** [comment]
One additional reference to SMC was found while implementing this ticket. This will be removed as well
![image](https://github.com/user-attachments/assets/83e48ab6-6cac-49f9-aaf5-c6ff48933184)
