### ISSUE TITLE
SJ: Page Not Found error when editing partner users

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#4481]
Dave in SJ reported that when he is logged into his j-admin account, and clicks on a user to edit their profile, he gets a "Page Not Found" error. I was able to replicate this on my account, and it is persisting after logging out and logging back in. This is a high priority issue :red_circle:.

**Comment by ludtkemorgan** [comment]
This has been resolved. Too much data was getting sent when calling the listing endpoint.
