### ISSUE TITLE
copy listing does not work if a paper application is attached to listing

### ISSUE THREAD

**Issue by ludtkemorgan** [bloom-housing/bloom#4490]
When attempting to copy a listing that has a paper application attached the backend fails with a duplicate "id" error.

 Steps to reproduce:
1. Go to a listing in partners and edit
2. Within the "Application Process" tab select "yes" to the "Is there a paper application?" and "Add paper Application".
3. After saving the listing click "Copy" and confirm
4. The generic error message appears

**Comment by ludtkemorgan** [comment]
@ColinBuyck with Sarah being out are you able to QA this?

**Comment by ColinBuyck** [comment]
Yep! Just tested in staging sites and LGTM 🖱️
