### ISSUE TITLE
Allow form pages to be easily configured off and on

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#453]
The end goal is to have this configurable from the back-end, but after some discussion it seems like doing this on the front-end only first and then working back from there. Things that need to be configured include:

- [ ] which screens of the form are supposed to be used in which order 
- [ ] validation rules for various forms (e.g. the listing-specific thresholds for income / preference validation should be passed in from the config, and then the rules for evaluating them can be coded into each screen)
- [ ] conditional use of screens, if they're only supposed to be part of the flow based on other answers
- [ ] text configuration based on listing type (e.g. FCFS vs. Lottery, see also #424 and #278)

**Comment by bk3c** [comment]
Just to document what's currently in my head, I think an ideal solution would have the configuration in a JSONable object that can easily be served from the backend in the future, and that had a format that was easy to expand as we add steps and options over time. For example, something like a `FormSequence` object with a structure like:

```js
{ steps: [
  {component: 'HouseholdMemberForm', props: {dataKey: 'HouseholdMember', title: 'Household Member'}},
  {component: 'IncomeForm', props: {dataKey: 'Income', title: 'Income', otherConfig: value}}
  ],
  metaField1: value,
  metaField2: value
}
```

The basic idea here is that the configuration just references an existing form component in the code base, and can pass in any props that are exposed but we want that to be pretty minimal and not try to represent the form itself in the config. As particular form steps are added or overridden, they can just be added to the array or the component name changed. Having the data key there is a way to be able to re-use the same component for multiple data elements, and to decouple the component from knowing too much about where the resulting data is stored (though I imagine it will still map the individual fields below the specified key). 

All of the details here are only meant to spark discussion -- I'm not sure that any of them are correct, and I welcome all ideas including completely different approaches.

**Comment by bk3c** [comment]
cc: @james-willis-sf, since I know you had experience in this area and thoughts for how it might go. I expect we'll be starting on code for this soon, so would love to get any thoughts or feedback on your mind.

**Comment by jaredcwhite** [comment]
@bk3c I think that's a good start. I'd probably suggest we add the relative URLs for each step so that we can anticipate where to go when clicking "Next" on a form, unless we want to derive the URLs from some other logic.

**Comment by bk3c** [comment]
@jaredcwhite In my ideal world, we wouldn't have to explicitly specify URLs and the conductor (or whatever it evolves into) would be able to act as a controller and just send the user to the right place based on their current session state and whatever the sequence defined for their form is. I don't think there's any sensible concept of deep linking into the middle of a form, so each step doesn't need to have a distinct public URL per se. That said, I don't want to fight against the nextjs router or other SSR functionality, so if it's easier to get what we want with URLs, then that's fine with me.

**Comment by bk3c** [comment]
The other thing I was thinking about is whether we should call this more of a `ApplicationConfig` rather than a sequence, and have basically a 1:1 mapping between this and a listing. Then we could have a hash with all of the relevant preference information, as well as whatever else from the listing (e.g. AMI table) we need for form validation and display.

If we went down this road, I'm thinking that this JSON object would be completely denormalized (e.g. it would duplicate all of the relevant information from the listing itself so the front-end didn't need to correlate the state), but that doesn't imply that we'd duplicate everything in the backend DB, just that we'd serve it from two endpoints. Seems like minimal network impact of a few kb, and it would help keep the front-end logic simpler.

**Comment by jaredcwhite** [comment]
> @jaredcwhite In my ideal world, we wouldn't have to explicitly specify URLs and the conductor (or whatever it evolves into) would be able to act as a controller and just send the user to the right place based on their current session state and whatever the sequence defined for their form is. I don't think there's any sensible concept of deep linking into the middle of a form, so each step doesn't need to have a distinct public URL per se. That said, I don't want to fight against the nextjs router or other SSR functionality, so if it's easier to get what we want with URLs, then that's fine with me.

Well, given the way everything's currently architected (using Next pages/router/etc.), we would need to define the steps via relative URL rather than component name. Otherwise, I think everything else you're saying would apply.

**Comment by bk3c** [comment]
Yeah, I think having a relative URL instead of a component name would work just as well.

**Comment by jaredcwhite** [comment]
@bk3c For the routing, I'm thinking a structure something like this:

```
{steps: [
  {
    name: "0.1 - Choose Language",
    url: "/applications/start/choose-language",
    nextUrls: [{ url: "/applications/start/what-to-expect" }],
  },
  {
    name: "0.2 - What To Expect",
    url: "/applications/start/what-to-expect",
    nextUrls: [{ url: "/applications/contact/name", conditions: {?} }, {url: "/applications/something/else"}],
  }
]}
```

On the `nextUrls` I'm imagining one, or several, routes that require some kind of condition to be met in order for the route to be used…I'm not sure how we write that condition, or if that should reference something else that happens in code.

**Comment by jaredcwhite** [comment]
So, some follow-up questions/thoughts after our discussion a couple of days ago:

* For the form config templates which can be selected in the backend on a per-listing basis, would those templates themselves be defined as files in the repo? Or should they be stored in the database directly?
* When a template is applied to a new listing, does that literally clone the template data structure and save that newly associated with the listing in the DB?
* Should the frontend get a full list of steps (including the ones that were deactivated) and make a determination what to do at that point? Or should the backend automatically filter out deactivated steps before passing it along to the frontend? (probably the latter I would say…)
* I think we need some kind of optional data for some steps to "get promoted" to the progress nav, so we can obtain the You, Household, Income, etc. labels/links right out of the config.
* Regarding "props" to the form step components, how were you envisioning that might work? I think technically speaking, the component is loaded by Next/React prior to accessing any data via hooks, so the lifecycle might be off. But certainly once the step loads and gets that config data, it can use that data to influence the appearance/behavior of the form from that point forward as it sets up the render.

**Comment by bk3c** [comment]
> * For the form config templates which can be selected in the backend on a per-listing basis, would those templates themselves be defined as files in the repo? Or should they be stored in the database directly?

I see the form configs themselves as an object in the database. For each listing object that allowed for online application through our system, there would be a matching 1:1 config object specifying how that application process was to work. If we had just a listing where the application was external, then no need for the matching form config. From the perspective of a user of the Partners app, I think it would seem like setting up the form config would just be part of setting up the listing -- another tab (or whatever @slowbot decides) as part of the listing setup process. I just think we want to separate the underlying objects to keep the config stuff a little distanced from all the user-facing fields on a listing itself.

> * When a template is applied to a new listing, does that literally clone the template data structure and save that newly associated with the listing in the DB?

I would say that a listing can have one and only form config, two objects 1:1. Then, to make the creation of the form config easier we could have templates which could be hard-coded for now. Eventually, I think it'll get a little more complicated, since we'll want jurisdictions to be able to constrain the set of choices for listings within their purview. For example, if a jurisdiction requires that everyone is asked about their ethnicity in a certain way, the property manager setting up the listing and form config should not be able to select anything different than that. I don't think this needs to be enforced at the object model level, just that we eventually need to be able to write a Partners UI with those kinds of concepts of constraints. Given the current small number of jurisdictions and success we've had getting them to align their application processes to something common, I think it would be entirely reasonable to put the jurisdictional template part of this is code for at least the short-medium term. Also, just in the interest of being explicit, the "template" I'm referring to here would never need to be seen beyond Partners -- it's only the "form config" (which I realize you may have meant) that the public app needs to see and act on.

> * Should the frontend get a full list of steps (including the ones that were deactivated) and make a determination what to do at that point? Or should the backend automatically filter out deactivated steps before passing it along to the frontend? (probably the latter I would say…)

I agree the latter. I think the whole point is that the form config defines how any listing-specific application process is exactly going to work.

> * I think we need some kind of optional data for some steps to "get promoted" to the progress nav, so we can obtain the You, Household, Income, etc. labels/links right out of the config.

Agreed.

> * Regarding "props" to the form step components, how were you envisioning that might work? I think technically speaking, the component is loaded by Next/React prior to accessing any data via hooks, so the lifecycle might be off. But certainly once the step loads and gets that config data, it can use that data to influence the appearance/behavior of the form from that point forward as it sets up the render.

Yeah, I'm certainly open to a more clever hooks-based solution to managing the state than my old-school props plan. My point more generally was that we need a way for the form config to not only define what the steps in the process are, but also some details of how each step might operate, in a way that can be passed to the UI component for render / evaluation.

For example, maybe we have a part of the form that asks about age. We might want that screen to a) just collect the information; b) warn the user that they're too young for a senior building; or c) not let the user proceed with the application if they're too young. What I think we want to avoid is having the form screen component know anything about the underlying listing schema (e.g. having logic that says `if (listing.isSeniorBuilding) { warn() }`, instead the constraints that apply to each screen just get passed into it, whatever way is best, and then it does the right thing.

I think (hope?) this approach also sets us up to do conditional logic correctly, since what's passed to one screen can be based on what happens from another screen based on code logic in the Conductor (or whatever that becomes), not just what's sent up from the back-end.

**Comment by bk3c** [comment]
Just to add an explicit example of that last thought, we want a way to say something like "If the user indicates they have an income > X on screen A, then take them to screen B, otherwise skip to screen C". I guess I won't complain if there's a way to reasonably represent that kind of conditional in a form config object, but I'm not expecting it -- I think it's totally fine to say that conditionals need to be coded for the foreseeable future, and at most the form config will just control whether they're off or on.

**Comment by jaredcwhite** [comment]
@bk3c That all makes sense to me. The least immediately obvious aspect of it is that last part, and as you said we might need to go at it incrementally where some conditional logic is still hardcoded on the form pages for a while until the config smarts are more fully baked. But otherwise I feel like we have enough to go on.

Maybe the next step would be to draft a template based on the current forms and use that as a jumping off point for how we'll store and utilize the config?

**Comment by james-wills-sf** [comment]
@bk3c Just read through this thread. I pretty much agree with the idea of a json config! I have a few ideas that you can take or leave:

### Titles shouldn't include step numbers in them
Ex: Instead of "0.1 - Choose Language" I think the title (either passed from the backend or defined using the `ApplicationStep` frontend interface) should just be "Choose Language" and the conductor calculates the step number and returns the string used for display. This way the steps can change order without changing the data

### Use the backend ordering + a skip_step function to decide what next/previous steps are
Instead of defining next/previous steps as part of the ApplicationStep definition or adding it to the components themselves, the Conductor should be the sole place where ordering is calculated.

If each step has a function like `skip_step: (dataController: DataController) => boolean`, it might look something like:
```
[
  {
    title: "step 1",
    skip_step: () => false
  },
  {
    title: "step 2",
    skip_step: (dataController) => dataController.isUserLivingAlone()
  },
  {
    title: "step 3",
    skip_step: () => false
  }
]
```


And you're on step 1, and you click "Next Step" the conductor can walk through the list starting at "Step 2", check if ` dataController.isUserLivingAlone()` is true or false, and show "step 2" or "Step 3" respectively.


### Backend just supplies keys, step definitions on frontend
The `ApplicationStep` type definition could look something like:
```
{
  backend_key: string,
  skip_step: (dataController: DataController) => boolean,
  name: string
  url: string,
}
```

And then the backend returns a list of `ApplicationStep.backend_key` strings. This list would be the superset of all possible steps the user could get in order, and skip_step would be checked before each to know what the actual next/last steps are.

This just makes it easier to store functions like skip_step in each step.

However, if it's likely that the same step for different listings or sites will require a single different value, like slightly different titles, this will result in a lot of duplication. Like SFLanguageStep, AlamedaLanguageStep, etc.

### List of step options + order defined on the frontend for each site, skip_step used to show/hide steps based on listing properties
Since it seems like the only differences between the step arrays on a listing level is whether to turn a step on or off (ie: no switching the ordering of steps), you could just put that logic in skip_step on the frontend, like:

```
{
  title: "Live/Work in SF preference step",
  skip_step: (dataController: DataController) => !dataController.listingHasLiveWorkPreferenceOption()
}
```

I just think since whether you need to show or hide a step is sometimes based on listing data that you have on the front or backend and sometimes based on the application data you only have on the frontend, it might be easier to consolidate the show/hide logic on the frontend, where you can do all of it.

### Idea: instead of promoting steps to the progress nav, maybe have separate ideas of steps and sub-steps?
The data could look something like:
```
[
  {
    navBarTitle: "About you"
    subSteps: [
      {
        title: "Language",
        ...
      },
      {
        title: "Address",
        ...
      },
      {
        title: "Phone Number",
        ...
      }
    ]
  },
    {
    navBarTitle: "Preferences"
    subSteps: [
      {
        title: "Live/Work",
        ...
      },
      {
        title: "Another preference",
        ...
      },
    ]
  },
  ...
]
```

Only nice thing about this is it makes it more explicit which top level step you're in when you're on a subStep.

None of these are hard requirements, just ideas to think about. Mostly what I laid out here is how I've seen stuff like this built before, but there are definitely multiple ways to do this.

**Comment by jaredcwhite** [comment]
@james-wills-sf Thanks James! A few comments on your comments:

I was thinking the purpose of the name field was our internal naming for reference, not something user facing. (I'm guessing user facing titles should still come out of the translation files.)

The steps/sub-steps idea is interesting…I think that approach makes sense.

The function for determining if a step should be skipped is something I was thinking about too, but I'm not sure the best heuristic for pairing a step config coming from the backend with a logical step function defined on the frontend. Maybe using a key-based approach which I think you're suggesting.

**Comment by bk3c** [comment]
Ok, I put some thoughts in #596, which I did as a PR rather than a comment because it seemed like it was getting to big to just plop in this thread.

**Comment by kathyccheng** [comment]
MVP version merged
