### ISSUE TITLE
Don't show a Listing Map without a valid location

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#457]
This is mostly just a code quality issue at this point since I can't think of a realistic situation where we'd have no location information at all, but since they tightened up the types for react-map-gl, we're now getting a type failure on jest tests because we're not checking for the undefined case. Our Address (correctly) allows those fields to be null, and the map component rightly complains if you try to put a marker without valid coordinates.

For bonus points, we can go ahead and implement #448 as we do this, but that's also fine to do in the more distant future so long as we gracefully handle the null case in the short term, which I assume means just not showing the map.

**Comment by jaredcwhite** [comment]
Well that's weird…on the latest `review-form-step` branch, I can't get the "No overload matches this call" error with Marker to happen on my machine. Tests run fine. I wonder if there's some difference in env vars or something…

**Comment by bk3c** [comment]
Try it now on master now that everything is merged? I can replicate it locally no problem.
