### ISSUE TITLE
Create TS interface for application forms and improve data model

### ISSUE THREAD

**Issue by jaredcwhite** [bloom-housing/bloom#460]
Currently the application data model lives in `apps/public-reference/lib/AppSubmissionContext.ts`

We should relocate this to a more centralized location and add a genuine interface. While doing that, we should take another look at the data model and identify ways we can improve it as well as use other data types in our system (such as `Address`—which BTW currently has a slight discrepancy with the addresses in application).

**Comment by pbn4** [comment]
I suggest that we expand actual ORM model for application (which is now a jsonb column) with rich typing and  an interface will be automatically generated along with axios client for the frontend.

**Comment by jaredcwhite** [comment]
Do we feel comfortable enough at this point to lock down the scheme at the backend DB level? What about configurations that might change from app to app?
