### ISSUE TITLE
Improve frontend protection from null or malformed JWTs

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#475]
While doing QA on #464, I got into a situation where a valid JWT wasn't returned from the backend because I was running the old service instead of the new one, which caused a NextJS error and required a manual cookie wipe to resolve. It seems like the browser being unable to connect to the backend or otherwise getting an unexpected error is a case that we should handle a little better.

**Comment by kathyccheng** [comment]
@jaredcwhite can you see if this is still an issue?

**Comment by jaredcwhite** [comment]
@kathyccheng Sure, I'll take a look.

**Comment by jaredcwhite** [comment]
Looks like we need to catch any `InvalidTokenError` thrown and deal with it accordingly. I'll work on a fix.

**Comment by kathyccheng** [comment]
Ongoing tech debt
