### ISSUE TITLE
Replace sign-in option for already-signed-in users starting their application

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#477]
Looks like this case wasn't explicitly covered in #277, but it seems weird to present the sign-in button to users who are already signed in. 

At a minimum, we can just not show that block, but I think it would be better to provide some reminder feedback like:

You are currently logged in as [name].
 - Once submitted, you will be able to view this application later
 - Your information from prior applications may be auto-filled to save you time.

Neither of the bulleted items will be true immediately, so we can phase them in over time unless it's too much detail and then we can just forego it entirely.

--> @slowbot for design, and then we can implement it maybe next sprint?

**Comment by kathyccheng** [comment]
I think this is handled
