### ISSUE TITLE
Align listing/unit type definitions between shared/core, backend/core, and JSON files

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#485]
I discovered these were misaligned while researching a different problem and coming across a suspicious use of `any`. Easiest example is `monthlyIncomeMin`, which is defined as a `number` in both the shared/core and backend/core type definition files, but is a string in every test and production JSON file I see.

I don't have a particular opinion on what the type should be in each case (for example, I know that JSON decimal numbers can be fraught for dollar amounts since JS numbers are floating point), but anything we can do to align the types one way or the other and remove the `any` references will be good for code quality and bug avoidance.

**Comment by jaredcwhite** [comment]
Duplicate now of #885
