### ISSUE TITLE
Consider moving swagger-axios-codegen to the client side

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#497]
Split off from #482, with my comment from there:

Now that I've dug into it a little more, I think the right thing to do for the medium-long term is to move the swagger-axios-codegen stuff over to the front-end (either ui-components, or maybe this is time to refactor some of the more logic-centric pieces to a different shared frontend package). It's already set up to to the generation from a live URL, and this can become part of the client build in a pretty straight-forward way. It should also remove the need for any imports from front-end of back-end pieces, and it will make the swagger.json definitions on the backend the definitive source for the API, which seems good from a documentation perspective. If people agree with this approach, I'll file a separate issue for it, and then we can decide if can wait until @pbn4 is back or we need to try and do it faster. Also if this all seems to work, I think we can finally abandon #384, which I'm assuming @jaredcwhite will not be sad about.

**Comment by jaredcwhite** [comment]
@pbn4 Does this issue still make sense, or can we close it now? I'm not sure why it's assigned to me at this point. Thanks!

**Comment by ludtkemorgan** [comment]
I think we should discuss this as a team again. Right now the `backend-swagger.ts` file is the only file referenced outside of backend-core. It is not an issue as part of the monorepo, but it can cause some dependency nightmares if we want to split everything out (pull backend separate from the front-ends) as it now needs to pull in the whole backend. I'd recommend either putting it in the shared-helpers package or create a separate package just for this file.
