### ISSUE TITLE
Remove static swagger.json(?)

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#499]
I'm creating an issue instead of a PR for this since I'm not sure if this file is used in some way I can't see, but it seems like the static file that's checked into the root of `backend/core` isn't used, and the real version is generated by going to `/docs-json` against a running backend (as swagger-axios-codegen is already configured to do). I recommend we remove the confusion, unless there's some reason we need a static version of the file.

**Comment by pbn4** [comment]
It can be safely deleted. I was not creating a PR to speed things up.

**Comment by bk3c** [comment]
Bookkeeping note: fixed in 0b83d17820fed59ad7c84a5f50639293882a5576
