### ISSUE TITLE
Clean up static references to Router.push()

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#501]
It seems like [the preferred nextjs pattern](https://nextjs.org/docs/api-reference/next/router#userouter) has changed from:

```
import Router from "next/router"
Router.push(url)
```

to the hook-oriented:

```
import { useRouter } from "next/router"
const router = useRouter()
router.push(url)
```

So we should probably update accordingly?

**Comment by jaredcwhite** [comment]
Codebase has been updated to `useRouter` now, except for inside the `ApplicationConductor` object. We can't use hooks there, so we'll revisit if and when our current usage breaks in a future Next.js update.
