### ISSUE TITLE
Clean up nextjs config to use getStaticProps/getStaticPaths

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#509]
It looks like our current configuration using `exportPathMap()` in `next.config.js` has been superseded by getStaticProps and getStaticPaths as [the proper way to tell next to do SSG](https://nextjs.org/blog/next-9-3#next-gen-static-site-generation-ssg-support).

It's not hurting anything in the meantime, but it seems like a pretty straight-forward way to clean up our build process before we keep adding more pages.

**Comment by jaredcwhite** [comment]
Continued conversation now on #834

**Comment by jaredcwhite** [comment]
Whoa, didn't realize this was still open. Time to close! 😅
