### ISSUE TITLE
Update backend/core auth tests to work without a database

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#517]
`backend/core` auth tests are failing in CI for lack of a database. I guess we can provision one if need be, but I'm hoping there's a reasonable way to do it with a fixture so we can keep the CI configuration simpler for the time being.

Split off from #511

**Comment by bencpeters** [comment]
Ya, adding a fixture should be pretty trivial for the unit tests. It might a little bit trickier for the cypress/e2e tests, but probably still possible, I just haven't looked at it yet...

**Comment by bencpeters** [comment]
An example of this are the tests in PR #550.

Do we want to focus around this & write tests for all the modules? Or just use that as a template going forward?

**Comment by bk3c** [comment]
@bencpeters I think just using that as a template going forward is fine for now, though I'll never turn down more test coverage if you're feeling enthusiastic about adding more there. The main thing I want to do at this point is make sure all of the existing tests pass. I thought it was failing on auth, but it looks like I was wrong and it's failing on listings.spec.ts, so re-assigning to @pbn4.

**Comment by pbn4** [comment]
@bk3c We have both end-to-end and unit tests and listings.spec.ts are e2e, but they are started together with unit tests for reason unknown. Normally those are started by a separate command `yarn test:e2e`. Should I move listings tests there and make the `yarn test` contain only unit tests? BTW End to end test contain also a suite for /applications route which is not run by the CI at the moment so we are not using all the tests we have anyway. @bk3c We can either mock the DB access for e2e or run them locally. What do you think?
