### ISSUE TITLE
Refactor the Apply UI component and attachment/applicationmethod schema

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#518]
Split off from #516, where the first implementation had the IDs hard-coded in the apply links. As it currently stands, we consider external links "attachments", and I had hacked on top of that to point back to our internal application link. What I'm proposing we change to is:

- add a new TS interface called ApplicationMethod that has a 1:M relationship with listings (e.g. each listing can have one or more methods to apply).
- add multiple types to implement ApplicationMethod for internal online applications, links to external applications, download of PDF, pickup of paper application from leasing agent, etc.
- refactor all of the appropriate fields on Listing into listing.applicationMethod.whatever
- get rid of boolean fields for whether or not a listing has specific methods, and just use the presence of the relevant ApplicationMethods on a particular listing to define whether a method applies
- add logic to the Apply UI component to do the right thing passing through the listing ID for internal applications
- fix all of the other sidebar UI components to work with the new schema appropriately
- continue to have an Attachment object, but focus it holding metadata for 3rd party assets that we're going to manage in the system (e.g. images and PDFs).

cc: @akegan since this is a schema change that will move us further from the historical DAHLIA schema. I think it's the right direction for future flexibility and should be pretty easy to facade for compatibility in the SF case, but would be happy for your input here.

**Comment by jaredcwhite** [comment]
@bk3c New ApplicationMethod model sounds good. I'm not sure we'd even need Attachment anymore…probably should be changed to more of a generic Asset model, and then have a polymorphic relationship with anything that needs to contain assets (Listings as well as other stuff down the road).

**Comment by jaredcwhite** [comment]
So, are all of these flags going to be redundant given what we'll build into ApplicationMethod?

* `acceptingApplicationsAtLeasingAgent`
* `acceptingApplicationsByPoBox`
* `acceptingOnlineApplications`
* `acceptsPostmarkedApplications`
* `blankPaperApplicationCanBePickedUp`

**Comment by bk3c** [comment]
Yes, I think those all disappear from the main listing, though maybe `acceptsPostmarkedApplications` needs to exist as a key on the mail-in method.

**Comment by akegan** [comment]
@bk3c this seems reasonable and seems like something we'd be able to translate our listings into. The idea is that the listing will have a property called something like ApplicationMethods with type ApplicationMethod[], right?

**Comment by jaredcwhite** [comment]
I think this is ready to close now. Any further thoughts @bk3c?

**Comment by bk3c** [comment]
Agreed. Fixed in #551.
