### ISSUE TITLE
[RFC] Maintain front-end interfaces separately from backend interfaces

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#526]
I'll preface this by saying that I'm not at all convinced what the right answer is here, but I think I'm seeing some different tradeoffs after varying attempts to consolidate to a single entity/interface scheme this week, so I wanted to open up the discussion.

TL;DR: As much as it would be great to have key objects defined in one and only one place, I think the definitions will diverge just enough that it may not be a good idea. There will be enough times when we want different fields, different types, or different structure on the front-end compared to the back-end that hacking it all to work from one universal source will be more trouble than it's worth.

Some examples that are on my mind so far:

- There are definitely fields that we want on the backend but probably want to exclude from the front-end entirely. This seems pretty straight-forward with the swagger tools in basic cases (e.g. passwordHash), but seems to become way more difficult with nested/complex objects. For example, listing.applications is certainly a useful field for the backend, probably helpful to have for Partners (though I wouldn't want to load them all by default), but almost certainly not a field we would ever want or use in the public app. I guess we could make it optional?

- It seems reasonable to keep many of our front-end interfaces flatter than we probably want on the back-end (eventually). For example, we might want to have a LeasingAgent entity on the back-end but keep things flat as we currently do for listings on the front. I think we could do this by having the front-end based on the DTO rather than internal backend entity, but then we have the constraints of the DTO schema (e.g. IDs for things we do want as deep objects rather than the objects themselves for the front-end, like application.listing)

In general using DTOs separate from entities seems like a fine pattern regardless, since they never need to be considered further than the data-loading hooks on the front-end side, and it's nice to be able to optimize them for that purpose (e.g. including a status field or other metadata). To me it's really just a question of whether or not we want to re-assemble things on the front end in the exact same way as either the DTOs or how we're doing the back-end entities, and I'm not so convinced any more.

I recognize that having things with similar names and representing the same entities in slightly different ways is a potential maintenance nightmare, so I'm not convinced we should definitely split things up either, but I think it's worth a discussion before we build out the rest of the entity object model in the next few sprints.

**Comment by jaredcwhite** [comment]
@bk3c It does seem risky to start maintaining two different sets of interfaces for all the "same" objects. I wonder if any deviations between backend storage and public-facing API could perhaps be handled programmatically in some fashion (aka merge a nested object's interface into the top-level interface).

**Comment by kathyccheng** [comment]
Closed
