### ISSUE TITLE
Build a Cypress test for the Application form

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#529]
This is a pretty high priority, but I think we should maybe wait until after we do #453, since I'm expecting that will be a pretty big refactor that might have enough implications on the rendered DOM to cause spinning.

@dominikx96 I'm not sure what your experience with Cypress is from the past, so if you want to start scheduling in some ramp-up time on that if needed, that seems reasonable to me.

**Comment by dominikx96** [comment]
Tests have been merged.
