### ISSUE TITLE
Fold in homepage.mdx and AdditionalResourcesSidebar.mdx to their respective pages

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#548]
The actual AdditionalResources page is long enough that it probably still makes sense as an MDX file, but both of these seem short and mostly layout code, so I think we're better off just migrating the content back into the relevant pages and pushing the translatable strings into JSON.

It'd be great to do this on the soon side, since the translation company is about to take a pass through.

**Comment by bk3c** [comment]
Re-opening this so I remember to check on the AdditionalResources component.

**Comment by kathyccheng** [comment]
Reclosing
