### ISSUE TITLE
Figure out a better way to pass alert messages than encoded in the URL

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#570]
As @jaredcwhite perviously mentioned, putting those messages in the URL string makes it trivial to have arbitrary messages show up on the site, which doesn't seem like a good look. I also noticed that some messages aren't URLdecoded so they have `%20` characters in the user-facing text boxes.

I don't have an opinion on what the right/best solution is, so open to suggestions.

**Comment by jaredcwhite** [comment]
The two obvious options would be:

* Setting alert state within a React context
* Temporarily saving the alert within sessionStorage

The first option is probably the more idiomatic way to do it within React, but the second option could persist between browser loads if we need to support redirects or some other activity that triggers a page refresh

**Comment by bk3c** [comment]
I'm fine with either of those options. Maybe we can have a centralized function in what's about to be `site-core` that's available to pages to use, and then we can change the exact mechanism in one central place if needed (e.g. from option 1 to 2 as listed above)?

**Comment by jaredcwhite** [comment]
There's sort of a centralized component already in `ui-components`, named `UrlAlert`, so I think we'll want to tweak that to start.
