### ISSUE TITLE
Improve import of listings to the backend

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#582]
Building on an idea from @pbn4, we should have a cleaner way to create multiple listings in the database from JSON files in the format we used for the old listings service. This probably means a combination of CRUD endpoints within backend/core, and then a command line tool similar to (or adapted from) the current `seed.ts` to read a directory full of JSON files and call the API to make the appropriate objects.

Some other things that will be needed to make this work:

- [ ] The new endpoints will have to be secured, and the calling script will need to authenticate without too much trouble
- [ ] Ideally there should be some way to check for existing objects and then update rather than create duplicates. This can be done later.

The other important thing to note is that the schema for listings will soon undergo some pretty fundamental changes as we break out Properties as their own entity (and likely keep going further from there), but once we have the basic scheme in place it seems like it should be straight-forward to evolve.

**Comment by pbn4** [comment]
@bk3c Hey Ben I think it's done, isn't listings importer script exactly what we have here?

**Comment by kathyccheng** [comment]
@bk3c followup on @pbn4's comment, is this good to close?

**Comment by kathyccheng** [comment]
Closing
