### ISSUE TITLE
Fix migrations from CLI 

### ISSUE THREAD

**Issue by pbn4** [bloom-housing/bloom#597]
In https://github.com/bloom-housing/bloom/pull/562 I changed ormconfig to use entities, migrations and subscribers from `src/*.js` instead of `src/*.ts` which is working on my setup but stopped working for @dominikx96.

**Comment by bk3c** [comment]
Yeah, it looks like it might be broken in CI too, so this would be great to fix when you have a moment.

**Comment by pbn4** [comment]
I fixed it by commiting directly to master.
