### ISSUE TITLE
Make /applications (list) return only applications for a given auth 

### ISSUE THREAD

**Issue by pbn4** [bloom-housing/bloom#608]
As stated there is a need for this endpoint to return only user's applications. Now this endpoints returns the entire table.

**Comment by software-project** [comment]
@pbn4 I think we need both. User's applications for user facing apps and full list for partners.

**Comment by pbn4** [comment]
OK understood. I figured we also need https://github.com/bloom-housing/bloom/issues/609 for a case when we return the entire table.

**Comment by kathyccheng** [comment]
Closed in #724
