### ISSUE TITLE
Change appUrl in application/review/terms.tsx to be SSR-friendly

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#631]
From #567 we moved the site's base URL to be sent in with the application so it can be referred back to e.g. for email links, but it's broken since we can't read the URL from window.location when we're doing server-side rendering for nextjs. I did a quick fix for the Alameda site specifically to read it from an environment variable in the short-term, but I'm open to any sort of better answer.

**Comment by kathyccheng** [comment]
I think this is now fixed
