### ISSUE TITLE
Year Validation of Birth Incorrectly Showing

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#641]
When I fill out my date of birth on the first You screen, 
And then I fill out the rest of the screen and click Next, 
And then I come click back or come back to this screen via Edit in the Review Information screen 
I see an error on my year of birth even though it's valid 
But I can still move forward when I click next 

![Screen Shot 2020-09-10 at 9 12 49 PM](https://user-images.githubusercontent.com/3453407/92858805-5b017200-f3ab-11ea-89b5-dd86316dfb45.png)

**Comment by pbn4** [comment]
Same thing happens for househould members when I add one it's fine, but when I decide to edit it (actually just enter edition of a household member but do nothing just try to submit it again) validation is triggered on year of birth.

**Comment by jaredcwhite** [comment]
Weird! On latest master, I can't seem to trigger this error. Did anyone somehow fix it already?

**Comment by kathyccheng** [comment]
Can't reproduce either! I'll mark it closed for now!
