### ISSUE TITLE
applications/review/summary page shows "Midname" in place for an empty input

### ISSUE THREAD

**Issue by pbn4** [bloom-housing/bloom#643]
I create a submission without a middle name and that's what I get on a summary page: Michal Midname Plebanski
![Zrzut ekranu 2020-09-11 o 16 00 50](https://user-images.githubusercontent.com/11684414/92934633-03fdaa80-f448-11ea-833d-eb5ad6b443e3.png)

**Comment by bk3c** [comment]
@pbn4 Good catch!

**Comment by dominikx96** [comment]
@pbn4 are sure that autofill didn't make you surprise? I tried to fill out the form end to end and I didn't notice extra "Midname".

**Comment by pbn4** [comment]
Yup something wrong in my environment. Closing as invalid.
