### ISSUE TITLE
Component prop interface documentation

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#650]
As we continue to work to keep our code accessible to new and outside developers, it might be helpful to adopt typedoc to document our ui-component library props.

typedoc is the standard that Storybook uses, so when we add typedoc comments to our component prop interfaces, they surface on the docs page in Storybook.

Ideally we would be able to use tsdoc as our preferred format, but it might not be possible for Storybook to pick up those comments. This ticket will be a small spike on whether or not Storybook can pick up and display tsdoc formatted comments.

**Comment by jaredcwhite** [comment]
I don't mind taking a poke at this. Been working with YARD a lot over in Ruby land…curious to see how TSDoc compares.

**Comment by jaredcwhite** [comment]
Also adding a link here to https://typedoc.org/ in case we want to generate code-level docs.

**Comment by ludtkemorgan** [comment]
Closing this as documentation is different in seeds
