### ISSUE TITLE
Store date/time consistently in the database, in a timezone-safe way

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#678]
Split off from my review of #646, I noticed that we're storing created_at and updated_at on the key objects as `timestamp without time zone` and other things like listing.application_due_date as string/text fields. I think we'd benefit from consolidating, preferably on one of the myriad of postgres date/time types so that we can write queries with date math or conditionals when appropriate. I don't have a particularly strong opinion about what type we use at this point, and I don't think that there are any major size/performance concerns, so it should really be about what's easiest to code consistently and maintain.

Whatever we choose, we need to make sure that values we're storing in database are correct across multiple timezones. I'm 100% fine if that means we always store everything in UTC and then do any appropriate conversions further up the stack -- I've seen it done anywhere from the model layer the whole way up to the front-end. 

I'm also fine if we standardize on postgres `with time zone` types, if that seems easier. At the very least, it would potentially avoid us having to store or try to infer the correct time zone for a listing. Unless @slowbot strongly disagrees, the one thing I think we should **avoid** doing is trying to get too smart/helpful about automatically displaying time zones based on something like the user's browser time, which is unreliable in just enough cases that I think it's likely to get us into trouble.

Now that we have a live database with real data, we should also consider migration concerns, but I think there's a very high chance we'll end up re-populating the full DB sometime in the next couple months given all the schema changes coming, so maybe let's not worry about migration too much.

No matter what we do, we should add a few basic tests to make sure that we're storing and retrieving things correctly, no matter the server or DB time zone.

**Comment by seanmalbert** [comment]
@kathyccheng ,
I think we should bring this back into play. I think we should store the dates in UTC and make updates client side so that the browser's locale/timezone doesn't affect the displayed datetime. If we're worried about user's applying in different timezones and them not being sure about which timezone they're seeing the application close date in, then we can display the timezone for the listing. We can store a jurisdictions timezone in the jurisdiction table to achieve this.

**Comment by emilyjablonski** [comment]
A tangible issue we run into related to this:
If a team member sets an application date and time, it is specific to their own time zone. If someone in PST sets the due time as 5pm, someone in MST sees it as 6pm.
