### ISSUE TITLE
fix test failure in ui-components authentication/RequireLogin.test.tsx

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#717]
I think this is just a minor update that we missed in the big authn PR 

FAIL  __tests__/authentication/RequireLogin.test.tsx
  ● Test suite failed to run

    __tests__/authentication/RequireLogin.test.tsx:17:7 - error TS2739: Type '{ id: string; email: string; passwordHash: string; firstName: string; lastName: string; dob: Date; createdAt: Date; updatedAt: Date; applications: never[]; }' is missing the following properties from type 'User': isAdmin, roles

    17 const mockUser: User = {

**Comment by jaredcwhite** [comment]
Forgot to mark this as fixed on master.
