### ISSUE TITLE
Add map component for listing page

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#72]
Should be pretty straight-forward, but this will need to include a method to inject the API key for the mapping platform from an environment variable similar to / extending #64.

I could go either way with respect to using Mapbox (consistent with other recent Exygy work) or Google Maps (consistent with SF Dahlia), and ideally we'll probably do both and let the site configuration specify. @akegan do you / SFDS have a strong preference here?

**Comment by akegan** [comment]
Sounds like dataSF uses MapBox so as a DS team we are generally pro-mapbox.

Allowing configurability sounds good too, but switching to MapBox should be easy enough for us if we don't have to procure it 🤞
