### ISSUE TITLE
Short-term Authz tests + follow-ups

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#758]
Filing these as a separate issue since I don't think any of them are strictly blocking a merge of #715 at this point, but I'm in favor of getting these items addressed as soon as is reasonable:

- Users can't be created with isAdmin set to true. I think it just needs to be added to the CreateDTO, but maybe there's more than that?
- User creation endpoint should probably be moved from auth/register to user/create. Seems to be more consistent that way, and I think it would make it easier to have authz set up on the user methods themselves, especially once we have editing
- We need an endpoint to update user accounts. Right now it looks like SQL is the only option once the user has been created (or maybe I'm missing it?)
- Need to build out test coverage to make sure authz continues to operate correctly as we keep moving with development. I know it might seem cumbersome, but ideally I think this will include a test of every endpoint with a) no token, b) an invalid/expired token, and c) the wrong permissions (e.g. isAdmin = false, for now) to make sure things fail every time, plus at least some spot checks that things are working correctly when they should. Obviously the priority is on making sure we don't accidentally allow inappropriate use.

**Comment by pbn4** [comment]
> Users can't be created with isAdmin set to true. I think it just needs to be added to the CreateDTO, but maybe there's more than that?

@bk3c Isn't that going to allow users to register as admins? I think we should not include that in CreateDto and instead allow admins to edit any user profile -> make others admins too.

**Comment by bk3c** [comment]
@pbn4 sorry for the delay in response. My machine hard-crashed yesterday and it must have eaten my reply. I agree that we definitely don't want to let arbitrary users sign up with isAdmin = true, but I still think we need a way for admin users to set permissions at user create time. 

I guess it's fine if we want to have it be two API calls from the front-end one right after the other (create, and then immediately set permissions), so long as it's transparent to a Partners user. Either way, I do think we should probably move the endpoint to users/create, if that still makes sense to you.

Also note that we should maybe go ahead now and add a second permission called `isPartner` now, so that we can separate users who can log in to partners at all from people who are truly admins (e.g. Exygy team for now). Obviously permissions will get more complicated from there, but I expect both of those globals will probably continue for the foreseeable future.

**Comment by pbn4** [comment]
@bk3c I moved user creation to user controller in #770 but this is a branch off from env configuration fix since it was a blocker for this change to be introduced. Could you please fix ENVs on build systems so that jest-backend test passes? (It's related to ENV validation)
