### ISSUE TITLE
Consider replacing react-map-gl with direct use of mapbox-gl

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#768]
It looks like react-map-gl has it's own Marker implementation for performance reasons that don't necessarily impact us. Unfortunately, that means we can't use the `anchor` property, which causes the marker to appear in slightly the wrong place at lower zoom levels.

Based on https://github.com/mapbox/mapbox-react-examples, I think we might be able to bypass the extra package and use mapbox directly? cc: @jaredcwhite who I think did the initial implementation and might have more context that I'm missing?

Note there also seem to be some hacks to dynamically set the market `offset` based on window size (e.g. https://stackoverflow.com/questions/38768270/mapbox-gl-js-marker-offset). That doesn't seem to be preferred anymore, but given this is a relatively minor issue, I'm open to whatever works reliably.

**Comment by emilyjablonski** [comment]
We are now using react-map-gl
