### ISSUE TITLE
Take another pass to remove React non-unique key warnings

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#776]
This seems to be a somewhat recurring battle, but the ui-components tests throw up a bunch of warnings when we have react tables where we don't have unique keys. So far as I understand the issue this isn't really a user-facing problem (other than marginal performance), but it creates a lot of noise in the test results, so it would be great to take another pass at removing the current problem cases. For example:

```
      Warning: Encountered two children with the same key, ``. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
          in tr
          in Unknown
          in tbody
          in table
          in div
          in Unknown (created by storyFn)
          in div (created by storyFn)
          in storyFn (created by WrapperComponent)
          in WrapperComponent
```

As the stack trace shows, these look to be primarily in Storybook stories at this point, so I'm hoping that will make it easier to fix?

For extra credit, it would be great to write up a couple paragraphs on the best practices for avoiding this kind of problem without creating too much overhead, and then we can put it in to the docs directory with other best practice notes we want to do.

**Comment by jaredcwhite** [comment]
I'm thinking we either need to add specific IDs to all test data (ugh, not an ideal solution), or perhaps there's a way to calculate a deterministic value based on the test data, like a hash of the row text or something to that effect.
