### ISSUE TITLE
Add purgecss 

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#78]
Appears to be a best practice. See https://github.com/zeit/next.js/pull/9145 for more details. That issue only modifies the example, though.

See also the caution in that PR about dynamically rendered CSS, if that applies to us?

**Comment by jaredcwhite** [comment]
@bk3c Sounds like a good idea, but I wonder if it's something we could enable only for production builds? I'm finding compilation times in general to be somewhat frustratingly slow during development as it is… Regarding the dynamic class names, I'm not sure what that's referring to exactly. I think most of our class names are just strings in the className prop, so I'm guessing that'll work out fine.

**Comment by taylorbryant** [comment]
@jaredcwhite If you wanted to use Purgecss only for production builds, you could do something like this:

```js
module.exports = {
  plugins: [
    require("tailwindcss"),
    ...(process.env.NODE_ENV === `production`
      ? [
          require("@fullhuman/postcss-purgecss")({
            content: ["./src/**/*.js"],
            defaultExtractor: content =>
              content.match(/[A-Za-z0-9-_:/]+/g) || []
          }),
          require("autoprefixer")
        ]
      : [])
  ]
};
```

**Comment by jaredcwhite** [comment]
@taylorbryant Thanks for the tip! That seems like a good approach.

**Comment by bk3c** [comment]
Turns out we're shipping quite a bit of unneeded CSS, so I think it's time to get this fixed. Want to take this on @pbn4?

See also https://tailwindcss.com/docs/controlling-file-size/ for more documentation.

**Comment by pbn4** [comment]
@bk3c I opened a PR for that https://github.com/bloom-housing/bloom/pull/300 , but it seems the effect is neglible. Either I am doing something wrong or we are not shipping a lot of unneeded CSS.

**Comment by taylorbryant** [comment]
@bk3c @pbn4 Sorry to butt in, but just FYI Tailwind has a purge option built in now. For reference: https://github.com/taylorbryant/next-starter-tailwind/blob/master/tailwind.config.js

**Comment by pbn4** [comment]
@taylorbryant Can we somehow check what have been purged?

**Comment by taylorbryant** [comment]
@pbn4 Yeah, definitely! You can use PurgeCSS’ `rejected` option.

For example:
```js
// tailwind.config.js
module.exports = {
  purge: {
    content: ['./src/**/*.js'],
    options: {
        rejected: true,
    }
  },
  // ...
}
```

**Comment by taylorbryant** [comment]
That _should_ output a list of unused selectors in your terminal.
