### ISSUE TITLE
Partners can add household details 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#800]
As a partner, 
I want to add household details from the paper application 
When I'm on the new application page
I expect to see a section for Household Details with a checkbox allowing me to select multiple ADA priorities 
When I click Submit
Then I'll see the Household Detail section on the Detail page with what I selected filled in 

![image](https://user-images.githubusercontent.com/13915/98024088-aa1cbf80-1dbc-11eb-8df5-edea217adf34.png)
![image](https://user-images.githubusercontent.com/13915/98024101-b1dc6400-1dbc-11eb-90a1-303a60af53e6.png)

**Comment by dominikx96** [comment]
Merged.
