### ISSUE TITLE
Partners can add declared household income 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#801]
As a partner
I want to add household income details from the paper application 
When I'm on the new application page
Then I'll see a section for Declared Household Income with annual, monthly and housing voucher fields 
When I click submit 
Then I'll see the Declared Household Income section on the details page with whatever I had filled in 

![image](https://user-images.githubusercontent.com/13915/98024209-d59faa00-1dbc-11eb-8480-d4ec8df7daa9.png)
![image](https://user-images.githubusercontent.com/13915/98024233-dcc6b800-1dbc-11eb-92b8-8dfd0498a4d0.png)

**Comment by dominikx96** [comment]
Merged.
