### ISSUE TITLE
Partners can add Application Preferences 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#804]
As a partner
I want to add application preferences 
When I'm on the New Application page
I'll see an Application Preferences section with the ability to select the application's preferences 
When I click Submit
Then I'll see an Application Preferences section on the detail page 

![image](https://user-images.githubusercontent.com/13915/98025107-2368e200-1dbe-11eb-8f51-fb20a7189271.png)
![image](https://user-images.githubusercontent.com/13915/98025129-29f75980-1dbe-11eb-8c29-239ca4085f54.png)

**Comment by dominikx96** [comment]
Merged.
