### ISSUE TITLE
Partners can add Terms 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#806]
As a partner
I want to indicate if the applicant has signed the Terms of Agreement or not 
When I'm on the New Application page
Then I'll see a Terms section with a yes/no
When I click Submit
I'll see a Terms section on the detail page with what I filled out 

![image](https://user-images.githubusercontent.com/13915/98025754-f8cb5900-1dbe-11eb-900b-1adb1d676cc0.png)
![image](https://user-images.githubusercontent.com/13915/98025785-02ed5780-1dbf-11eb-9352-a65aca60289b.png)

**Comment by dominikx96** [comment]
Merged.
