### ISSUE TITLE
Partners can delete an application 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#807]
As a partner
I might want to delete an application 
When I'm on the application detail page 
I expect to see a delete link 
When I click on delete
Then I expect to see a modal that asks me if I'm sure 
When I click delete
Then I will be directed back to the application list page 
And the application will no longer be there 

Notes 
* We want to track who took the delete action and when 
* A partner can delete ONLY a paper application, not a digital application 
* This is a soft delete 

![image](https://user-images.githubusercontent.com/3453407/101061755-b031c780-3545-11eb-9bb5-61eb647d4b23.png)
![image](https://user-images.githubusercontent.com/3453407/101061792-bde74d00-3545-11eb-8b2d-b8d6e6babe59.png)

Designs
* https://www.figma.com/file/Y8bFd0aSz7eYJ2TCNid6s3/bloom-partners?node-id=1640%3A98892
* https://www.figma.com/file/Y8bFd0aSz7eYJ2TCNid6s3/bloom-partners?node-id=1479%3A0

**Comment by dominikx96** [comment]
Merged.
