### ISSUE TITLE
Partners can go directly from one application to another 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#809]
As a partner
I want to be able to add multiple applications back to back
When I'm on the New Application page and I fill out an application
Then I will see the option to Submit and New
When I click that 
Then I'll see a new application page
When I go back to the application listings page 
Then I'll see the previous application is there 

![image](https://user-images.githubusercontent.com/3453407/101095741-3f090900-3573-11eb-8b6c-800fb214e0a6.png)

**Comment by dominikx96** [comment]
Merged.
