### ISSUE TITLE
Application properties sameAddress and workInRegion should be boolean

### ISSUE THREAD

**Issue by pbn4** [bloom-housing/bloom#816]
Currently the `sameAddress` and `workInRegion` properties on the application entity are string types and saved as "yes" "no" "n/a" - we should migrate these fields to a boolean type and save as true / false / null. There is no reason to use a property with semantic meaning of yes/no as a string instead of boolean.

**Comment by YazeedLoonat** [comment]
closing we use a yesnoenum
