### ISSUE TITLE
Fix listing applicationPickupAddress regression

### ISSUE THREAD

**Issue by pbn4** [bloom-housing/bloom#819]
As pointed out by @jaredcwhite  there is a probable regression indtroduced here https://github.com/bloom-housing/bloom/commit/052abe887fd507cfdca99bf8eff6abd05bd0e5ea#diff-b086abfddfe12d17056078f84fea09a2a62ee35825ed9a866da0763358432049L117

Although if it's an actual regression requires verification.

**Comment by jaredcwhite** [comment]
I was able to find an example of an application pick up address and office hours in the [Montara listing in the housingbayarea repo](https://github.com/housingbayarea/bloom/blob/master/services/listings/listings/montara.json).

**Comment by jaredcwhite** [comment]
Seems likely we didn't have it in our test examples upstream so it didn't make its way into the DB schema.
