### ISSUE TITLE
Images on Storybook are missing

### ISSUE THREAD

**Issue by jaredcwhite** [bloom-housing/bloom#820]
I was trying to track down why the close icon wasn't showing up for modals in Storybook, and upon further investigation I discovered that *none* of the files in `ui-components/public/images` are working anymore…404s on all of them. Not sure yet if this happened due to a recent upgrade to Storybook, or some other configuration that got hosed.

**Comment by jaredcwhite** [comment]
Strange, it's working for me locally on the `updated-button-styles` branch. Is it just an issue on Netlify then? (look at https://storybook.bloom.exygy.dev/?path=/story/headers-hero--with-background — no background image is showing up!)

**Comment by emilyjablonski** [comment]
At the current moment, images appear to be working just fine, but icons are not - focusing the effort there
