### ISSUE TITLE
Refactor applications table to support sorting by the backend

### ISSUE THREAD

**Issue by dominikx96** [bloom-housing/bloom#866]
Currently, sorting is only applied for an active page - not for all the table data. We should implement it after the backend changes.

**Comment by pbn4** [comment]
@bpsushi This task is about adding a new query param to GET `/applications` which would allow client to sort by any of:

- First Name
- Last Name
- Application Submission Date

Root issue: https://github.com/bloom-housing/bloom/issues/392

Notes:
- you could either create a complex input object type that takes all 3 parameters at once or split that into 3 separate query params. I'm not sure if our current swagger-axios-codegen lib will correctly generated a frontend client and models for a complex query param type, that is to be checked,
- make sure newly added code correctly generates swagger `/docs` page and model/client for frontend (`yarn generate:client` from `./backend/core/package.json`,
- add few tests for happy path and invalid input,
- CSV endpoint does not need those query params at the moment.

**Comment by bpsushi** [comment]
@pbn4 ready for review on PR: #1063
