### ISSUE TITLE
Address the nextjs issue with react hooks

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#87]
See https://github.com/zeit/next.js/issues/9022. Hopefully someone else will resolve this or come up with a workaround, and then we can just adjust as needed. On hold for now.

**Comment by bk3c** [comment]
@jaredcwhite Given that we're now updated to the latest nextjs + react, can we close this? I think it might have been a red herring all along, and there was some other issue with our react versioning causing the error when we originally hit it, but in any case I can't duplicate it now.

**Comment by jaredcwhite** [comment]
Yeah I think they got this fixed and I haven't seen any issue since our latest upgrades. Let's consider this a wrap.
