### ISSUE TITLE
Add rate limiting to `POST /applications/submit`

### ISSUE THREAD

**Issue by pbn4** [bloom-housing/bloom#889]
We need to add rate limiting to prevent malicious users/bots from flooding our database with trash data.

**Comment by emilyjablonski** [comment]
@pbn4 Do you have input on what strategies we should use for rate limiting so we are all on the same page?

**Comment by bpsushi** [comment]
@emilyjablonski after my discussion with @pbn4 we see two possible approaches:

Approach 1: Rate limits based on user IP
This will be pure backend approach where rate limits are calculated for each IP address that sends the request. Frontend will only need to show proper message in case of reaching the limits. This approach will require from us to set up Redis - we cane use free plan of heroku addon for this (for now it should be enough and can be scaled in the future: https://elements.heroku.com/addons/heroku-redis). @pbn4 mentioned that setting up Redis is in backlog anyway.

Approach 2: Google reCaptcha v3
Classic approach where we implement Google reCaptcha. A little more frontend work will be required, but no need of any additional work like setting up Redis. Captcha will then take care of any flood tries.

**Comment by dominikx96** [comment]
@kathyccheng we discussed with Bart about showing an error message on a frontend side.
"Rate limit exceeded, try again later." is okay? Do we want to add translations?

**Comment by kathyccheng** [comment]
@dominikx96 Sure error message sounds good, we will want to add translations. I'll add that into the next batch for the translators
