### ISSUE TITLE
Allow multiple language application download URLs

### ISSUE THREAD

**Issue by jaredcwhite** [bloom-housing/bloom#90]
The Bloom analog to:
https://www.pivotaltracker.com/story/show/169412575

> AC:
> 
> 1. User can download the application in the following languages: English, Spanish, Chinese (Traditional), Chinese (Simplified), Vietnamese, and Filipino
> 2. The Download Application dropdown only displays the application links for the languages that are provided in the database for a specific listing
> 
> Notes:
> Each Listing may display different languages:
> - Listing A may only have English
> - Listing B may have English and Spanish, Vietnamese
> - Listing C may have English, Chinese (Traditional), Chinese (Simplified)

**Comment by bk3c** [comment]
FWIW, my longer-term vision here is that we'll want a first class Attachment object (open to other names, maybe Asset?) with it's own ID and the relevant metadata, and then we can have a mapping between attachments and listings. I could think of cases where it will be M:M, such as program brochures or other supporting material that might be common to many listings.

This is sort of an iceberg feature, if you include upload functionality, versioning, etc. so I don't think we need to get too carried away with all of that now, but it would be great to get some of the object model parts worked out.

**Comment by jaredcwhite** [comment]
That sounds good to me (the Attachment object). I'll augment the current JSON to use that concept in as general a way as possible with the current URLs we have, and once we turn our attention to the backend we can evolve that further.
