### ISSUE TITLE
Translation Bugs

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#911]
Capturing translation bugs I'm noticing:  
 
**Listings: per month labels in the rent table** 
![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/3ebffcaa-b954-464f-8e99-15f5c214c8ab)
![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/3ac2aaa4-b089-4c90-9f77-4b57ed42da37)

**Listings: household size table** 
![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/56e6ae1e-2d19-4a47-b4dc-efeb26cdd892)

**Application: app progress bar** 
![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/a0d59fa2-b3d5-4fa4-b1da-037f62c7349c)

Application: Middle Name (optional) placeholder text 
![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/43dd7214-4a9b-41ae-a8d4-06862fd83fdc)

Application: ADA needs 
![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/ab5e2390-2c01-4e3a-b6c3-4859baf7839d)

**Comment by kathyccheng** [comment]
@jaredcwhite I captured some missing translations I noticed. Can you take a look at these and see if these are issues on our end or if it's something the contractors missed? if we hooked something up wrong, we can fix it. if we missed a string when we sent it over or if they missed something, then I'll follow up with the contractors before they do their translations QA round.

**Comment by jaredcwhite** [comment]
@kathyccheng Will do…in some cases I know we have the translated strings already and just need to slot them into the layout, otherwise there could be a few things we previous overlooked.

**Comment by jaredcwhite** [comment]
OK I think I got all the issues here resolved except for the headers on the HMI table…it's a little funky in that the summary data is coming from the backend so we need to (a) change the backend text to programmatic labels instead of "regular" copy, and then (b) add the translation strings for those to all 4 language files.

**Comment by jaredcwhite** [comment]
@kathyccheng Actually a couple of other issues: we are missing translations (I think?) for "Household" and "Review" on the application form progress nav. I'm also seeing some bugs around the Apply button and the "choose a language" options for application form, but maybe that should be filed as a separate issue?

**Comment by kathyccheng** [comment]
Yeah the bugs for Apply and Choose Language should probably be a separate issue. And then for the Household and Review, did we not send them over (ie is it not in our general JSON file) or did we just not get them back?

**Comment by jaredcwhite** [comment]
> @jaredcwhite Yeah the bugs for Apply and Choose Language should probably be a separate issue. And then for the Household and Review, did we not send them over (ie is it not in our general JSON file) or did we just not get them back?

All right I'll file new issues for Apply & Choose Language (assuming you didn't already). Regarding the progress nav, we didn't use translated labels for those unfortunately, so they didn't make their way into the file we went them.

**Comment by kathyccheng** [comment]
Alright @jaredcwhite can you go ahead and file the bugs for the Apply and Choose Language? I also created a separate issue for the household size table headers here in #931 and added those strings to a set I'll send back to the translation agency to translate. And then otherwise, looked at the deploy preview in #925 and it's looking good so let's go ahead and merge that and then we can close this issue out.
