### ISSUE TITLE
Partners: CSV Export Update with Duplicates

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#918]
With duplicates
* Update the CSV export to include 2 tabs, one with all of the applications excluding ones the ones removed by the developer, one tab more removed applications that will include all of the duplicates that were removed 
* The applications that we flag as potential duplicates do not matter in this case, we only segment out the ones that the developer has taken action on

**Comment by netrabadami** [comment]
@kathyccheng @jaredcwhite @dominikx96 I did a bit of research and figured that you cannot have multiple tabs in csv, CSV is a single-sheet format.

**Comment by kathyccheng** [comment]
@netrabadami can you look into zipping the 2 CSVs for unique + duplicates into one download?

**Comment by netrabadami** [comment]
@kathyccheng @slowbot What will be the name of the csv file for duplicate applicat
