### ISSUE TITLE
[RFC] Improve integrating new changes into county specific sites.

### ISSUE THREAD

**Issue by pbn4** [bloom-housing/bloom#919]
While working on a migration task and integrating new changes to our Alameda county site I noticed that we keep 3 copy-paste versions of public-reference in housingbayarea fork. 

**Such state makes integrating new changes error prone and basically impossible to do right**. Here is why: 

Our main repository `bloom-housing/bloom` contains only `apps/public-reference`. Once we merge newest changes to `housingbayarea/bloom` fork it only applies changes to `apps/public-reference` which makes sense, but there are 3 more apps there that are untouched by this merge action: `public-sj`, `public-smc` and `public-ala`. One might think: OK but they were supposed to differ anyway so what's the problem? Well they are different to certain degree but 90% of it's code is duplicated. Now imagine in newest upsteam version we added some fixes e.g. "Apply online" button was sometimes crashing and we fixed that in `public-reference` app. This fix won't get propagated in any way to `public-sj`, `public-smc` and `public-ala` while merging changes to our fork. It will only propagate to `public-reference`. This is an unnacceptable state which makes integrating new changes right almost impossible because the only thing I can do after merging is copying folder `public-reference` over to e.g. `public-ala` and somehow figure out which changes are Alameda specific code that I just overwritten with copying or are a new bug fix/feature. We use git for versioning but we do not really have versioning between `public-reference` and county specific sites, mainly because they are copy pastes and there are separate files. 

So far I wasn't aware what impact it has on developers (because I didn't have a chance to introduce new changes to county specific sites) but @software-project can confirm what I experienced recently that integrating new changes consumes way too much developer's time. It's what makes us move so slow and we need to do something about immediately because it will only get worse as codebase grows. 

I had a discussion with @software-project on how we can address this problem, here is a mixed solution we came up with in simple words: let's use **only a public-reference** site within our main repository and use separate branches/forks to track county specific sites. Now `public-ala` becomes `public-reference` on `alameda` branch.  In that way we will have all the good things coming with git versioning. During merge all changes from upstream `public-reference` will be reported by git and potential conflicts will be marked for resolution (we won't miss any changes while updating).

**Comment by dominikx96** [comment]
I totally agree with this idea. When the project will grow, it will be harder and harder to maintain it and e.g. implement hotfixes.
A variant with fork better suited for me, because we still have the ability to create separate GitHub issues for new site instances, versioning also should be more flexible.

**Comment by jaredcwhite** [comment]
Also totally agree!

**Comment by jaredcwhite** [comment]
@pbn4 I'd recommend getting the PR merged in where you move types from backend to to ui-components, and then this should be our next priority.
