### ISSUE TITLE
Partners Pilot Single Listing Flow Audit

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#935]
As a partner
When I sign in with the email and password someone at Exygy sent me
Then I expect to see... 
(A screen with all of the applications for my listing) 

Engineering Notes
* Remove properties and application menu items 
* Remove current landing page
* Route leasing agent to the listings page with the listings they have permissions to view
* Fix visual display of listings table
* Recommended Listing columns
   * Listing Name
   * Application Due Date
   * Applications Submitted
   * Available units (quantity) Let me know if this is easily available. 
   * Open Waitlist (yes/no) Let me know if this is easily available. 
   * Listing Status (coming soon, accepting applications, closed)  Let me know if this currently exists or not.
   * If any of these fields do not exist or represent significant effort we can hold off on them for now and finish the rest. 

![image](https://user-images.githubusercontent.com/13915/104659864-4d6e3880-567a-11eb-94e8-feb0c1f08167.png)

**Comment by dominikx96** [comment]
@slowbot not sure, but we have 2 properties inside listing data: waitlistCurrentSize, waitlistMaxSize
So it means, waitlist is open when waitlistCurrentSize < waitlistMaxSize or any other scenarios exists?
