### ISSUE TITLE
Cache bug

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#944]
When I go to https://housing.acgov.org/
And then I click See Rentals 
And then I refresh the page, I'll see two old listings - Jones and something else 
When I continue the refresh, those two listings will persist 
Then when I click back to the homepage and then click See Rentals again
Then those disappear and it's back to everything being all closed

**Comment by jaredcwhite** [comment]
This should be resolved once the latest master build (https://ala.bloom.exygy.dev/listings) has been promoted to production.
