### ISSUE TITLE
WIP: Translate Preferences Screen in Application for SoHay 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#961]
Here are translations for the Preferences in SoHay 

"opt_out": "I don't want to claim any of these preferences",
"opt_out": "No quiero solicitar ninguna de estas preferencias",
"opt_out": "我不想使用這些優先權",
"opt_out": "Tôi không muốn chọn bất kỳ ưu tiên nào trong số này",

"hayward_live_detail": "At least one member of my household lives in the City of Hayward",
"hayward_live_detail": "Al menos un miembro de mi hogar vive en la Ciudad de Hayward",
"hayward_live_detail": "Ít nhất một thành viên trong hộ gia đình tôi sống tại Thành phố Hayward",
"hayward_live_detail": "我家至少有一人住在 Hayward 市",

"hayward_work_detail": "At least one member of my household works or has been offered work in the City of Hayward",
"hayward_work_detail": "Al menos un miembro de mi hogar trabaja o le han ofrecido trabajo en la Ciudad de Hayward",
"hayward_work_detail": "Ít nhất một thành viên trong hộ gia đình tôi đã làm việc hoặc được đề nghị làm việc tại Thành phố Hayward",
"hayward_work_detail": "我家至少有一人在 Hayward 市工作或獲得工作機會",

"hayward_displacement_preference_title": "Displaced Tenant Housing Preference",
"hayward_displacement_preference_title": "Preferencia de vivienda para inquilinos desplazados",
"hayward_displacement_preference_title": "Lựa chọn Ưu tiên Nhà ở dành cho Người Thuê Nhà phải Chuyển chỗ",
"hayward_displacement_preference_title": "無居所租客房屋優先權",

"hayward_displacement_detail": "At least one member of my household was displaced from a residential property due to redevelopment activity by the Hayward Housing Authority, the Redevelopment Agency or the City of Hayward." 
"hayward_displacement_detail": "Al menos un miembro de mi hogar fue desplazado de una propiedad residencial debido a la actividad de reurbanización por parte de la Autoridad de Vivienda de Hayward, la Agencia de Reurbanización o la Ciudad de Hayward." 
"hayward_displacement_detail": "Ít nhất một thành viên trong hộ gia đình tôi phải chuyển chỗ ở khỏi một bất động sản gia cư do hoạt động xây dựng lại bởi Cơ quan Quản lý Nhà Ở Hayward (Hayward Housing Authority), Cơ quan Tái Phát triển hay Thành phố Hayward."
"hayward_displacement_detail": "由於 Hayward 房屋管理局、重建管理局或 Hayward 市政府進行重建活動，我家至少有一人被迫搬出住宅物業。"

"hayward_238_preference_title": "Mission Boulevard Corridor (SR 238) Displaced Tenant Housing Preference",
"hayward_238_preference_title": "Preferencia de vivienda para inquilinos desplazados de Mission Boulevard Corridor (SR 238) ",
"hayward_238_preference_title": "Mission Boulevard Corridor (SR 238) Lựa chọn Ưu tiên Nhà ở dành cho Người Thuê Nhà phải Chuyển chỗ",
"hayward_238_preference_title": "Mission Boulevard Corridor (SR 238) 無居所租客房屋優先權",

"hayward_238_detail": "At least one member of my household is an SR 238 Program Participant as required under the terms of the SR 238 Settlement Implementation Project. Program Participants are tenants of previously sold Caltrans properties along the SR 238 Mission Boulevard Corridor and are given occupancy preference when new below-market housing is constructed in the Corridor.", 
"hayward_238_detail": "Al menos un miembro de mi hogar es Participante del Programa de SR 238 de acuerdo con lo requerido por los términos del Proyecto de Implementación del Acuerdo de SR 238. Los participantes del programa son inquilinos de propiedades de Caltrans vendidas anteriormente a lo largo del corredor de SR 238 Mission Boulevard y se les dará preferencia de ocupación cuando se construyan nuevas viviendas por debajo del valor del mercado en el corredor." 
"hayward_238_detail": "Ít nhất một thành viên trong gia đình tôi là Người Tham gia Chương trình SR 238 theo yêu cầu của các điều khoản của Dự án Triển khai Tái Định cư SR 238. Những Người Tham gia Chương trình là người thuê nhà của các bất động sản Caltrans trước đây đã bán dọc theo Hành lang SR 238 Mission Boulevard và đang được ưu tiên cho cư ngụ khi có nhà ở mới thấp hơn giá thị trường được xây dựng trong Hành lang."
"hayward_238_detail": "根據 SR 238 和解實施項目條款規定，我家至少有一人是 SR 238 計劃參與者。計劃參與者是 SR 238 Mission Boulevard 走廊沿線先前已出售的 Caltrans 物業租戶；此走廊興建低於市價的全新住房時，計劃參與者有入住優先權。"

WIP
"name_displaced": "Which member of your household is applying for this preference?" 
"address_displaced:" "What is their address?"

**Comment by software-project** [comment]
@kathyccheng should this translation go to this repo? Or housingbay? Cause they seems to be  location specific

**Comment by kathyccheng** [comment]
@software-project good point, I feel like this is actually housing bay

**Comment by kathyccheng** [comment]
Moved to housingbayarea
