### ISSUE TITLE
Partners app: a page reload wipes out login state, must sign in again

### ISSUE THREAD

**Issue by jaredcwhite** [bloom-housing/bloom#970]
After merging in #966, the page navigation is working in an SPA sort of way, but if I do a browser refresh (select the URL bar and hit enter, or press cmd-R, etc.), my login state is wiped out and I'm brought back to the Sign In page. Going back to a previously working URL just kicks me back to Sign In.

**Comment by dominikx96** [comment]
@jaredcwhite tested on the Netlify and I'm still logged in after refresh (CMD + R)/enter in the URL bar.

There is only one situation when I was logged out - when I navigated to a new tab, but this behavior is the same as in the public app.

**Comment by jaredcwhite** [comment]
It's working better in Brave (aka Chrome), but I'm still having issues in Safari.

Also:

> when I navigated to a new tab, but this behavior is the same as in the public app.

Huh…this seems to be a limitation of `sessionStorage`. I wasn't aware it is different than session cookies. Apparently, a session cookie can be utilized across multiple tabs/windows, whereas session storage is only for the single window. I wonder what we could do to fix this?

**Comment by dominikx96** [comment]
> It's working better in Brave (aka Chrome), but I'm still having issues in Safari.

Do you have problems on the public app as well?

**Comment by kathyccheng** [comment]
Closing until we can reproduce
