### ISSUE TITLE
Catch up housingbayarea with new translations 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#990]
Add translations from bloom general to housingbayarea 

* Translations bar to add Spanish, Vietnamese, Chinese, 
* Applications should include all language options on first selection screen

**Comment by kathyccheng** [comment]
@jaredcwhite what do we have to do to update housingbayarea with translations?

**Comment by jaredcwhite** [comment]
@kathyccheng I think this is ready to roll in Netra's PR #207

**Comment by jaredcwhite** [comment]
> Applications should include all language options on first selection screen

This will be enabled when there's a full merge of latest upstream bloom with the new housingbayarea Alameda branch.

**Comment by kathyccheng** [comment]
@pbn4 @software-project just putting this on your guys's radar to make sure we have in Alameda 0.3 branch

**Comment by kathyccheng** [comment]
Closed
